- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
`ChangeType$ Card` would slip by and result in "Card card" output
> avoid "Card card" in ChangeZone StackDesc

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardPlayOption.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-gui/res/cardsfolder/upcoming/maestros_ascendancy.txt
Works with cards that already have additional costs - regular mana cost, additional cost, and the may play's creature sac cost are all required
> SNC: Maestros Ascendancy and support

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/keyword/KeywordsChange.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
This stops Static Abilities from creating the same Keyword again for the same Card (until Card moves zones)
for this MR or later ones, the same can be done for other CardTraits created by StaticAbilities (which would reduce the amount of CardTraits being created)
> Card: store Keywords created by Static Abilities

- forge-gui-desktop/src/main/java/forge/GuiDesktop.java
- forge-gui-desktop/src/main/java/forge/ImageCache.java
- forge-gui-desktop/src/main/java/forge/itemmanager/filters/StatTypeFilter.java
- forge-gui-desktop/src/main/java/forge/itemmanager/views/ImageView.java
- forge-gui-desktop/src/main/java/forge/screens/deckeditor/AddBasicLandsDialog.java
- forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/ACEditorBase.java
- forge-gui-desktop/src/main/java/forge/screens/deckeditor/views/VStatistics.java
- forge-gui-desktop/src/main/java/forge/toolbox/CardFaceSymbols.java
- forge-gui-desktop/src/main/java/forge/toolbox/FSkin.java
- forge-gui-desktop/src/main/java/forge/toolbox/imaging/FCardImageRenderer.java
- forge-gui-desktop/src/main/java/forge/toolbox/imaging/FImagePanel.java
- forge-gui-desktop/src/main/java/forge/view/arcane/CardPanel.java
- forge-gui-desktop/src/main/java/forge/view/arcane/ScaledImagePanel.java
- forge-gui-mobile/src/forge/GuiMobile.java
- forge-gui/src/main/java/forge/gui/interfaces/IGuiBase.java
The change in Fskin.java is using BaseMultiResolutionImage, which needs Java version >= 9.
Currently this handles all card images rendering and some of icons like those used in the deck editor.
But some icons or icons are still not scaled:
- Icons in the main tab.
- Player/Opponent avatar images in the duel screen
- Card ability icons above card images in the duel screen
- Card details panel <- This is using HTMLText to render texts and symbols, which I am not sure how to fix.
But I think this fix is big enough for now and can be merged first, and I will try to fix the above cases later.
Also I only tested in my environment, so I think other should test this fix and see if it works correctly in other environments too.
> Detect Screen DPI and scale images accordingly

- forge-gui/res/editions/Game Day Promos.txt
- forge-gui/res/editions/Shards of Alara.txt
Updated ALA edition file and booster due to new Rafiq of the Many [showcase] card
Added new GDY promos
Source: https://magic.wizards.com/en/articles/archive/feature/whats-new-list-streets-new-capenna-2022-04-14
> Update ALA and GDY editions

- forge-gui-desktop/src/main/java/forge/itemmanager/views/ImageView.java
This is the better fix for the card list dancing light issue.
I dropped the image dimension change added by kevlahnota, but call a different image rendering function.  
By Snoops test this seems to also solves the issue.
The code before and after the fix should work equivalently. I can't reproduce this issue in my environment, so I can only guess maybe there are some rendering bug in the Java runtime depends on the version.
> Better fix for card list dancing light issue.

- .github/workflows/test-build.yaml
Very minor improvement:
Only installs the virtual framebuffer if the package is not installed yet. Saves a few seconds, since the apt doesn't have to be updated.
> Testing workflow: Only install xvfb if not available

- forge-game/src/main/java/forge/game/ability/effects/DiscardEffect.java
- forge-gui/res/cardsfolder/i/inquisition_of_kozilek.txt
Clean up where important calculations are made and not making the same `sa.getParam` etc. more than once
Improve verb conjugation for one vs. multiple targets
Introduce `DiscardValidDesc$` for garbled `DiscardValid$` values
Improve syntax for `Mode$ RevealYouChoose`
Before (thanks @paulsnoops)
After
New rainy day issue is to batch check cards with `DiscardValid$` to see which would need `DiscardValidDesc$`
> DiscardEffect getStackDescription() overhaul

- forge-game/src/main/java/forge/game/ability/effects/MustAttackEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/combat/AttackRequirement.java
- forge-game/src/main/java/forge/game/phase/Untap.java
Following interactions are fixed for cards like _Gideon, Battle-Forged_:
- his +2 wasn't working at all (fix is bandaid until it can be refactored better)
- when the taunted player confiscates him it would still try to obey the attack requirement = GUI deadlock
- attack requirement would still count if he got blinked
> Fix attack requirement check

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ability/EffectAi.java
- forge-ai/src/main/java/forge/ai/ability/PermanentAi.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/m/mangara_the_diplomat.txt
- another timing fix, this one is for NextTurnForEachPlayer:
_Sphinx's Decree_ could have been skipped with _Stasis_ in play
- Fix getting tokens with _Arachnogenesis_ for attackers that get removed from combat before it resolves
- Fix _Mangara, the Diplomat_:
> If some of the attacking creatures leave the battlefield while Mangara’s triggered ability is on the stack, use the player or planeswalker they were attacking before they left to determine whether you draw a card. On the other hand, if they’re removed from combat without leaving the battlefield, use their current information to determine that they’re not attacking you or a planeswalker you control anymore.
> Fix a couple of interactions

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/ability/effects/MillEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/cost/CostExile.java
- forge-game/src/main/java/forge/trackable/TrackableProperty.java
- forge-gui/res/cardsfolder/upcoming/arcane_bombardment.txt
- forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
- forge-gui/src/main/java/forge/player/HumanPlay.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
This PR solves two quality of life issues with this card and hopefully "future proofs" for similar cards to come:
1. multiple copies of the card on the battlefield would not list cards exiled without also including remembering... latching onto the existing code for exiling cards seemed the best solution
2. multiple triggers from multiple copies would be seen by Forge as identical and therefore not be possible to order by the human player – in this case a new param seems the easiest fix, rather than implementing some sort of deeper check
> Arcane Bombardment - quality of life

- forge-game/src/main/java/forge/game/ability/effects/ReplaceTokenEffect.java
- forge-gui/res/cardsfolder/upcoming/jinnie_fay_jetmirs_second.txt
- forge-gui/res/tokenscripts/g_2_2_cat_haste.txt
- forge-gui/res/tokenscripts/g_3_1_dog_vigilance.txt
Possibly it would be better to skip GenericChoice and do the choice/choice prompt on ReplaceTokenEffect? It would need to be some kind of map <String, String> with <Description, TokenScript>, right? Then we probably wouldn't need the repSA stuff I added at the beginning of the ReplaceTokenEffect yet.
Unsure what is better for AI – initially at least this requires less finagling on ReplaceTokenEffect.
It may also be the case that this is "good enough for now" and we revisit this card and effect if/when more similar cards are printed.
> SNC: Jinnie Fay, Jetmir's Second and support

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-game/src/main/java/forge/game/replacement/ReplaceDestroy.java
Closes #142
This adds the Replacement Effects for Shield Counters
they should be unaffected by any card trait changes
for later MR, do `CARDNAME can't be regenerated.` as StaticAbility and undo `If CARDNAME would be destroyed, regenerate it.` Keyword
> Card: add Shield counter Replacement Effects

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/cost/Cost.java
- forge-gui/res/cardsfolder/upcoming/dusk_mangler.txt
What do you think of using `_` to separate the alternative costs? I thought it might be nice to avoid `:` as it could be used for other things. `;` is out as it is used so much in cost strings.
This seems to work well for the new card as well as the old ones. Smoothed out a few things in keyword to text like unneeded "pay" always tacked on to second cost.
> SNC: Dusk Mangler and support

- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ReplaceTokenEffect.java
- forge-gui/res/cardsfolder/e/esix_fractal_bloom.txt
Finally if you create token with Encore and use Esix the rest (Haste, MustAttack & Exile trigger) is now still applied to other choice too.
> Fix Esix replacing too much from other effects

- forge-gui/res/cardsfolder/upcoming/jetmirs_fixer.txt
- forge-gui/res/cardsfolder/upcoming/psionic_snoop.txt
- forge-gui/res/cardsfolder/upcoming/sewer_crocodile.txt
- forge-gui/res/cardsfolder/upcoming/sparas_adjudicators.txt
Jetmir's Fixer - causing crash from deck editor because of no cost in A:AB$ Branch
Sewer Crocodile - removed redundant SubAbility$ DBEffect
Psionic Snoop - Added missing Flash keyword
Spara's Adjudicators - EtB wasn't working
> SNC card fixes

- forge-game/src/main/java/forge/game/zone/Zone.java
Because tokens are now also copied the new one kept Battlefield as zone.
> Always change zone of cards when they move

- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
These parts haven't been needed since a long time when Exalted got converted to real trigger which the AI is able to predict correctly with the better checks that follow there. So this stops misplays like this example:
> Remove duplicate exalted calculation

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/GameState.java
- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- forge-ai/src/main/java/forge/ai/ability/ZoneExchangeAi.java
- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/GameEntity.java
- forge-game/src/main/java/forge/game/ability/effects/AttachEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
- forge-game/src/main/java/forge/game/ability/effects/ZoneExchangeEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardPredicates.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/player/PlayerPredicates.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
- forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/GameWrapper.java
Closes #136
> 702.6e “Equip planeswalker” is a variant of the equip ability. “Equip planeswalker [cost]” means “[Cost]: Attach this permanent to target planeswalker you control as though that planeswalker were a creature. Activate only as a sorcery.”
Thinking about it, there isn't a way for it to cause a problem with it
it either fails because the target becomes invalid, or there isn't another way for it to attach something to a planeswalker (because most stuff checks for creatures anyway)
> canEquip checks for SpellAbility

- forge-game/src/main/java/forge/game/GameAction.java
Is this fix safe?
Tested with _Tayam, Luminous Enigma_ and it also still got vigilance counter
> GameAction: Add ETB counters before checking statics

- forge-gui-mobile/src/forge/adventure/pointofintrest/PointOfInterestChanges.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/world/World.java
This will revert shops back to being handled consistently. Temporary solution, most changes are code re-arranging to prepare for more drastic changes.
The current design for shops doesn't allow for easy dynamic changes, it's going to need to be rewritten so PointOfInterestChanges saves the type and current contents of a shop. As it is, a world will always generate a limited amount of cards unless that's done.
> Adventure mode - Revert RNG

- forge-gui/res/cardsfolder/a/artillery_enthusiast.txt
- forge-gui/res/cardsfolder/c/captain_eberhart.txt
- forge-gui/res/cardsfolder/c/citystalker_connoisseur.txt
- forge-gui/res/cardsfolder/e/experimental_pilot.txt
- forge-gui/res/cardsfolder/g/garruk_wrath_of_the_wilds.txt
- forge-gui/res/cardsfolder/g/geist_of_regret.txt
- forge-gui/res/cardsfolder/p/painful_bond.txt
- forge-gui/res/cardsfolder/rebalanced/a-omnath_locus_of_creation.txt
- forge-gui/res/cardsfolder/s/semblance_scanner.txt
- forge-gui/res/cardsfolder/s/settle_the_wilds.txt
- forge-gui/res/cardsfolder/s/swarm_saboteur.txt
- forge-gui/res/cardsfolder/t/tireless_angler.txt
- forge-gui/res/cardsfolder/v/veteran_ghoulcaller.txt
Source: https://magic.wizards.com/en/articles/archive/magic-digital/alchemy-rebalancing-may-5-2022
All cards are Alchemy only so no need for new scripts
> Alchemy Rebalancing for May 5, 2022

- forge-ai/src/main/java/forge/ai/ability/PeekAndRevealAi.java
- forge-gui/res/cardsfolder/c/candles_of_leng.txt
- forge-gui/res/cardsfolder/d/depala_pilot_exemplar.txt
- forge-gui/res/cardsfolder/e/epiphany_at_the_drownyard.txt
- forge-gui/res/cardsfolder/o/orcish_spy.txt
- forge-gui/res/cardsfolder/p/prophecy.txt
- forge-gui/res/cardsfolder/v/visions.txt
- forge-gui/res/cardsfolder/w/wand_of_denial.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Not sure why only mobile had this changed, but passing min also for max there seems like a simple oversight...?
> Fix chooseCardsToDiscardFrom

- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
- forge-gui/res/cardsfolder/h/howling_mine.txt
- forge-gui/res/cardsfolder/m/mana_vault.txt
- forge-gui/res/cardsfolder/n/nim_abomination.txt
- forge-gui/res/cardsfolder/s/sphinx_sovereign.txt
- forge-gui/res/cardsfolder/upcoming/syndicate_infiltrator.txt
- forge-gui/res/cardsfolder/v/voodoo_doll.txt
> If Sphinx Sovereign is no longer on the battlefield by then, the ability checks whether Sphinx Sovereign was tapped or untapped at the time it left the battlefield.
> Update some older cards to use LKI correctly

- forge-gui/res/cardsfolder/upcoming/tenuous_truce.txt
What do we think about `Defined$ This,That` with the comma for a split?
Seems we could go back and clean up many files using stuff like `TargetedAndYou`
Also things where we use the same effect/params twice but for different Defined$ (if there are any of those... seems there may be)
closes #230
> NCC: Tenuous Truce

- forge-game/src/main/java/forge/game/ability/effects/AnimateEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/MillEffect.java
- forge-gui/res/cardsfolder/b/blood_for_bones.txt
- forge-gui/res/cardsfolder/b/blood_on_the_snow.txt
- forge-gui/res/cardsfolder/b/bond_of_insight.txt
- forge-gui/res/cardsfolder/c/cauldrons_gift.txt
- forge-gui/res/cardsfolder/c/connive_concoct.txt
- forge-gui/res/cardsfolder/c/corpse_dance.txt
- forge-gui/res/cardsfolder/e/eerie_ultimatum.txt
- forge-gui/res/cardsfolder/f/forbidden_friendship.txt
This all kind of grew from making the upcoming Summon Undead (#255) generate a good stack description
**Animate** should less frequently generate a weird sentence fragment as it also looks for Defined now... cards like Corpse Dance will just need a DefinedDesc as their Defined won't be populated at the time of building the Stack Description
**ChangeZone (Hidden from Graveyard)** some more tweaks here – might be worth figuring out a way to move "WithCountersType" out a little to catch more possibilities, that's for another time
**Mill** adds "may" for Optional and tossed in the general IfDesc thing
> various getStackDescription improvements

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui/res/adventure/Shandalar/ui/hud_landscape.json
Make GameHud controls/layout for Android landscape mode identical to Android portrait mode. Desktop Adventure mode retains previous layout and controls.
> [Adventure] Refactor GameHud

- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
- forge-gui/res/cardsfolder/w/witness_the_future.txt
A simple tweak to make the card playable - since the Pump here is "fake", the ordinary AI rules for its playability clashed with those of ChangeZone+Dig :)
> Make Witness the Future AI playable.

- forge-gui/res/cardsfolder/upcoming/parnesse_the_subtle_brush.txt
- forge-gui/res/cardsfolder/upcoming/syrix_carrier_of_the_flame.txt
A few pretty fiddly ones... no engine changes, though
We might potentially do Syrix later with:
```
SVar:X:Count$ThisTurnEntered_Any_from_Graveyard_Creature.YouOwn
```
Just need to support `Any` there
closes #303 
closes #304
> NCC: 9 April

- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
> You can't cast an instant (or activate an ability as an instant) while casting a spell. Therefore, much like Lion's Eye Diamond, you can't activate the ability intending to use the mana to cast a spell from your hand. 
E.g. you could cheat by starting to cast a Sol Ring from your hand and then paying with _Lion's Eye Diamond_.
> Fix missing check for mana abilities at instant speed

- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/CountersPutOrRemoveAi.java
- forge-ai/src/main/java/forge/ai/ability/CountersRemoveAi.java
- forge-ai/src/main/java/forge/ai/ability/PermanentAi.java
- forge-ai/src/main/java/forge/ai/ability/RepeatAi.java
- forge-ai/src/main/java/forge/ai/ability/SetStateAi.java
- forge-core/src/main/java/forge/card/CardDb.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/GlobalRuleChange.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardPredicates.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityIgnoreLegendRule.java
- forge-gui/res/cardsfolder/b/brothers_yamazaki.txt
- forge-gui/res/cardsfolder/m/mirror_box.txt
- forge-gui/res/cardsfolder/m/mirror_gallery.txt
- forge-gui/res/cardsfolder/s/sakashima_of_a_thousand_faces.txt
Closes #331
Handle Ignore Legend Rule as Static Ability.
Also do corner cased with Spy Kit
I think one corner case is missing if i have 2 legendary both equipped with Spy Kit. Currently these are checked for empty names. Should Probably for all of them
> Card: ignoreLegendRule as StaticAbility

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/PermanentAi.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-gui/res/cardsfolder/h/hematite_talisman.txt
- forge-gui/res/cardsfolder/s/shreds_of_sanity.txt
- forge-gui/res/cardsfolder/t/tezzeret_betrayer_of_flesh.txt
This fixes cheating when using multiple mana abilities from artifacts during one payment.
E.g. you could have activated _Doubling Cube_ for {1} and paid that with _Prismite_ for {0} still
> Fix Tezzeret, Betrayer of Flesh

- forge-game/src/main/java/forge/game/ability/effects/EncodeEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/s/skeletonize.txt
For reference the previous version only returned if it was true:
```diff
-            final CardType type = face.getType();
-            if (type.isCreature() && !type.isLegendary())
-                return true;
+            return StaticData.instance().getCommonCards().isNonLegendaryCreatureName(name);
```
so I think we can just let the other overloaded one handle it
> Spy Kit Fix

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-gui/res/cardsfolder/upcoming/rain_of_riches.txt
Need to track spells cast with mana from treasure each turn
We could expand the Card Property to ManaFrom<Whatever> if need arises later
closes #418
> NCC: Rain of Riches and support

- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
When casting multiple spells, each card is put on the stack after another.
So I think e. g. _Chandra Ablaze_ should be able to trigger _Tormod, the Desecrator_ also more than once.
> PlayEffect: add TriggerChangesZoneAll

- forge-game/src/main/java/forge/game/ability/effects/ControlGainEffect.java
- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/seize_the_spotlight.txt
- forge-gui/res/cardsfolder/upcoming/turf_war.txt
added non-targeted "Choices" to ControlGainEffect - for now choice is always 1 card, can be expanded later if need be
this might mean the AI needs some tweaking too?
closes #433
closes #449
> NCC: Seize the Spotlight and support

- forge-core/src/main/java/forge/ImageKeys.java
- forge-gui/src/main/java/forge/gui/download/GuiDownloadPicturesLQ.java
- Replaces a repeated directory scan and HashSet creation (over a directory that probably has thousands of files) with a File.exists() check. This gets called ~10 times _for each card_ on every image set download attempt.  On my (Windows) machine, this change reduced the time it took to determine image files that need to be downloaded from ~30 minutes to ~10 seconds
- Also cleans out some data structures in the LQ image downloader that weren't being used
> Stop unnecessarily directory scanning 1000s of times when downloading images

- forge-ai/src/main/java/forge/ai/ability/DestroyAi.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/PlayerProperty.java
- forge-gui/res/cardsfolder/a/assassins_blade.txt
- forge-gui/res/cardsfolder/b/bearer_of_the_heavens.txt
- forge-gui/res/cardsfolder/c/champions_victory.txt
- forge-gui/res/cardsfolder/c/command_of_unsummoning.txt
- forge-gui/res/cardsfolder/c/cryptic_gateway.txt
- forge-gui/res/cardsfolder/d/deep_wood.txt
- forge-gui/res/cardsfolder/d/defiant_stand.txt
- forge-gui/res/cardsfolder/e/eightfold_maze.txt
- forge-gui/res/cardsfolder/h/harsh_justice.txt
- forge-gui/res/cardsfolder/h/heavy_fog.txt
- forge-gui/res/cardsfolder/h/holistic_wisdom.txt
- forge-gui/res/cardsfolder/j/just_fate.txt
- forge-gui/res/cardsfolder/k/kongmings_contraptions.txt
- forge-gui/res/cardsfolder/r/rally_the_troops.txt
- forge-gui/res/cardsfolder/r/remove.txt
- forge-gui/res/cardsfolder/s/scorching_winds.txt
- forge-gui/res/cardsfolder/s/sigardian_zealot.txt
- forge-gui/res/cardsfolder/t/treetop_defense.txt
- forge-gui/res/cardsfolder/v/vigorous_charge.txt
- forge-gui/res/cardsfolder/v/viridian_zealot_avatar.txt
- forge-gui/res/cardsfolder/w/warriors_stand.txt
@Hanmac
Doing it as PlayerProperty felt cleaner instead of ``ActivatorWasAttackedThisCombat$ True``
But I wasn't sure if ``checkActivatorRestrictions`` needs changing because of that [MayPlay part](https://github.com/Card-Forge/forge/blob/875f6c78c092f88631007ad3133ef5eba3ed0986/forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java#L353) (I couldn't find a case where it was even making a difference)
> wasAttackedThisCombat restriction for multiplayer

- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-core/src/main/java/forge/card/CardRulesPredicates.java
- forge-core/src/main/java/forge/card/DeckHints.java
1. DeckHas for other Types besides Ability$ finally works
2. DeckHas no longer requires exact matching to have an effect but cards that care about multiple entries for a given type will be judged higher if a card seems to provide even "more" synergy for it.
Example:
_Chishiro_ has two abilities so ``DeckHas:Ability$Token & Ability$Counters`` is used, therefore score for ``DeckNeeds:Ability$Token|Counters`` is increased
4. if for some reason you want a type more than once in DeckHas/DeckNeeds you can do so now
this will provide the intersection of both e.g.
``DeckNeeds:Type$Human & Type$Warrior`` will only find Human Warrior compared to ``DeckNeeds:Type$Human|Warrior`` which will match either like before
> AiHints upgrade

- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-game/src/main/java/forge/game/trigger/TriggerTapsForMana.java
- forge-gui/res/cardsfolder/p/pillar_of_war.txt
- forge-gui/res/cardsfolder/p/piston_fist_cyclops.txt
If you have _Ashaya_ and activate _Deathrite Shaman_ first ability to generate mana _Vorinclex, Voice of Hunger_ or _Naked Singularity_ can both affect it.
> 106.12a. An ability that triggers whenever a permanent "is tapped for mana" or is tapped for mana of a specified type triggers whenever such a mana ability resolves and produces mana or the specified type of mana.
106.12b. A replacement effect that applies if a permanent "is tapped for mana" or tapped for mana of a specific type and/or amount modifies the mana production event while such an ability is resolving and producing mana or the specified type and/or amount of mana.
_Caged Sun_ should continue to work for non-mana abilities.
> Non-mana abilities incorrectly triggering/replaced

- forge-gui-mobile/src/forge/adventure/data/SettingData.java
- forge-gui-mobile/src/forge/adventure/scene/StartScene.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- forge-gui/res/adventure/Shandalar/ui/start_menu.json
- forge-gui/res/adventure/Shandalar/ui/start_menu_portrait.json
- forge-gui/res/languages/en-US.properties
Persist the filename of the last game that was saved in `settings.json` and, if it's not `null` and the user isn't in a game, display a continue button that loads it. 
Notes:
- `settings.json` may not be the right place to persist this, but it seems like the best fit from what I could see
- I have not localised the continue string for locales other than `en-US`
- We load the save directly from `StartScene`, which seems non-idiomatic, but creating a separate scene seems wasteful unless we want to provide other info to the user
- It's possible the desired behaviour is actually to use the most recently *loaded* filename rather than the most recently *saved*
> [Adventure] Add continue button to main menu

- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-gui/res/cardsfolder/upcoming/ellyn_harbreeze_busybody.txt
I think cards like this too easily lock in a numeral as part of the stack description. For example:
- After making one token this turn, you activate Ellyn
- Before the ability resolves, make another token at instant speed somehow
- stack description would still say "one card" but the effect would use the correct two cards
So this is less specific, but at least it won't lock in a readout of something that isn't accurate.
closes #600
> CLB: Ellyn Harbreeze, Busybody and DigEffect stackDesc update

- forge-gui/res/quest/duels/Evangelyne 3.dck
Quest deck 'Evangelyne (hard)' was missing then [main] tag in its .dck file.
As a result, AI's library was empty and the player won turn 0, because AI could not draw a card. The player also got a ton of achievements -- win by turn 0, win without playing any spells, win while having 0 lands, etc -- and a ton of gold (about 1700).
The game log typically looked like this:
> Phase: Jakob's Untap step
> Turn: Turn 1 (Jakob)
> Match result: Jakob: 1 Evangelyne: 0 
> Game outcome: **Evangelyne has lost trying to draw cards from empty library**
> Game outcome: Jakob has won because all opponents have lost
> Game outcome: **Turn 0**
> Player control: Evangelyne is controlled by Evangelyne
> Player control: Jakob is controlled by Jakob
> Mulligan: **Evangelyne has kept a hand of 0 cards**
> …
> Fixed quest deck 'Evangelyne (hard)'

- forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
- forge-game/src/main/java/forge/game/GameEntityCounterTable.java
- forge-game/src/main/java/forge/game/card/CardDamageHistory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/player/PlayerProperty.java
- forge-gui/res/cardsfolder/a/ancient_brass_dragon.txt
- forge-gui/res/cardsfolder/b/bess_soul_nourisher.txt
- forge-gui/res/cardsfolder/t/the_fallen.txt
Most importantly, added manual cleanup because unfortunately every single card has to track its damage dealt for the whole game for this unique ability.
This helps with earlier Garbage Collection, which can be quite a few Card and related objects like View or State etc.
> Fix The Fallen ignoring planeswalkers

- forge-game/src/main/java/forge/game/ability/effects/ChangeCombatantsEffect.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCantBeCast.java
- forge-gui/res/cardsfolder/c/capricopian.txt
- forge-gui/res/cardsfolder/c/chronozoa.txt
- forge-gui/res/cardsfolder/e/epic_experiment.txt
- forge-gui/res/cardsfolder/m/martial_impetus.txt
> The player Capricopian is attacking can’t reselect it to attack a planeswalker instead. If Capricopian is attacking a planeswalker, no player may activate its last ability.
> Capricopian PW fix

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/m/mogg_assassin.txt
- forge-gui/res/cardsfolder/s/searing_blaze.txt
- forge-gui/res/cardsfolder/upcoming/ancient_bronze_dragon.txt
- forge-gui/res/cardsfolder/y/yosei_the_morning_star.txt
Closes #714
Yosei not tapping if player gains hexproof:
> If the player becomes an illegal target, the target permanents are tapped, but the player doesn’t skip their untap step.
> Fix scripts

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/GameEntityCounterTable.java
- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/replacement/ReplaceAddCounter.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
Fixes last part of #668
I found the corner case i have been looking for, because i was only testing it with Mowu, Loyal Companion:
> Mowu, Loyal Companion
> Because Mowu’s replacement effect affects only Mowu, it will apply if Mowu somehow enters the battlefield with one or more +1/+1 counters on it and give Mowu an additional +1/+1 counter. 
This one should apply
> Conclave Mentor
> Conclave Mentor’s first ability doesn’t apply to itself if it’s somehow entering the battlefield with a +1/+1 counter on it. 
This should not
> Winding Constrictor
> Winding Constrictor’s effect can’t apply to itself as it’s entering the battlefield or to any other permanent entering the battlefield at the same time as it.
This also not
for this i look back at LastStateBattlefield if the hostCard of the …
> GameAction: better handle etb counter + doubler + same time

- forge-core/src/main/java/forge/card/CardType.java
- forge-game/src/main/java/forge/game/ability/effects/VentureEffect.java
- forge-gui/res/cardsfolder/upcoming/undercity.txt
Closes #254
* fixes CardType to handle "Dungeon Master" as one Type and "Dungeon Undercity" as two
* VentureEffect better handles `Venture into [quality]` with Quality be a SubType
this would also support other Undercity Dungeons
> CardType: better handling for multiword types

- forge-gui/res/cardsfolder/upcoming/gate_of_the_black_dragon.txt
- forge-gui/res/cardsfolder/upcoming/gate_to_manorborn.txt
- forge-gui/res/cardsfolder/upcoming/gate_to_seatower.txt
- forge-gui/res/cardsfolder/upcoming/gate_to_the_citadel.txt
- forge-gui/res/cardsfolder/upcoming/gate_to_tumbledown.txt
As these are "Types:Land Colour Gate" they auto have the ability to produce the colour but it doesn't show in card detail so added Text:
-closes #766 and other gates from YCLB
> YCLB Land Gate cycle

- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
You should be allowed to turn _Lumithread Field_ face up with _Humility_ in play.
> Fix unmorphing being prevented by invalid static

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/e/ertais_meddling.txt
- forge-gui/res/cardsfolder/e/evelyn_the_covetous.txt
sa.copy does reset it for copied spells
> only reset castFaceDown when making a full spell copy

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
- forge-game/src/main/java/forge/game/keyword/KeywordInterface.java
@Agetian @tool4ever 
This is for Blitz only triggering when the specific cost was paid (for this Reference to Keyword)
But there is a corner case i couldn't get working:
* Toolbox on the Field
* Cast Hill Giant with Blitz
* while on the Stack, copy the Blitz Hill Giant with Double Major
* Currently the token doesn't get Haste and trigger because the condition does fail.
but i can't find it at what place from copying the Spell, the Spell gaining Blitz on the Stack again (for this i copied the KW so the ability should give it the new one?) til the creature entering the battlefield.
somewhere i get the wrong static ability with a different keyword instance
can some one of you debug it?
> Blitz Again, check for Keyword

- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-gui/res/cardsfolder/upcoming/vhal_candelkeep_researcher.txt
closes #710
The AI seems to be able to use this legally, though it prioritizes tapping down lands first and then using the restricted mana, so kind of an ai-dumb-not-cheating type of thing.
Here it tapped three plains and only used 1 of its Vhal mana to cast Chapel Shieldgeist 3 W - it would have been "smarter" to use all the Vhal mana and only tap one of its plains.
I have it marked as RemoveDeck:Random since not every deck uses cast from other zones mechanics.
> CLB: Vhal, Candlekeep Researcher and support

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkin.java
- forge-gui-mobile/src/forge/assets/FSkinFont.java
- forge-gui-mobile/src/forge/assets/FSkinTexture.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- forge-gui-mobile/src/forge/card/CardRenderer.java
- forge-gui-mobile/src/forge/screens/SplashScreen.java
-fixes memory leaks since these objects are not properly disposed by the GC
-Textures, BitmapFonts and others should be disposed manually if not loaded in the assetmanager
> refactor libgdx static objects to be disposed

- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
https://github.com/Card-Forge/forge/blob/7f9d327e43a550f438836d9ba20f52493a2da42c/forge-game/src/main/java/forge/game/trigger/TriggerAttackerBlockedOnce.java#L36
calls this label, but it hadn't been added
> add lblAttacker from TriggerAttackerBlockedOnce

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-gui/res/cardsfolder/d/djerus_resolve.txt
- forge-gui/res/cardsfolder/g/godtoucher.txt
- forge-gui/res/cardsfolder/h/harvestguard_alseids.txt
- forge-gui/res/cardsfolder/i/indestructible_aura.txt
- forge-gui/res/cardsfolder/p/piston_fist_cyclops.txt
- forge-gui/res/cardsfolder/s/shielded_passage.txt
- forge-gui/res/cardsfolder/w/wellgabber_apothecary.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
The checkRestrictions() was too early before it was on the stack, so the static couldn't prevent it.
I've decided to change it by doing rollback cleanly like HumanController if it fails, which seems to work fine.
Closes #1088
Also cleaned up some more outdated damage KW.
> Fix AI casting suspended spells against Drannith Magistrate

- forge-game/src/main/java/forge/game/ability/effects/ChooseCardEffect.java
- forge-gui/res/cardsfolder/upcoming/call_to_the_void.txt
- Created CardScript for call to the void.
- Added "ControlAndNot" parameter to ChooseCardEffect as suggested by @northmoc on discord (https://discord.com/channels/267367946135928833/994588726254633090/994610830815539370)
- Added and implemented "SecretlyChoose" in ChooseCardEffect.
- Added RevealTitle to ChooseCardEffect.
> Card script for Call to the Void and changes to ChooseCardEffect to enable card mechanisms.

- forge-gui/res/editions/Jumpstart Historic Horizons.txt
- forge-gui/res/editions/Modern Horizons 2.txt
I have moved the two rebalanced cards from MH2 to J21 so that they show up as legal in Historic and not Modern. It makes no sense to have them in MH2 (even though Scryfall lists them there) as the set is not in Arena but J21 is (where these two cards are part of the set)
> Move MH2 rebalanced to J21

- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
1. Fixes _Giada, Font of Hope_:
if multiple angels ETB together they don't see each other
2. I noticed cases where StaticAbilityContinuous kept checking stuff, even if there was nothing to affect.
E. g. _Heroes' Podium_ if you control no legendary creature it would still call into `AbilityUtils.calculateAmount` and then still deeper into `CardProperty`
> LastState: pass through from GameAction into ReplacementHandler & performance fixes

- forge-game/src/main/java/forge/game/ability/effects/TwoPilesEffect.java
- forge-gui/res/cardsfolder/a/atris_oracle_of_half_truths.txt
- forge-gui/res/cardsfolder/b/boneyard_parley.txt
- forge-gui/res/cardsfolder/b/brilliant_ultimatum.txt
- forge-gui/res/cardsfolder/c/choose_your_demise.txt
- forge-gui/res/cardsfolder/e/epiphany_at_the_drownyard.txt
- forge-gui/res/cardsfolder/f/fact_or_fiction.txt
- forge-gui/res/cardsfolder/f/fight_or_flight.txt
- forge-gui/res/cardsfolder/f/fortunes_favor.txt
- forge-gui/res/cardsfolder/j/jace_architect_of_thought.txt
- forge-gui/res/cardsfolder/l/liliana_of_the_veil.txt
- forge-gui/res/cardsfolder/m/make_an_example.txt
- forge-gui/res/cardsfolder/p/phyrexian_portal.txt
- forge-gui/res/cardsfolder/r/raging_river.txt
- forge-gui/res/cardsfolder/s/sphinx_of_uthuun.txt
- forge-gui/res/cardsfolder/s/stand_or_fall.txt
- forge-gui/res/cardsfolder/s/steam_augury.txt
- forge-gui/res/cardsfolder/u/unesh_criosphinx_sovereign.txt
- forge-gui/res/cardsfolder/u/urza_academy_headmaster.txt
- forge-gui/res/cardsfolder/upcoming/split_the_spoils.txt
Seems more straightforward to always handle cleaning up remembering after pile subabilities similar to RepeatEach... might be nice to add a further param to avoid the host clear remembered for the few here that are messing with imprinted, but that is for another day.
-closes #944
> TwoPiles streamline (+ CLB Split the Spoils)

- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- for mobile backport, hover the card and left click to switch the tooltip
- for android, double tap the image before holdtouching to switch tooltip
> support showing back face on shops and loot on adventure mode

- forge-core/src/main/java/forge/ImageKeys.java
- forge-gui-mobile/src/forge/util/LibGDXImageFetcher.java
- removed unnecessary keys for 2nd variants displaying first art.
should fix displaying duplicated art when using image fetcher
> fix LibGDXImageFetcher not deleting .tmp files

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- support for tall phones, ultra wide and unfolded screen (11.2:9)
- tested with simulated display aspect ratio of (4:3, 5:4, 16:9, 16:10, 18:9, 19:9, 21:9)
> update RewardScene & RewardActor for various screen display

- forge-game/src/main/java/forge/game/card/Card.java
Another thing that could have been exploited with (but not limited to) _Myrkul, Lord of Bones_ by e.g. creating a copy of _Leafkin Avenger_ that could still deal damage with its ability.
> Fix noncreature permanents having P/T

- forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
- forge-gui/res/cardsfolder/upcoming/celestial_vault.txt
- closes #777 
I have wondered if Draft stuff should start in None zone, then go to Hand, THEN go to the zone specified by cards like this
Stinking digital-only no CR support :(
> YSNC: Celestial Vault and support

- forge-gui-mobile/src/forge/adventure/data/SettingData.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- user can adjust the values seperately for landscape or portrait mode
> landscape and portrait settings for reward/shop card display/tooltips

- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- either due to being corrupted, invalid header or libgdx failed to load dependency (wrong path, etc..)
> catch unloaded card images

- forge-gui-mobile/src/forge/assets/Assets.java
- if not using classpath, it will fail to get the fallback_skin hidden inside the jar, to prevent crash use dummy instead;
> prevent startup crash adventure (ExceptionInInitializerError)

- forge-gui/res/cardsfolder/upcoming/herald_of_vengeance.txt
This is the one that cares about "the same name as a permanent that dealt damage to you last turn."
Done here with statics... should be fine as long as there isn't a way to make this card with MakeCard?
We may need to make this more official somewhere rather than storing the pertinent data on the card.
- closes #778
> YSNC: herald_of_vengeance.txt

- forge-gui/res/cardsfolder/rebalanced/a-baleful_beholder.txt
- forge-gui/res/cardsfolder/rebalanced/a-blessed_hippogriff_tyrs_blesing.txt
- forge-gui/res/cardsfolder/rebalanced/a-carnelian_orb_of_dragonkind.txt
- forge-gui/res/cardsfolder/rebalanced/a-circle_of_the_land_druid.txt
- forge-gui/res/cardsfolder/rebalanced/a-dragonborn_looter.txt
- forge-gui/res/cardsfolder/rebalanced/a-druidic_ritual.txt
- forge-gui/res/cardsfolder/rebalanced/a-emerald_dragon_dissonant_wave.txt
- forge-gui/res/cardsfolder/rebalanced/a-eyes_of_the_beholder.txt
- forge-gui/res/cardsfolder/rebalanced/a-goggles_of_night.txt
- forge-gui/res/cardsfolder/rebalanced/a-guildsworn_prowler.txt
- forge-gui/res/cardsfolder/rebalanced/a-jade_orb_of_dragonkind.txt
- forge-gui/res/cardsfolder/rebalanced/a-kenku_artificer.txt
- forge-gui/res/cardsfolder/rebalanced/a-lantern_of_revealing.txt
- forge-gui/res/cardsfolder/rebalanced/a-lapis_orb_of_dragonkind.txt
- forge-gui/res/cardsfolder/rebalanced/a-manticore.txt
- forge-gui/res/cardsfolder/rebalanced/a-navigation_orb.txt
- forge-gui/res/cardsfolder/rebalanced/a-pseudodragon_familiar.txt
- forge-gui/res/cardsfolder/rebalanced/a-sigil_of_myrkul.txt
- forge-gui/res/cardsfolder/rebalanced/a-split_the_spoils.txt
- forge-gui/res/cardsfolder/rebalanced/a-steadfast_unicorn.txt
- forge-gui/res/cardsfolder/rebalanced/a-you_come_to_a_river.txt
- forge-gui/res/cardsfolder/rebalanced/a-young_blue_dragon_sand_augury.txt
- forge-gui/res/cardsfolder/rebalanced/a-young_red_dragon_bathe_in_gold.txt
- forge-gui/res/cardsfolder/upcoming/blessed_hippogriff_tyrs_blesing.txt
- forge-gui/res/cardsfolder/upcoming/circle_of_the_land_druid.txt
- forge-gui/res/cardsfolder/y/you_come_to_a_river.txt
- forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt
Source: https://magic.wizards.com/en/articles/archive/magic-digital/alchemy-rebalancing-august-11-2022-08-10
**Not in this PR**:
- Cabaretti Revels (in another PR)
- Racketeer Boss (in another PR)
- Alora, Rogue Companion (Specialize not yet implemented)
- Vhal, Eager Scholar (Specialize not yet implemented)
- Dragonborn Immolator (not yet scripted)
- Water Weird (not yet scripted)
> Alchemy Rebalancing for August 11, 2022

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCantTarget.java
- forge-gui/res/cardsfolder/d/dream_leash.txt
- forge-gui/res/cardsfolder/e/enthralling_hold.txt
- forge-gui/res/cardsfolder/r/roil_elemental.txt
Currently you can make it fizzle.
> The middle ability of Enthralling Hold affects only the choice of target as the spell is cast. **If the creature becomes untapped before the spell resolves, it still resolves.** If a player is allowed to change the spell's target while it's on the stack, they may choose an untapped creature. If you put Enthralling Hold onto the battlefield without casting it, you may attach it to an untapped creature.
> CantTarget "as you cast it" is checked on resolve

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/world/WorldSaveHeader.java
- on some android devices, it doesn't support RGBA Framebuffer, this should fix the lastScreenTexture rendering black
> fix captured image

- forge-gui-mobile/src/forge/adventure/world/WorldSaveHeader.java
- take screenshot and redraw it on a new framebuffer so it renders properly on some android devices that don't support RGBA framebuffer directly.
> fix save preview for some android devices

- forge-gui-mobile/src/forge/adventure/world/WorldSaveHeader.java
- the screenshot is already flipped to render correctly so we don't need to flip it again
> fix autosave flip preview

- forge-gui/res/editions/Celebration Cards.txt
Added Post Malone's custom card to PCEL set.
Source: https://scryfall.com/card/pcel/8/zur-the-enchanter
> Post the Enchanter

- forge-gui/res/editions/Love Your LGS 2022.txt
Removed these cards as the JP versions were put in the edition incorrectly by Scryfall and have since been taken out.
> Fix PLG22 edition

- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Fixes an issue where cards cheated into play by dev mode on their back side wouldn't be set as back side, breaking "dies" triggers because LKI was always original state. Prior to this patch, this trigger would not happen:
> Dev Mode fix for cards cheated in transformed/modal

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/impede_momentum.txt
This adds the Effect for Stun Counter
for the color, i don't know yet, maybe something blueish?
AI logic should not be needed, it is registered as Negative.
The Replacement Effects from Counters are marked as Secondary so they don't pollute the Card description
Closes #1355
> Card: add Stun Counter Effect

- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-gui/res/cardsfolder/upcoming/karn_living_legacy.txt
- forge-gui/res/lists/TypeLists.txt
- forge-gui/res/tokenscripts/c_a_powerstone.txt
DMU: Add script for Karn, Living Legacy, his Powerstone token, and engine support for mana restriction "can't be spent to cast nonartifact spells."
- Karn, Living Legacy
- Powerstone token closes #1375
- AbilityManaPart.java small addition
> DMU: Karn, Living Legacy + Powerstone token, engine support

- forge-game/src/main/java/forge/game/player/RegisteredPlayer.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
In my testing, dungeon effects that add cards to the field weren't working (such as in the "Skep" dungeon). I think this broke when [!1319](https://github.com/Card-Forge/forge/pull/1319) was merged, which added an additional call to `RegisteredPlayer.setCardsOnBattlefield()` to cover equipment effects, which happens after the dungeon effects. This function replaces the existing list each time, so we were never getting the cards from the dungeon effect.
I fixed this by changing the function call to `RegisteredPlayer.addExtraCardsOnBattlefield()`, which I thought would be able to add to the list each time. Unfortunately, this had the same behaviour as the "set" call, replacing the list each time. So I changed the behaviour of that call so that it adds to the cards on the battlefield each …
> Adventure: Fix Dungeon Effect that adds Creatures to the field

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
This fixes a logic error so that the "Card Reward Bonus" will cap out at 3. See the comment here, which suggests it should be max 3: https://github.com/Card-Forge/forge/blob/0c3536a561a947c84cdf922956ba2a6d3ccbb1eb/forge-gui-mobile/src/forge/adventure/data/EffectData.java#L21
Previous logic returned `Math.max(result, 3)` which has the effect of always returning at least 3. What we need is `Math.min(result, 3)` which ensures only values less than or equal to 3 can be returned.
In-game, this resulted in 3 more deck card rewards than intended whenever you defeat an enemy.
> Adventure: Fix "Card Reward Bonus" to properly max at 3

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/menu/FMenuBar.java
- forge-gui-mobile/src/forge/screens/match/MatchScreen.java
- forge-gui-mobile/src/forge/screens/match/views/VAvatar.java
- forge-gui-mobile/src/forge/toolbox/ListChooser.java
- forge-gui/release-files/GAMEPAD_README.txt
Update Controls:
L1/Left Shoulder - Select Player Panel
R1/Right Shoulder - Select Zone tabs/Show Zone Tabs
Back Button - Show Menu Tabs
Left Analog Down - Select Player (for spell/ability that needs to select player, choose player with L1/Left Shoulder first, then Left Analog Down to choose that player)
ListChooser Dialog:
DPAD Up/Down - List Item Selector
L2/Left Trigger - Ok/Confirm
R2/Right Trigger - Cancel
> add DPAD selector for gamepad in ListChooser

- forge-gui/res/cardsfolder/upcoming/kobold_warcaller.txt
- forge-gui/res/cardsfolder/upcoming/orca_siege_demon.txt
- forge-gui/res/cardsfolder/upcoming/talas_lookout.txt
- forge-gui/res/cardsfolder/upcoming/tattered_apparition.txt
- forge-gui/res/cardsfolder/upcoming/tatyova_steward_of_tides.txt
- forge-gui/res/cardsfolder/upcoming/tear_asunder.txt
- forge-gui/res/cardsfolder/upcoming/territorial_maro.txt
- forge-gui/res/cardsfolder/upcoming/tidepool_turtle.txt
- forge-gui/res/cardsfolder/upcoming/timely_interference.txt
- forge-gui/res/cardsfolder/upcoming/tolarian_geyser.txt
- forge-gui/res/cardsfolder/upcoming/tolarian_terror.txt
- forge-gui/res/cardsfolder/upcoming/tori_davenant_fury_rider.txt
Added AI:RemoveDeck:Random to Kobold Warcaller since the AI keeps activating it's ability even when all the card in the creatures in the AI's hand have haste. I've looked around a bit with AI logic in ChooseCard but coudn't find anything usefull
> DMU 10 Cards + 2 cleanup

- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-gui/res/cardsfolder/m/mirrorwing_dragon.txt
- forge-gui/res/cardsfolder/t/tatsumasa_the_dragons_fang.txt
Happens when you get the spell copied with _Ivy, Gleeful Spellthief_ and then do a zone change.
The problem was because it technically counts as token `copyCard` would be fooled and even transform the real card part into one.
> Fix mutated cards disappearing when top is token

- forge-game/src/main/java/forge/game/GameRules.java
- forge-game/src/main/java/forge/game/Match.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
In Quest Mode, you don't get warnings about cards the AI can't play well, even if Quest Decks sometimes include them. This makes Adventure Mode do the same thing. The creators of Quest and Adventure decks chose to put those cards in, so it's best just to leave out the warning. (It ruins the surprise, otherwise.)
Digging into the code, I found that currently this works via a check to `isCardPoolLimited()`, which is tied to the `GameType`. The "Quest" game type has this set to true. Doing the same approach won't work for Adventure, since Adventure selects "Constructed" as the game type, rather than "Quest". Notably, I believe Adventure wants the game type to be configurable (maybe someone will make an Oathbreaker world?), so we should not have a new game type called "Adventure".
Instead, I …
> Adventure: Don't warn about cards the AI can't play well

- forge-ai/src/main/java/forge/ai/ability/DamageAiBase.java
- forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
- forge-gui/res/cardsfolder/f/fiery_justice.txt
[Fiery Justice](https://scryfall.com/card/2x2/212/fiery-justice) is a cool and unique card. This adds logic so the AI plays it reasonably well. 
Before this, the AI would cast Fiery Justice with all the damage going to the opponent, which is useless (unless life gain is prevented or reversed). The AI now avoids this behaviour via two new similar but slightly different checks in the damage AI code, based on a new "OpponentGainLife" AILogic string:
1. In `DamageAiBase.shouldTargetP()`, avoid targeting players unless life gain is not beneficial for that player. That makes the AI prioritize targeting creatures in those cases, throwing only leftover damage to the opponent.
2. At the end of `DamageDealAi.damageChoosingTargets()`, check if we're targeting only the opponent, and don't do that if …
> Add AI support for Fiery Justice

- forge-core/src/main/java/forge/ImageKeys.java
- forge-core/src/main/java/forge/StaticData.java
- forge-core/src/main/java/forge/item/IPaperCard.java
- forge-core/src/main/java/forge/item/PaperCard.java
- forge-core/src/main/java/forge/item/PaperToken.java
- forge-core/src/main/java/forge/util/ImageUtil.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-gui-desktop/src/main/java/forge/ImageCache.java
- forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/DeckHtmlSerializer.java
- forge-gui-desktop/src/main/java/forge/toolbox/imaging/FImageUtil.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui/src/main/java/forge/gui/download/GuiDownloadPicturesHQ.java
- forge-gui/src/main/java/forge/gui/download/GuiDownloadPicturesLQ.java
- forge-gui/src/main/java/forge/gui/download/GuiDownloadSetPicturesLQ.java
- forge-gui/src/main/java/forge/util/ImageFetcher.java
**UPDATE 9/6/22**
Works for local images
Works for images on the FTP
Does not auto-download from Scryfall (I think I will leave that for a different PR/someone else)
> HBG: Specialize face images for local/FTP

- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-gui/res/cardsfolder/a/ashling_the_extinguisher.txt
- forge-gui/res/cardsfolder/b/balefire_dragon.txt
- forge-gui/res/cardsfolder/c/cephalid_constable.txt
- forge-gui/res/cardsfolder/c/commando_raid.txt
- forge-gui/res/cardsfolder/d/dawning_purist.txt
- forge-gui/res/cardsfolder/e/emissary_of_despair.txt
- forge-gui/res/cardsfolder/e/emissary_of_hope.txt
- forge-gui/res/cardsfolder/e/etrata_the_silencer.txt
- forge-gui/res/cardsfolder/h/hellkite_tyrant.txt
- forge-gui/res/cardsfolder/h/hoard_hauler.txt
- forge-gui/res/cardsfolder/k/kappa_tech_wrecker.txt
- forge-gui/res/cardsfolder/l/lightwielder_paladin.txt
- forge-gui/res/cardsfolder/m/mairsil_the_pretender.txt
- forge-gui/res/cardsfolder/m/mindleech_mass.txt
- forge-gui/res/cardsfolder/m/mistblade_shinobi.txt
- forge-gui/res/cardsfolder/m/mordant_dragon.txt
- forge-gui/res/cardsfolder/n/narset_of_the_ancient_way.txt
- forge-gui/res/cardsfolder/o/o_kagachi_vengeful_kami.txt
- forge-gui/res/cardsfolder/r/riptide_entrancer.txt
- forge-gui/res/cardsfolder/s/shield_mare.txt
- forge-gui/res/cardsfolder/s/shockmaw_dragon.txt
- forge-gui/res/cardsfolder/s/skirk_commando.txt
- forge-gui/res/cardsfolder/s/snapping_thragg.txt
- forge-gui/res/cardsfolder/s/soul_seizer_ghastly_haunting.txt
- forge-gui/res/cardsfolder/s/spark_mage.txt
- forge-gui/res/cardsfolder/s/standstill.txt
- forge-gui/res/cardsfolder/u/uvilda_dean_of_perfection_nassari_dean_of_expression.txt
- forge-gui/res/cardsfolder/w/wrathful_red_dragon.txt
This helps AI make correct block decision to survive in cases where the commander otherwise wouldn't be the strongest attacker.
In this example I've already dealt 14 commander damage (from two combats with the same attacks before):
Of course it could be argued that AI should not have even take those 14 just to prevent 1 more dmg by blocking the Eldrazi before that instead, but that's a bit more situational so I'll leave it at that for now. :)
> AiBlockController: check commanders in sortPotentialAttackers

- forge-gui/res/formats/Casual/Pauper.txt
Pauper:
- Aarakocra Sneak is banned.
- Stirring Bard is banned.
- Underdark Explorer is banned.
- Vicious Battlerager is banned.
Source: https://magic.wizards.com/en/articles/archive/news/september-19-2022-banned-and-restricted-announcement
> Banned and Restricted Announcement for September 19, 2022

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
E. g. when _Felidar Sovereign_ triggers and in response opponent gains control of him you usually wouldn't win the game because it would now check his life instead.
> Fix resolving trigger check using wrong controller

- forge-game/src/main/java/forge/game/card/CardDamageHistory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/b/blazing_effigy.txt
- forge-gui/res/cardsfolder/c/conquerors_galleon_conquerors_foothold.txt
- forge-gui/res/cardsfolder/k/kytheon_hero_of_akros_gideon_battle_forged.txt
> Kytheon’s first ability will count creatures that attacked but are no longer on the battlefield (perhaps because they didn’t survive combat damage being dealt). It will not count any creatures that were put onto the battlefield attacking, as those creatures were never declared as attackers.
> Kytheon Fix

- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/trigger/TriggerAbilityTriggered.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/upcoming/historians_boon.txt
Fixing this meant I also had to extend `chooseOrderOfSimultaneousStackEntry` to follow CR more strictly:
> First, each player, in APNAP order, puts each triggered ability they control with a trigger condition that isn’t another ability triggering on the stack in any order they choose. Second, each player, in APNAP order, puts all remaining triggered abilities they control on the stack in any order they choose.
> Fix AbilityTriggered failing when cause lacks targets

- forge-gui-desktop/pom.xml
Each Snapshot will now provide individual CHANGES.txt with all commits included since last release.
Currently uses standard template (markdown) but looks okay in plain text for now.
Follow-up PR can try to tweak it further, I think even GitHub integration could be supported to combine with Issue tracker.
> Maven: include git history on package

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-gui/res/cardsfolder/c/cloud_key.txt
- forge-gui/res/cardsfolder/s/stenn_paranoid_partisan.txt
- forge-gui/res/cardsfolder/u/umori_the_collector.txt
This adds basic AI support for cards that reduce costs for spells of a chosen card type. Specifically, it adds logic so that when the AI is asked to choose a card type, it recognizes if that choice is for reducing costs and in that case it picks the most common card type in its deck. It also excludes Lands in that case to avoid picking 'Land' for [Umori, the Collector](https://scryfall.com/card/iko/231/umori-the-collector).
I removed `AILogic$ MostProminentInComputerDeck` from [Umori, the Collector](https://scryfall.com/card/iko/231/umori-the-collector) since that logic wasn't working in the first place, and isn't needed in this implementation. I also marked [Cloud Key](https://scryfall.com/card/tsr/265/cloud-key) and [Stenn, Paranoid …
> Add basic AI logic for reducing costs for chosen card type

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-game/src/main/java/forge/game/ability/effects/MeldEffect.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
The problem was this would create LKI with Original State but Planeswalker type
@Hanmac
I also don't think we need the extra `setType` anymore because the `getCurrentState().copyFrom` above will already store it in a new object
> Fix crash from meld missing backside for new Urza

- forge-gui/res/formats/Archived/Arena Standard/2022-10-13.txt
- forge-gui/res/formats/Archived/Modern/2022-10-10.txt
- forge-gui/res/formats/Archived/Standard/2022-10-10.txt
Standard:
- The Meathook Massacre is banned.
Modern:
- Yorion, Sky Nomad is banned.
Source: https://magic.wizards.com/en/articles/archive/news/october-10-2022-banned-and-restricted-announcement
> Banned and Restricted Announcement for October 10, 2022

- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-gui/res/cardsfolder/e/eerie_interlude.txt
This adds additional AI logic for blink effects, focused around two common use cases:
- Get my own stuff back
- Trigger ETB effects
There was some commented-out code that tried to do this before, which I removed in favour of this. I put it above the "bounce opponent's stuff" logic since it needs to happen before that logic tampers with `list`. A few caveats:
- The original commented code was going to avoid flickering ETB creatures if they have a counter on them. I decided not to include that, since often the better move will still be to get the ETB effect again even if you lose a +1/+1 counter or something. It would be a tricky thing for the AI to evaluate in general. I think for decks built around ETB effects, this is the better way to lean.
- The AI will prefer to blink ETB creatures …
> Add additional AI logic for playing blink effects

- forge-gui/res/cardsfolder/d/diviner_of_fates.txt
They stealth rebalanced Diviner of Fates and changed its toughness. Alchemy only card so no need for another script.
Source: https://magic.wizards.com/en/articles/archive/magic-digital/mtg-arena-announcements-october-12-2022
> Rebalancing: Diviner of Fates

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-gui/res/cardsfolder/b/belbes_portal.txt
- forge-gui/res/cardsfolder/b/bloodline_shaman.txt
- forge-gui/res/cardsfolder/b/brass_herald.txt
- forge-gui/res/cardsfolder/c/cavern_of_souls.txt
- forge-gui/res/cardsfolder/h/heralds_horn.txt
- forge-gui/res/cardsfolder/k/kolvori_god_of_kinship_the_ringhart_crest.txt
- forge-gui/res/cardsfolder/m/molten_echoes.txt
- forge-gui/res/cardsfolder/r/realmwalker.txt
- forge-gui/res/cardsfolder/r/reflections_of_littjara.txt
- forge-gui/res/cardsfolder/u/unclaimed_territory.txt
- forge-gui/res/cardsfolder/u/urzas_incubator.txt
- forge-gui/res/cardsfolder/v/vexing_arcanix.txt
Improve AI logic for cavern of souls.
- Don't count token creature types when looking for most prominent creature type, since cavern of souls doesn't help with them. This is done with a new AI logic name, with cavern of souls and a few other cards being switched to it.
- Weigh cards in hand and commanders double, as they are more likely to be cast.
I tested with a Tiny Leaders deck running Geist of Saint Traft that didn't have any creature type synergy and confirmed that the changes make the AI choose Spirit for Geist, rather than Human as before.
Also some code clean up:
- Delete a couple of unused methods.
- Use getOrDefault(), addressing a TODO. I confirmed the codebase uses this already elsewhere.
> Improve AI logic for cavern of souls.

- forge-gui-desktop/src/main/java/forge/CachedCardImage.java
- forge-gui-desktop/src/main/java/forge/ImageCache.java
Fixes a bug where a card's image will be repeatedly downloaded when ImageCache would return for a reason other than the image not being present, such as when requesting a very small image. That happened in practice during the drawing a card animation, where the card is scaled during the animation.
> Image fetcher: Don't download card images that are already present.

- forge-ai/src/main/java/forge/ai/simulation/GameSimulator.java
- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
This got broken by the following refactor:
https://github.com/Card-Forge/forge/commit/79c9c914e21521c03ed219954810105fac3a639a
The result was that simulation AI was ignoring certain decision trees that involved
playing lands, leading to not considering certain lines of play and some log
messages printed to standard error. I've added a test that covers this logic to prevent
it breaking again in the future.
Also, a couple small clean ups to related tests.
> Fix simulation AI logic related to playing lands.

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
- forge-gui/res/cardsfolder/a/absorb_energy.txt
- forge-gui/res/cardsfolder/a/arcane_denial.txt
- forge-gui/res/cardsfolder/b/bottled_cloister.txt
- forge-gui/res/cardsfolder/h/heroism.txt
- forge-gui/res/cardsfolder/k/king_narfis_betrayal.txt
- forge-gui/res/cardsfolder/m/moonring_mirror.txt
- forge-gui/res/cardsfolder/s/serpents_soul_jar.txt
- forge-gui/res/cardsfolder/t/tasha_the_witch_queen.txt
- forge-gui/res/cardsfolder/t/tibalts_trickery.txt
- forge-gui/res/cardsfolder/upcoming/titania_natures_force.txt
- forge-gui/res/cardsfolder/w/witch_hunter.txt
This is so you don't get to draw cards from _Swift Silence_ if you also control _Guile_.
> Fix RememberCountered when replaced

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/spellability/OptionalCost.java
- forge-game/src/main/java/forge/game/spellability/OptionalCostValue.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/d/defiler_of_dreams.txt
- forge-gui/res/cardsfolder/d/defiler_of_faith.txt
- forge-gui/res/cardsfolder/d/defiler_of_flesh.txt
- forge-gui/res/cardsfolder/d/defiler_of_instinct.txt
- forge-gui/res/cardsfolder/d/defiler_of_vigor.txt
Some of this feels pretty boilerplate (the five different optional costs for example) and I'm sure can be improved, either now or in future when further card design forces it. But it does seem to be working correctly... and it seems like the AI should be able to handle it reasonably well.
Choosing both leads to:
If I choose both with Mistmeadow Witch (only one colored hybrid pip) -- seems right:
Saying you'll pay the 2 life, then cancelling, then casting the spell again but not choosing additional cost results in normal mana cost, so that seems good too.
> DMU: Defiler cycle and support

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/30th Anniversary Edition.txt
- forge-gui/res/editions/The Brothers War.txt
**30th Anniversary Edition**
Source: https://magic.wizards.com/en/articles/archive/news/celebrate-30-years-magic-gathering-30th-anniversary-edition-2022-10-04
"Each pack contains 15 cards, 13 cards in the modern frame—1 rare, 3 uncommons, 7 commons, and 2 basic lands—plus one basic land in the retro frame, one additional retro frame card, and a token."
**The Brothers' War**
Source: https://magic.wizards.com/en/news/feature/whats-inside-the-brothers-war-boosters
> Booster Draft for BRO & 30A

- forge-game/src/main/java/forge/game/zone/Zone.java
This fixes previous zone changes e.g.:
- Destroy your creature
- Return it to your hand
- Discard it
- _Brought Back_ is still able to target it
> Improve isCardAddedThisTurn

- forge-gui/res/quest/commanderprecons/Buckle Up [NEC] [2022].dck
- forge-gui/res/quest/commanderprecons/Cabaretti Cacophony [NCC] [2022].dck
- forge-gui/res/quest/commanderprecons/Draconic Dissent [CLB] [2022].dck
- forge-gui/res/quest/commanderprecons/Exit from Exile [CLB] [2022].dck
- forge-gui/res/quest/commanderprecons/Forces of the Imperium [40K] [2022].dck
- forge-gui/res/quest/commanderprecons/Legends' Legacy [DMC] [2022].dck
- forge-gui/res/quest/commanderprecons/Maestros Massacre [NCC] [2022].dck
- forge-gui/res/quest/commanderprecons/Mind Flayarrrs [CLB] [2022].dck
- forge-gui/res/quest/commanderprecons/Mishra's Burnished Banner [BRC] [2022].dck
- forge-gui/res/quest/commanderprecons/Necron Dynasties [40K] [2022].dck
- forge-gui/res/quest/commanderprecons/Obscura Operation [NCC] [2022].dck
- forge-gui/res/quest/commanderprecons/Painbow [DMC] [2022].dck
- forge-gui/res/quest/commanderprecons/Party Time [CLB] [2022].dck
- forge-gui/res/quest/commanderprecons/Riveteer Rampage [NCC] [2022].dck
- forge-gui/res/quest/commanderprecons/Tyranid Swarm [40K] [2022].dck
- forge-gui/res/quest/commanderprecons/Upgrades Unleashed [NEC] [2022].dck
- forge-gui/res/quest/commanderprecons/Urza's Iron Alliance [BRC] [2022].dck
This includes all the new commander decks from 2022 except the Ruinous Powers one since we are missing "Seeker of Slaanesh". 
While most of these decks can be downloaded from the net decks, these usually miss the correct art. Also this makes the decks available in Quest mode.
> 2022 Commander decks

- forge-gui/res/adventure/Shandalar/maps/map/lavaforge_1.tmx
- forge-gui/res/adventure/Shandalar/maps/map/lavaforge_2.tmx
- forge-gui/res/adventure/Shandalar/maps/tileset/buildings.atlas
- forge-gui/res/adventure/Shandalar/world/points_of_interest.json
- forge-gui/res/adventure/Shandalar/world/red.json
This adds two new dungeons in the Red biome to the default Shandalar world in Adventure mode. They both use this sprite on the overworld map:
**"LavaForge1"**: Each enemy starts with [Sulfuric Vortex](https://scryfall.com/card/ema/150/sulfuric-vortex), putting pressure on the duel, especially if you don't have a lot of life. Burn spells are especially potent. Minibosses are a Red Wizard (who plays burn), and Mindclaw Shaman, who further punishes your life total for having cards in hand.
**"LavaForge2"**: Each enemy starts with  [Burning Sands](https://scryfall.com/card/ody/180/burning-sands), making it costly to lose creatures. It's a bit frustrating if you fall behind, but fun if you can get ahead and really bully the AI decks. The Red Wizard miniboss is especially challenging when it …
> Adventure: Add two new dungeons to the Red biome

- forge-gui/res/adventure/Shandalar/maps/map/fort_5.tmx
In the dungeon called ["Fort4" ](https://github.com/Card-Forge/forge/blob/535478fda0e33ccc0a54558b15733a412185410e/forge-gui/res/adventure/Shandalar/world/points_of_interest.json#L436), there's a Demon enemy standing on a pentagram. The pentagram has a collision rectangle that prevents the player from fighting the Demon. The only way through is to sneak around it, currently:
This changes the "Fort4" dungeon slightly, while trying to stay as close as possible to the intent of the original dungeon author. I moved the pentagram sprite into the room, and re-positioned the Demon. I also fiddled with the Collision layer a little bit so that you can't sneak around the Demon.
*(Images included since the file diff doesn't show you much.)*
> Adventure: Fix collision for Demon enemy in dungeon "Fort4"

- forge-gui/res/adventure/Shandalar/world/enemies.json
I'm hesitant to submit balance fixes, but I hope this is not too controversial. There is an enemy in Adventure mode called "Doppelganger" who plays a copy of your deck and starts with 20 life on Normal difficulty. Currently, its reward is to give you one card that is a copy of a card in your deck (and sometimes some gold). This changes it so that the Doppelganger never gives you a basic land as that card. 
Note the the Doppelganger essentially gets more challenging as your deck improves, so it is always a difficult enemy. I think buffing the reward a little bit is okay.
> Adventure: [Balance] Doppelganger enemy no longer drops basic lands

- forge-gui-mobile/src/forge/adventure/data/RewardData.java
- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
Enemies and chests in Adventure mode can drop cards of color "colorID", which is determined by the color identity of the player's currently selected deck. The current logic is flawed, since it relies on `Current.player().getColorIdentityLong()`, which will return the string "multi" if the color identity contains more than one color. This can be easily verified in the Adventure console (F10) via this command `setColorID wu`. "multi" isn't a color, so it doesn't match any cards.
To avoid building up a new array of colors in RewardData, I moved the logic that checks "colorID" to the CardPredicate instead, where it's easier to interact directly with the color objects. I also added a slight tweak to logic to make it work if your color identity is colorless (without the change, it does not …
> Adventure: Fix "colorID" card rewards when a player's color identity is multicolor

- forge-gui/res/adventure/Shandalar/maps/map/dreamhalls.tmx
- forge-gui/res/adventure/Shandalar/world/points_of_interest.json
- forge-gui/res/adventure/Shandalar/world/waste.json
This adds a new dungeon called "Dream Halls" to the Wastes biome in the default Shandalar world in Adventure mode. As per its namesake, each enemy in this dungeon starts with [Dream Halls](https://scryfall.com/card/tpr/46/dream-halls) on the battlefield -- a busted card for sure, but a pretty cool symmetric effect to play around. 
Enemies in the dungeon can all make use of Dream Halls pretty well if they draw the right hand. The minibosses are the Green Wizard who normally plays ramp, and a Dragon. Each one can have a pretty explosive start, but I gave them each some minor card draw on the battlefield to give them a little push ([Arcane Encyclopedia](https://scryfall.com/card/clb/297/arcane-encyclopedia) and [Dragon's Hoard](https://scryfall.com/card/m19/232/dragons-hoard) respectively). …
> Adventure: Add new dungeon "Dream Halls" to the Wastes biome

- forge-gui/res/cardsfolder/upcoming/keeper_of_the_cadence.txt
fix toughness typo keeper_of_the_cadence.txt
Changed "PT:2/2" to "PT:2/5" to match card scan.
> fix typo from PR 1809

- forge-game/src/main/java/forge/game/GameAction.java
- forge-gui/res/cardsfolder/upcoming/creeping_bloodsucker.txt
Similar cards use `SVar:Y:Count$TotalDamageDoneByThisTurn` but since this is a permanent, I thought it might be safer to do it this way.
> J22: Creeping Bloodsucker and support

- forge-gui/res/cardsfolder/upcoming/raze_to_the_ground.txt
Mana cost is wrong. Should be 2R instead of 1R.
See: https://scryfall.com/card/bro/149/raze-to-the-ground
> Fix mana cost of Raze to the Ground

- forge-game/src/main/java/forge/game/GameFormat.java
- forge-gui-desktop/src/main/java/forge/screens/home/quest/CSubmenuQuestPrefs.java
- forge-gui-desktop/src/main/java/forge/screens/home/quest/VSubmenuQuestPrefs.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/gamemodes/quest/QuestUtil.java
- forge-gui/src/main/java/forge/gamemodes/quest/data/QuestPreferences.java
This PR includes two changes:
1. Enforcing the current world's rules for player decks. `getDeckConformanceProblemsBeforeGame()` runs the deck through the quest's `GameFormat`'s `getPoolLegalityProblem()`, which applies its `filterRules` and also checks for banned/restricted cards. Challenges with custom human decks, such as Tibalt vs Sorin don't need to pass these checks.
2. Add a new Quest Preferences setting that toggles this behavior on and off. Off by default.
Test by:
- Making a new quest with a starting pool of cards from mixed vintage/standard sets. Create a vintage deck. Travel to Alara or Random Standard. Try to run a duel. Should work. Now go to Quest Preferences and change World Rules Conformance to 1. Try to run another duel. Should fail and tell you which cards are illegal.
- …
> Enforce sets in quest

- forge-game/src/main/java/forge/game/GameFormat.java
- forge-gui-desktop/src/main/java/forge/screens/home/quest/CSubmenuQuestPrefs.java
- forge-gui-desktop/src/main/java/forge/screens/home/quest/VSubmenuQuestPrefs.java
- forge-gui/res/languages/en-US.properties
- forge-gui/res/quest/world/worlds.txt
- forge-gui/src/main/java/forge/gamemodes/quest/QuestUtil.java
- forge-gui/src/main/java/forge/gamemodes/quest/QuestUtilCards.java
- forge-gui/src/main/java/forge/gamemodes/quest/QuestWorld.java
- forge-gui/src/main/java/forge/gamemodes/quest/data/GameFormatQuest.java
- forge-gui/src/main/java/forge/gamemodes/quest/data/QuestData.java
- forge-gui/src/main/java/forge/gamemodes/quest/data/QuestPreferences.java
- forge-gui/src/main/java/forge/gamemodes/quest/setrotation/ISetRotation.java
- forge-gui/src/main/java/forge/gamemodes/quest/setrotation/QueueRandomRotation.java
Depends on #1794 being merged first.
Adds a new `ISetRotation` interface that can be used by `GameFormatQuest` to change the behavior of its own set legality checks. Adds the new quest world Evolving Wilds that uses such a combo of `GameFormatQuest` and `ISetRotation`. Basically, all core- and expansion sets are potentially legal in Evolving Wilds, but only a few at a time. After a certain number of wins, the oldest set(s) are rotated out and replaced with new ones. Both the starting sets and the rotation order is random and uses the quest name as seed.
Why?
In quest mode, I like the early game where I have to scramble a deck together and quickly upgrade it into something strong. At that point it gets a bit boring though, because it's more efficient to keep upgrading my already good deck …
> Evolving wilds world

- forge-gui/res/formats/Archived/Historic/2022-11-15.txt
- forge-gui/res/formats/Sanctioned/Historic.txt
I missed the fact that BRR is legal in Historic on Arena and also that they preemptively banned Mishra's Bauble so have fixed it. There was also a ban for Historic Brawl but we don't currently support that.
Source: https://magic.wizards.com/en/news/mtg-arena/mtg-arena-state-game-the-brothers-war
> Format changes: Add BRR and Mishra's Bauble ban to Historic

- forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
- forge-game/src/main/java/forge/game/phase/Untap.java
- forge-gui/res/cardsfolder/b/biblioplex_kraken.txt
- forge-gui/res/cardsfolder/c/captain_rex_nebula.txt
- forge-gui/res/cardsfolder/c/cuombajj_witches.txt
- forge-gui/res/cardsfolder/i/isu_the_abominable.txt
- forge-gui/res/cardsfolder/p/portcullis.txt
- forge-gui/res/cardsfolder/p/priority_boarding.txt
- forge-gui/res/cardsfolder/r/rubinia_soulsinger.txt
- forge-gui/res/cardsfolder/s/six_sided_die.txt
I checked and the ``SpellAbility.copy`` should now safely retain all that information.
Closes #2012
Closes #2016
> CharmEffect: Remove redundant code

- forge-gui/res/cardsfolder/m/molten_impact.txt
The Arena team made a small QoL rebalance of Molten Impact back in October.
"Minor quality-of-life rebalance to Molten Impact (in digital-only formats) to make it no longer force you to damage your own creatures when the opponent has an empty board"
Source:
https://mtgarena-support.wizards.com/hc/en-us/articles/5053877055380-Patch-Notes-2022-14-10
https://scryfall.com/card/yneo/22/molten-impact
> Molten Impact rebalance

- forge-gui/res/editions/Jumpstart Historic Horizons.txt
Fixes #2037
Less destructive version of #2038 as discussed [here](https://github.com/Card-Forge/forge/issues/2038#issuecomment-1340149577)
Changes:
- Swap collector numbers 22 and 23 to get correct Scryfall picture
- Remove [conjured cards](https://scryfall.com/search?order=set&q=set%3Aj21+is%3Aconjureonly&unique=prints), because their collector numbers match with different cards on Scryfall. If the images get fetched, they are wrong.
> Sync J21 to match Scryfall collector numbers [less destructive fix]

- forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
- if subgame ended via Shahrazad (or any subgame effect), restore the matchscreen view current daytime
> update daytime matchscreen view

- forge-gui/res/adventure/Shandalar/maps/map/main_story/plains_capital.tmx
- forge-gui/res/adventure/Shandalar/maps/map/swamp_town.tmx
Prior to this change, Selesnya shops are twice as frequent in plains capital, and swamp towns contain Simic (UG) shops. Neither appears to be intended.
> Removing extra shop entries from plains capital & swamp towns

- forge-gui/res/tokenscripts/zeppelin.txt
Changed card type from "Artifact Creature" to "Artifact Vehicle" to match "Lita, Mechanical Engineer" card's text.
> Fix zeppelin token script

- forge-gui/src/main/java/forge/gamemodes/quest/data/GameFormatQuest.java
After #1797 was merged, Quest mode was allowing card reprints in the spell shop and rewards that were not compliant with the current world or unlocked sets. It was unintentional and this PR fixes that. Thank you @Robbatog !
> Quest reprint fix

- forge-core/src/main/java/forge/card/CardEdition.java
- forge-core/src/main/java/forge/util/storage/StorageReaderBase.java
- forge-core/src/main/java/forge/util/storage/StorageReaderFile.java
- forge-core/src/main/java/forge/util/storage/StorageReaderFileSections.java
- forge-core/src/main/java/forge/util/storage/StorageReaderFolder.java
- forge-core/src/main/java/forge/util/storage/StorageReaderRecursiveFolderWithUserFolder.java
This moves the createMap() function up to the StorageReaderBase class and makes all subclasses call this function in readAll() to allow subclasses to override this.  We then override this in the CardEdition Reader class to create a case-insensitive map for the card sets during deck import.  This matches the way set aliases are already using a case-insensitive map, so lowercase set codes (e.g. Moxfield and other sites exports) will work for all sets during deck import.
> Make set codes case-insensitive during deck import

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui-desktop/src/main/java/forge/toolbox/FSkin.java
- fixes problem with display of Phyrexian hybrid following #1773 
- converts "life spent for Phyrexian mana" from boolean to int for loyalty calculations
- appropriate reminder text modifications for keyword display (will need to be checked against exact Oracle when it becomes available)
- closes #2106
> Compleated update/fix

- forge-gui-desktop/src/main/java/forge/deckchooser/FDeckChooser.java
- forge-gui-mobile/src/forge/deck/FDeckChooser.java
This would happen due to `split()` not including the trailing empty string if ending in a delimiter. Passing -1 as a 2nd arg fixes this. (Just avoids a printed error message, otherwise no behavior changes since the case would still result in an empty list.)
> Fix ArrayIndexOutOfBounds exception printed to stderr.

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/simulation/GameSimulator.java
- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityChoicesIterator.java
- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
This change improves Simulated AI logic by eliminating many unnecessary simulations, particularly due to:
- Invalid targets involving counterspells countering themselves (including modal spells).
- Pruning identical land drop decisions and fixing land drop logic that had resulted in duplicates.
Tests are added to cover these cases.
Some core logic is changed, in particular, SpellAbility.canTarget() was not rejecting self-targeting for counterspells. This was likely being done at a higher level somewhere (e.g. in UI code for choosing targets for the human player or AI-specific code for non-simulated AI).
A few small style clean ups are included in the code being changed.
> Simulated AI: Fix land pruning logic and skip invalid targets.

- forge-gui/res/cardsfolder/b/bloodthirsty_adversary.txt
- forge-gui/res/cardsfolder/i/intrepid_adversary.txt
- forge-gui/res/cardsfolder/p/primal_adversary.txt
- forge-gui/res/cardsfolder/s/spectral_adversary.txt
- forge-gui/res/cardsfolder/t/tainted_adversary.txt
Fixes some bugs like Necroduality + Tainted Adversary by remembering the important number straight to the trigger
> tighten up Adversary cycle from MID

- forge-gui-desktop/src/main/java/forge/itemmanager/filters/CardSetFilter.java
Null pointer exception caused a crash when trying to filter by set in the debug workshop.  Null value was in the limitedSets parameter being passed in.
> Fix crash when filtering card sets in workshop

- forge-ai/src/main/java/forge/ai/GameState.java
Previously, the dump/setup game state dev options were only able to handle a 2-player human vs. AI game. This PR expands the functionality to support any number of players and ignores the type of player (naming them p0,p1,...,pN). The previous names of ai and human are supported for backwards compatibility.
> Support export/import states with arbitrary players.

- forge-core/src/main/java/forge/util/Localizer.java
ResourceBundle doesn't have an overriden toString but has a nice `baseBundle` name as per https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html#getBaseBundleName--
Replace one with the other.
Before:
```
Language 'java.util.PropertyResourceBundle@49e53c76' loaded successfully.
```
After:
```
Language 'en-US' loaded successfully.
```
> Fix language bundle log string

- forge-gui-desktop/src/main/java/forge/screens/home/CLobby.java
- forge-gui-desktop/src/main/java/forge/screens/home/PlayerPanel.java
- forge-gui-desktop/src/main/java/forge/screens/home/VLobby.java
This PR cleans up game lobby code related to game types, specifically removing a lot of code duplication related to managing deck choosers for different game types. Instead, we now only keep around the deck choosers that correspond to the player slots being shown.
This also fixes a bug where changing the AI type (e.g. simulation) can deselect the deck, which would happen at least with Tiny Leaders. (This PR supersedes https://github.com/Card-Forge/forge/pull/2066).
Some other small clean ups are included that were suggested by IntelliJ (deleting unused methods, using lambdas, etc.).
> Clean up lobby code and fix a deck deselect bug.

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-game/src/main/java/forge/game/zone/PlayerZoneBattlefield.java
- forge-gui/res/cardsfolder/a/animate_dead.txt
- forge-gui/res/cardsfolder/d/dance_of_the_dead.txt
- forge-gui/res/cardsfolder/n/necromancy.txt
The combo for infinite tokens didn't work because the return effect happened before _Abdel_ was added to the Graveyard, leading to the very awkward situation of him **not existing in any zone** during that moment of trying to attach the Aura from indirect ETB.
> Rework UntilHostLeavesPlay timing

- forge-ai/src/main/java/forge/ai/simulation/MultiTargetSelector.java
- forge-ai/src/main/java/forge/ai/simulation/PossibleTargetSelector.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SimulationTest.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
The previous code was not correctly handling dependencies between targets (e.g. mutual exclusion). This PR rewrites the logic so that whenever we update a target selection, we update the list of candidates for additional targets to be selected.
Fixes an AI simulation crash when simulating such a spell and removes a lot of illegal simulations.
> Simulated AI: Fix multi-target spell simulation.

- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-game/src/main/java/forge/game/card/Card.java
This was showing up in simulation AI profiles.
> Small code speed up: Avoid calling getFirstAbility() redundantly.

- forge-game/src/main/java/forge/game/card/Card.java
This change speeds up simulation AI code by as much as 30% (!) by optimizing getChangedCardTypes() when they are unchanged. That method is on the hot path of a lot of engine code, such as evaluating static and replacement effects.
On a specific game state I was testing with, it made a simulation that was taking ~26s previously to 18s after this change.
Another minor optimization is included as well, which avoids some unnecessary sb.toString() calls.
> Speed up simulation AI code.

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/trigger/TriggerChangesZone.java
The accuracy for ETB checks is improved by using the LKI from the zone change.
I also had to fix a minor bug in GameAction: in some cases e.g. with _Kalitas, Traitor of Ghet_ on the token ETB it would grab the wrong LKI (from the previous replaced) and use that together with it.
This should allow _Mentor of the Meek_ to work in all cases like this:
which would previously not trigger it if you choose to attach the Equipment to the token from Nahiri +2.
However this doesn't take care of _Welcoming Vampire_ yet, but since LKI support in ChangesZoneAll is still lacking that should probably be addressed in a bigger work in the future.
> TriggerChangesZone: improve ETB check

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/cost/Cost.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/cost/CostPayment.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCantTarget.java
- forge-gui/src/main/java/forge/player/HumanPlay.java
> Can be targeted by a modal spell that can target a non-Wall in one of its modes, even if it has a mode that targets only Walls. That spell can, in theory, target a non-Wall, so it is not a “spell that can target only Walls”.
> Wall of Shadows + Thought Lash fix

- forge-gui/res/editions/Ikoria Lair of Behemoths.txt
It has unique artwork: https://scryfall.com/card/iko/275a/zilortha-strength-incarnate
> Edition update: IKO (add Arena only Zilortha variant)

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/GameState.java
- forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
- forge-game/src/main/java/forge/game/cost/Cost.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCantGainLosePayLife.java
- forge-gui/res/cardsfolder/l/land_grant.txt
- forge-gui/res/cardsfolder/t/the_lady_of_otaria.txt
- forge-gui/src/main/java/forge/player/HumanPlay.java
This is a transition PR towards #2244.
It cleans up some parts and not considering AI checks either disables merging of costs not supported by the rules ~~or skips it for performance by setting the amount directly~~.
That does already fix the _Drought_ case causing sacrifices to be split into different payments.
Outside of CostAdjustment there could be other modifications happening where further undesired interactions might occur, but I'll investigate more after this one.
> Cost tweaks

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerChangesZone.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/a/ardenn_intrepid_archaeologist.txt
- forge-gui/res/cardsfolder/a/armed_and_armored.txt
- forge-gui/res/cardsfolder/h/haakon_stromgald_scourge_avatar.txt
- forge-gui/res/cardsfolder/h/heavenly_blademaster.txt
Another fix required as a result of the stricter check from #2248.
It would be nice to make that part deprecated instead, but I think that will require game timestamps first.
Some nice Attach cleanup as bonus.
> Fix timestamp reset messing up LKI

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java
> 704.5e If a copy of a spell is in a zone other than the stack, it ceases to exist. If a copy of a card is in any zone other than the stack or the battlefield, it ceases to exist.
Fixes ETB replacements for casting copies
> Increase SBA check precision

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/RestartGameEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
Closes #2267
this is for:
>  Activate only if an oil counter was removed from a permanent you controlled this turn or a permanent with an oil counter on it was put into a graveyard this turn.
The second part should be easy
> Game: add CountersRemovedThisTurn

- forge-gui/res/cardsfolder/g/goblin_trapfinder.txt
- forge-gui/res/cardsfolder/i/imperial_blademaster.txt
- forge-gui/res/cardsfolder/o/obsessive_collector.txt
- forge-gui/res/cardsfolder/rebalanced/a-akki_ronin.txt
- forge-gui/res/cardsfolder/rebalanced/a-ancestral_katana.txt
- forge-gui/res/cardsfolder/rebalanced/a-asari_captain.txt
- forge-gui/res/cardsfolder/rebalanced/a-binding_geist_spectral_binding.txt
- forge-gui/res/cardsfolder/rebalanced/a-brine_comber_brinebound_gift.txt
- forge-gui/res/cardsfolder/rebalanced/a-devoted_grafkeeper_departed_soulkeeper.txt
- forge-gui/res/cardsfolder/rebalanced/a-dorothea_vengeful_victim_dorotheas_retribution.txt
- forge-gui/res/cardsfolder/rebalanced/a-dreamshackle_geist.txt
- forge-gui/res/cardsfolder/rebalanced/a-eiganjo_exemplar.txt
- forge-gui/res/cardsfolder/rebalanced/a-gutter_skulker_gutter_shortcut.txt
- forge-gui/res/cardsfolder/rebalanced/a-imperial_subduer.txt
- forge-gui/res/cardsfolder/rebalanced/a-lantern_bearer_lanterns_lift.txt
- forge-gui/res/cardsfolder/rebalanced/a-mischievous_catgeist_catlike_curiosity.txt
- forge-gui/res/cardsfolder/rebalanced/a-patrician_geist.txt
- forge-gui/res/cardsfolder/rebalanced/a-peerless_samurai.txt
- forge-gui/res/cardsfolder/rebalanced/a-phantom_carriage.txt
- forge-gui/res/cardsfolder/rebalanced/a-raiyuu_storms_edge.txt
- forge-gui/res/cardsfolder/rebalanced/a-shipwreck_sifters.txt
- forge-gui/res/editions/Innistrad Crimson Vow.txt
- forge-gui/res/editions/Innistrad Midnight Hunt.txt
- forge-gui/res/editions/Kamigawa Neon Dynasty.txt
It seems the original Mischievous Catgeist // Catlike Curiosity didn't match the card so updated that too.
Source: https://mtgarena-support.wizards.com/hc/en-us/articles/12438205894164-Patch-Notes-2022-22-50
> Alchemy Rebalancing for January 17, 2023

- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
Previous code that was put in place to prevent duplicate shops from spawning if another option of that rarity was available was flawed due to shallow copy of possibleShops into filteredPossibleShops. Intention is to spawn all shops of given rarity at least once before spawning any duplicates, but still spawn from that list. With a shallow copy, the fallback option of possibleShops was also getting updated during the filtering of filteredPossibleShops. This caused potential duplicates to be replaced by ANY shop, regardless of biome or rarity.
> Adventure shop spawn correction

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-core/src/main/java/forge/card/CardSplitType.java
- forge-core/src/main/java/forge/item/PaperCard.java
- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/spellability/SpellPermanent.java
- forge-gui/res/cardsfolder/a/arcee_sharpshooter_arcee_acrobatic_coupe.txt
- forge-gui/res/cardsfolder/b/blaster_combat_dj_blaster_morale_booster.txt
- forge-gui/res/cardsfolder/b/blitzwing_cruel_tormentor_blitzwing_adaptive_assailant.txt
- forge-gui/res/cardsfolder/c/cyclonus_the_saboteur_cyclonus_cybertronian_fighter.txt
- forge-gui/res/cardsfolder/f/flamewar_brash_veteran_flamewar_streetwise_operative.txt
- forge-gui/res/cardsfolder/g/goldbug_humanitys_ally_goldbug_scrappy_scout.txt
- forge-gui/res/cardsfolder/j/jetfire_ingenious_scientist_jetfire_air_guardian.txt
- forge-gui/res/cardsfolder/m/megatron_tyrant_megatron_destructive_force.txt
- forge-gui/res/cardsfolder/o/optimus_prime_hero_optimus_prime_autobot_leader.txt
- forge-gui/res/cardsfolder/r/ratchet_field_medic_ratchet_rescue_racer.txt
- forge-gui/res/cardsfolder/s/slicer_hired_muscle_slicer_high_speed_antagonist.txt
- forge-gui/res/cardsfolder/s/soundwave_sonic_spy_soundwave_superior_captain.txt
- forge-gui/res/cardsfolder/s/starscream_power_hungry_starscream_seeker_leader.txt
- forge-gui/res/cardsfolder/u/ultra_magnus_tactician_ultra_magnus_armored_carrier.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
@kevlahnota on Desktop GUI, on the Select it shill shows the Wrong Name when casting for "More than Meets the Eye"
* I removed converted CardState from Code, it is just Transformed with no difference rules vise - Closes #1807
* Closes #1998
> CardFactoryUtil: More Than Meets the Eye create there instead

- forge-ai/src/main/java/forge/ai/simulation/GameStateEvaluator.java
- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SimulationTest.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
- Lands now have a small bonus for each color they can produce
- Lands now count for each mana they can produce
This does create a lot of messages like:
```
Forest Did not have activator set in SpellAbility_Condition.checkConditions()
```
Is that warning something to look out for or is it just noise that can be removed?
> Improve AI land evaluation

- forge-gui/res/cardsfolder/g/goblin_polka_band.txt
- forge-gui/res/cardsfolder/upcoming/cankerbloom.txt
- forge-gui/res/cardsfolder/upcoming/kaya_intangible_slayer.txt
- forge-gui/res/cardsfolder/upcoming/nahiris_sacrifice.txt
Nahiri's Sacrifice feels a little hacky – "good enough" or is there a better way to fix it?
> ONE: Nahiri's Sacrifice, Kaya, and misc.

- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
There's a small risk that when it takes the RE from LKI another effect calls copyLastState after, in that case it will recreate it from the original and the `hasRun()` will be false again.
Now (if the RE could apply again) it will loop.
This would only affect scenarios where a full replacement is needed, luckily most are already done with Updated result.
> ReplacementHandler: guard against StackOverflow if LKI gets used for Moved

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
- forge-game/src/main/java/forge/game/ability/effects/MillEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-gui/res/cardsfolder/a/ashiok_nightmare_weaver.txt
- forge-gui/res/cardsfolder/b/bane_alley_broker.txt
- forge-gui/res/cardsfolder/p/profane_procession_tomb_of_the_dusk_rose.txt
- forge-gui/res/cardsfolder/s/sisters_of_stone_death.txt
- forge-gui/res/cardsfolder/t/toluz_clever_conductor.txt
Closes #1122
I've considered switching to only `getOriginalAbility()` for compare but this should be ok until the big rework can be done.
I've added a TODO in ``cleanupExiledWith()`` with another (already existing) area of concern but since this thing is rather complex I'd rather take baby steps for improving.
> ExiledWith: fix clone interaction

- forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
- forge-game/src/main/java/forge/game/keyword/KeywordInterface.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
This makes Flashback use castKeyword
meaning if a spell has multiple instances of the keyword, the Exile Replacement should only activate once
Also casting a card with Flashback doesn't add a second instance onto it if its intrinsic
Keyword instances now have HostCard and Intrinsic available (its mostly knowing when the SpellAbility is created in GameActionUtil for Split Cards)
> Flashback: use castKeyword

- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
This fixes phasing affecting delayed triggers.
E.g. activating _Angel of Condemnation_ first ability, then phasing him out would only let the return trigger fire after phase in again.
> Delayed triggers vs. phased out

- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
Closes #2464
This should Fix Henzie giving Blitz without breaking Riot or other cards
> ReplacementHandler: fix adding CastSA Keyword again

- forge-game/src/main/java/forge/game/cost/CostTapType.java
- forge-gui/res/cardsfolder/e/explosive_singularity.txt
The new lines in CostTapType aren't referenced in the cleanest-looking version of Explosive Singularity... so maybe we should just take those out? They might be future-proofing, not sure...
> Explosive Singularity fiddling

- forge-gui/res/puzzle/PS_J221.pzl
Fixed the counters of Magnanimous Magistrate from REPRIEVE to REPR. Fix the cost of trigger ability of Magnanimous Magistrate can't be paid in this puzzle.
> Fixed puzzle PS_J221

- forge-gui/res/cardsfolder/d/dross_skullbomb.txt
Activation cost was 1 B instead of 2 B.
> Dross Skullbomb: Fix cost of activated ability

- forge-gui/res/blockdata/printsheets.txt
The silver lining seems to be that all the missing cards are reprints.
> Fix ONE Jumpstart

- forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
- forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/adventure/world/BiomeTexture.java
- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui/res/adventure/Shandalar/ui/spellsmith.json
- forge-gui/res/adventure/Shandalar/ui/spellsmith_portrait.json
- forge-gui/src/main/java/forge/util/ImageFetcher.java
- silently download back image along with the front image. fixes #2551
- update SpellSmithScene label
- add an expiremental fix for texture bleeding. some weird/tall aspect ratio will still produce some bleeding.
> update RewardActor, SpellSmithScene, InventoryScene

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-ai/src/main/java/forge/ai/ability/CharmAi.java
- forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
- forge-ai/src/main/java/forge/ai/ability/DestroyAi.java
- forge-ai/src/main/java/forge/ai/ability/DestroyAllAi.java
- forge-game/src/main/java/forge/game/phase/Untap.java
- forge-game/src/main/java/forge/game/spellability/AbilityStatic.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/s/subtle_strike.txt
Currently, the AI only goes by shouldPumpCard when deciding whether to put a +1/+1 counter on its own creature or not. This is suboptimal because: (a) shouldPumpCard is truly designed for combat trick pumps that last until the end of turn, while PutCounter is a lasting effect that gives a more permanent bonus to the creature; (b) shouldPumpCard mostly evaluates combat tricks in the AI's own turn during the pre-combat phases or various blocking scenarios in the opponent's turn, thus, the AI would fail to activate the PutCounter ability at other times even when it's clearly beneficial.
Example case: the AI has a creature on board and I have a Raging Goblin in play. The AI casts Subtle Strike. It'll pretty much never choose to put a counter on its own creature because shouldPumpCard fails. …
> CountersPutAI: shouldPumpCard is too restrictive for instant speed PutCounter

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/b/boneyard_scourge.txt
- forge-gui/res/cardsfolder/c/chandras_phoenix.txt
- forge-gui/res/cardsfolder/d/dark_intimations.txt
- forge-gui/res/cardsfolder/g/garzas_assassin.txt
- forge-gui/res/cardsfolder/w/warcry_phoenix.txt
This makes AI consider all possible defenders.
Before it would just take the first legal one, which would often be you in absence of more specific requirements.
This meant when something globally affecting like _Avatar of Slaughter_ got played the next combats quickly end up with very unpretty "ganging up".
> Improve applying attack requirements in multiplayer

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/AnimateEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- SBA for lethal damage -> ``runWaitingTriggers``
- the static trigger to remove the Effect card for the Dies RE would run
- LTB trigger would be lost
@Hanmac
here's the original commit:
https://github.com/Card-Forge/forge/commit/f990f1
even without knowing the full case I doubt you wanted to do it for static ones?
> Fix static trigger messing up LTB trigger

- forge-core/src/main/java/forge/StaticData.java
- forge-core/src/main/java/forge/card/CardEdition.java
- forge-core/src/main/java/forge/item/IPaperCard.java
- forge-core/src/main/java/forge/item/ItemPredicate.java
- forge-core/src/main/java/forge/item/PaperCard.java
- forge-core/src/main/java/forge/item/PaperToken.java
- forge-game/src/main/java/forge/game/GameFormat.java
This makes "A-" cards not legal in other formats other Arena ones,
while also stopping the Replaced Cards being legal in Arena
I'm unsure about the naming, or if i should put a cache around the checks?
do we need to update any format files? or did we forget to ban the cards respectively?
Also we might need to update the LDA data? I mean it does slightly check for the format, but maybe not always?
> GameFormat: filter Rebalanced cards

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkin.java
- Reverts Card-Forge/forge#2657
- seems some devices needs skin texture directly to load if res is missing and fallbackskins are the only available
> Revert "update initial skin texture load"

- forge-adventure/pom.xml
- forge-gui-desktop/pom.xml
- forge-gui-mobile/pom.xml
- forge-gui/pom.xml
Now GDX will be excluded from Desktop JAR.
> Maven: relocate platform-specific dependency

- forge-gui/res/cardsfolder/f/fallaji_antiquarian.txt
Without `ValidCard$ Card.Self` Fallaji Antiquarian triggers even when not in play and any permanent entering the battlefield.
> Fallaji Antiquarian: Fix trigger

- forge-game/src/main/java/forge/game/cost/CostExile.java
- forge-game/src/main/java/forge/game/mana/ManaPool.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/upcoming/arek_false_goldwarden.txt
When undoing a mana ability it would remove the first matching mana from floating.
This meant if the generated mana had riders like _Pyromancer's Goggles_  and you had any other floating red mana with this trick you could Undo that many times to convert all into mana with the trigger.
> Anti-Cheat: fix refunding wrong mana

- forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
- forge-gui/res/cardsfolder/d/domris_ambush.txt
I think the conditional ``resetTargets`` is just too risky as shown by this case...
@Agetian
do you remember why you fixed it like that:
https://github.com/Card-Forge/forge/commit/0ca045
At that time "PowerDmg" was not supported by ``CountersPutAi`` but that is now taken care of, so during my tests this seems to be played correctly?
Also made path for _Crater's Claws_ work again.
> Fix using old target from previous checks

- forge-gui/src/main/java/forge/gamemodes/match/input/InputLondonMulligan.java
Selext first N cards for London Mulligan. 
This does not automatically mulligan again, you need to click Auto to select N cards. 
Then click Mulligan to roll the next round of mulligans.
> Speed up London Mulligan when you just want to mulligan again.

- forge-gui-desktop/src/main/java/forge/sound/AudioClip.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkinFont.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- forge-gui-mobile/src/forge/sound/AudioClip.java
- forge-gui/src/main/java/forge/sound/IAudioClip.java
- forge-gui/src/main/java/forge/sound/NoSoundClip.java
- forge-gui/src/main/java/forge/sound/SoundSystem.java
- investigate why sound is called outside edt -> Forge.getAssets().getSound(fileHandle), seems the audioclip is cached in SoundSystem instead of using it directly from assetManager
> revert AudioClip, refactor Texture get

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- fix issue when downloaded image is reloaded while holdtooltip is engaged locks up all the buttons
> fix holdtooltip bug

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
found this while i was also doing the Unearth cost
rules wise an Artifact Equipment Creature with Equip can target itself with the Equip Ability
but of cause it doesn't has any effect (except you activated an ability)
@Agetian do we need more logic for AI so an Equipment Creature doesn't try to target itself?
> CardFactoryUtil: Equip shouldn't care if it is a creature

- forge-game/src/main/java/forge/game/card/CardFactory.java
Both of these are already done recursively by copy() so we can save just a few calls here.
https://github.com/Card-Forge/forge/blob/395eab4d59a54a26988b71b011452da171486a4f/forge-game/src/main/java/forge/game/spellability/SpellAbility.java#L1156
> CardFactory: remove redundant copying

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityDisableTriggers.java
- forge-game/src/main/java/forge/game/trigger/Trigger.java
- forge-game/src/main/java/forge/game/trigger/TriggerCounterAdded.java
Closes #1489
I first thought about adding isValid to Trigger but then i thought it might be too complicated
the ReadAhead on PutCounter i keep for now, it might not be needed because you can get the Keyword from the SpellAbility anyway now, but it might be useful for AI to not choose TOO high or TOO low in case of counter doubler like Vorinclex
AI might need a bit more tweaking?
> CardFactoryUtil: Read Ahead use DisableTriggers

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/Shadows over Innistrad Remastered.txt
A note on the SIR draft format: As you can see on the link below, Arena has an evolving draft format that includes different cards from SIS on a weekly basis. As not all cards have rotated in yet there are no draft rankings available. Once all cards have a ranking I will probably come back to this and include them but with the following difference: because Forge's draft doesn't support the way Arena handles it, the draft will pick a SIS card at random to include in a pack; keep it simple.
https://magic.wizards.com/en/news/mtg-arena/shadows-of-the-past-card-list-and-schedule
> Booster Draft: SIR

- forge-gui/res/adventure/Shandalar/sprites/heroes/devil_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/devil_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/dwarf_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/dwarf_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/elf_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/elf_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/human_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/human_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/kor_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/kor_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/metathran_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/metathran_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/phyrexian_r.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/phyrexian_u.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/undead_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/undead_m.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/viashino_f.atlas
- forge-gui/res/adventure/Shandalar/sprites/heroes/viashino_m.atlas
Fix to bug in PC walking animations where the 3rd frame when walking directly down came from the idle animations instead of the walking ones.
> Fix to Bug in PC Walk Down Animations

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardState.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
When an animated Vehicle dies, Kinzu of the Bleak Coven should make a token with PT = 1/1
But does this break Mindlink Mech?
> If a player crews Mindlink Mech with a nonlegendary permanent that is not normally a creature or Vehicle, the resulting permanent Mindlink Mech becomes is a 0/0 artifact creature and will usually be put into its owner's graveyard. This is because a copy effect can't set the power and toughness of a permanent if being a creature isn't part of that permanent's copiable characteristics. The crew effect is then applied after the copy effect, and it becomes a creature with no defined power or toughness, so both are set to 0. (2022-02-18)
should the set of PT before `state.addType(types)` ?
> CardFactory getCloneStates set PT for Vehicle

- forge-gui-mobile/src/forge/adventure/character/PlayerSprite.java
When a player runs up against an obstacle, this change will maintain the player's intended direction, allowing them to resume moving in the intended direction without having to re-press the movement key after they have cleared the obstacle.
> Prevent player from needing to re-press movement key

- forge-gui/res/adventure/Shandalar/maps/map/main_story/templeofchandra.tmx
Chandra, Supreme Pyromancer doesn't seem to exist.  I'm guessing it should be Chandra, Bold Pyromancer, though "Novice" is another option.  A quick playtest showed reasonable difficulty for the encounter.
> Renamed an invalid card for Chandra Adventure battle

- forge-gui/res/cardsfolder/f/futurist_operative.txt
- forge-gui/res/cardsfolder/h/hinterland_chef.txt
- forge-gui/res/cardsfolder/k/krydle_of_baldurs_gate.txt
- forge-gui/res/cardsfolder/l/lonely_end.txt
- forge-gui/res/cardsfolder/m/moon_circuit_hacker.txt
- forge-gui/res/cardsfolder/n/nightclub_bouncer.txt
- forge-gui/res/cardsfolder/rebalanced/a-circuit_mender.txt
- forge-gui/res/cardsfolder/rebalanced/a-dawnbringer_cleric.txt
- forge-gui/res/cardsfolder/rebalanced/a-dokuchi_silencer.txt
- forge-gui/res/cardsfolder/rebalanced/a-futurist_operative.txt
- forge-gui/res/cardsfolder/rebalanced/a-haywire_mite.txt
- forge-gui/res/cardsfolder/rebalanced/a-knockout_blow.txt
- forge-gui/res/cardsfolder/rebalanced/a-krydle_of_baldurs_gate.txt
- forge-gui/res/cardsfolder/rebalanced/a-moon_circuit_hacker.txt
- forge-gui/res/cardsfolder/rebalanced/a-nashi_moon_sages_scion.txt
- forge-gui/res/cardsfolder/rebalanced/a-nezumi_prowler.txt
- forge-gui/res/cardsfolder/rebalanced/a-prosperous_thief.txt
- forge-gui/res/cardsfolder/rebalanced/a-satoru_umezawa.txt
- forge-gui/res/cardsfolder/rebalanced/a-silver_fur_master.txt
- forge-gui/res/cardsfolder/rebalanced/a-thousand_faced_shadow.txt
- forge-gui/res/cardsfolder/s/swarm_saboteur.txt
- forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt
- forge-gui/res/editions/Kamigawa Neon Dynasty.txt
- forge-gui/res/editions/Streets of New Capenna.txt
- forge-gui/res/editions/The Brothers War.txt
Source: https://magic.wizards.com/en/news/mtg-arena/alchemy-rebalancing-for-april-4-2023
> Alchemy Rebalancing for April 4, 2023

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/flitting_guerrilla.txt
Seems like we shouldn't need line 8 and be able to just use `ExileAnyGrave<1/Card.TriggeredNewCard>` in line 9 – but that doesn't work.
All other cards like that are AB$ with Cost$ but this kind of has to be DB$ with UnlessCost$ because it's after the Mill ☹️ 
Made this a separate PR in case the engine should be updated
> Draft: flitting_guerrilla.txt

- forge-gui/res/cardsfolder/f/fire_prophecy.txt
- forge-gui/res/cardsfolder/m/mordenkainen.txt
- forge-gui/res/cardsfolder/rebalanced/a-akki_ronin.txt
- forge-gui/res/cardsfolder/upcoming/nahiris_warcrafting.txt
- forge-gui/res/cardsfolder/upcoming/shatter_the_source.txt
- forge-gui/res/cardsfolder/upcoming/thrashing_frontliner.txt
- forge-gui/res/cardsfolder/upcoming/volcanic_spite.txt
- forge-gui/res/cardsfolder/upcoming/war_trained_slasher.txt
Nothing that directly needs Battle for testing
I *think* this is the best trigger to use for Thrashing Frontliner / War-Trained Slasher … works fine in testing with an identical trigger using `AttackedTarget$ Planeswalker`
nahiris_warcrafting.txt
shatter_the_source.txt
thrashing_frontliner.txt
volcanic_spite.txt
war_trained_slasher.txt
> MOM: more battle-adjacent cards

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui-desktop/src/main/java/forge/toolbox/imaging/FCardImageRenderer.java
- forge-gui/res/cardsfolder/upcoming/invasion_of_amonkhet_lazotep_convert.txt
- forge-gui/res/cardsfolder/upcoming/invasion_of_dominaria_serra_faithkeeper.txt
- forge-gui/res/cardsfolder/upcoming/invasion_of_new_phyrexia_teferi_akosa_of_zhalfir.txt
- forge-gui/res/cardsfolder/upcoming/invasion_of_zendikar_awakened_skyclave.txt
> If a permanent that is represented by a transforming double-faced card becomes a copy of a Siege, it will be exiled as that Siege's triggered ability resolves, then it will be cast transformed. Note that this applies only to transforming double-faced cards, not to modal double-faced cards that can normally be played using either face.
This will now correctly cast the back of _Aetherblade Agent_.
> Battle: lazy build SpellPermanent on TDFC

- forge-gui/src/main/java/forge/gamemodes/match/input/InputConfirmMulligan.java
It was previously just exiling the hand and not drawing cards
> fix to allow Serum Powder to draw cards after exiling hand

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
Example: Target _Solemn Simulacrum_ with _Rogue's Passage_ and then deal lethal dmg to it
This is because the Static ExileOnMoved$ trigger will resolve first and the registered trigger from the LKI before death will be lost.
Notably it will fail with any combination of such cards but only if it dies from SBA, otherwise MagicStack handles it correctly.
I think a full call to ``resetActiveTriggers`` is unneeded / would be wrong during SBA.
> Effect cleanup can prevent any LTB trigger

- forge-gui/res/cardsfolder/upcoming/preening_champion.txt
>  Preening Champion {2}{U}
> Creature — Bird Knight
> Flying
> When Preening Champion enters the battlefield, create a 1/1 blue and red Elemental creature token.
[Gatherer](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=607100)
> Fix: Preening Champion only creates one token

- forge-gui/res/adventure/Shandalar/world/enemies.json
prevent the captain giving Sol Ring (which is classed as an uncommon) to the player
> Scarecrow Captain fix

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ExploreEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RegenerateEffect.java
- forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
- forge-gui/res/cardsfolder/a/armament_master.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
- Fixed Valakut not triggering when ETB last together with enough mountains:
Got broken by https://github.com/Card-Forge/forge/commit/fb317f
- Closes #2229:
I went back to the original commit (https://github.com/Card-Forge/forge/commit/9c7871) and after testing consider it safe to remove completely because `clearActiveTriggers` now already takes care of avoiding a misfire
> Fix RE messing up Triggers

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/adventure/Shandalar/custom_cards/flame_sword.txt
- forge-gui/res/cardsfolder/p/penregon_besieged.txt
The CardProperty tweak will allow @jjayers99 to implement a rebalanced version of Death Ring. It smells like something we'll probably need in the future, so I think it's OK to put in even though no "actual" MtG cards use it yet.
EDIT: we actually need the CardProperty tweak to get Penregon Besieged working properly.
> various Adventure-related things

- forge-gui/res/cardsfolder/upcoming/spark_rupture.txt
There was some discussion regarding this one in the Discord, but it seems to work fine without engine changes... making it its own PR in case it gets hairy with corner cases or something.
It seems to work properly on Planeswalkers that are already on the battlefield when it is cast, and on any other Planeswalkers that ETB afterward.
Planeswalkers also seem to revert properly after it is removed.
> MAT: spark_rupture.txt

- forge-game/src/main/java/forge/game/cost/CostExileFromStack.java
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
So I think this bug (which only affects human) has been hiding and potentially causing confusion for quite a while because it's 1. a bit hard to notice and 2. also requires specific board states to occur which are usually not obvious either.
As you can see in the reported Screenshot Ward triggers way too late:
This happens because the Spell cast by the AP also triggers a Magecraft ability which however fails targeting but leaves the stack frozen for the following (NAP) Ward trigger.
> Fix failed trigger keeping the stack frozen

- forge-gui/src/main/java/forge/gamemodes/gauntlet/GauntletIO.java
- forge-gui/src/main/java/forge/gamemodes/tournament/TournamentIO.java
- old saves with cards using old edition code always crash on newer version of Forge due to Edition updates/changes. Try to load it by getting replacement card with any edition first found in db since those are migration error and editing the extracted save file manually are not user friendly.
> try to fix older gauntlet/tournament saves.

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-gui/res/cardsfolder/a/abdel_adrian_gorions_ward.txt
- forge-gui/res/cardsfolder/d/darigaaz_reincarnated.txt
This fixes some exiling of combined permanents interactions:
- ExiledWith, e.g. _Helvault_ not returning all components
- WithCountersType, e.g. Etrata only putting HIT counters on the first
Closes #3070
> Fix exiling sometimes handled incomplete for combined permanents

- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
fix around SetPower and setToughness
@tool4ever this should fix the possible NPE, or do you still want to debug why originalState might be null?
> Update CardFactory CloneStates: fix SetPower and setToughness

- forge-gui-mobile/src/forge/adventure/data/DialogData.java
Fix for adventure save file deserialization error caused by adding a new field to ActionData.
(I've learned my lesson and this will not happen again.)
> Adventure - fix ActionData deserialization

- forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
- forge-gui/res/cardsfolder/t/tempered_veteran.txt
It'll now prefer the cheaper ability if the target card already has +1/+1 counters.
Fixes #2563
> Improve AI for Tempered Veteran

- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-gui/res/cardsfolder/d/donal_herald_of_wings.txt
- forge-gui/res/cardsfolder/f/fork.txt
- forge-gui/res/cardsfolder/o/ob_nixilis_the_adversary.txt
- forge-gui/res/cardsfolder/t/tawnos_the_toymaker.txt
Handles the SpellCopy part of #2866
> CardFactory: copySpellHost uses getCloneStates

- forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
- forge-game/src/main/java/forge/game/trigger/Trigger.java
- forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
- forge-gui/res/cardsfolder/b/bloodthirsty_adversary.txt
- forge-gui/res/cardsfolder/c/cemetery_desecrator.txt
- forge-gui/res/cardsfolder/g/guile_sonic_soldier.txt
- forge-gui/res/cardsfolder/i/intrepid_adversary.txt
- forge-gui/res/cardsfolder/p/primal_adversary.txt
- forge-gui/res/cardsfolder/s/spectral_adversary.txt
- forge-gui/res/cardsfolder/t/tainted_adversary.txt
- forge-gui/res/cardsfolder/upcoming/tranquil_frillback.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
I have some ideas for teaching the AI to actually use the abilities Tranquil Frillback / Adversary cycle, but that is for another PR. For now they get the `RemoveDeck:All` because the AI will never use the abilities.
On the human side, I think I've finally got Cemetery Desecrator and Guile, Sonic Soldier displaying well:
> MAT: tranquil_frillback.txt + support/related

- forge-gui-mobile/src/forge/adventure/data/AdventureQuestData.java
- forge-gui/res/adventure/Shandalar/maps/map/teferi.tmx
- forge-gui/res/adventure/Shandalar/maps/tileset/main.tsx
Bugfix for quests that used Arena objectives, previously the quest offer dialog would hang because target POI was not being set properly.
Redo of Teferi Hideout collisions / terrain - Fixed blocked ramp to Teferi, extended shoreline slightly to give more natural appearance, added lots of missing corners to island clutter, replaced hidden collision layer with collision mapped terrain, removed tiles duplicated between layers, added threat range to eastern crab to defend booster pack
> Adventure fixes

- forge-gui/res/formats/Archived/Arena Standard/2023-05-30.txt
- forge-gui/res/formats/Archived/Standard/2023-05-29.txt
Standard:
- Fable of the Mirror-Breaker // Reflection of Kiki-Jiki is banned.
- Invoke Despair is banned.
- Reckoner Bankbuster is banned.
Effective Date:
- Tabletop and Magic Online: May 29, 2023
- MTG Arena: May 30, 2023
Source: https://magic.wizards.com/en/news/announcements/may-29-2023-banned-and-restricted-announcement
> Banned and Restricted Announcement for May 29, 2023

- forge-core/src/main/java/forge/item/PaperToken.java
- exclude cardedition and cardrules for serialization
> fix PaperToken crash on Networkplay (Incubate, etc)

- forge-core/src/main/java/forge/card/CardRules.java
- forge-core/src/main/java/forge/card/CardRulesPredicates.java
- forge-game/src/main/java/forge/game/ability/effects/ClashEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/h/hordewing_skaab.txt
This makes matching parametrized ones like `Keyword$Suspend` from _Alaundo the Seer_ actually work... 💩
> Fix DeckHints only finding SimpleKeyword

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/RemoveFromGameEffect.java
- forge-gui/res/cardsfolder/k/kynaios_and_tiro_of_meletis.txt
- forge-gui/res/cardsfolder/t/the_great_aurora.txt
For the same reason you could also get Zellix to trigger from the mill if he gets returned.
> Follow-up tweak for when triggers are checked during resolve

- forge-gui/res/cardsfolder/rebalanced/a-kumano_faces_kakkazan_etching_of_kumano.txt
- forge-gui/res/cardsfolder/t/traumatic_prank.txt
- forge-gui/res/editions/Kamigawa Neon Dynasty.txt
> We have a couple of rebalances coming Tuesday, May 30, to the Alchemy format.
Source: https://magic.wizards.com/en/news/mtg-arena/mtg-arena-announcements-may-29-2023
> Alchemy Rebalancing for May 30, 2023

- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/trigger/TriggerLifeGained.java
- forge-gui/res/cardsfolder/a/ankle_shanker.txt
- forge-gui/res/cardsfolder/a/attended_healer.txt
- forge-gui/res/cardsfolder/c/cleric_of_lifes_bond.txt
- forge-gui/res/cardsfolder/c/company_commander.txt
- forge-gui/res/cardsfolder/c/cunning_rhetoric.txt
- forge-gui/res/cardsfolder/c/curse_of_shaken_faith.txt
- forge-gui/res/cardsfolder/d/dance_with_calamity.txt
- forge-gui/res/cardsfolder/d/deathless_knight.txt
- forge-gui/res/cardsfolder/h/howling_mine.txt
- forge-gui/res/cardsfolder/m/mana_vault.txt
- forge-gui/res/cardsfolder/n/nim_abomination.txt
- forge-gui/res/cardsfolder/r/ratchet_field_medic_ratchet_rescue_racer.txt
- forge-gui/res/cardsfolder/r/resolute_veggiesaur.txt
- forge-gui/res/cardsfolder/v/voodoo_doll.txt
- forge-gui/res/cardsfolder/w/whirlwind_denial.txt
In some corner cases checking "first time" triggers from script calculation could fail (e.g. multiple life gain during resolve).
Closes #3198
> Cleanup more ResolvingChecks

- forge-gui/res/cube/MTGO Vintage Cube February 2022.dck
- forge-gui/res/cube/MTGO Vintage Cube May 2023.dck
- forge-gui/res/draft/MTGO Vintage Cube February 2022.draft
- forge-gui/res/draft/MTGO Vintage Cube Februrary 2022.draft
- forge-gui/res/draft/MTGO Vintage Cube May 2023.draft
- Added MTGO Vintage Cube (May 2023), per https://www.mtgo.com/vintage-cube-cardlist
- Fixed the name of MTGO Vintage Cube (February 2022).
> Add MTGO Vintage Cube (May 2023).

- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
Closes #3201
need to fix the Tests, don't have time right now
The Main Reason for this is to have cards like Ratadravik to be able to copy Transforming Double faced cards (and their transformed state)
> LKICopy Transform and flip

- forge-gui-mobile/src/forge/adventure/scene/DraftScene.java
- forge-gui-mobile/src/forge/adventure/scene/EventScene.java
- forge-gui-mobile/src/forge/adventure/scene/PlayerStatisticScene.java
After the double music fix was implemented previously, the town event / draft screens went completely silent. This PR intends to add music back to those scenes without the "double music" effect. Not sure what music was originally intended for these screens, so for now, I'm using the Menus playlist for contrast against the normal Town playlist played in town as such.
Also fixes double music playback in the player stats screen.
> Add music back to town events/draft scene

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
Fixes #3061 .
The code at AiAttackController.java:140-141 originally skipped all checks for tokens in this manner (probably for speed?) I currently made an exclusion to consider transformable tokens such as Incubator stuff, is that a viable solution? :/
> AI: Account for transformable cards (e.g. Incubator tokens) when considering defenders

- forge-gui/res/adventure/Shandalar/world/enemies.json
- forge-gui/res/adventure/Shandalar/world/shops.json
.Makes it possible for phyrexian enemies to drop mythic rares. (Still very rarely.) 
.Adds missing keyword ("compleated") to the string search for Phyrexian shops.
> Phyrexian Server Request Implementation

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-ai/src/main/java/forge/ai/ability/AnimateAi.java
- forge-ai/src/main/java/forge/ai/ability/SacrificeAi.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeTargetsEffect.java
- forge-gui/res/cardsfolder/a/ancient_imperiosaur.txt
- forge-gui/res/cardsfolder/e/elminster.txt
- forge-gui/res/cardsfolder/h/hateful_eidolon.txt
- forge-gui/res/cardsfolder/i/imps_mischief.txt
- forge-gui/res/cardsfolder/l/living_lore.txt
- forge-gui/res/cardsfolder/s/spark_of_creativity.txt
- Fix AI treating some abilities like on _Lifespark Spellbomb_ as though they would animate the card itself (could possibly be extented in the future so those kind of choices are also included)
- Fix AI getting stuck in loop because it didn't account for raises to the Crew ability from e.g. _Suppression Field_
- Fix AI not ignoring attackers that get used for crewing instead
> Attack fixes

- forge-ai/src/main/java/forge/ai/AiCardMemory.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/ability/PeekAndRevealAi.java
- forge-game/src/main/java/forge/game/ability/effects/PeekAndRevealEffect.java
- forge-gui/res/cardsfolder/d/delver_of_secrets_insectile_aberration.txt
- forge-gui/res/draft/rankings.txt
Makes the AI skip the reveal if it sees a non-Instant/non-Sorcery card on Delver of Secrets, for which it's optional.
Can most likely be used for other similar effects and possibly other stuff too.
Currently remembers only the last reveal (will clean up the revealed cards the next time something is revealed). If this is to be extended to allow some complex logic depending on what was revealed during the turn, this will need to be changed (the cleanup in the reveal method will need to be removed).
The overload of the "reveal" method with the CardView parameter is tricky because it doesn't allow to get to the card directly, so I'm currently using a "bruteforce" iteration over all the cards in the game to find the source. Can this be done faster/easier somehow? Luckily, this method isn't …
> AI: simple Reveal logic, example implementation for Delver of Secrets

- forge-game/src/main/java/forge/game/card/CardDamageHistory.java
This seems to make Dunerider Outlaw to work correctly and not crash after dealing damage, but I'm not sure if maybe this is masking a bigger issue elsewhere in the code, so needs some consideration and review.
Test case for this: the AI has Dunerider Outlaw and attacks into the human's empty battlefield. Without the NPE guard, the game will crash.
> NPE guard for cases like Dunerider Outlaw dealing damage.

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/ability/RevealAiBase.java
- forge-ai/src/main/java/forge/ai/ability/SetStateAi.java
- forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PumpAllEffect.java
- forge-gui/res/cardsfolder/a/assembled_alphas.txt
- forge-gui/res/cardsfolder/f/fireflux_squad.txt
While there are probably some other places that could benefit from this function for performance I've tried catching the most devastating counterattack scenario for starters...
AI now correctly decides to skip attacking since it would lose without a blocker (that is if you give it another strong enough wall it will still commit to bait it out):
It will obviously encounter memory loss on next turn but that's a problem we can think on some more.
> Consider fog effects ruining assaults

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/ability/effects/RevealEffect.java
- forge-game/src/main/java/forge/game/ability/effects/VoteEffect.java
- forge-gui/res/cardsfolder/a/awakened_awareness.txt
- forge-gui/res/cardsfolder/b/bioplasm.txt
- forge-gui/res/cardsfolder/d/danitha_new_benalias_light.txt
- forge-gui/res/cardsfolder/g/ghitu_chronicler.txt
- forge-gui/res/cardsfolder/g/graveyard_shovel.txt
- forge-gui/res/cardsfolder/m/maelstrom_archangel_avatar.txt
- forge-gui/res/cardsfolder/r/rundvelt_hordemaster.txt
- forge-gui/res/cardsfolder/s/sapling_of_colfenor.txt
- forge-gui/res/cardsfolder/t/tetsuo_imperial_champion.txt
While the amount of cards that can be activated for mana while being tapped isn't that large AI should really consider it.
The resposible block I removed was pretty ancient and the ``canPayAdditionalCosts`` above should already handle it fine.
But feel free to test a bit that no new cheating is introduced...
Here's my scenario which will now allow the AI to pay for the game winning ability asap:
[CRYPTOLITE.txt](https://github.com/Card-Forge/forge/files/11745298/CRYPTOLITE.txt)
>  Fix AI not being able to use mana from tapped sources 

- forge-game/src/main/java/forge/game/GameEntity.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/a/arixmethes_slumbering_isle.txt
> If you target an Aura with Immovable Rod's last ability, it will lose its enchant ability and be put into its owner's graveyard because it can't legally enchant anything.
Also partial tweak for #2229
> Aura without Enchant shouldnt't stay attached

- forge-core/src/main/java/forge/card/CardChangedType.java
- forge-core/src/main/java/forge/card/RemoveType.java
- forge-game/src/main/java/forge/game/ability/effects/AmassEffect.java
- forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
Closes #3223 
Maybe First part or first draft?
Currently it is just Internal Flags without Changing the Card Scripts
More Opinions about this?
Should we update the `RemoveLandTypes` params to be something like `RemoveAllTypes$ Land` ?
> CardChangedType: use Enum Flags for removeAllSubTypes

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-ai/src/main/java/forge/ai/SpellApiToAi.java
- forge-ai/src/main/java/forge/ai/ability/BranchAi.java
- forge-ai/src/main/java/forge/ai/ability/PermanentCreatureAi.java
- forge-gui/res/cardsfolder/b/bring_the_ending.txt
- forge-gui/res/cardsfolder/g/grisly_sigil.txt
- forge-gui/res/cardsfolder/h/hold_for_ransom.txt
- Improved Blitz AI support (will cast in Main 1 when viable, will avoid casting in Main 2).
- Hold for Ransom AI hint to actually use the ability when able.
- Basic AI support for Grisly Sigil so that at least it doesn't fizzle.
- Basic BranchAi framework, currently will mostly just return true, but may be used for special logic when needed.
Current issues, most likely for the future PR:
- Grisly Sigil is very basic. Casualty payment is currently disabled for it (the AI will always pay for it, and when it does, it'll also fail to target something else, choosing the same target as for the original). Probably needs #3262 in order to work better, as well as some improvement to the targeting system for copied spells.
> Several AI improvements

- forge-gui/res/adventure/Shandalar/custom_cards/ghaltas_presence.txt
- forge-gui/res/adventure/Shandalar/sprites/animals/wolf.atlas
- Fix Green Castle crash on any non-Windows operating system with a case sensitive file system.
- Fix Ghalta's Presence increasing the cost of everything (most likely should be non-creature and non-battle for a single card, otherwise it increases the costs of [non-battle] creatures and [non-creature] battles.
> Fix Green Castle crash on non-case insensitive file systems, fix Ghalta's Presence effect.

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
This old (https://github.com/Card-Forge/forge/commit/25f0e0) timestamp-related code seems very problematic:
- technically it shouldn't even fizzle untargeted ones
- it breaks other cards that don't want to affect the target directly, e.g. _Bellowing Fiend_
- the card mentioned in the original commit is already fixed for LKI usage anyway
So we rip it out asap.
> Remove outdated fizzle code

- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- AI will avoid enchanting crewed vehicles since that leads to card disadvantage and in most cases, that AI does this by mistake as opposed to some kind of a strategic way that leads to definitive advantage. Probably worth somehow implementing a check where the AI may be able to gain critical advantage or outright win by enchanting the said vehicle and attacking with it (e.g. when the opponent is low on health) - could be something for a future PR, not sure yet.
- AI will avoid equipping crewed vehicles for the same reason. The current exception is when the AI is actually attacking with the said vehicle this turn, when equipping it is likely to cause more damage (for the cost of mana for equip). Not sure how useful this is, probably needs testing and may need tweaking.
- Tested the AI not …
> AI: AttachAi should avoid enchanting or equipping crewed vehicles

- pom.xml
Hi!
I recently bumped the Maven version in Nixpgks (NixOS/nixpkgs#238746) and ran into some small but annoying manual effort w.r.t. the `forge-mtg` package. The issue is that `forge-mtg` is packaged using the [double invocation](https://ryantm.github.io/nixpkgs/languages-frameworks/maven/#double-invocation) method which unfortunately breaks if not all maven plugin versions are set explicitly.
We're extending the documentation to prevent this (NixOS/nixpkgs#238774), but I'm reaching out to fix the packages which have already been packaged. In this PR, we explicitly set the versions of the only two plugins which hadn't been set explicitly before and add a check with the enforcer plugin to make sure this won't accidentally break in the future.
I took the liberty of deduplicating the …
> Enforce explicit plugin versions

- forge-gui/res/adventure/common/world/enemies.json
Ibis sprite is too small. Turns out it is even being scaled *down*! Scaling it up instead.
> upscale ibis from 60% to 130%

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-ai/src/main/java/forge/ai/ability/ControlGainAi.java
- forge-ai/src/main/java/forge/ai/ability/CounterAi.java
- forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-gui/res/cardsfolder/o/odric_master_tactician.txt
- forge-gui/res/cardsfolder/upcoming/archivist_of_gondor.txt
- forge-gui/res/cardsfolder/upcoming/the_grey_havens.txt
- forge-gui/res/cardsfolder/v/valakut_the_molten_pinnacle.txt
- Closes #3400
- > If a Mountain you control leaves the battlefield between the time Valakut’s second ability triggers and the time it resolves, be aware if that was the Mountain that caused Valakut’s ability to trigger or not. If it was, Valakut’s count isn’t affected; if it wasn’t, Valakut’s count goes down by one.
- Closes #3404
> Fix cheating when paying hybrid shards with combo abilities

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityCondition.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/i/imminent_doom.txt
This fixes a missing opportunity to "reduce" some of the interactions of an exiled card.
For testing have _Rest in Peace_ and try to remove exiled cards with _Pull from Eternity_:
- with the activated ability of _Torrent Elemental_ on the stack it should be prevented from ETB
- ExiledWith links should break
- MayPlay stuff should end
- etc.
Because the rules say it doesn't change zones this would also stop effect cleanup, but luckily we have another trigger for this.
> Exiled card becomes new object when it's exiled

- forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
Correcting faulty logic in draft set filtering to filter out sealed-only sets
> Adventure - Updated draft set filtering

- forge-ai/src/main/java/forge/ai/ability/DamageAiBase.java
- forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
- forge-ai/src/main/java/forge/ai/ability/PermanentAi.java
- forge-gui/res/cardsfolder/c/chalice_of_the_void.txt
Not the smartest thing in the world, but better than nothing.
Can be improved if the AI looks at the library/hand contents instead of all cards (assuming that it knows the deck lists *and* looks at the graveyard and exile for what already left the game), but it's a bit more like outright cheating, so I don't know, lol :)
I'm not sure if the AI should really go above X=2 or X=3 for this card or so, it's usually played for low X in specific decks against specific (usually low-cost) threats, so... Not sure too, haha.
Also fixes #3442, improving damage prediction when deciding to deal damage to the opponent with AF DealDamage.
> Basic AI for Chalice of the Void, minor DamageDealAi improvement

- forge-game/src/main/java/forge/game/staticability/StaticAbilityDisableTriggers.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityPanharmonicon.java
> Look at each creature as it exists on the battlefield, taking into account continuous effects, to determine whether any triggered abilities will trigger multiple times. For example, if a land that has become a creature dies, an ability that triggers when it dies triggers twice.
> Panharmonicon: support LKI of cause

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java
- forge-gui/res/cardsfolder/h/hargilde_kindly_runechanter.txt
- forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
Also prevent autopay letting you cheat away the cost partly when activating an ability that could not produce fitting mana, e.g.:
> Fix Doubling Cube producing C out of nothing if floating colors have gap

- forge-gui/res/cardsfolder/c/crucias_titan_of_the_waves.txt
- forge-gui/res/editions/Commander Masters.txt
- forge-gui/res/formats/Archived/Alchemy/2023-07-18.txt
Source: https://magic.wizards.com/en/news/mtg-arena/alchemy-rebalancing-for-july-18-2023
- Crucias, Titan of the Waves rebalanced (no new script needed as Alchemy only card)
- Fable of the Mirror-Breaker is banned from Alchemy.
- Updated CMM edition file.
> Alchemy Rebalancing for July 18, 2023 (also CMM edition update)

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- forge-ai/src/main/java/forge/ai/ability/PumpAiBase.java
- forge-game/src/main/java/forge/game/GlobalRuleChange.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityWitherDamage.java
- forge-gui/res/cardsfolder/e/everlasting_torment.txt
Closes #3491 
it also allows for a more generic `isWitherDamage`
> Card: Wither damage as property, use Static for Everlasting Torment

- forge-gui/res/editions/The Lord of the Rings Tales of Middle-earth.txt
It seems to me that Nazgûl appear too frequently in generated draft boosters.
If I understand correctly, Nazgûl should have the same frequency as every other uncommon. (In RL it seems that the amount is split evenly among all art variants.) If I understand the BoosterGenerator.java code correctly, listing Nazgul 9x in the "cards" sections will make it appear 9x more frequently than in RL draft boosters.
My proposal would be to mark all but the first version als "alternate art", similar to M21 "Teferi, Master of Time"
> set Nazgûl variants as alternate art

- forge-gui/res/editions/Commander Masters.txt
- forge-gui/res/editions/The Lord of the Rings Tales of Middle-earth.txt
Currently army tokens aren't recoignised by types (zombie, orc, sliver etc.) so have renamed the entries inside LTR and CMM editions as they were throwing out errors due to not finding an existing script with typed names. Also fixed germ token line.
> Fix token names in LTR, CMM editions

- forge-gui/res/cardsfolder/e/elvish_impersonators.txt
Elvish Impersonators doesn't have flying.
https://scryfall.com/card/und/62/elvish-impersonators
> Fix Elvish Impersonators: remove flying

- forge-game/src/main/java/forge/game/ability/effects/HauntEffect.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
@Hanmac 
looks like this was broken for a while:
the LTB trigger would get hosted by LKI and then fail timestamp check
Closes #3631
> Fix creature haunting

- forge-ai/src/main/java/forge/ai/ability/TokenAi.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-gui/res/cardsfolder/upcoming/spellbook_vendor.txt
- forge-gui/res/cardsfolder/upcoming/spiteful_hexmage.txt
- forge-gui/res/lists/TypeLists.txt
- forge-gui/res/tokenscripts/role_cursed.txt
- forge-gui/res/tokenscripts/role_monster.txt
- forge-gui/res/tokenscripts/role_royal.txt
- forge-gui/res/tokenscripts/role_sorcerer.txt
- forge-gui/res/tokenscripts/role_virtuous.txt
- forge-gui/res/tokenscripts/role_wicked.txt
- forge-gui/res/tokenscripts/role_young_hero.txt
Closes #3685 
the Send to Graveyard should only be needed as StateBasedAction
as per rules, it looks like they are directly send to GY instead of getting unattached first? That might matter?
I still unattach them first for better trigger
As for the Cards that makes the Roles, @Agetian AI might need some logic to not add Roles to cards that already has Roles? (except the Cursed one?)
> Role: add StateBasedAction

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
- forge-ai/src/main/java/forge/ai/simulation/GameStateEvaluator.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseSourceEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/token/TokenInfo.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SimulationTest.java
- forge-gui/res/cardsfolder/i/ignoble_soldier.txt
Closes #3729
I did some preliminary work on the simulation to avoid cheating from hidden information, with the added performance benefit that less cards need to be copied fully.
E.g. in this scenario the AI "shouldn't" recognize it can draw->cast the Colossus instead of using the mana for the Griffin:
But I need to refine it further so for now the path is disabled by default.
> fix script

- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-gui/res/cardsfolder/upcoming/ashiok_wicked_manipulator.txt
@Hanmac 
Current implementation can lead to card duplication:
- Cast _Genesis Ultimatum_ with 3 _Breeding Pool_  on top
- Choose top two for ETB
- Pay 2 Life for both to replace with _Ashiok_
- End Result: 4 Pools ⚠️  (1 Exile, 1 Hand, 2 in play)
Here's my idea
> Fix Ashiok

- forge-ai/src/main/java/forge/ai/ability/FightAi.java
The issue here is that in Ent's Fury, DB Fight is not immediately a child of DB Pump, therefore, some traversal is needed. We also include DB DealDamage in the search because AILogic$ PowerDmg expects it (for AI logic in DB Pump).
> Improve AI support for Ent's Fury

- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
Before this change, Sim AI would just choose effects that should be blocked by Pithing Needle (and similar cards). Adds a test.
> Fix SimAI not respecting Pithing Needle effects.

- forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/DeckHtmlSerializer.java
First: super cool project!
When printing a deck from forge-desktop-gui, cards with back faces were not fully represented. This simple PR, simply adds back faced cards to the output of `DeckHtmlSerializer.writeDeckHtml`.
/ Henry
> Add back faced cards to writeDeckHtml

- forge-gui/res/cardsfolder/a/animar_soul_of_elements.txt
- forge-gui/res/cardsfolder/d/damia_sage_of_stone.txt
- forge-gui/res/cardsfolder/d/doran_the_siege_tower.txt
- forge-gui/res/cardsfolder/f/fervent_charge.txt
- forge-gui/res/cardsfolder/f/fungal_shambler.txt
- forge-gui/res/cardsfolder/g/galea_kindler_of_hope.txt
- forge-gui/res/cardsfolder/g/ghave_guru_of_spores.txt
- forge-gui/res/cardsfolder/g/guided_passage.txt
- forge-gui/res/cardsfolder/i/intet_the_dreamer.txt
- forge-gui/res/cardsfolder/k/kaalia_of_the_vast.txt
- forge-gui/res/cardsfolder/m/maelstrom_wanderer.txt
- forge-gui/res/cardsfolder/m/modo_the_gnarled_oracle.txt
- forge-gui/res/cardsfolder/n/numot_the_devastator.txt
- forge-gui/res/cardsfolder/o/oros_the_avenger.txt
- forge-gui/res/cardsfolder/o/overgrown_estate.txt
- forge-gui/res/cardsfolder/p/palladia_mors_the_ruiner.txt
- forge-gui/res/cardsfolder/p/perrie_the_pulverizer.txt
- forge-gui/res/cardsfolder/r/riku_of_two_reflections.txt
- forge-gui/res/cardsfolder/r/ruhan_of_the_fomori.txt
- forge-gui/res/cardsfolder/t/tariel_reckoner_of_souls.txt
- forge-gui/res/cardsfolder/t/teneb_the_harvester.txt
- forge-gui/res/cardsfolder/t/the_mimeoplasm.txt
- forge-gui/res/cardsfolder/t/thunderhawk_gunship.txt
- forge-gui/res/cardsfolder/v/vorosh_the_hunter.txt
Reordered wedge and shard mana symbols for 23 cards. Updated oracle text for Thunderhawk Gunship.
> Card cleanup

- forge-gui-mobile/src/forge/adventure/data/RewardData.java
- forge-gui-mobile/src/forge/adventure/data/SettingData.java
- forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
Adds an option (off by default) to Adventure Mode that adds variants of all cards from all sets to the mix. This effectively ignores the card art preference option ("latest art", "original art", etc.) and simply allows to encounter different variations of the same card in shops. I haven't noticed any negative effects from doing this when playing through a nearly complete Adventure run. As a side effect, you might have a slightly higher chance of encountering a duplicate card in a shop (potentially as a variant from a different set), but I'm not sure if that's the case, as I'm pretty sure I've seen duplicates with this option off as well. If there are any possible issues with this, please let me know.
> Add an option to use all card variants in Adventure Mode

- forge-game/src/main/java/forge/game/ability/effects/ChooseCardNameEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RollPlanarDiceEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/g/garth_one_eye.txt
- forge-gui/res/cardsfolder/i/invasion_of_new_capenna_holy_frazzle_cannon.txt
- forge-gui/res/cardsfolder/l/livaan_cultist_of_tiamat.txt
- forge-gui/res/cardsfolder/w/willbreaker.txt
Follow-up to #3890 so it doesn't always use the choice of the first activation.
To be fair the "hasn't been chosen" part was also already broken because of the abilities no longer being unique thing.
Switched to using the part from _Conundrum Sphinx_ for now so we don't keep adding empty names after all choices are "exterminated". Feels bad because I'd like to get rid of that eventually but that is a worry for another day...
Closes #3895
> Fix Garth One-Eye

- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
- forge-gui/res/puzzle/PS_WOE3.pzl
- In All Card Variants mode, do not regenerate the card variant every time a POI is entered, instead honor the world seed.
- Add puzzle PS_WOE3 - Possibility Storm - Wilds of Eldraine 03.
> Ensure that cards correspond to the world seed in All Card Variants mode + add puzzle PS_WOE3

- forge-gui/res/cardsfolder/d/discover_the_formula.txt
- forge-gui/res/cardsfolder/m/manor_guardian.txt
- forge-gui/res/cardsfolder/n/norns_fetchling.txt
- forge-gui/res/cardsfolder/o/obscura_polymorphist.txt
- forge-gui/res/cardsfolder/p/perilous_iteration.txt
- forge-gui/res/cardsfolder/s/seek_new_knowledge.txt
- forge-gui/res/cardsfolder/w/wandering_treefolk.txt
- forge-gui/res/cardsfolder/y/yuan_ti_scaleshield.txt
All cards using seek mechanic now need to use SeekEffect for proper trigger interaction (currently only Vexyr, Ich-Tekik's Heir)
> refactor ChangeZone -> Seek for Alchemy seek cards

- forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java
Changing default preference for targeting arcs "always on" setting "2".
> Default preference targeting arcs always on

- forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
- forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
> For example, if you control Archetype of Courage, a spell cast by an opponent that gives creatures they control first strike wouldn’t cause the creatures to have first strike, even if later in the turn Archetype of Courage left the battlefield.
> CantHaveKeyword can prevent effect creation

- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/EffectAi.java
- forge-gui/res/cardsfolder/m/mistcaller.txt
Fixes #3975 (not perfect, but at least the basic handling is there), improves AI pulling lands via AF ChangeZone in general.
Fixes #3780
Fixes #3707, although it's quite tricky to cover all possible variants, so I'm sure there are corner case and variant implementations of moving stuff from wherever to the Battlefield indirectly that are not yet covered.
> Improve various AI routines

- forge-ai/src/main/java/forge/ai/ability/ScryAi.java
- forge-gui/res/cardsfolder/w/woe_strider.txt
Fixes #4151 (at least improves it, anyway).
ScryAi currently won't sacrifice things in response to them being targeted though, I might think of a clean enough way to improve that later. Also, need to think about how to make the AI not Scry repeatedly if it's scrying the same stuff to the top of the library :/
> Improve AI for Woe Strider

- forge-gui/res/adventure/common/decks/starter/Adventure - Low Dimir.dck
- forge-gui/res/adventure/common/decks/starter/Adventure - Low Gruul.dck
- forge-gui/res/adventure/common/decks/starter/Adventure - Low Selesnya.dck
An update of the Constructed decks in Adventure to help with the play experience. As some of them were incredibly slow, to the point they were unplayable unless the AI got flooded or screwed. No change to number of rarities in each deck. Simply a better curve that stays in-theme to original deck theme. All have been tested in-game now to confirm they are now playable and can win battles in starting Wastes, while still being simply a starting point for a deck to come together.
> An update of the Constructed decks in Adventure

- forge-gui/res/cardsfolder/upcoming/hotel_of_fears.txt
- forge-gui/res/lists/TypeLists.txt
Fixes a bug where, if a card exiled with Hotel of Fears isn't played before end of turn, the next player during their upkeep would lose life equal to that card's mana value plus the mana value of their own exiled card (and further stacking if that card isn't played, and so on). Also adds two planar types from WHO plane cards that are already merged but didn't update the TypeLists
> Hotel of Fears bugfix, planar types

- forge-gui/res/puzzle/PS_LCI01.pzl
For some reason, when the Saga goes to the graveyard, its front face trigger fires, as if it was untransformed. I tried updating its LKI info via game.updateLastStateForCard after setting the card to the Transformed card state, as well as forcing an update of the card in the setState call, but the net effect is the same - as soon as the card goes to the graveyard, its front face trigger fires away. I tried debugging this and got as far as GameAction#changeZone, in which the temporary "copied" object seems to have the front face characteristics (such as the Creature type, for instance). I couldn't figure out why this happens though. I could use some help here... What do you think @Hanmac @tool4ever ?
On a possibly related note, there seems to be an issue with other things not happening as …
> Add puzzle PS_LCI01 (needs GameState update/fix)

- forge-ai/src/main/java/forge/ai/ability/LifeSetAi.java
Attempts to fix a crash when chaos ensues on The Doctor's Tomb during an AI's turn. (The AI can already safely use the one other Redistribute effect in the game - though it's removed from AI decks and they won't choose to do so, if you use dev tools to force them to cast Reverse the Sands, it won't crash.) However, from my testing this just results in chaos rolls on the AI's turn being ignored entirely, with the trigger not even going on the stack in the first place. (The Doctor's Tomb lacks AIRollPlanarDieParams anyway, but this crash can be relevant if chaos ensues through other effects, such as the "Will of the Planeswalkers" cycle or through Missy's villainous choice ability.)
> [Draft] Update LifeSetAi.java

- forge-gui/res/cardsfolder/m/mahadi_emporium_master.txt
- forge-gui/res/cardsfolder/r/rakshasa_deathdealer.txt
- forge-gui/res/cardsfolder/r/rakshasa_debaser.txt
- forge-gui/res/cardsfolder/r/rakshasa_gravecaller.txt
- forge-gui/res/cardsfolder/r/rakshasa_vizier.txt
- forge-gui/res/cardsfolder/s/soulhunter_rakshasa.txt
This was reported as not working as intended.
https://scryfall.com/card/anb/62/soulhunter-rakshasa
I also removed the cat subtype from relevant cards as seen here (I didn't make any of the other changes from the bottom of the article):
https://magic.wizards.com/en/news/announcements/card-updates-coming-with-khans-of-tarkir-on-mtg-arena
> Fix Soulhunter Rakshasa and remove cat subtype from Rakshasa cards

- forge-gui/res/cardsfolder/b/blight_herder.txt
- forge-gui/res/cardsfolder/e/emergency_powers.txt
- forge-gui/res/cardsfolder/e/ent_draught_basin.txt
- forge-gui/res/cardsfolder/g/graveyard_marshal.txt
- forge-gui/res/cardsfolder/p/prossh_skyraider_of_kher.txt
- forge-gui/res/cardsfolder/s/shadowborn_apostle.txt
- forge-gui/res/cardsfolder/t/titania_voice_of_gaea_titania_gaea_incarnate.txt
- forge-gui/res/editions/Commander 2021.txt
- forge-gui/res/editions/Kaldheim Commander.txt
I was going to do a small typo patch but found the Ent-Draught Basin error partway through, so hopefully it's okay to combine the fixes.
1 FUNCTIONAL CHANGE
Ent-Draught Basin now must tap to activate its ability, as it should be.
8 NON-FUNCTIONAL CHANGES
- Fixed six minor typos for the SpellDescription$ of various cards. These all show up fine in Deck Editor, but in the game, the SpellDescription takes over and there are typos in some of those. None of these are functional changes. See individual description for Graveyard Marshal.
- Changed two rarities (Greed C21 and Momentary Blink KHC).
> Minor typo fixes patch + Ent-Draught Basin tap fix

- forge-ai/src/main/java/forge/ai/ComputerUtilAbility.java
- forge-ai/src/main/java/forge/ai/ability/RollPlanarDiceAi.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/PlanarDice.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/player/Player.java
Closes #4262, by moving the planeswalking ability and the static chaos trigger to an effect carried with the player in a planechase game. Technically the special action to roll the planar die should be part of it too, but then you either have to make the "Planechase Effect" card visible in the UI so that human players can actually click it to roll, or rework how the UI relates to planechase entirely
> Planechase inherent effects

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/SpecialAiLogic.java
- forge-ai/src/main/java/forge/ai/ability/ChooseGenericEffectAi.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/cost/CostPayment.java
- forge-game/src/main/java/forge/game/cost/CostPutCounter.java
- forge-game/src/main/java/forge/game/spellability/AbilityActivated.java
- forge-game/src/main/java/forge/game/spellability/Spell.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
This refactors Riot into an UnlessCost similar to Fabricate
because the rules say, if you can't put counters on the creature, then it needs to gain haste
See #1076
> Riot: refactor into UnlessCost like Fabricate

- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
Hi everyone!
When Forge loads a map, if it cannot find an enemy definition it simply skips adding the enemy. Here is a PR that generates a random enemy instead, chosen from the ones available for the current biome.
This may be particularly useful if someone is tinkering with a new world - initially cloned from the default one - and ends up with mostly empty maps due to removed enemy definitions.
> Adventure: generate random enemy if definition is not found

- forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
- forge-gui-mobile/src/forge/adventure/data/ConfigData.java
- forge-gui-mobile/src/forge/adventure/data/RewardData.java
- forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
Hi everyone,
here is a PR that adds a new config option: "allowedEditions". It works as an alternative to "restrictedEditions", so if someone wants to tinker with worlds limited to just a few sets, they can do so without having to provide a huge "restrictedEditions" list.
> Adventure: config setting 'allowedEditions'

- forge-gui-mobile/src/forge/adventure/data/AdventureQuestStage.java
- forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
- forge-gui-mobile/src/forge/adventure/scene/TileMapScene.java
- forge-gui-mobile/src/forge/adventure/util/AdventureQuestController.java
- forge-gui/res/adventure/Shandalar/world/quests.json
Corrects issue with change list for first map in a point of interest being looked up under different name based on how it was loaded (POI entry, inner map transition, external lookup)
> Adventure - POIChanges & reputation fix

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings/rvr.rnk
- forge-gui/res/editions/Ravnica Remastered.txt
Attempted to recreate the [booster collation ](https://magic.wizards.com/en/news/feature/collecting-ravnica-remastered)as good as possible:
> - 8–10 Commons
> - 3–4 Uncommons
> - 1 Rare or mythic rare
> - 1 Mana slot card
>   - 58% Guildgate (common)
>   - 33% Signet (uncommon)
>   - 9% Chromatic Lantern or a shock land (rare)
> - 1 Retro frame card of any rarity
I ignored the retro slot for now.
> Add Ravnica Remastered draft

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
I'm linking the list to the new Card directly so there's no chance of a GameCommand running twice (though I'm not certain that's a real risk).
Closes #4452
> Fix UntilHostLeavesPlay being dropped when replaced

- forge-gui/res/blockdata/blocks.txt
I made a mistake while extending the blocks.txt file. Ravnica Remastered has no basics, so the entry there has the problem, that after the draft, the a.i. has no basics to choose from and will not add any to their decks.
> Fix: Ravnica Remastered draft

- forge-gui/src/main/java/forge/player/GamePlayerUtil.java
This printing is made whenever a match is started. 
When running ai simulations it floods the console.
> Remove useless print

- forge-gui/src/main/java/forge/gamemodes/limited/ReadDraftRankings.java
Fixes #4522
Not the prettiest solution though.
Proof it works:
> Draft rankings:  make split cards retrievable

- forge-gui/res/cardsfolder/rebalanced/a-visions_of_phyrexia.txt
- forge-gui/res/editions/Dominaria United.txt
- forge-gui/res/editions/Multiverse Legends.txt
Wizards' being Wizards'
The patch notes for A-Visions of Phyrexia do not reflfect the card on Arena so I've fixed it.
They also included A-Radha, Coalition Warlord from MUL when the rest were from DMU/BRO so moved it to group with the rest.
> Fix some rebalanced errors

- forge-game/src/main/java/forge/game/card/CardDamageHistory.java
- forge-game/src/main/java/forge/game/combat/Combat.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/player/Player.java
Fixed a bug with cards that care about "this combat". For example warriors stand could be used offensively. Also cleaned up a little bit by moving all of the expiry for "this combat" effects to the same place.
> "this combat" bug

- forge-gui-desktop/src/main/java/forge/menus/HelpMenu.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/model/FModel.java
> Simplify how users can open the log file when we need it

- forge-gui/res/cardsfolder/e/elder_spawn.txt
Description had "Elder Spawn can't be blocked by red creatures" twice.
> fixed elder spawn description

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
Repro:
Cast Essence Vortex on opponents creature
AI pays 0 life to save creature, because the Unless Ghsot ability doesn't have a reference to the Target.
> Fix Essence Vortex (unless costs not referencing targets properly)

- forge-gui/res/cardsfolder/upcoming/forensic_gadgeteer.txt
Abilities copied/derived from:
~Heartstone~ Training Grounds - For the activation cost reduction ability, but to cover *your artifacts*
Riddlesmith - For the "Whenever you cast an artifact spell" trigger template, but to trigger investigation instead of looting
~Only point of doubt is I am unsure whether the `ValidActivatingPlayer$ You` constraint is correct for the cost reduction ability so that only your artifacts get the reduction bonus and not the opponent's. I couldn't figure out a good way to test that.~
All ~other~ abilities work as advertised based on the decks I've built and tested with this card.
> MKM: Forensic Gadgeteer

- forge-game/src/main/java/forge/game/ability/effects/CountersPutOrRemoveEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TimeTravelEffect.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
Previously, the message would be identical for every card chosen, and it was impossible to know whether you should click "Add a counter" or "Remove a counter"
It was also visually impossible to tell that anything had happened at all after clicking one of the options, since the prompt was immediately replaced by a new one and the counters are added all at once after all selections have been made. This could look similar to a frozen/crashed client
Translations need review - I've used google translate and tried to tweak the wordings a bit to match the text that was previously there on this and similar strings
> Add the target card name to the prompt for Time Travel

- forge-gui/res/cardsfolder/upcoming/yes_man_personal_securitron.txt
- forge-gui/res/cardsfolder/upcoming/young_deathclaws.txt
- [Young Deathclaws](https://scryfall.com/card/pip/125/young-deathclaws)
- [Yes Man, Personal Securitron](https://scryfall.com/card/pip/29/yes-man-personal-securitron): While I was working on it, it wasn't showing the `StackDescription$` text I placed on the reflexive trigger. Hopefully setting it to `None` fixes things satisfactorily, though I understand that `StackDescription$` has current general issues being displayed correctly.
> Two PIP cards

- forge-game/src/main/java/forge/game/ability/effects/ChooseGenericEffect.java
Updates "Urza, Academy Headmaster"-specific SpellAbility processing code to use `targetRestrictions` from the selected sub SpellAbility (where the targeting restrictions are actually specified) instead of the top level ("Head to AskUrza.com and click [+1,-1,-6]") `SpellAbility` where `targetRestrictions = null`.
Error spawned by Urza's ability selection without this fix:
```
java.lang.NullPointerException: Cannot invoke "forge.game.spellability.TargetRestrictions.hasCandidates(forge.game.spellability.SpellAbility)" because the return value of "forge.game.spellability.SpellAbility.getTargetRestrictions()" is null
at forge.game.ability.effects.ChooseGenericEffect.resolve(ChooseGenericEffect.java:94)
at forge.game.ability.AbilityApiBased.resolve(AbilityApiBased.java:41)
at …
```
> Fix Urza, Academy Headmaster targeting

- forge-gui/res/cardsfolder/u/nexus_of_becoming.txt
- forge-gui/res/cardsfolder/upcoming/sword_of_wealth_and_power.txt
- [Sword of Wealth and Power](https://scryfall.com/card/big/26/sword-of-wealth-and-power)
- [Nexus of Becoming](https://scryfall.com/card/big/25/nexus-of-becoming)
> BIG: Sword of Wealth and Power & Nexus of Becoming

- forge-gui/res/cardsfolder/upcoming/at_knifepoint.txt
- forge-gui/res/cardsfolder/upcoming/intrepid_stablemaster.txt
- forge-gui/res/cardsfolder/upcoming/magebane_lizard.txt
- forge-gui/res/cardsfolder/upcoming/marauding_sphinx.txt
- forge-gui/res/cardsfolder/upcoming/ornery_tumblewagg.txt
- forge-gui/res/cardsfolder/upcoming/wanted_griffin.txt
- [At Knifepoint](https://www.magicspoiler.com/mtg-spoiler/at-knifepoint/)
- [Intrepid Stablemaster](https://www.magicspoiler.com/mtg-spoiler/intrepid-stablemaster/)
- [Magebane Lizard](https://www.magicspoiler.com/mtg-spoiler/magebane-lizard/)
- [Marauding Sphinx](https://www.magicspoiler.com/mtg-spoiler/marauding-sphinx/)
- [Ornery Tumblewagg](https://www.magicspoiler.com/mtg-spoiler/ornery-tumblewagg/)
Minor fixes:
- Added missing AI deckbuilding tags on At Knifepoint and Wanted Griffin
> OTJ: At Knifepoint, Intrepid Stablemaster, Magebane Lizard, Marauding Sphinx, Ornery Tumblewagg

- forge-gui/res/cardsfolder/s/space_marine_scout.txt
- forge-gui/res/cardsfolder/upcoming/claim_jumper.txt
- forge-gui/res/cardsfolder/upcoming/dance_of_the_tumbleweeds.txt
- forge-gui/res/cardsfolder/upcoming/demonic_ruckus.txt
- forge-gui/res/cardsfolder/upcoming/roxanne_starfall_savant.txt
- forge-gui/res/tokenscripts/meteorite.txt
- [Claim Jumper](https://scryfall.com/card/otj/8/claim-jumper)
- [Dance of the Tumbleweeds](https://scryfall.com/card/otj/160/dance-of-the-tumbleweeds)
- [Demonic Ruckus](https://scryfall.com/card/otj/120/demonic-ruckus)
- [Roxanne, Starfall Savant](https://scryfall.com/card/otj/228/roxanne-starfall-savant)
Minor fixes
- [Space Marine Scout](https://scryfall.com/card/40k/15/space-marine-scout)'s "may" triggered ability was missing the `OptionalDecider$ You` and  `ShuffleNonMandatory$ True` parameters.
> OTJ: Claim Jumper, Dance of the Tumbleweeds, Demonic Ruckus, Roxanne

- forge-gui/res/cardsfolder/upcoming/insatiable_avarice.txt
- forge-gui/res/cardsfolder/upcoming/oltec_matterweaver.txt
- forge-gui/res/cardsfolder/upcoming/vaultborn_tyrant.txt
- [Oltec Matterweaver](https://scryfall.com/card/big/3/oltec-matterweaver)
- [Vaultborn Tyrant](https://scryfall.com/card/big/20/vaultborn-tyrant)
Minor fixes:
- Corrected `CharmNum$` on Insatiable Avarice.
> BIG: Oltec Matterweaver, Vaultborn Tyrant

- forge-gui/res/cardsfolder/upcoming/thunder_salvo.txt
- forge-gui/res/cardsfolder/upcoming/trick_shot.txt
- forge-gui/res/cardsfolder/upcoming/vault_plunderer.txt
- [Thunder Salvo](https://scryfall.com/card/otj/150/thunder-salvo)
- [Trick Shot](https://scryfall.com/card/otj/151/trick-shot)
- [Vault Plunderer](https://scryfall.com/card/otj/114/vault-plunderer)
On the chance the use of `DamageMap` and `DamageResolve` in Trick Shot is curious: I referenced the script partly from [Drakuseth, Maw of Flames](https://scryfall.com/card/cmm/218/drakuseth-maw-of-flames) and, given the similarity between the spell ability and the triggered ability, assumed that's what's to be used in this particular case.
> OTJ: Thunder Salvo, Trick Shot, Vault Plunderer

- forge-gui/res/cardsfolder/d/dimir_informant.txt
- forge-gui/res/cardsfolder/g/geralfs_masterpiece.txt
- forge-gui/res/cardsfolder/g/grim_strider.txt
- forge-gui/res/cardsfolder/upcoming/roxanne_starfall_savant.txt
- forge-gui/res/cardsfolder/upcoming/spinewoods_paladin.txt
- forge-gui/res/cardsfolder/upcoming/stagecoach_security.txt
- forge-gui/res/cardsfolder/upcoming/steer_clear.txt
- forge-gui/res/cardsfolder/upcoming/sterling_hound.txt
- forge-gui/res/cardsfolder/upcoming/sterling_keykeeper.txt
- forge-gui/res/cardsfolder/upcoming/stingerback_terror.txt
- forge-gui/res/cardsfolder/upcoming/take_the_fall.txt
- forge-gui/res/cardsfolder/upcoming/vaultborn_tyrant.txt
- forge-gui/res/tokenscripts/meteorite.txt
- [Spinewoods Paladin](https://scryfall.com/card/otj/183/spinewoods-paladin)
- [Stagecoach Security](https://scryfall.com/card/otj/30/stagecoach-security)
- [Steer Clear](https://scryfall.com/card/otj/31/steer-clear)
- [Sterling Hound](https://scryfall.com/card/otj/249/sterling-hound)
- [Sterling Keykeeper](https://scryfall.com/card/otj/32/sterling-keykeeper)
- [Stingerback Terror](https://scryfall.com/card/otj/147/stingerback-terror)
Minor fixes:
- Fixed Take the Fall missing a crucial `YouCtrl` on a counting `SVar`.
- Cleanup of Vault Tyrant's `Oracle` and `TriggerDescription` text.
- Moved the likely spurious `SVar:PlayMain1:TRUE` tag on the token version of Meteorite to Roxanne, Starfall Savant itself. Also added the required `SVar:HasAttackEffect:TRUE` for …
> OTJ: Spinewoods Paladin, Stagecoach Security, Steer Clear, Sterling Hound, Sterling Keykeeper, Stingerback Terror

- forge-ai/src/main/java/forge/ai/ability/PermanentCreatureAi.java
- forge-gui/res/puzzle/PS_PIP1.pzl
E.g. Discover X or a transformed Battle - assume that an out-of-timing permanent cast without paying its mana cost is good enough to not rely on advanced Flash considerations.
> Fix advanced Flash logic messing with PlayEffectAi

- forge-gui/res/cardsfolder/upcoming/nimble_brigand.txt
- forge-gui/res/cardsfolder/upcoming/seize_the_secrets.txt
- forge-gui/res/cardsfolder/upcoming/shackle_slinger.txt
- forge-gui/res/cardsfolder/upcoming/shepherd_of_the_clouds.txt
- [Nimble Brigand](https://scryfall.com/card/otj/58/nimble-brigand)
- [Seize the Secrets](https://scryfall.com/card/otj/64/seize-the-secrets)
- [Shackle Slinger](https://scryfall.com/card/otj/65/shackle-slinger)
- [Shepherd of the Clouds](https://scryfall.com/card/otj/28/shepherd-of-the-clouds)
I must say, regarding Nimble Brigand (and similar cards), that it would be nice to have the text: "`CARDNAME` can't be blocked" displayed on the card when the (non-)ability is active just to make things a bit clearer.
> OTJ: Nimble Brigand, Seize the Secrets, Shackle Slinger, Shepherd of the Clouds

- forge-gui/res/cardsfolder/upcoming/vengeful_regrowth.txt
- forge-gui/res/cardsfolder/upcoming/vihaan_goldwaker.txt
- forge-gui/res/cardsfolder/upcoming/we_ride_at_dawn.txt
- forge-gui/res/cardsfolder/v/vexing_puzzlebox.txt
- [Vengeful Regrowth](https://scryfall.com/card/otc/35/vengeful-regrowth)
- [Vihaan, Goldwaker](https://scryfall.com/card/otc/8/vihaan-goldwaker)
- [We Ride at Dawn](https://scryfall.com/card/otc/12/we-ride-at-dawn)
Minor fixes:
- Vexing Puzzlebox: cleaning up extraneous duplication on the first activated ability's `SpellDescription$`.
> OTC: Vengeful Regrowth, Vihaan, We Ride at Dawn

- forge-gui/res/cardsfolder/a/awakener_druid.txt
- forge-gui/res/cardsfolder/b/balduvian_frostwaker.txt
- forge-gui/res/cardsfolder/b/brenard_ginger_sculptor.txt
- forge-gui/res/cardsfolder/h/halsin_emerald_archdruid.txt
- forge-gui/res/cardsfolder/h/hedge_whisperer.txt
- forge-gui/res/cardsfolder/i/ignition_team.txt
- forge-gui/res/cardsfolder/j/jolrael_voice_of_zhalfir.txt
- forge-gui/res/cardsfolder/k/koth_of_the_hammer.txt
- forge-gui/res/cardsfolder/r/roaring_earth.txt
- forge-gui/res/cardsfolder/s/synth_infiltrator.txt
- forge-gui/res/cardsfolder/upcoming/thieving_varmint.txt
- forge-gui/res/cardsfolder/upcoming/thunderclap_drake.txt
- forge-gui/res/cardsfolder/upcoming/tower_winder.txt
- forge-gui/res/cardsfolder/w/woodwraith_corrupter.txt
Tested scripts for:
- [Thieving Varmint](https://scryfall.com/card/otc/59/thieving-varmint)
- [Thunderclap Drake](https://scryfall.com/card/otc/53/thunderclap-drake)
- [Tower Winder](https://scryfall.com/card/otc/70/tower-winder)
Minor fixes
- Per discussion on Discord, added `Creature` to the `AddTypes$` parameter of the `CopyPermanent` effect of [Brenard, Ginger Sculptor](https://scryfall.com/card/woc/27/brenard-ginger-sculptor) and [Synth Infiltrator](https://scryfall.com/card/pip/40/synth-infiltrator) to follow the relevant rulings. (Moved from https://github.com/Card-Forge/forge/pull/4776 )
- Similar effect review: 
• Halsin, Emerald Archdruid was missing the color-setting part of its ability
• Hedge Whisperer had the wrong creature type and since the ability, unlike Halsin's, …
> OTC: Thieving Varmint, Thunderclap Drake, Tower Winder

- forge-core/src/main/java/forge/card/CardDb.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
I think this should close #4472 
- now you can add specialize faces to battlefield through Dev cheats
-  In the issue's corner case with that Maelstrom Archangel Avatar Vanguard + the specialize face now Forge will spit out a non-specialized version of the card. Is that legal/correct? I'm sure we'll never know since this combines Alchemy and Vanguard. I'm not convinced that the Maelstrom Archangel Avatar should find a mana cost match at all.
- seems like the CardDb code also makes loading the proper art for each specialize face work now
> fix crashes issue4472

- forge-ai/src/main/java/forge/ai/ability/CopyPermanentAi.java
- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardState.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/v/vizier_of_many_faces.txt
- forge-gui/res/cardsfolder/v/vizier_of_the_anointed.txt
Removed `EternalizeOrEmbalm` for Vizier of the Anointed
Refactored `Vizier of Many Faces` a bit 
Technically it could be affected by CardTextChanges, even if there isn't a card like that right now
> Embalm and Eternalize use Keyword and Refactor Copy

- forge-gui/res/cardsfolder/upcoming/orochi_soul_reaver.txt
- forge-gui/res/cardsfolder/upcoming/pyretic_charge.txt
- forge-gui/res/cardsfolder/upcoming/sand_scout.txt
- [Orochi Soul-Reaver](https://scryfall.com/card/otc/22/orochi-soul-reaver)
- [Pyretic Charge](https://scryfall.com/card/otc/29/pyretic-charge)
- [Sand Scout](https://scryfall.com/card/otc/11/sand-scout)
> OTC: Orochi Soul-Reaver, Pyretic Charge, Sand Scout

- forge-gui/res/cardsfolder/a/angels_tomb.txt
- forge-gui/res/cardsfolder/a/arlinn_the_packs_hope_arlinn_the_moons_fury.txt
- forge-gui/res/cardsfolder/c/cavernous_maw.txt
- forge-gui/res/cardsfolder/g/glint_hawk_idol.txt
- forge-gui/res/cardsfolder/h/hidden_ancients.txt
- forge-gui/res/cardsfolder/h/hidden_gibbons.txt
- forge-gui/res/cardsfolder/h/hidden_guerrillas.txt
- forge-gui/res/cardsfolder/h/hidden_herd.txt
- forge-gui/res/cardsfolder/h/hidden_predators.txt
- forge-gui/res/cardsfolder/h/hidden_spider.txt
- forge-gui/res/cardsfolder/h/hidden_stag.txt
- forge-gui/res/cardsfolder/l/lurking_evil.txt
- forge-gui/res/cardsfolder/l/lurking_jackals.txt
- forge-gui/res/cardsfolder/l/lurking_skirge.txt
- forge-gui/res/cardsfolder/o/opal_acrolith.txt
- forge-gui/res/cardsfolder/o/opal_archangel.txt
- forge-gui/res/cardsfolder/o/opal_avenger.txt
- forge-gui/res/cardsfolder/o/opal_caryatid.txt
- forge-gui/res/cardsfolder/o/opal_champion.txt
- forge-gui/res/cardsfolder/o/opal_gargoyle.txt
- forge-gui/res/cardsfolder/o/opal_guardian.txt
- forge-gui/res/cardsfolder/o/opal_titan.txt
- forge-gui/res/cardsfolder/s/sanguine_statuette.txt
- forge-gui/res/cardsfolder/s/sarkhan_the_dragonspeaker.txt
- forge-gui/res/cardsfolder/s/sarkhan_the_masterless.txt
- forge-gui/res/cardsfolder/v/veil_of_birds.txt
- forge-gui/res/cardsfolder/v/veiled_apparition.txt
- forge-gui/res/cardsfolder/v/veiled_crocodile.txt
- forge-gui/res/cardsfolder/v/veiled_sentry.txt
- forge-gui/res/cardsfolder/v/veiled_serpent.txt
After further discussion here, https://github.com/Card-Forge/forge/pull/5016 , turns out I was a bit confused in my recollection of the rules around card type and subtype changes. This is a hopefully more correct attempt at what I was trying to do, which is to ensure that when the rules require it creature types are removed when cards self-animate.
> Animate effect cleanup pass #2.5

- forge-gui/res/cardsfolder/h/honor_worn_shaku.txt
- forge-gui/res/cardsfolder/s/show_of_confidence.txt
- forge-gui/res/cardsfolder/upcoming/kirri_talented_sprout.txt
- forge-gui/res/cardsfolder/upcoming/leyline_dowser.txt
- forge-gui/res/cardsfolder/upcoming/lock_and_load.txt
Tested card scripts for :
- [Kirri, Talented Sprout](https://scryfall.com/card/otc/7/kirri-talented-sprout)
- [Leyline Dowser](https://scryfall.com/card/otc/39/leyline-dowser)
- [Lock and Load](https://scryfall.com/card/otc/15/lock-and-load)
Minor fixes
- As a source for Lock and Load, I felt [Show of Confidence](https://scryfall.com/card/stx/28/show-of-confidence)'s counting `SVar` should follow the text of the card more closely even if that's unlikely to have functional significance anytime soon. Tested both new and updated cards to satisfaction.
- As a source for Leyline Dowser, updated [Honor-Worn Shaku](https://scryfall.com/card/cmm/954/honor-worn-shaku)'s second ability, subsuming the explicit `CostDesc$` into the `Cost$` parameter.
> OTC: Kirri, Leyline Dowser, Lock and Load

- forge-gui/res/cardsfolder/g/gorging_vulture.txt
- forge-gui/res/cardsfolder/upcoming/discreet_retreat.txt
- forge-gui/res/cardsfolder/upcoming/dream_thiefs_bandana.txt
- forge-gui/res/cardsfolder/upcoming/dune_chanter.txt
- [Discreet Retreat](https://scryfall.com/card/otc/20/discreet-retreat)
- [Dream-Thief's Bandana](https://scryfall.com/card/otc/38/dream-thiefs-bandana)
- [Dune Chanter](https://scryfall.com/card/otc/31/dune-chanter)
Minor fixes
- Updated Oracle and `TriggerDescription$` text for [Gorging Vulture](https://scryfall.com/card/clu/112/gorging-vulture).
> OTC: Discreet Retreat, Dream-Thief's Bandana, Dune Chanter

- forge-gui/res/cardsfolder/b/bloodborn_scoundrels.txt
- forge-gui/res/cardsfolder/b/bring_down.txt
- forge-gui/res/cardsfolder/d/dwarven_lightsmith.txt
- forge-gui/res/cardsfolder/f/fan_favorite.txt
- forge-gui/res/cardsfolder/g/game_plan.txt
- forge-gui/res/cardsfolder/g/gang_up.txt
- forge-gui/res/cardsfolder/g/golden_argosy.txt
- forge-gui/res/cardsfolder/h/huddle_up.txt
- forge-gui/res/cardsfolder/l/lava_field_overlord.txt
- forge-gui/res/cardsfolder/m/magma_hellion.txt
- forge-gui/res/cardsfolder/o/out_of_bounds.txt
- forge-gui/res/cardsfolder/p/play_of_the_game.txt
- forge-gui/res/cardsfolder/s/skystreamer.txt
- forge-gui/res/cardsfolder/s/spellweaver_duo.txt
- forge-gui/res/cardsfolder/t/the_crowd_goes_wild.txt
- forge-gui/res/cardsfolder/v/vampire_charmseeker.txt
Scripts for the remaining Assist cards. Needs #4986. Charging Binox already in that PR.
> BBD: Assist cards

- forge-gui/res/cardsfolder/a/artistic_refusal.txt
- forge-gui/res/cardsfolder/a/aurelias_fury.txt
- forge-gui/res/cardsfolder/a/avacyns_judgment.txt
- forge-gui/res/cardsfolder/b/barbarian_guides.txt
- forge-gui/res/cardsfolder/b/builders_bane.txt
- forge-gui/res/cardsfolder/c/catch_release.txt
- forge-gui/res/cardsfolder/c/choking_vines.txt
- forge-gui/res/cardsfolder/c/conflagrate.txt
- forge-gui/res/cardsfolder/d/deepwood_elder.txt
- forge-gui/res/cardsfolder/f/fireball.txt
- forge-gui/res/cardsfolder/f/firestorm.txt
- forge-gui/res/cardsfolder/f/flockchaser_phantom.txt
- forge-gui/res/cardsfolder/g/game_of_chaos.txt
- forge-gui/res/cardsfolder/h/henrika_domnathi_henrika_infernal_seer.txt
- forge-gui/res/cardsfolder/h/hotel_of_fears.txt
- forge-gui/res/cardsfolder/i/ichor_aberration.txt
- forge-gui/res/cardsfolder/k/kaboom.txt
- forge-gui/res/cardsfolder/k/kaylas_command.txt
- forge-gui/res/cardsfolder/m/meteor_shower.txt
- forge-gui/res/cardsfolder/o/officious_interrogation.txt
- forge-gui/res/cardsfolder/r/rolling_thunder.txt
- forge-gui/res/cardsfolder/s/sacellum_godspeaker.txt
- forge-gui/res/cardsfolder/s/serras_hymn.txt
- forge-gui/res/cardsfolder/s/soulfire_eruption.txt
- forge-gui/res/cardsfolder/s/subversive_acolyte.txt
- forge-gui/res/cardsfolder/t/the_fourth_doctor.txt
- forge-gui/res/cardsfolder/w/wand_of_the_worldsoul.txt
- forge-gui/res/cardsfolder/w/woeleecher.txt
- forge-gui/res/cardsfolder/w/wurmquake.txt
Here's some stragglers that escaped the last typo cleanup ( https://github.com/Card-Forge/forge/pull/5036 ). I also took the opportunity to do some minor standardization of `SVar` items: a few rare ones that referred to the same concept under different aliases.
If the change to [The Fourth Doctor](https://scryfall.com/card/who/2/the-fourth-doctor) is curious it's because I'm following the standard set by ["Ach! Hans, Run!"](https://scryfall.com/card/unh/116/ach!-hans-run!) on how an ellipsis is displayed in a Magic card text box.
> Typo cleanup pass #3

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-gui/res/cardsfolder/upcoming/forgers_foundry.txt
- forge-gui/res/cardsfolder/upcoming/savvy_trader.txt
- forge-gui/res/cardsfolder/upcoming/smirking_spelljacker.txt
- forge-gui/res/cardsfolder/upcoming/smoldering_stagecoach.txt
- [Forger's Foundry](https://scryfall.com/card/otc/14/forgers-foundry)
- [Savvy Trader](https://scryfall.com/card/otc/33/savvy-trader)
- [Smirking Spelljacker](https://scryfall.com/card/otc/16/smirking-spelljacker)
- [Smoldering Stagecoach](https://scryfall.com/card/otc/30/smoldering-stagecoach)
On Smoldering Stagecoach, I wasn't entirely sure how to merge the common bits of the cascade-granting effects safely, if it is at all possible, so I opted for splitting them entirely. Yes, the structure there is interleaved so I could more easily compare each line to their counterpart. I can change that though.
> OTC: Forger's Foundry, Savvy Trader, Smirking Spelljacker, Smoldering Stagecoach

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/altair_ibn_laahad.txt
- forge-gui/res/cardsfolder/upcoming/haystack.txt
- forge-gui/res/cardsfolder/upcoming/the_animus.txt
- [Altaïr Ibn-La'Ahad](https://scryfall.com/card/acr/45/alta%C3%AFr-ibn-laahad)
- [Haystack](https://scryfall.com/card/acr/175/haystack)
- [The Animus](https://scryfall.com/card/acr/69/the-animus)
Also added memory counters used by two of the above and [Owen Grady](https://scryfall.com/card/rex/16/owen-grady-raptor-trainer)'s haste counters to `CounterEnumType.java`.
> ACR: Altaïr, Haystack, The Animus

- forge-ai/src/main/java/forge/ai/ability/ExploreAi.java
AI shouldn't miss triggers with AF Explore. Fixes #5063.
> Add AI implementation for Subterranean Schooler

- forge-gui/res/cardsfolder/d/dust_animus.txt
Changed `ConditionCompare$` to `ConditionSVarCompare$` since otherwise it would default to `GE1`. Tested to satisfaction: it counts the required untapped lands now. Closes https://github.com/Card-Forge/forge/issues/5078 .
> Fixing Dust Animus static "enters with" ability

- forge-ai/src/main/java/forge/ai/AiProps.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/Match.java
- forge-gui/res/ai/Cautious.ai
- forge-gui/res/ai/Default.ai
- forge-gui/res/ai/Experimental.ai
- forge-gui/res/ai/Reckless.ai
Currently very basic, initially will only make modifications on a loss and only with cards that are more or less equivalent when it comes to their colors and mana value. Will skip lands and cards with mana abilities in order not to screw up the mana base and curve, and will only replace creatures with creatures. Easily toggled on/off via AI profile settings.
> Basic AI sideboarding framework

- forge-gui/res/cardsfolder/c/cathars_companion.txt
- forge-gui/res/cardsfolder/o/overzealous_muscle.txt
Comparing the scripts of [Overzealous Muscle](https://scryfall.com/card/otj/97/overzealous-muscle) and [Cathar's Companion](https://scryfall.com/card/jmp/94/cathars-companion), the only pertinent difference was `Defined$ Card.Self` on the first, contrasting `Defined$ Self` on the second. Testing Overzealous Muscle with the Companion's relevant argument for that parameter had the Ogre working properly. 
Noticing the latter was lacking `SpellDescription$` on the indestructible-granting line and not seeing that text displayed anywhere in the GUI for Cathar's Companion, I removed the `SpellDescription$` from the Dog's relevant line.
> Fixing Overzealous Muscle granting indestructible to players and not itself

- forge-gui/res/cardsfolder/v/vexyr_ich_tekiks_heir.txt
Closes https://github.com/Card-Forge/forge/issues/5192 . 
As described in the bug report, a missing `TriggerZones$ Battlefield` parameter allowed the card to trigger from anywhere. That is now resolved. While I was at it, I added relevant deckbuilding tags.
> Fixing Vexyr, Ich-Tekik's Heir triggering from library

- forge-gui/res/cardsfolder/c/champions_of_tyr.txt
As the title says, doing so by correcting the capitalization of the keyword to follow what the `*.java` files lay out. Any other relevant foray is patently beyond my expertise.
> Fixing Champions of Tyr double team ability not triggering

- forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
Imo we might not need any extra checks there because the logic from CardZoneTable already provides the right state:
https://github.com/Card-Forge/forge/blob/bfba7ea773c362cb288af907953390dcb0e62867/forge-game/src/main/java/forge/game/card/CardZoneTable.java#L47-L55
Urborg involved is also fine.
Closes #5299
> Fix Scapeshift returning Lake of the Dead + Swamp which it can sacrifice

- forge-gui/res/cardsfolder/p/planeswalkers_mischief.txt
- forge-gui/res/cardsfolder/p/psychic_theft.txt
The delayed trigger for both [Planeswalker's Mischief](https://scryfall.com/card/pls/29/planeswalkers-mischief) and [Psychic Theft](https://scryfall.com/card/pcy/40/psychic-theft) wasn't working properly: the exiled card wasn't returned to hand if it wasn't cast. So, by comparison with [Bank Job](https://scryfall.com/card/ysnc/18/bank-job), a similar enough card, I restored the former cards' functionality.
> Fixing Planeswalker's Mischief, Psychic Theft

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityAlternativeCost.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-gui/res/cardsfolder/b/bludgeon_brawl.txt
- forge-gui/res/cardsfolder/g/graywaters_fixer.txt
- forge-gui/res/cardsfolder/k/kentaro_the_smiling_cat.txt
- forge-gui/res/cardsfolder/m/marshland_bloodcaster.txt
- forge-gui/res/cardsfolder/s/sliver_gravemother.txt
- forge-gui/src/main/java/forge/player/HumanPlay.java
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
Fixes using _Marshland Bloodcaster_ ability for casting breaking in case the spell uses some hardcoded X SVar.
Also reworked hopefully all remaining {X} cases, so that the calculation only happens before you pay.
(This makes them work with the `CostContainsX` mana restriction - currently done in 4 cards).
> StaticAbilityAlternativeCost: improve X handling

- forge-gui/res/cardsfolder/e/ecological_appreciation.txt
Prevents the AI from cheating with Ecological Appreciation. It seems to do the job, but if need be, we may design a better targeted AI logic for this card and/or similar cards. Fixes #5378
> Remove erroneous AILogic flag from Ecological Appreciation

- forge-gui/res/cardsfolder/upcoming/localized_destruction.txt
- forge-gui/res/cardsfolder/upcoming/selective_obliteration.txt
AI will need help to pick a logical color for Selective Obliteration
Right now it always picks Black
Seems like it needs to be:
- color of "best" mono colored permanent AI controls
- color of highest number of mono colored permanents AI controls
I poked around in PlayerControllerAi.chooseColor but I don't think that's the right spot
> M3C: final 2 "easy" cards

- forge-gui/res/puzzle/PS_OTJ4.pzl
No idea what they actually meant here:
https://i2.wp.com/www.possibilitystorm.com/wp-content/uploads/2024/05/latest-1-scaled.jpg?ssl=1
They draw 3 Restless Bivouac and 2 Shivan Reef, but say in text that there are 2 Restless Bivouac and 3 Shivan Reef :/ Any ideas, guys?...
> Add puzzle PS_OTJ4

- forge-gui/res/cardsfolder/rebalanced/a-tyvar_kell.txt
- forge-gui/res/cardsfolder/t/tyvar_kell.txt
The +1 loyalty ability reads "Put a +1/+1 counter on up to one target Elf."
> Missing up to one logic.

- forge-gui/res/quest/commanderprecons/Creative Energy [M3C] [2024].dck
- forge-gui/res/quest/commanderprecons/Eldrazi Incursion [M3C] [2024].dck
- forge-gui/res/quest/commanderprecons/Graveyard Overdrive [M3C] [2024].dck
- forge-gui/res/quest/commanderprecons/Tricky Terrain [M3C] [2024].dck
I tried to assign the right image numbers, as the first image for most of cards is the extended version. Since Overclocked Electromancer is still unimplemented, Creative Energy won't work yet.
> MH3 Precon decks

- forge-gui/res/cardsfolder/upcoming/ral_crackling_wit.txt
- forge-gui/res/cardsfolder/upcoming/three_tree_city.txt
- forge-gui/res/tokenscripts/ur_1_1_otter_prowess.txt
Tested card scripts developed with an assist from [ForgeScribeGPT4](https://chatgpt.com/g/g-TGeM8rWuF-forgescribegpt4):
- [Ral, Crackling Wit](https://www.reddit.com/r/magicTCG/comments/1dn0ua7/blb_leaks_from_rumors_ral_crackling_wit_parting/) and its token
- [Three Tree City](https://www.reddit.com/r/magicTCG/comments/1dnxc1q/blb_another_leak_from_rumors_three_tree_city/)
I gave these as best a once over as I could to deal with the inevitable generative model mishaps but a double- or even triple-check doesn't hurt.
> BLB: Three Tree City, Ral and its Otter token

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/s/secret_plans.txt
- forge-gui/res/cardsfolder/upcoming/carrot_cake.txt
- forge-gui/res/cardsfolder/upcoming/chainsaw.txt
- forge-gui/res/cardsfolder/upcoming/cursed_recording.txt
- forge-gui/res/cardsfolder/upcoming/early_winter.txt
- forge-gui/res/cardsfolder/upcoming/fear_of_missing_out.txt
- forge-gui/res/cardsfolder/upcoming/leyline_of_hope.txt
- forge-gui/res/cardsfolder/upcoming/might_of_the_meek.txt
- forge-gui/res/cardsfolder/upcoming/pearl_of_wisdom.txt
- forge-gui/res/cardsfolder/upcoming/roshan_hidden_magister.txt
- forge-gui/res/cardsfolder/upcoming/salvation_swan.txt
- forge-gui/res/cardsfolder/upcoming/screaming_nemesis.txt
- forge-gui/res/cardsfolder/upcoming/sunshower_druid.txt
- forge-gui/res/cardsfolder/upcoming/the_wandering_rescuer.txt
- forge-gui/res/cardsfolder/upcoming/toby_beastie_befriender.txt
- forge-gui/res/cardsfolder/upcoming/twitching_doll.txt
- forge-gui/res/lists/TypeLists.txt
- forge-gui/res/quest/commanderprecons/Eldrazi Incursion [M3C] [2024].dck
- forge-gui/res/tokenscripts/g_2_2_spider_reach.txt
- forge-gui/res/tokenscripts/w_4_4_beast_lonely.txt
Added rev counters for Chainsaw and nest counters for Twitching Doll.
Added new tokens for Toby, Beastie Befriender and Twitching Doll.
Corrected a typo in Secret Plans.
Added ACR: Roshan, Hidden Magister
Added BLB: Carrot Cake, Early Winter, Might of the Meek, Pearl of Wisdon, Salvation Swan, Sunshower Druid
Added DSK: Chainsaw; Cursed Recording; Fear of Missing Out; Leyline of Hope; Screaming Nemesis; The Wandering Rescuer; Toby, Beastie Befriender; Twitching Doll
> 15 ACR/BLB/DSK cards

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
Both goldLoss and lifeLoss where not being set on creation + update difficulty. So regardless of difficulty chosen, on defeat the default value on the difficultyData class for the properties (0.2f) was being used
> Update to AdventurePlayer.java

- forge-gui/res/cardsfolder/m/monoxa_midway_manager.txt
Adds a parameter so Monoxa only triggers off the controller's die rolls.
> Fix Monoxa triggering on opponents' dice rolls.

- forge-gui/res/cardsfolder/h/hero_of_bretagard.txt
- forge-gui/res/cardsfolder/upcoming/ezio_brash_novice.txt
Noticed [Ezio, Brash Novice](https://scryfall.com/card/acr/55/ezio-brash-novice) was missing from repository, so I scripted it and tested it successfully. 
Also fixed redundancy and a typo in one of the source cards, [Hero of Bretagard](https://scryfall.com/card/khc/4/hero-of-bretagard): as the second static ability adds the God type without overwriting existing creature types, it doesn't need to reiterate the Angel type granted by the first static ability. Tested the new script version: it works as expected.
> ACR: Ezio, Brash Novice

- forge-gui/res/cardsfolder/d/dryad_arbor.txt
- forge-gui/res/cardsfolder/e/elvish_impersonators.txt
- forge-gui/res/cardsfolder/j/jasconian_isle.txt
- forge-gui/res/cardsfolder/r/robot_chicken.txt
Had an idle look at the Card Catalog ordered by type:
- [Robot Chicken](https://scryfall.com/card/pcel/6/robot-chicken): Changed the unlisted Chicken type to Bird, following the rationale used for other old funny cards in the [Oracle Changes announcement for _Ikoria_](https://magic.wizards.com/en/news/announcements/oracle-changes-2020-04-10) (`CTRL + F` "FOWL PLAY"). `*`
- [Elvish Impersonators](https://scryfall.com/card/und/62/elvish-impersonators): Changed the creature type to the singular declension, since otherwise the card doesn't count as an Elf as the game engine understands it. The appended screenshot shows, for instance, that this creature isn't gaining forestwalk from an [Elvish Champion](https://scryfall.com/card/10e/261/elvish-champion), when it plainly should. `*`
- …
> Incidental cleanup pass #3

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-gui/res/cardsfolder/w/wandering_archaic_explore_the_vastlands.txt
The shortcut for card copies became problematic because in this case the host would still be LKI from the "Henzie" AltCost logic.
> Fix LKI entering battlefield

- forge-ai/src/main/java/forge/ai/ability/ChooseGenericEffectAi.java
- forge-core/src/main/java/forge/util/CardTranslation.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-gui/res/lists/altwin-achievements.txt
- forge-gui/src/main/java/forge/localinstance/achievements/AltWinAchievements.java
Addressing code issues relevant to this pull request series:
- Per [discussion](https://github.com/Card-Forge/forge/pull/5518#discussion_r1667378878), attempted to locate all the spots where the code refers to emblems in association with an `-` (en-dash), so that changing the `-` to an  `—` (em-dash) in emblem names goes smoothly.
> July 2024 cleanup: code

- forge-gui/res/cardsfolder/upcoming/enduring_tenacity.txt
Tested card script for:
- [Enduring Tenacity](https://www.reddit.com/r/magicTCG/comments/1dphm0f/dsk_enduring_tenacity/)
While [ForgeScribeGPT4](https://chatgpt.com/g/g-TGeM8rWuF-forgescribegpt4) sped up laying things out, comparison with [Defiant Bloodlord](https://scryfall.com/card/c21/142/defiant-bloodlord) and [Old-Growth Troll](https://scryfall.com/card/khm/185/old-growth-troll) allowed me to curb the generative model's excesses. I assume Glimmer is a new enchantment type but the card seems to work fine without having that defined so I'd default to waiting on relevant explicit information to add it to `TypeLists.txt`.
>  DSK: Enduring Tenacity

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/upcoming/overlord_of_the_hauntwoods.txt
- forge-gui/res/tokenscripts/everywhere.txt
Closes #5481
First try of Impending Keyword and Everywhere Land Token. These might be updated later when we know more about the rules.
The Current Implementation of Impending uses a Static Ability that can be enabled by any Time counter.
The Everywhere Land currently has the Land types hard coded, so it can be affected by Card Text Changes.
While The Creature should not, that's why the "LockTokenScript"
> Keyword: Impending

- forge-gui/res/cardsfolder/upcoming/doomsday_excruciator.txt
- forge-gui/res/tokenscripts/ur_1_1_otter_prowess.txt
Tested card script for:
- [Doomsday Excruciator](https://scryfall.com/card/dsk/94/doomsday-excruciator)
Minor fix:
- Reordering lines on Ral, Crackling Wit's Otter token to conform to existing pattern.
> DSK: Doomsday Excruciator

- forge-gui/res/cardsfolder/upcoming/bello_bard_of_the_brambles.txt
[Bello, Bard of the Brambles](https://scryfall.com/card/blc/1/bello-bard-of-the-brambles)'s static ability wasn't granting the relevant types the right way because the argument was using syntax for `$ Animate` effects (types separated by `,` instead of ` & ` as in similar continuous effects like [Ambush Commander](https://scryfall.com/card/scg/111/ambush-commander)). The script now works as expected. I also took the opportunity to change newline characters from `CR LF` (Windows) to `LF` (Unix). Closes https://github.com/Card-Forge/forge/issues/5574 .
> Fixing Bello's static ability

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/PermanentEffect.java
- forge-game/src/main/java/forge/game/card/CardZoneTable.java
Refreshes active triggers before collecting, in line with
> 603.10. Normally, objects that exist immediately after an event are checked to see if the event matched any trigger conditions, and continuous effects that exist at that time are used to determine what the trigger conditions are and what the objects involved in the event look like.
For that to work with LTB trigger their registering has to be done after again (so they're not lost). This also means it's performed only once now for simultaneous zone change.
I tried to test a couple of basic scenarios and it seems to work...
Closes #5557
> Refresh active triggers after statics from ETB

- forge-gui/res/cardsfolder/n/nearby_planet.txt
Attempted to add UNF's Nearby Planet using the Omo effect from M3C (and to a lesser extent Planar Nexus from MH3) as a reference.
Tested card in Forge, seems to work as intended. The displayed typeline is messier than with the Mistform Ultimus/changeling effect for creatures (Mistform displays "(All)" whereas this spells out the types), but it is consistent with the referenced Modern Horizons cards.
> UNF Nearby Planet

- forge-gui/res/cardsfolder/v/vona_de_iedo_the_antifex.txt
In pursuance of a cleanup pass, heading off the issue that the third word in this card's name ( [`Vona de Iedo, the Antifex`](https://scryfall.com/card/yotj/28/vona-de-iedo-the-antifex) ) starts with an uppercase `I` and not a lowercase `l`. File name, card name and relevant mentions in rules text are thus corrected.
> Renaming Vona de Iedo's file

- forge-gui/res/editions/Unfinity.txt
With the recent creation of the eternal category to fix Zur the Enchanter I figured it would also be a good time to fix that same issue with Unfinity.
I believe I included the correct cards. At first I checked the legality on scryfall, but once I noticed that all the illegal cards seemed to start with "F" I just started to move the ones that didn't start with that without checking legality.
> Update Unfinity.txt to include eternal cards

- forge-gui/res/cardsfolder/g/grip_of_chaos.txt
As [Grip of Chaos](https://scryfall.com/card/scg/98/grip-of-chaos) has two trigger condition lines for its trigger `SVar`, one should be marked as `Secondary$` so only one `TriggerDescription$` is displayed in the in-game Card Detail pane.
> Fixing Grip of Chaos in-game display

- forge-ai/src/main/java/forge/ai/AiCostDecision.java
- forge-gui/res/cardsfolder/upcoming/the_capitoline_triad.txt
Not sure about the sorting of cards in the card list... Should we do it at all, or just let the AI grab whatever cards? Sometimes leaving more cards in the graveyard seems better, sometimes grabbing the cheapest stuff may be preferable, so it's difficult to properly account for in our AI...
> Add basic AI for The Capitoline Triad

- forge-gui/res/cardsfolder/upcoming/arthur_marigold_knight.txt
- forge-gui/res/cardsfolder/upcoming/azure_beastbinder.txt
- forge-gui/res/cardsfolder/upcoming/bonebind_orator.txt
- forge-gui/res/cardsfolder/upcoming/daggerfang_duo.txt
- forge-gui/res/cardsfolder/upcoming/dire_downdraft.txt
- forge-gui/res/cardsfolder/upcoming/evercoat_ursine.txt
- forge-gui/res/cardsfolder/upcoming/murmuration.txt
- forge-gui/res/cardsfolder/upcoming/rootcast_apprenticeship.txt
- forge-gui/res/cardsfolder/upcoming/scurry_of_squirrels.txt
- forge-gui/res/cardsfolder/upcoming/swarmyard_massacre.txt
- forge-gui/res/cardsfolder/upcoming/twenty_toed_toad.txt
Dire Downdraft sometimes doesn't give the choice of top or bottom of library. Rootcast Apprenticeship executes third option instead of fourth; not sure why.
> BLB/BLC update 18-07 #2

- forge-core/src/main/java/forge/deck/Deck.java
- forge-core/src/main/java/forge/deck/DeckSection.java
- forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/ACEditorBase.java
- forge-gui-mobile/src/forge/deck/FDeckEditor.java
- forge-gui-mobile/src/forge/screens/quest/QuestMenu.java
Resolves an issue where quest commander was functioning as quest mode in some ways, like commander mode in other ways, and like quest commander in no way whatsoever.
In doing this, I deleted this condition from the deck editor's constructor:
```
if (editorType0 == EditorType.QuestCommander) //fix saving quest commander
editorType = EditorType.Quest;
else
editorType = editorType0;
```
Removing something commented with the words "fix saving" leaves me very nervous because I'm not sure exactly what the issue there was. I did run into these lines in `QuestMenu.java` that seem like they could cause a quest commander deck saving issue since they don't include `EditorType.QuestCommander`:
```
((DeckController<Deck>)EditorType.Quest.getController()).setRootFolder(FModel.getQuest().getMyDecks()); …
```
> Fix for QuestCommander deck editor

- forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
- forge-game/src/main/java/forge/game/card/CardState.java
- forge-gui/res/cardsfolder/e/eriette_the_beguiler.txt
- forge-gui/res/tokenscripts/rock.txt
Reverts the previous cleanup.
@Hanmac
The problem is when the final token gets created from its prototype the traits that get copied over will have that original CardState instead.
Since this seems to be a bigger flaw in the engine related to #143 I probably can't do anything else here 🤔
Closes #5677
> Update cardstates after creating token from prototype

- forge-gui/res/cardsfolder/c/cutthroat_centurion.txt
- forge-gui/res/cardsfolder/upcoming/long_river_lurker.txt
- forge-gui/res/cardsfolder/upcoming/mistbreath_elder.txt
- forge-gui/res/cardsfolder/upcoming/waterspout_warden.txt
Most of Mistbreath Elder's effects didn't work and it was a 4|4 for G instead of a 2|2.
Waterspout Warden had Haste for some reason.
Long River Lurker's effect straight-up crashed Forge due to a naming mismatch.
> Fixes for Mistbreath Elder, Long River Lurker, Waterspout Warden

- forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
- forge-game/src/main/java/forge/game/card/CardZoneTable.java
- forge-gui/res/cardsfolder/a/athreos_shroud_veiled.txt
- forge-gui/res/cardsfolder/upcoming/corpseberry_cultivator.txt
Additional work might be needed once such trigger needs to find the new objects too, but seems this case hasn't been printed yet...
> ChangesZoneAll: stricter LKI filtering

- forge-ai/src/main/java/forge/ai/ability/SacrificeAi.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityVariables.java
- forge-gui/res/cardsfolder/a/aleatory.txt
- forge-gui/res/cardsfolder/c/chaotic_strike.txt
- forge-gui/res/cardsfolder/c/curtain_of_light.txt
- forge-gui/res/cardsfolder/f/flash_foliage.txt
- forge-gui/res/cardsfolder/t/trap_runner.txt
> 506.7f. If a spell states that it may be cast "only during combat after blockers are declared," but the declare blockers step is skipped that combat phase (see rule 508.8), then the spell may not be cast during that combat phase.
> Fix casting Chaotic Strike when no attacker gets declared

- forge-ai/src/main/java/forge/ai/ability/DamageEachAi.java
- forge-ai/src/main/java/forge/ai/ability/DestroyAi.java
- forge-ai/src/main/java/forge/ai/ability/SacrificeAllAi.java
- forge-game/src/main/java/forge/game/ability/effects/DestroyEffect.java
- forge-gui/res/cardsfolder/a/animate_dead.txt
- forge-gui/res/cardsfolder/a/arcum_dagsson.txt
- forge-gui/res/cardsfolder/a/ashling_the_extinguisher.txt
- forge-gui/res/cardsfolder/b/barrins_spite.txt
- forge-gui/res/cardsfolder/b/basalt_golem.txt
- forge-gui/res/cardsfolder/d/dance_of_the_dead.txt
- forge-gui/res/cardsfolder/d/demonic_hordes.txt
- forge-gui/res/cardsfolder/i/incriminate.txt
- forge-gui/res/cardsfolder/m/mercy_killing.txt
- forge-gui/res/cardsfolder/m/myriad_construct.txt
- forge-gui/res/cardsfolder/n/necromancy.txt
- forge-gui/res/cardsfolder/r/reality_acid.txt
- forge-gui/res/cardsfolder/r/retribution.txt
- forge-gui/res/cardsfolder/r/reweave.txt
- forge-gui/res/cardsfolder/rebalanced/a-incriminate.txt
- forge-gui/res/cardsfolder/s/sarkhan_the_mad.txt
- forge-gui/res/cardsfolder/s/shape_anew.txt
Closes #5719 
This reworks "Sacrifice" Effects that were hiding inside Destroy Effects via SacrificeAll
i'm not yet happy with them, i think i would like them more if they were Sacrifice Effects instead of All.
or that Defined is required then using Targets?
> Destroy: refactor fake into SacrificeAll

- forge-gui/res/adventure/common/custom_cards/grolnok_boss_effect.txt
- forge-gui/res/adventure/common/custom_cards/lorthos_presence.txt
- forge-gui/res/adventure/common/custom_cards/third_head_of_the_hydra.txt
- forge-gui/res/tokenscripts/meteorite.txt
- forge-gui/res/tokenscripts/rg_1_1_dragon_flying_devour.txt
- forge-gui/res/tokenscripts/rw_1_2_human_rogue_haste_damage.txt
(Split off from https://github.com/Card-Forge/forge/pull/5720 )
Context for custom card edits:
- Grolnok's Boss Effect, Lorthos' Presence: [Faerie Artisans](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=622700&printed=false)
- Third Head of the Hydra: [Gev, Scaled Scorch](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=669128&printed=false)
The devour Dragon token script had the `Oracle:` reminder text brought in line with what's on other cards, such as [Bloodspore Thrinax](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=627740&printed=false).
> ETB update: 'tokenscripts', 'custom_cards' in `\adventure` 

- forge-gui/res/cardsfolder/b/blessing_of_frost.txt
- forge-gui/res/cardsfolder/b/blood_on_the_snow.txt
- forge-gui/res/cardsfolder/g/graven_lore.txt
- forge-gui/res/cardsfolder/j/jayas_immolating_inferno.txt
- forge-gui/res/cardsfolder/k/kamahls_druidic_vow.txt
- forge-gui/res/cardsfolder/k/karns_temporal_sundering.txt
- forge-gui/res/cardsfolder/p/primevals_glorious_rebirth.txt
- forge-gui/res/cardsfolder/s/search_for_glory.txt
- forge-gui/res/cardsfolder/t/tundra_fumarole.txt
- forge-gui/res/cardsfolder/u/urzas_ruinous_blast.txt
- forge-gui/res/cardsfolder/y/yawgmoths_vile_offering.txt
These were missed for [the main event](https://github.com/Card-Forge/forge/pull/5081) a few months ago. That lapse is thus corrected.
> Cost$ cleanup: Instants and Sorceries with supertypes: Legendary, snow

- forge-game/src/main/java/forge/game/card/Card.java
This decade old shortcut would mean turning ordinary tokens into copies with e.g. _Mirrorweave_ would still keep their CMC at 0.
> Fix token CMC when copying

- forge-gui/res/cardsfolder/a/astral_cornucopia.txt
- forge-gui/res/cardsfolder/n/nykthos_shrine_to_nyx.txt
- forge-gui/res/cardsfolder/n/nyx.txt
- forge-gui/res/cardsfolder/n/nyx_lotus.txt
- forge-gui/res/cardsfolder/r/rhystic_cave.txt
- forge-gui/res/cardsfolder/upcoming/three_tree_city.txt
Mana abilities that require you to choose a color and then generate an arbitrary amount of mana of that color, like that of [Nykthos, Shrine to Nyx](https://scryfall.com/card/ths/223/nykthos-shrine-to-nyx), should have a `SubAbility$ DBCleanup` to immediately clear the chosen color on resolution.
I also took the opportunity to adjust the AI behavior tags for the mana abilities [Nyx Lotus](https://scryfall.com/card/thb/235/nyx-lotus) and [Three Tree City](https://scryfall.com/card/blb/260/three-tree-city) based on what's used for other effects of the same kind.
> Fixing Nykthos, Shrine to Nyx and other related cards

- forge-ai/src/main/java/forge/ai/ability/ControlGainAi.java
- forge-gui/res/cardsfolder/r/rootwater_matriarch.txt
The initial issue is that the AI will target creatures it can't keep with the [Matriarch](https://scryfall.com/card/tmp/83/rootwater-matriarch), as they're not enchanted.
Attempts to fix this through `ControlGainAi.java` bar one result in the AI stalling in an infinite loop. 
This is the **Line 139** edit by itself which has the AI seemingly ignore the Matriarch's ability entirely even with a likely enchanted creature on the board. Because of that this one has been included for convenience but has been commented out to be turned on (or off) as necessary.
The **Line 26** and **Line 127** edits combined by themselves result in the AI stalling when it starts a turn with the Matriarch and a targetable creature on the board.
The **Line 26** + **Line 127** + **Line 139** situation has the AI …
> Fixing Rootwater Matriarch

- forge-gui/res/cardsfolder/m/mountain_mover.txt
An outline of the rationale for adapting this one to Forge follows: 
[Mountain Mover](https://scryfall.com/card/ph20/2/mountain-mover)'s card text reads fairly close to the first printing rules text for [Purgatory](https://scryfall.com/card/mir/275/purgatory) and [Cold Storage](https://scryfall.com/card/tmp/280/cold-storage). Thus interpreting it for Forge's game engine should follow the errata for those cards, functional or otherwise. 
Furthermore, since this is a fairly recent, exceedingly limited run funny card, created well after the consolidation of "set aside" and "removed from the game" and the renaming of that zone to "exile", we can assume there was a looser approach to writing this card up. So, in a similar way to the more serious cards I mentioned, "underneath Mountain Mover" …
> PH20: Mountain Mover

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/phase/Untap.java
- forge-gui/res/cardsfolder/s/surge_of_salvation.txt
Example:
Oppononent uses _Azorius Arrester_ trigger on your creature, then you kill him after. Now your creature would have been detained till game end
> Implement CR 800.4m

- forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
- forge-gui/res/cardsfolder/s/searing_blaze.txt
This aims to improve AI for Searing Blaze so it doesn't limit itself too much with targeting the player specifically, aiming more at the creatures rather than the player's face. Fixes #3997. Not sure if there need to be any preferences for the phase at which this is done, currently the AI will consider it when able.
> Improve AI for Searing Blaze

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityAssignNoCombatDamage.java
- forge-gui/res/cardsfolder/b/bone_dancer.txt
- forge-gui/res/cardsfolder/c/carrion_rats.txt
- forge-gui/res/cardsfolder/c/carrion_wurm.txt
- forge-gui/res/cardsfolder/c/cloak_of_confusion.txt
- forge-gui/res/cardsfolder/d/delifs_cone.txt
- forge-gui/res/cardsfolder/d/delifs_cube.txt
- forge-gui/res/cardsfolder/d/dwarven_vigilantes.txt
- forge-gui/res/cardsfolder/f/farrels_mantle.txt
- forge-gui/res/cardsfolder/f/farrels_zealot.txt
- forge-gui/res/cardsfolder/f/floral_spuzzem.txt
- forge-gui/res/cardsfolder/g/gaze_of_pain.txt
- forge-gui/res/cardsfolder/g/goblin_vandal.txt
- forge-gui/res/cardsfolder/k/keeper_of_tresserhorn.txt
- forge-gui/res/cardsfolder/k/kukemssa_pirates.txt
- forge-gui/res/cardsfolder/l/laccolith_grunt.txt
- forge-gui/res/cardsfolder/l/laccolith_rig.txt
- forge-gui/res/cardsfolder/l/laccolith_titan.txt
- forge-gui/res/cardsfolder/l/laccolith_warrior.txt
- forge-gui/res/cardsfolder/l/laccolith_whelp.txt
- forge-gui/res/cardsfolder/l/lim_duls_paladin.txt
- forge-gui/res/cardsfolder/m/master_of_cruelties.txt
- forge-gui/res/cardsfolder/o/ophidian.txt
- forge-gui/res/cardsfolder/o/orcish_squatters.txt
- forge-gui/res/cardsfolder/p/pygmy_hippo.txt
- forge-gui/res/cardsfolder/r/rysorian_badger.txt
- forge-gui/res/cardsfolder/s/stromgald_spy.txt
Closes #5992 
Static Ability and first batch of cards, others will be added later to this MR
> StaticAbilityAssignNoCombatDamage: Static and first batch

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/shellfish_scholar.txt
- forge-gui/res/cardsfolder/upcoming/tasteful_offering.txt
- forge-gui/res/cardsfolder/upcoming/tempest_trapper.txt
- forge-gui/res/cardsfolder/upcoming/thought_rattle.txt
- forge-gui/res/cardsfolder/upcoming/three_tree_battalion.txt
- forge-gui/res/cardsfolder/upcoming/vigorous_farming.txt
Tested card scripts for these, [as revealed elsewhere](https://imgur.com/a/yblb-cards-AcWuoKt):
- [Shellfish Scholar](https://i.imgur.com/RRwX45r.png)
- [Tasteful Offering](https://i.imgur.com/bOUBRQA.png)
- [Tempest Trapper](https://i.imgur.com/QZi0BPo.png)
- [Three Tree Battalion](https://i.imgur.com/2wzqE6T.png)
- [Thought Rattle](https://i.imgur.com/R7p8a1G.png)
- [Vigorous Farming](https://i.imgur.com/i2tLsaE.png), with the necessary support added to `CardProperty.java`.
~WIP card script for:~
- ~[Vigorous Farming](https://i.imgur.com/i2tLsaE.png)~
• ~While the script doesn't work as it is, I took the pattern from `TopGraveyardCreature` as used in, for instance, [Shallow Grave](https://scryfall.com/card/mir/141/shallow-grave), even if I feel both could be generalized so the …
> YBLB: Shellfish Scholar, Tasteful Offering, Tempest Trapper, Thought Rattle, Three Tree Battalion, Vigorous Farming

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-gui/res/puzzle/PS_BLB3.pzl
GameState update isn't strictly necessary for this puzzle since it defaults to the class level of 1, but I thought it would be a good addition anyway.
> Add puzzle PS_BLB3, add support for class level to GameState.

- forge-gui/res/cardsfolder/c/call_forth_the_tempest.txt
- forge-gui/res/cardsfolder/d/dimir_strandcatcher.txt
- forge-gui/res/cardsfolder/d/dream_thief.txt
- forge-gui/res/cardsfolder/h/hotheaded_giant.txt
- forge-gui/res/cardsfolder/l/lock_and_load.txt
- forge-gui/res/cardsfolder/s/show_of_confidence.txt
- forge-gui/res/cardsfolder/s/soul_reap.txt
- forge-gui/res/cardsfolder/s/storm_entity.txt
- forge-gui/res/cardsfolder/t/talaras_battalion.txt
- forge-gui/res/cardsfolder/t/thrasta_tempests_roar.txt
- forge-gui/res/cardsfolder/t/thunder_salvo.txt
Tested fixes for:
- `Count$ThisTurnCast` where the spell that's being cast or resolving is excluded from the count. 
The above has been variably implemented by adding `Other` or `Minus.1` to the `SVar` syntax. 
The issue with the first option, in the context of a resolution check, is that a previous casting of the same card isn't counted even though these aren't the same object. The issue with the second option, for the same scenario, is that it doesn't account for corner cases involving abilities of objects that weren't cast that look back in time for information about what was cast during a turn.
In the context of checks during the casting of a spell (eg.: [Talara's Batallion](https://scryfall.com/card/ddu/24/talaras-battalion)), `Other` and the like are unnecessary since a spell is …
> Fixes gleaned from notes: pass #1

- forge-gui/res/cardsfolder/upcoming/altanak_the_thrice_called.txt
- forge-gui/res/cardsfolder/upcoming/blazemire_verge.txt
- forge-gui/res/cardsfolder/upcoming/drag_to_the_roots.txt
- forge-gui/res/cardsfolder/upcoming/floodfarm_verge.txt
- forge-gui/res/cardsfolder/upcoming/ghost_vacuum.txt
- forge-gui/res/cardsfolder/upcoming/gloomlake_verge.txt
- forge-gui/res/cardsfolder/upcoming/grievous_wound.txt
- forge-gui/res/cardsfolder/upcoming/hedge_shredder.txt
- forge-gui/res/cardsfolder/upcoming/hushwood_verge.txt
- forge-gui/res/cardsfolder/upcoming/leyline_of_resonance.txt
- forge-gui/res/cardsfolder/upcoming/leyline_of_transformation.txt
- forge-gui/res/cardsfolder/upcoming/meathook_massacre_ii.txt
- forge-gui/res/cardsfolder/upcoming/overlord_of_the_floodpits.txt
- forge-gui/res/cardsfolder/upcoming/patchwork_beastie.txt
- forge-gui/res/cardsfolder/upcoming/say_its_name.txt
- forge-gui/res/cardsfolder/upcoming/shardmages_rescue.txt
- forge-gui/res/cardsfolder/upcoming/the_swarmweaver.txt
- forge-gui/res/cardsfolder/upcoming/thornspire_verge.txt
- forge-gui/res/cardsfolder/upcoming/valgavoths_faithful.txt
- forge-gui/res/tokenscripts/bg_1_1_insect_flying.txt
Ghost Vacuum has a weird bug: if AI uses the second ability, I get a window where I can order how the cards should enter the battlefield.
> 19 DSK cards

- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-gui/res/cardsfolder/u/ulasht_the_hate_seed.txt
E. g. playing a land with "enters tapped" from _Wish_.
> Fix intrinsic ETB replacement not working if card enters from sideboard

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/a/archon_of_coronation.txt
use LifeReduced CantHappen instead of Keyword
Also fixes FatefulHour flag on trigger/replacement
> Player: use LifeReduced CantHappen for Archon of Coronation

- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
@kevlahnota
reverting with `toString` is much better, otherwise it can't recognize situations such as:
> If two or more players each have resolved Crafty Cutpurse’s triggered ability and a token would be created, the token’s would-be controller chooses one of the applicable Crafty Cutpurse effects to apply. Then the new would-be controller of the token repeats this process among the remaining Crafty Cutpurse effects, and so on, until there are no more possible such effects to apply. Each effect can be applied to the token only once this way.
> Fix RE choice for different sources

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/a/agatha_of_the_vile_cauldron.txt
- forge-gui/res/cardsfolder/c/combustible_gearhulk.txt
- forge-gui/res/cardsfolder/d/doors_of_durin.txt
- forge-gui/res/cardsfolder/g/grist_voracious_larva_grist_the_plague_swarm.txt
- forge-gui/res/cardsfolder/i/isolated_watchtower.txt
- forge-gui/res/cardsfolder/p/palantir_of_orthanc.txt
- forge-gui/res/cardsfolder/u/urza_assembles_the_titans.txt
- Minor copyedits
◦ [Agatha of the Vile Cauldron](https://scryfall.com/card/woe/199/agatha-of-the-vile-cauldron)
◦ [Grist, Voracious Larva // Grist, the Plague Swarm](https://scryfall.com/card/mh3/251/grist-voracious-larva-grist-the-plague-swarm)
- Standardizing `GenericChoice` options for [Combustible Gearhulk](https://scryfall.com/card/dsc/163/combustible-gearhulk) and [Palantír of Orthanc](https://scryfall.com/card/ltr/247/palant%C3%ADr-of-orthanc)
- Fixing mid-effect "you may reveal the top card of your library" step not actually being optional, along with some cleanup
◦ [Doors of Durin](https://scryfall.com/card/ltr/199/doors-of-durin)
◦ [Isolated Watchtower](https://scryfall.com/card/c18/59/isolated-watchtower)
◦ [Urza Assembles the …
> Fixes gleaned from notes: pass #3

- forge-gui/res/cardsfolder/upcoming/disturbing_mirth.txt
- forge-gui/res/cardsfolder/upcoming/trial_of_agony.txt
Fixed Trial of Agony which wasn't dealing the damage, and Disturbing Mirth which was only allowing you to sacrifice another enchantment (not a creature).
> Fixed 2 DSK cards

- forge-game/src/main/java/forge/game/card/Card.java
Copies the cleanup logic for `becameTargetThisTurn`
FLUP to #6178
> Fix valiant cards only triggering once per game rather than once per turn

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/adventure/common/custom_cards/farmers_tools.txt
- forge-gui/res/cardsfolder/a/alliance_of_arms.txt
- forge-gui/res/cardsfolder/c/collective_voyage.txt
- forge-gui/res/cardsfolder/d/disciple_of_caelus_nin.txt
- forge-gui/res/cardsfolder/d/druid_of_purification.txt
- forge-gui/res/cardsfolder/e/eureka.txt
- forge-gui/res/cardsfolder/f/fortunate_few.txt
- forge-gui/res/cardsfolder/h/hypergenesis.txt
- forge-gui/res/cardsfolder/l/liege_of_the_hollows.txt
- forge-gui/res/cardsfolder/m/mana_charged_dragon.txt
- forge-gui/res/cardsfolder/m/manifold_insights.txt
- forge-gui/res/cardsfolder/m/minds_aglow.txt
- forge-gui/res/cardsfolder/m/morphic_tide.txt
- forge-gui/res/cardsfolder/p/plague_of_vermin.txt
- forge-gui/res/cardsfolder/p/protection_racket.txt
- forge-gui/res/cardsfolder/r/reality_shaping.txt
- forge-gui/res/cardsfolder/s/shared_trauma.txt
- forge-gui/res/cardsfolder/t/the_horus_heresy.txt
- forge-gui/res/cardsfolder/t/thieves_auction.txt
- forge-gui/res/cardsfolder/upcoming/sadistic_shell_game.txt
* Added `InTurnOrder` parameter check for case when getting opponents in turn order to [AbilityUtils.java](forge-game/src/main/java/forge/game/ability/AbilityUtils.java)
* Added `getOpponentsInTurnOrder()` for same case to [Player.java](forge-game/src/main/java/forge/game/player/Player.java)
Note: Not many cards require forced turn order of opponents. Honestly, I could only find three. Turn order breaks when AI activates the ability due to normally just getting the opponents of the player. With AI the human is always at the top of the players list from [Game.java](forge-game/src/main/java/forge/game/Game.java)'s `getPlayers()` method. I have not tested this in net play at all so I am not sure how players are ordered in Game.java in an online game. ~~If there was an issue before this …
> InTurnOrder parameter check for specific cards that force turn order of opponents

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/SpellAbilityAi.java
- forge-ai/src/main/java/forge/ai/SpellApiToAi.java
- forge-core/src/main/java/forge/card/CardStateName.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/ability/ApiType.java
- forge-game/src/main/java/forge/game/ability/effects/CloneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/UnlockDoorEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/PlayerController.java
- forge-game/src/main/java/forge/game/trigger/TriggerType.java
- forge-game/src/main/java/forge/game/trigger/TriggerUnlockDoor.java
- forge-game/src/main/java/forge/trackable/TrackableObject.java
- forge-gui-desktop/src/main/java/forge/gui/CardDetailPanel.java
- forge-gui-desktop/src/main/java/forge/toolbox/imaging/FCardImageRenderer.java
- forge-gui-desktop/src/main/java/forge/view/arcane/CardPanel.java
- forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
- forge-gui-mobile/src/forge/card/CardImageRenderer.java
- forge-gui-mobile/src/forge/card/CardRenderer.java
- forge-gui/res/cardsfolder/upcoming/dollmakers_shop_porcelain_gallery.txt
- forge-gui/res/cardsfolder/upcoming/ghostly_keybearer.txt
- forge-gui/res/cardsfolder/upcoming/glassworks_shattered_yard.txt
- forge-gui/res/tokenscripts/w_1_1_a_toy.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
> Room: First Spell Part

- forge-core/src/main/java/forge/card/CardType.java
- forge-core/src/main/java/forge/card/CardTypeView.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardPredicates.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/demonic_covenant.txt
- Added a method to CardTypeView that supports getting all types of a card (super, sub and core).
- Added a method to CardType that checks if a another card shares all types with the card.
- Added a parameter to CardProperty for "sharesAllCardTypesWithOther".
- Added a parameter to GameAction.sacrifice() for "ShowSacrificedCards".
- Without showing that Demonic Covenant was sacrificed due to the milling the end of turn seems extremely abrupt. In a multiple player game it gets confusing quickly when an Enchantment just disappears without notification of some sort. I did not notice any sacrifices going to the Game Log and felt this was an pretty good solution.
> Add Demonic Covenant and supporting changes

- forge-gui/res/cardsfolder/upcoming/defiled_crypt_cadaver_lab.txt
- forge-gui/res/cardsfolder/upcoming/fear_of_infinity.txt
- forge-gui/res/cardsfolder/upcoming/oblivious_bookworm.txt
Fear of Infinity now triggers only in graveyard
Cadaver Lab changed valid target from battlefield to graveyard 
Oblivious Bookworm made draw optional, and turning a permanent faceup triggers no discard now
> Updated 3 DSK Cards

- forge-game/src/main/java/forge/game/card/CardCopyService.java
- forge-gui/res/cardsfolder/upcoming/entity_tracker.txt
The problem was it tries to fetch the right state while still doing the left.
I really don't think we need that View update during copying anyway, so that's my solution.
Closes #6275
Closes #6276
> Fix NPE when creating room token

- README.md
Corrected "[enviroment]" to "[environment]" in [README.md].
This pull request addresses a minor typo found in repository. The typo has been corrected to improve clarity and maintain the quality of the documentation.
This change is purely cosmetic and does not affect functionality.
> Docs: Typo fix

- forge-ai/src/main/java/forge/ai/AiCostDecision.java
- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ability/CountersRemoveAi.java
- forge-game/src/main/java/forge/game/GameEntity.java
- forge-game/src/main/java/forge/game/ability/effects/CountersMoveEffect.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutOrRemoveEffect.java
- forge-game/src/main/java/forge/game/ability/effects/CountersRemoveAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/CountersRemoveEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/cost/CostRemoveAnyCounter.java
- forge-game/src/main/java/forge/game/cost/CostUntap.java
- forge-game/src/main/java/forge/game/cost/CostUntapType.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/upcoming/fear_of_sleep_paralysis.txt
- forge-gui/src/main/java/forge/player/HumanCostDecision.java
- the logic for this was tricky, _Dramatist's Puppet_ should now correctly force you to put (or remove) another Stun counter on the target if the other choice is impossible
- Untap costs checks extended
- some AI parts updated to avoid cheating
- Also fixed _Afiya Grove_ trigger moving counters if it gets phased out in response
> Fear of Sleep Paralysis and support

- forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
Closes #5354.
Looks like the list just needed to be filtered before selecting the other 7 participants, not after. Could do it a bit nicer with the Stream utils though, once that's merged.
> Fix IndexOutOfBoundsException in generateParticipants

- forge-core/src/main/java/forge/card/mana/ManaCost.java
- forge-core/src/main/java/forge/card/mana/ManaCostParser.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/spellability/Spell.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
> If a card with no mana cost gains flashback, it has no flashback cost. It can't be cast this way.
Related to #5289
> Grant abilities based on mana cost even if a card doesn't have one not just for Flashback

- forge-ai/src/main/java/forge/ai/AiCostDecision.java
- forge-game/src/main/java/forge/game/GameEntityCounterTable.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/cost/CostUnattach.java
- forge-gui/res/cardsfolder/c/cyclopean_tomb.txt
- forge-gui/res/cardsfolder/upcoming/black_panther_wakandan_king.txt
- forge-gui/res/cardsfolder/upcoming/captain_america_first_avenger.txt
- forge-gui/res/cardsfolder/upcoming/iron_man_titan_of_innovation.txt
- forge-gui/res/cardsfolder/upcoming/storm_force_of_nature.txt
- forge-gui/res/cardsfolder/upcoming/wolverine_best_there_is.txt
- forge-gui/res/lists/TypeLists.txt
- forge-gui/src/main/java/forge/player/HumanCostDecision.java
As seen on [Secret Lair | Marvel Superdrop](https://magic.wizards.com/en/news/announcements/secret-lair-marvel-superdrop).
Card scripts tested and fully working for:
- Iron Man, Titan of Innovation
- Wolverine, Best There Is
- Storm, Force of Nature
Card scripts tested to a point, and in need of support, for:
- Black Panther, Wakandan King
→ Contrasting [CountersMoveEffect.java](https://github.com/Card-Forge/forge/blob/master/forge-game/src/main/java/forge/game/ability/effects/CountersMoveEffect.java) with [CountersRemoveEffect.java](https://github.com/Card-Forge/forge/blob/master/forge-game/src/main/java/forge/game/ability/effects/CountersRemoveEffect.java) the former doesn't have a `RememberAmount$` (or `RememberRemoved$`) parameter yet so the gaining life and drawing a card part isn't …
> SLD: Marvel x MTG Superdrop

- forge-gui/res/formats/Archived/Arena Standard/2024-10-22.txt
Source: https://magic.wizards.com/en/news/announcements/mtg-arena-banned-and-restricted-announcement-october-22-2024
Didn't include the suspension in Alchemy because it's not a proper "ban" and is pending a rebalance.
> Ban Leyline of Resonance in Arena Standard archive

- forge-installer/libs/install.xml
- forge-installer/pom.xml
Add support for .command files on macOS
Previously, macOS users would need to manually set executable permissions on .command files after using forge-installer*.jar . This PR should make .command files properly marked as executable during installation, matching the behavior of .sh files on Unix/Linux systems.
Changes:
- Updated forge-installer's install.xml to handle .command files in the Script pack section with executable permissions (chmod 775)
- Modified pom.xml copy task to ensure .command files are included in the target directory alongside their .sh counterparts
- Added .command files to the executable fileset in IzPack configuration
This allows macOS users to double-click .command files to run Forge, Forge Adventure, and the Adventure Editor immediately after installation without …
> update: add executable permissions for .command files during installation

- forge-game/src/main/java/forge/game/zone/MagicStack.java
>  An ability that triggers when another ability resolves, such as Tom Bombadil's triggered ability, triggers when all of its instructions (as modified by applicable replacement effects) have been followed and it has been removed from the stack. For example, if Tom Bombadil is returned to the battlefield by the final chapter ability of Elspeth Conquers Death, it will be on the battlefield in time to see that final chapter ability finish resolving and get removed from the stack, and thus Tom Bombadil's last ability will trigger.
> Fix AbilityResolves timing

- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-game/src/main/java/forge/game/trigger/TriggerExiled.java
- forge-gui/res/cardsfolder/a/aminatou_veil_piercer.txt
- forge-gui/res/cardsfolder/f/falkenrath_gorger.txt
This fixes the Problem with Miracle and Madness not using the right value for Spells to cast.
I'm not 100% happy with PlayReduceCost yet, because i think this should reduce the cost BEFORE you choose values for X or how 2-hybrid costs are chosen.
> Miracle&Madness: use ManaCost instead of CardManaCost

- forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardCopyService.java
Closes #6579 
@Jetz72 can you do a Benchmark to test if it doesn't slowdown?
maybe CardState should cache getTypeWithChanges?
> Card: copy getChangedCardTypes

- forge-gui-mobile-dev/src/forge/app/GameLauncher.java
Helps with corner cases when fullscreen fails on Linux (e.g. on multiple monitor setups). Not sure why/how this works, maybe a better solution would be preferable, but I'm not an expert on what it might/should be :/
> Only set Resizable to false on non-fullscreen setups in mobile Forge

- forge-game/src/main/java/forge/game/ability/effects/ClassLevelUpEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RunChaosEffect.java
- forge-game/src/main/java/forge/game/ability/effects/SeekEffect.java
- forge-game/src/main/java/forge/game/ability/effects/SetInMotionEffect.java
- forge-game/src/main/java/forge/game/ability/effects/UnlockDoorEffect.java
- forge-game/src/main/java/forge/game/ability/effects/VentureEffect.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/a/anointed_peacekeeper.txt
- forge-gui/res/cardsfolder/c/carrionette.txt
- forge-gui/res/cardsfolder/d/dream_chisel.txt
- forge-gui/res/cardsfolder/i/iron_mastiff.txt
- forge-gui/res/cardsfolder/o/obscuring_aether.txt
- forge-gui/res/cardsfolder/s/suppression_field.txt
- forge-gui/res/cardsfolder/z/zirda_the_dawnwaker.txt
Probably doesn't make sense if the trigger would still fire either.
Closes #6634
> Fix cheating class level 3 by copying level 2 activation

- forge-gui/res/editions/DCI Promos.txt
- forge-gui/res/editions/Innistrad Remastered.txt
- forge-gui/res/editions/Media Inserts.txt
- forge-gui/res/editions/Resale Promos.txt
See image below for Scryfall changes:
- Instead of deleting PRES (which would cause problems with quest mode etc,) I have updated the edition and audited the images on the ftp.
- PMEI has been renumbered and audited the images on the ftp.
- JP1 did not already exist in Forge and has no unique artwork so did not include.
- DCI set code updated from PDCI.
> Edition updates: DCI, INR, PMEI, PRES

- forge-gui/res/cardsfolder/b/bloodbraid_challenger.txt
P/T doesn't match printed card or Oracle. Corrected to 4/3
> Fix for Bloodbraid Challenger P/T

- forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
Re: #6694
Ok I see what happened now. I edited this function in PR #6359 to fix issue #5354, but in doing so I introduced a usage of `Iterables.filter`, which I was simultaneously working to phase out on the de-guava-ing branch. I guess I tunnel-visioned on rewriting it using the Stream API rather than doing the sensible thing and swapping in `IterableUtil`. Then it broke because I tried to get clever with the generator function in `.toArray`.
This should fix the original crash and get us back where we were.
> Reapply fix IndexOutOfBoundsException in generateParticipants

- forge-ai/src/main/java/forge/ai/ability/CopySpellAbilityAi.java
- forge-gui/res/cardsfolder/c/chain_lightning.txt
The AI can most likely be improved here by deciding when it's more viable to play it, but so far, this will allow the AI to play the card (will try to respond to every opponent's activation if able).
Fixes #6704
> Fix the AI never playing Chain Lightning

- forge-gui/res/cardsfolder/s/shrine_keeper.txt
Random starting card pile gave me this, and I noticed a discrepancy between the cost shown in the art and the devotion to white it should have been providing when casting Daybreak Chimera.
Source: [Shrine Keeper](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=548127)
> Corrects cost of Shrine Keeper

- forge-gui/res/adventure/common/custom_cards/jace_boss_effect.txt
- forge-gui/res/adventure/common/custom_cards/jaces_signature_hoodie.txt
I'll rework this boss more profoundly later, this is only a hotfix.
> [[Adventure]] Jace quickfix

- forge-gui-android/pom.xml
- forge-gui-desktop/pom.xml
POM changes to skip "GenerateGitChangelog" in Android test and debug build profiles.
Update `se.bjurr.gitchangelog` to v2.2.0 (require Java 17)
> GenerateGitChangelog goal skip. Update se.bjurr.gitchangelog to v2.2.0.

- forge-gui/res/adventure/Shandalar/world/quests.json
Some quests would notify the player of Reputation Rewards that were not actually awarded. Likewise some dialogue choices or upon declining some quests would notify the player of a loss of reputation that wasn't actually deducted. And in one case, the listed reputation change was different than the actual change. This change should ensure all displayed reputation rewards and penalties are applied.
> Adventure Mode Quest Reputation Penalties/Rewards Fix

- forge-gui-mobile/src/forge/screens/match/views/VPlayerPanel.java
Had a backwards if-statement which put the hand, library, graveyard, and exile on the wrong side of the screen, and caused exile to get cut off the bottom.
> Fix Alternative Zone Layout on mobile

- .gitignore
- forge-gui-desktop/pom.xml
- forge-gui-desktop/src/main/config/forge.cmd
- forge-gui-desktop/src/main/config/forge.command
- forge-gui-desktop/src/main/config/forge.sh
fixes the --add-opens problem with the run-scripts using the Manifest.mf
> remove add-opens from mandatory.java.args, use MANIFEST.mf

- forge-gui-android/proguard.cfg
- forge-gui/pom.xml
- forge-gui/src/main/java/forge/gamemodes/net/server/FServerManager.java
```
Update forthline cling dependency to the more supported jupnp, removes http source.
FServerManager.java file formatted as a teduly
```
I believe this complies but Android builds fail to complete. The proguard step ends in error which fails the build
> Replace Cling with jupnp

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/simulation/GameStateEvaluator.java
- forge-game/src/main/java/forge/game/card/Card.java
Improved AI's handling of playing tapped lands. 
AI now considers what colors it has available and if an additional untapped land would help them cast a spell this turn before choosing to play an untapped land over a tapped land. When picking the land to play, it also takes into account the colors it can tap for, the amount of mana it can tap for, and the number of basic land types it has.
> Improved AI tapland playing

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityDevotion.java
- forge-gui/res/cardsfolder/a/altar_of_the_pantheon.txt
> 700.5a A player’s devotion to each color and combination of colors, taking into account any effects that modify devotion, is calculated after considering any copy, control, or text-changing effects but before any other effects that modify the characteristics of permanents. This is an exception to 613.10. See also rule 613, “Interaction of Continuous Effects.”
> Move Altar of the Pantheon to its own static

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/replacement/ReplaceCascade.java
- forge-game/src/main/java/forge/game/replacement/ReplacementType.java
- forge-gui/res/cardsfolder/a/averna_the_chaos_bloom.txt
> 702.85b If an effect allows a player to take an action with one or more of the exiled cards “as you cascade,” the player may take that action after they have finished exiling cards due to the cascade ability. This action is taken before choosing whether to cast the last exiled card or, if no appropriate card was exiled, before putting the exiled cards on the bottom of their library in a random order.
In my opinion, putting a land into play is "an action", so it should happen in sequence?
> Averna: use ReplaceCascade Effect

- forge-gui/res/cardsfolder/r/radiant_smite.txt
Radiant Smite was coded as costing {W}, when it should cost {1}{W}
> Fixing Radiant Smite's cost

- forge-gui/res/cardsfolder/t/the_battle_of_dragon_brothers_fate_reforged.txt
Card script adapted and tested for:
- [The Battle of Dragon Brothers // Fate Reforged](https://scryfall.com/card/da1/RC07b/the-battle-of-dragon-brothers-fate-reforged)
◦ Since the standard procedure is that an object moving between zones forgets what choices were made for it before moving zones, I opted to have the choices stored by noting them for "a card named ~" and only the last noted choice being considered, following existing cards like [Paliano Vanguard](https://scryfall.com/card/cn2/20/paliano-vanguard) and [Psychic Paper](https://scryfall.com/card/who/181/psychic-paper).
> DA1: The Battle of Dragon Brothers // Fate Reforged

- forge-gui/res/cardsfolder/p/protean_war_engine.txt
A few fixes:
- Protean War Engine was crashing the game inconsistently on resolution due to an extraneous space in the `Spellbook$` list. Removed it, managed to exile and clone the affected card to satisfactory results.
- Took the liberty of shortening the referential chain for the `Clone` effect's `Defined$` as I believe is preferred: `Remembered` to `ExiledWith`. An extraneous `Cost$` parameter was also removed.
- The cloning effect wasn't granting the Vehicle type to the cloned card. This is now working as expected.
- "Crew 3" was missing from the `Oracle:` line.
> Protean War Engine fix

- forge-gui/res/cardsfolder/h/harried_dronesmith.txt
- forge-gui/res/cardsfolder/k/kheru_lich_lord.txt
- forge-gui/res/cardsfolder/p/puppeteer_clique.txt
Working on [Come Back Wrong](https://scryfall.com/card/dsk/86/come-back-wrong), I noticed the sacrifice trigger was written as "sacrifice it at the beginning of **your** next end step" which would allow the returned creature to survive for two turns if the sorcery was flashed in during an opponent's turn via [Vedalken Orrery](https://scryfall.com/card/2x2/317/vedalken-orrery). 
This had me look it up to find a few effects needed to have `Your` prefixed to the sacrifice/exile trigger's `AtEOT$` argument. Took a while to get around to translating these observations into edits: this is a functional change for Puppeteer Clique and Kheru Lich Lord, but admittedly perfunctory for Harried Dronesmith. In any case these were tested to satisfaction, working as expected.
> Puppeteer Clique (and similar effects) fix

- forge-game/src/main/java/forge/game/GameAction.java
- forge-gui/res/cardsfolder/s/sanctifier_en_vec.txt
>  Sanctifier En-Vec's last ability cares only what the color of the card would be in the zone it's moving from, not what it would be in the graveyard. For example, if a Clone is a copy of a red creature on the battlefield and then dies, the Clone will be exiled. Conversely, if you cast Order, the white half of the split card Order//Chaos, it will not be exiled as it resolves because it is not red before it goes to the graveyard. 
Because reset is done below anyway I removed the redundant code.
> Fix split card reset before LKI creation

- forge-gui/res/adventure/common/config.json
- forge-gui/res/adventure/common/decks/standard/eldrazilarge.dck
- forge-gui/res/adventure/common/world/enemies.json
By adding MB2 to the restricted list all the non-convention cards become banned as well. This way fixes that. 
The restricted list also contained non existent sets which I have removed.
> [Adventure] further cleanup of the restricted cards

- forge-gui/res/cardsfolder/b/baneblade_scoundrel_baneclaw_marauder.txt
- forge-gui/res/cardsfolder/b/blizzard_specter.txt
- forge-gui/res/cardsfolder/f/froghemoth.txt
- forge-gui/res/cardsfolder/g/grenzo_havoc_raiser.txt
- forge-gui/res/cardsfolder/i/ink_eyes_servant_of_oni.txt
- forge-gui/res/cardsfolder/p/plague_wight.txt
- forge-gui/res/cardsfolder/r/rahilda_wanted_cutthroat_rahilda_feral_outlaw.txt
- forge-gui/res/cardsfolder/s/scion_of_darkness.txt
- forge-gui/res/cardsfolder/s/silent_blade_oni.txt
- forge-gui/res/cardsfolder/s/skullsnatcher.txt
- forge-gui/res/cardsfolder/s/sphinx_ambassador.txt
- forge-gui/res/cardsfolder/z/zombie_cannibal.txt
The first case involves triggers for combat damage dealt to players, where the expected behavior is that combat damage redirected to a non-defending player should also trigger the triggered ability. Addressed with reference to [Aberrant](https://scryfall.com/card/40k/86/aberrant), [Zareth San, the Trickster](https://scryfall.com/card/znr/242/zareth-san-the-trickster) and similar scripts.
The second case has to do with explicitly referencing the defending player in the context of who controls a blocking creature.  Addressed with reference to [Battle-Scarred Goblin](https://scryfall.com/card/ltr/115/battle-scarred-goblin) and similar scripts.
All these edits were tested to satisfaction, especially where it concerns the interaction between combat damage redirection and combat damage …
> Fixing mistaken references to defending player in triggered abilities

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/StaticEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/upcoming/pit_automaton.txt
- forge-gui/res/cardsfolder/upcoming/rangers_refueler.txt
> Reduce some View updates

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/player/Player.java
> Some cards get power, toughness, and/or abilities once you have the city’s blessing. If another card has an ability that triggers when creatures with certain characteristics enter the battlefield (such as Mentor of the Meek or Elemental Bond do), use the entering permanent’s characteristics after you have the city’s blessing to determine whether those abilities trigger. This is true even if the entering permanent is your tenth permanent.
E.g.  _Godtracker of Jund_ should trigger when _Dusk Charger_ ETB
> Fix Blessing applying too late for triggers

- forge-game/src/main/java/forge/game/event/GameEventSpeedUp.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/upcoming/aether_syphon.txt
- forge-gui/res/cardsfolder/upcoming/amonkhet_raceway.txt
- forge-gui/res/cardsfolder/upcoming/avishkar_raceway.txt
- forge-gui/res/cardsfolder/upcoming/burnout_bashtronaut.txt
- forge-gui/res/cardsfolder/upcoming/embalmed_ascendant.txt
- forge-gui/res/cardsfolder/upcoming/endrider_catalyzer.txt
- forge-gui/res/cardsfolder/upcoming/endrider_spikespitter.txt
- forge-gui/res/cardsfolder/upcoming/far_fortune_end_boss.txt
- forge-gui/res/cardsfolder/upcoming/gas_guzzler.txt
- forge-gui/res/cardsfolder/upcoming/gastal_raider.txt
- forge-gui/res/cardsfolder/upcoming/gastal_thrillseeker.txt
- forge-gui/res/cardsfolder/upcoming/glitch_ghost_surveyor.txt
- forge-gui/res/cardsfolder/upcoming/goblin_surveyor.txt
- forge-gui/res/cardsfolder/upcoming/hazoret_godseeker.txt
- forge-gui/res/cardsfolder/upcoming/hour_of_victory.txt
- forge-gui/res/cardsfolder/upcoming/howlsquad_heavy.txt
- forge-gui/res/cardsfolder/upcoming/kickoff_celebrations.txt
- forge-gui/res/cardsfolder/upcoming/leonin_surveyor.txt
- forge-gui/res/cardsfolder/upcoming/lightwheel_enhancements.txt
- forge-gui/res/cardsfolder/upcoming/loxodon_surveyor.txt
- forge-gui/res/cardsfolder/upcoming/mendicant_core_guidelight.txt
- forge-gui/res/cardsfolder/upcoming/muraganda_raceway.txt
- forge-gui/res/cardsfolder/upcoming/mutant_surveyor.txt
- forge-gui/res/cardsfolder/upcoming/nesting_bot.txt
- forge-gui/res/cardsfolder/upcoming/pride_of_the_road.txt
- forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
closes #6942 (INCLUDING tooltip problem referred to later in that issue)
> refactor Max Speed round 1

- forge-gui/res/cardsfolder/a/angelic_observer.txt
- forge-gui/res/cardsfolder/a/argivian_phalanx.txt
- forge-gui/res/cardsfolder/b/brine_giant.txt
- forge-gui/res/cardsfolder/e/emry_lurker_of_the_loch.txt
- forge-gui/res/cardsfolder/g/gate_colossus.txt
- forge-gui/res/cardsfolder/g/gearseeker_serpent.txt
- forge-gui/res/cardsfolder/h/hellspur_brute.txt
- forge-gui/res/cardsfolder/i/icebreaker_kraken.txt
- forge-gui/res/cardsfolder/m/millicent_restless_revenant.txt
- forge-gui/res/cardsfolder/n/nahiri_forged_in_fury.txt
- forge-gui/res/cardsfolder/o/oxidda_finisher.txt
- forge-gui/res/cardsfolder/p/polliwallop.txt
- forge-gui/res/cardsfolder/r/reality_heist.txt
- forge-gui/res/cardsfolder/r/riders_of_the_mark.txt
- forge-gui/res/cardsfolder/s/saheeli_the_gifted.txt
- forge-gui/res/cardsfolder/s/scales_of_shale.txt
- forge-gui/res/cardsfolder/s/sky_blessed_samurai.txt
- forge-gui/res/cardsfolder/t/the_circle_of_loyalty.txt
As requested by @Hanmac: updated scripts per Gatherer where explicitly written cost reduction effects were suitably keyworded. I also took the opportunity to clean up some of the existing `K:Affinity` lines.
Notable misses by WotC in this update are [Claws Out](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=679083&printed=false) and, arguably, [The Legend of Arena](https://scryfall.com/card/ph18/4/the-legend-of-arena), both of which I skipped as well.
> Oracle update: Affinity

- forge-core/src/main/java/forge/deck/DeckRecognizer.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/KeywordWithCostAndType.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/b/black_hole.txt
- forge-gui/res/cardsfolder/s/soul_swindler.txt
- forge-gui/res/cardsfolder/s/squirrel_squatters.txt
- forge-gui/res/cardsfolder/s/storybook_ride.txt
- forge-gui/src/main/java/forge/util/OperatingSystem.java
Small handful of minor fixes and changes.
* Fix importing when the last few letters of the card name are also a set code. Closes #5941.
* Add text formatting support for "[Keyword]cycling" and "Affinity for [Keyword]". Not really perfect since the reminder text for the former still comes out as "for a [keyword] card" instead of "for a card with [keyword]", but the text formatting there hooks into several other keywords so this seems acceptable for now. Unblocks #7003.
* "Number of attractions you visited this turn" now counts attractions that have left the battlefield or have stopped being Attractions, per rule 608.2i. Doesn't close any issues because it's a niche rule in an edge case scenario involving multiple cards from a pool that are almost never used... but it's been bugging me so …
> Bundle of Assorted Fixes

- forge-core/src/main/java/forge/card/CardFace.java
- forge-gui/res/lists/token-images.txt
Adds image key URLs for speed and max_speed; forgot those would be needed for them to download. Still needs the [speed tracker images](https://scryfall.com/card/tdft/14/start-your-engines!-max-speed) uploaded at some point. 
Also lets functional variants overwrite SVars in the base script by using the same name.
> Image Key URLs for speed and max_speed; Functional variant tweak

- forge-gui/res/cardsfolder/upcoming/cloud_ex_soldier.txt
- forge-gui/res/cardsfolder/upcoming/terra_herald_of_hope.txt
- forge-gui/res/cardsfolder/upcoming/tidus_yunas_guardian.txt
- forge-gui/res/cardsfolder/upcoming/yshtola_nights_blessed.txt
Scripts for the commanders of the relevant Final Fantasy supplement [as revealed on IGN](https://www.ign.com/articles/magic-the-gathering-final-fantasy-commander-deck-reveal-spoilers), all tested to satisfaction:
- Cloud, Ex-SOLDIER
- Terra, Herald of Hope
- Tidus, Yuna's Guardian
- Y'shtola, Night's Blessed
Based on [Brass Knuckles](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/b/brass_knuckles.txt), it felt opportune to add a hidden static ability to Cloud so the AI knows to equip its creatures. I restricted it to nondefenders, though I'm unsure if there should be a power cutoff.
> FIC: 4 cards

- forge-gui/res/cardsfolder/s/sojourners_enforcermite.txt
As far as functionality goes, the script works as expected. The only issue is in-game text display as seen below. 
My suggestion would be to have it as: 
> Affinity for permanents with affinity (This card costs {1} less to cast for each permanent you control with affinity.)
> Affinitycycling {2} ({2}, Discard this card: Search your library for a card with affinity, reveal it, put it into your hand, then shuffle.)
> DA1: Sojourner's Enforcermite

- forge-gui/res/cardsfolder/a/angel_of_suffering.txt
- forge-gui/res/cardsfolder/t/the_mindskinner.txt
- forge-gui/res/cardsfolder/w/weeping_angel.txt
It came to my attention that [The Mindskinner](https://scryfall.com/card/dsk/66/the-mindskinner)'s damage prevention effect wasn't interacting properly with [Questing Beast](https://scryfall.com/card/eld/171/questing-beast)'s "damage can't be prevented" effect: the damage **wasn't** prevented while the milling **didn't** happen. 
Per [CR 615.12](https://mtg.wiki/page/Prevention_effect#Rules) and the last ruling on [Angel of Suffering](https://scryfall.com/card/snc/67/angel-of-suffering), the damage **is** prevented and the milling **should** still happen. To resolve this, an `AlwaysReplace$ True` flag was added to the `R:` lines of three cards that were missing it.
> Fixing The Mindskinner and cards with similar effects

- forge-gui/res/cardsfolder/upcoming/support_skyforge.txt
As revealed recently, both [card](https://www.reddit.com/r/MagicAlchemy/comments/1ix9l9k/adft_support_skyforge/) and [associated spellbook](https://www.reddit.com/r/MagicAlchemy/comments/1iypx88/adft_support_skyforge_spellbook/).
> YDFT: Support Skyforge

- forge-gui-mobile/src/forge/itemmanager/views/ImageView.java
See the thread "Mobile deck editor doesn't show cards unless you scroll" on the discord server
> Delegate rendering of cards in deck viewer to piles all the time

- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityInfectDamage.java
- forge-gui/res/cardsfolder/p/phyrexian_unlife.txt
Changes _Phyrexian Unlife_ into a Static Ability
or should this new class be merged with StaticAbilityWitherDamage? (WitherDamage uses Source, this uses Target)
> StaticAbility InfectDamage for Phyrexian Unlife

- forge-gui/res/adventure/Amonkhet/world/shops.json
- forge-gui/res/adventure/Shandalar/world/quests.json
- forge-gui/res/adventure/Shandalar/world/shops.json
- forge-gui/res/adventure/common/decks/boss/emrakul.dck
- forge-gui/res/adventure/common/decks/boss/lorthos.dck
- forge-gui/res/adventure/common/decks/standard/banditarcher_damage.dck
- forge-gui/res/adventure/common/decks/standard/bluewizard_apprentice_2.dck
- forge-gui/res/adventure/common/decks/standard/not in use/goblins.dck
- forge-gui/res/adventure/common/decks/standard/not in use/golem.dck
- forge-gui/res/adventure/common/world/enemies.json
Generally dealing with clear typos. 
I am left wondering about `\common\world\sprites\map_sprites.json` and the trailing whitespace on a lot of the lines, though.
> Adventure Mode cleanup: February 2025 pass

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseCardNameEffect.java
- forge-gui/res/cardsfolder/a/agent_of_masks.txt
- forge-gui/res/cardsfolder/b/banquet_guests.txt
- forge-gui/res/cardsfolder/b/blood_artist.txt
- forge-gui/res/cardsfolder/e/euru_acorn_scrounger.txt
- forge-gui/res/cardsfolder/f/fallaji_antiquarian.txt
- forge-gui/res/cardsfolder/f/fear_of_change.txt
- forge-gui/res/cardsfolder/q/quicksilver_lapidary.txt
- forge-gui/res/cardsfolder/rebalanced/a-blood_artist.txt
- forge-gui/res/cardsfolder/u/underworld_sentinel.txt
- forge-gui/res/cardsfolder/upcoming/fuel_tank_feaster.txt
- forge-gui/res/cardsfolder/upcoming/great_fang_chroniclers.txt
- forge-gui/res/cardsfolder/upcoming/highway_reaver.txt
- forge-gui/res/cardsfolder/upcoming/kari_zev_crew_of_two.txt
- forge-gui/res/cardsfolder/upcoming/masterpiece_vault.txt
- forge-gui/res/cardsfolder/upcoming/ornate_imitations.txt
- forge-gui/res/cardsfolder/upcoming/quickbeast_amulet.txt
- forge-gui/res/cardsfolder/upcoming/rising_chicane.txt
- forge-gui/res/cardsfolder/upcoming/routeway_moose.txt
- forge-gui/res/cardsfolder/upcoming/sala_deck_boss.txt
- forge-gui/res/cardsfolder/upcoming/terrors_of_the_track.txt
- forge-gui/res/cardsfolder/upcoming/wish_good_luck.txt
As revealed recently:
- [**Terrors of the Track**](https://www.reddit.com/r/MagicArena/comments/1iytumc/ydft_sala_deck_boss_terrors_of_the_track/): tested to satisfaction
- [**Sala, Deck Boss**](https://www.reddit.com/r/MagicArena/comments/1iytumc/ydft_sala_deck_boss_terrors_of_the_track/) and support: tested to satisfaction
- [**Wish Good Luck**](https://x.com/MTG_Arena/status/1895203378969325799): tested to satisfaction
- [**Kari Zev, Crew of Two**](https://www.reddit.com/r/MagicArena/comments/1izvhhr/ydft_kari_zev_crew_of_two/): ~~In a working state except for the conjured Ragavan, Nimble Pilferer entering tapped and attacking. The latter only enters tapped. Needs support from someone more knowlegeable than me: I attempted to address this to no avail.~~ Addressed. Tested to …
> YDFT: 12 cards

- forge-gui/res/cardsfolder/c/chimeric_mass.txt
- forge-gui/res/cardsfolder/s/svogthos_the_restless_tomb.txt
As reported, the static ability granted by these cards' animating effects was applying the power/toughness setting to the whole board instead of just to the card itself. 
As these aren't characteristic-defining abilities (self-granted), I opted to be explicit to what these static abilities applied to, with the cards now working as expected.
> Fixing Chimeric Mass and Svogthos

- forge-gui/res/puzzle/PS_FDN1.pzl
Fix : Puzzle (Possibility Storm - Foundations #01). Opponent library is empty.
> Fix Puzzle Possibility Storm - Foundations #01

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/ability/effects/ControlPlayerEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityManaConvert.java
- forge-gui/res/cardsfolder/n/north_star.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
> Fix North Star

- forge-gui/res/cardsfolder/b/buxton_decorated_host.txt
- forge-gui/res/cardsfolder/c/chittering_illuminator.txt
- forge-gui/res/cardsfolder/d/dazzling_flameweaver.txt
- forge-gui/res/cardsfolder/e/ethrimik_imagined_fiend.txt
- forge-gui/res/cardsfolder/g/golden_sidekick.txt
- forge-gui/res/cardsfolder/i/impetuous_lootmonger.txt
- forge-gui/res/cardsfolder/w/wingbright_thief.txt
Source: https://magic.wizards.com/en/news/mtg-arena/announcements-march-3-2025#rebalances
Alchemy only - no new script needed:
> Alchemy Rebalancing for March 4, 2025

- forge-gui/res/cardsfolder/upcoming/transcendent_dragon.txt
- forge-gui/res/cardsfolder/upcoming/transforming_flourish.txt
- forge-gui/res/cardsfolder/upcoming/voracious_bibliophile.txt
- forge-gui/res/cardsfolder/upcoming/will_of_the_jeskai.txt
- Transcendent Dragon
- Transforming Flourish
- Will of the Jeskai
Needing support:
- Voracious Bibliophile: The trigger works as far as the condition goes. For the resulting draw effect, I got as far as lifting the `SVar:X:TriggerObjectsSpellAbilityTargets$` line from [Arcee, Acrobatic Coupe](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/a/arcee_sharpshooter_arcee_acrobatic_coupe.txt) but the results are as follows on casting a [Donate](https://scryfall.com/card/uds/31/donate) (2 distinct targets) for the variations that seemed relevant:
• `TriggerObjectsSpellAbilityTargets$Amount`: draw 1 card
• `TriggerObjectsSpellAbilityTargets$Valid Any`: no card draw
Either option would be fine to implement: unfortunately my aptitude for Java …
> TDC: 4 cards

- forge-gui-mobile/src/forge/adventure/util/KeyBinding.java
Reverts Card-Forge/forge#7206
First off, thanks for the wasd movement, pretty good. But the issue is, when you rename a deck and you use like W or S, it switches to the OK/Abort buttons.
How to recreate the bug:
Open your deck list
Rename a deck
Type W or S
It will change from the input box to the Ok button. If you tap W/S again, it will type the letter correctly though.
> Revert "WASD movement for Adventure mode"

- forge-gui/res/cardsfolder/b/battleground_geist.txt
- forge-gui/res/cardsfolder/c/captains_hook.txt
- forge-gui/res/cardsfolder/d/dwarfhold_champion.txt
- forge-gui/res/cardsfolder/d/dwindle.txt
- forge-gui/res/cardsfolder/f/full_moons_rise.txt
- forge-gui/res/cardsfolder/g/gallows_warden.txt
- forge-gui/res/cardsfolder/g/gearsmith_prodigy.txt
- forge-gui/res/cardsfolder/g/goldwardens_helm.txt
- forge-gui/res/cardsfolder/g/gryffs_boon.txt
- forge-gui/res/cardsfolder/h/hardy_veteran.txt
- forge-gui/res/cardsfolder/h/hexgold_hoverwings.txt
- forge-gui/res/cardsfolder/m/molting_snakeskin.txt
- forge-gui/res/cardsfolder/o/one_eyed_scarecrow.txt
- forge-gui/res/cardsfolder/rebalanced/a-dwarfhold_champion.txt
- forge-gui/res/cardsfolder/s/sporeback_wolf.txt
- forge-gui/res/tokenscripts/icingdeath_frost_tongue.txt
As a followup to https://github.com/Card-Forge/forge/pull/6878 , this PR removes redundant instances of `AddPower$ 0` and `AddToughness$ 0`.
> AddPower & AddToughness: Removing redundancy

- forge-gui/res/editions/Alchemy Aetherdrift.txt
- forge-gui/res/editions/Alchemy Bloomburrow.txt
- forge-gui/res/editions/Alchemy Duskmourn.txt
- forge-gui/res/editions/Alchemy Innistrad.txt
- forge-gui/res/editions/Alchemy Karlov Manor.txt
- forge-gui/res/editions/Alchemy Thunder Junction.txt
Alchemy Aetherdrift (YDFT),
Alchemy Bloomburrow (YBLB),
Alchemy: Duskmourn (YDSK),
Alchemy: Innistrad (YMID),
Alchemy: Murders at Karlov Manor (YMKM),
Alchemy: Outlaws of Thunder Junction (YOTJ)
> Alchemy sets boosters added

- forge-game/src/main/java/forge/game/ability/effects/EndureEffect.java
> If a permanent is instructed to endure 0, nothing happens. No counters are put on that permanent and no tokens are created.
> Fix creating token with Endure 0

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
- forge-gui/res/adventure/common/world/items.json
This removes quest items from a NG+ run in adventure mode. It might not remove all when a file has multiple NG+'s already, but multiple resets will remove all of the items. I decided to remove the quest item tag from the teleport runes, since they are not added by a quest but can be bought in the store instead. Keeping them seems a good move for NG+.
> Remove Quest items on NG+

- forge-gui/res/adventure/Shandalar/world/quests.json
Bosses, leaders and large enemies are now excluded from the enemies that the tutorial throws at you in the "defeat any enemy" part
> Disable certain enemies for tutorial fight (Adventure)

- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardState.java
This Updates Omen into an ReplacementEffect and moves both of them into Card State depending on the Type
(assuming something could mess with Spell Subtypes)
> Adventure and Omen as ReplacementEffect in CardState

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
Part of #7012 
reduces the use of `addChangedCardKeywords` and uses Layer instead
> Unearth: add gain Haste as StaticLayer

- forge-game/src/main/java/forge/game/ability/effects/DiscardEffect.java
- forge-gui/res/cardsfolder/d/distended_mindbender.txt
- forge-gui/res/cardsfolder/m/monomania.txt
It only looks big because I was able to remove the ugly
`if ((mode.equals("RevealTgtChoose") && firstTarget != null) || !sa.usesTargeting() || p.canBeTargetedBy(sa))`
wrapping everything.
Closes #7380
> Fix Distended Mindbender

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/IHasSVars.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardState.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java
- forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
I removed `getDirectSVars` and did some cleanup
one other thing i would like to remove is in createEffect, the call for `eff.setSVars(sa.getSVars());`
This is the reason why this still exist:
```java
@Override
public Map<String, String> getSVars() {
Map<String, String> res = Maps.newHashMap();
// TODO reverse the order
for (IHasSVars s : getSVarFallback()) {
res.putAll(s.getSVars());
}
res.putAll(sVars);
return res;
}
```
so what if Effect just uses `effectSourceAbility` instead? Or is the problem in case the Svars get cleaned up?
> removed getDirectSVars

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/phase/Untap.java
- forge-gui/res/cardsfolder/a/arbalest_elite.txt
- forge-gui/res/cardsfolder/b/bontus_last_reckoning.txt
- forge-gui/res/cardsfolder/c/cinder_marsh.txt
- forge-gui/res/cardsfolder/c/cloudcrest_lake.txt
- forge-gui/res/cardsfolder/d/deep_spawn.txt
- forge-gui/res/cardsfolder/h/hazorets_undying_fury.txt
- forge-gui/res/cardsfolder/h/homarid_warrior.txt
- forge-gui/res/cardsfolder/k/kefnets_last_word.txt
- forge-gui/res/cardsfolder/l/lantern_lit_graveyard.txt
- forge-gui/res/cardsfolder/m/mogg_hollows.txt
- forge-gui/res/cardsfolder/o/oketras_last_mercy.txt
- forge-gui/res/cardsfolder/o/orcish_farmer.txt
- forge-gui/res/cardsfolder/p/pinecrest_ridge.txt
- forge-gui/res/cardsfolder/r/reveka_wizard_savant.txt
- forge-gui/res/cardsfolder/r/rhonass_last_stand.txt
- forge-gui/res/cardsfolder/r/rootwater_depths.txt
- forge-gui/res/cardsfolder/s/samite_alchemist.txt
- forge-gui/res/cardsfolder/s/spectral_bears.txt
- forge-gui/res/cardsfolder/s/spectral_force.txt
- forge-gui/res/cardsfolder/t/thalakos_lowlands.txt
- forge-gui/res/cardsfolder/t/tranquil_garden.txt
- forge-gui/res/cardsfolder/v/vec_townships.txt
- forge-gui/res/cardsfolder/w/waterveil_cavern.txt
Patches `your next`, so remaining usage of the hidden KW should be reduced to only the types `player's|controller's/controllers' next`, making the final refactor a bit easier later.
> CantUntap Third Step

- forge-gui-mobile/src/forge/screens/match/MatchScreen.java
Usage of MatchController#concede() confirms an user input using WaitCallback, which results in an IllegalStateException due to EDT validations [here](https://github.com/Card-Forge/forge/blob/master/forge-gui/src/main/java/forge/util/WaitCallback.java#L22) and [here](https://github.com/Card-Forge/forge/blob/master/forge-gui/src/main/java/forge/gui/FThreads.java#L22).
```java
EDT > java.lang.IllegalStateException: forge.util.WaitCallback.invokeAndWait may not be accessed from the event dispatch thread.
at forge.gui.FThreads.assertExecutedByEdt(FThreads.java:22)
at forge.util.WaitCallback.invokeAndWait(WaitCallback.java:22)
at forge.GuiMobile.showOptionDialog(GuiMobile.java:174)
at forge.gui.util.SOptionPane.showOptionDialog(SOptionPane.java:67)
at …
```
> Adventure: fix concede shortcut not working due to event dispatch thread

- forge-core/src/main/java/forge/item/PaperCard.java
Fixes crashes in online play, and a potential-but-unconfirmed crash when saving if you recently acquired a no-sell-value card.
> Make PaperCardFlags serializable

- forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
Fixes #7165.
Could've just deleted the line entirely since this flag is almost never used, but supporting it via parameter adds parity with `MakeCardEffect`.
> Disable TokenCard flag on drafted cards by default.

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
> In some very rare situations, Aligned Hedron Network may enter the battlefield as a creature with power 5 or greater. If this happens, Aligned Hedron Network will exile itself along with other creatures with power 5 or greater. Those cards will immediately return to the battlefield. If this causes a loop with Aligned Hedron Network continually exiling and returning itself, the game will be a draw unless a player breaks the loop somehow.
> Fix UntilHostLeavesPlay corner case

- forge-core/src/main/java/forge/card/CardDb.java
- forge-core/src/main/java/forge/card/ICardDatabase.java
- forge-core/src/main/java/forge/deck/CardPool.java
Resolves [this debacle.](https://discord.com/channels/267367946135928833/1363076100502323333/1363076100502323333) 
This was a pretty big oversight during my testing. I had verified that decks retain the correct print when the deck was saved then re-opened, but I didn't realize the loading from file was done for most decks when Forge first starts, causing me to miss that the prints had changed then. Sincerest apologies to those affected.
> Fix cards in decks reverting to first art in set after game is restarted

- forge-gui/res/adventure/Shandalar/world/quests.json
I changed this number to test some stuff but apparently my attempt to change it back before committing was unsucessful earlier. 
Currently the main quest is out of order, this will put things right again.
> [Adventure] Quest order fix

- forge-gui-mobile/src/forge/screens/settings/SettingsPage.java
Fixed bug where android boolean settings were not properly displaying their checked state
> Android Boolean settings fix

- forge-gui/res/cardsfolder/i/imposing_grandeur.txt
- forge-gui/res/cardsfolder/r/ruin_grinder.txt
- forge-gui/res/cardsfolder/s/sail_into_the_west.txt
- forge-gui/res/cardsfolder/w/will_of_the_jeskai.txt
As discussed [here](https://github.com/Card-Forge/forge/pull/7208#discussion_r2005290115), updating existing optional wheel effects formatted as an `UnlessCost$` by following [Ruin Grinder](https://scryfall.com/card/c21/57/ruin-grinder) instead, to comply with relevant rulings. 
- [Imposing Grandeur](https://scryfall.com/card/voc/24/imposing-grandeur)
- [Sail into the West](https://scryfall.com/card/ltc/68/sail-into-the-west)
- [Will of the Jeskai](https://scryfall.com/card/tdc/40/will-of-the-jeskai)
Also updating: 
- Ruin Grinder so the selectable options more closely reflect its dies effect.
- Adding a `StackDescription$` to Imposing Grandeur and Sail into the West so their Stack items read a bit better.
> Cleanup: Optional wheel update

- forge-core/src/main/java/forge/StaticData.java
- forge-core/src/main/java/forge/card/CardDb.java
- forge-core/src/main/java/forge/card/CardEdition.java
- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
Adds support for an amount parameter to the `give card` and `give nosell card` commands, after the card name (e.g. `give card "Lotus Petal" 3`.)
Adds a `give print` command, which adds a card given a set code and collector number instead of a card name. It also supports the amount parameter. e.g. `give print SLD 7010 4` will give you four copies of the Spongebob Secret Lair Counterspell.
Also makes it possible for the `give card` command to fetch cards in the variant DB, (though the deck editor still doesn't yet support them properly).
> Adventure Console "give card" Updates

- forge-gui/res/cardsfolder/r/ravenous_harpy.txt
- forge-gui/res/cardsfolder/r/reaper_of_flight_moonsilver.txt
On a report that Ravenous Harpy was able to sacrifice itself to its own activated ability when its rules text instructs otherwise, it was found the script lacked the required cost restriction. While I was at it, I searched the card scripts and found another instance of this lapse.
> Fixing Ravenous Harpy, Reaper of Flight Moonsilver

- forge-gui/res/cardsfolder/l/loch_larent.txt
- forge-gui/res/cardsfolder/upcoming/dragonblood_twins.txt
- forge-gui/res/cardsfolder/upcoming/hamza_might_of_the_yathan.txt
- forge-gui/res/cardsfolder/upcoming/thunderbond_vanguard.txt
As revealed [here](https://www.reddit.com/r/MagicArena/comments/1k4komr/ytdm_hamza_might_of_the_yathan/) and [here](https://www.reddit.com/r/MagicArena/comments/1k5c28w/ytdm_thunderbond_vanguard_dragonblood_twins/); tested to satisfaction:
- Dragonblood Twins
- Hamza, Might of the Yathan
- Thunderbond Vanguard
Incidental fixes:
- Loch Larent: removerd extraneous `\n` in `Oracle:` line.
> YTDM: 3 cards

- forge-gui-mobile/src/forge/adventure/data/AdventureQuestStage.java
- forge-gui/res/adventure/common/world/items.json
If a user Receives an item specified in a 'Fetch' objective before the objective has started, it was impossible for them to finish the quest. Now, as long as they are in the PointofInterest where the item was found, they can enter their inventory and Use the item instead. This will prevent main quest softlocks.
I tested this on the only 'Fetch' objective in the game so far, stage 2 of The Dig Site.
I acquired the item before beginning the quest. I completed the quests up until that objective, entered the PoI and used enter.
I also deleted an empty line.
This is my first time using Github, IDEs, and contributing! Let me know your comments.
> Adventure - Fix for 'Fetch' objectives

- forge-core/src/main/java/forge/card/CardType.java
- forge-core/src/main/java/forge/card/CardTypeView.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
Not currently used by any official cards but the rules define their behavior to an extent and it was requested to support some custom cards. This doesn't fully support custom types - the engine won't even acknowledge unknown subtypes, much less handle their intrinsic abilities or state based actions. But this does enable various designs that are protected by their controllers.
> Support for non-Siege Battles

- forge-gui-mobile/src/forge/itemmanager/ItemManager.java
- forge-gui-mobile/src/forge/itemmanager/views/ImageView.java
I'm not sure I fully grasp the scope of this issue, but apparently if the mobile deck editor is in ImageView mode, `groupBy` is set to something non-null, `pileBy` is null, and you change your search filters in a way that causes a group that had cards in it to become empty, the group will be emptied of items but it won't clear the piles within that group. They won't be visible, but `getItemAtPoint` can still see them, which can cause it to return an item that was previously filtered out. That item that should no longer exist later gets referred to by its outdated index, then that wrong index gets used to look up a real item that actually is visible in the list. 
End result: you click one card and the menu opens for a different card, or for a null card and you get problems. The recent …
> Fix mobile deck editor selecting wrong cards under certain conditions

- forge-gui/res/cardsfolder/upcoming/quistis_trepe.txt
In the end, she exiles the card no matter who owns it; the original translation was imprecise.
> Quistis Trepe (FIN)

- forge-gui/res/cardsfolder/upcoming/phantom_train.txt
- forge-gui/res/cardsfolder/upcoming/poison_the_waters.txt
- forge-gui/res/cardsfolder/upcoming/suplex.txt
There's something strange with Phantom Train's ability where its P/T display doesn't update properly after getting the counter -- maybe because the counter is gained before animating?
> How to suplex a train

- forge-gui/res/cardsfolder/e/embereth_veteran.txt
- forge-gui/res/cardsfolder/l/living_lectern.txt
It came to my attention that [Living Lectern](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/l/living_lectern.txt)'s activated ability wasn't creating the Role token. Comparing with the working effect on [Betroth the Beast](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/b/besotted_knight_betroth_the_beast.txt), it was noticeable the `TokenOwner$` parameter was missing. Adding it to the relevant line now results in the token being created as expected. Looking over existing scripts, [Embereth Veteran](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/e/embereth_veteran.txt)'s corresponding line was found to also lack that parameter and behaved like the uncorrected Lectern. It's been fixed as well.
> Fixing Living Lectern, Embereth Veteran

- forge-gui/res/cardsfolder/b/blazing_crescendo.txt
- forge-gui/res/cardsfolder/upcoming/haste_magic.txt
- Blazing Crescendo: Missing text in description parameters and its formatting.
> Cleanup: Blazing Crescendo

- forge-core/src/main/java/forge/ImageKeys.java
- forge-core/src/main/java/forge/StaticData.java
- forge-core/src/main/java/forge/card/CardDb.java
- forge-core/src/main/java/forge/card/CardEdition.java
- forge-core/src/main/java/forge/item/PaperToken.java
- forge-core/src/main/java/forge/token/TokenDb.java
- forge-core/src/main/java/forge/util/ImageUtil.java
- forge-gui-desktop/src/main/java/forge/util/SwingImageFetcher.java
- forge-gui-mobile/src/forge/util/LibGDXImageFetcher.java
- forge-gui/src/main/java/forge/gamemodes/quest/QuestUtil.java
- forge-gui/src/main/java/forge/gamemodes/quest/bazaar/QuestPetStats.java
- forge-gui/src/main/java/forge/gui/download/GuiDownloadPicturesHQ.java
- forge-gui/src/main/java/forge/util/ImageFetcher.java
- Adds CollectorNumber to PaperToken
- Updates Token ImageKey to something more parseable, like with PaperCard
- Updates Downloader to use correct CollectorNumber if possible
This Updates the resulting the filename in the folder be be changed:
from `c_a_clue_draw2_mkm.jpg` with idx = 2
to `c_a_clue_draw_mkm_17.jpg` with nr = 17
Or should the filename to be changed to `mkn/17_c_a_clue_draw.jpg` with set based subfolder and Nr first?
> PaperToken: add CollectorNumber and update Downloader

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-gui/res/cardsfolder/f/force_of_rage.txt
- forge-gui/res/cardsfolder/r/rally_the_ancestors.txt
- forge-gui/res/cardsfolder/upcoming/firion_wild_rose_warrior.txt
The delayed trigger set up by [Firion, Wild Rose Warrior](https://scryfall.com/card/fin/137/firion-wild-rose-warrior)'s triggered ability was sacrificing the creature instead of the created token. I opted to implement `AtEOT$ SacrificeUpkeep` to resolve this. The script now works as expected.
As requested, propagated these changes to:
- [Force of Rage](https://scryfall.com/card/mh1/124/force-of-rage): tested to satisfaction
- [Rally the Ancestors](https://scryfall.com/card/frf/22/rally-the-ancestors) along with general support for `AtEOT$` in `ChangeZoneAll` lines, mirroring the existing support `ChangeZone` lines have: tested to satisfaction.
> Fixing Firion

- forge-gui-android/pom.xml
- forge-gui-ios/pom.xml
- forge-gui-mobile-dev/pom.xml
- forge-gui-mobile/pom.xml
Updates Libgdx dependency from 1.13.0 to the point release 1.13.5, which fixes mobile backport crashing on Steam Deck during any match (when trying to visualize cards).
This works on my Linux desktop without any issue as well.
Could use some testing on Android, perhaps, since I don't have a working Android build setup anymore.
> Update Libgdx to 1.13.5 (fixes Steam Deck mobile backport crash)

- forge-gui/src/main/java/forge/util/ImageFetcher.java
Extra Logic to download the `t:hidden` backside from scryfall (sadly only as png?)
> ImageFetcher: add downloadUrl for HiddenCard

- forge-core/src/main/java/forge/token/TokenDb.java
fixes that Endure has TokenImages but no different TokenScript for them
> TokenDb: fix Endure Token Images causing crash on Token Viewer

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-game/src/main/java/forge/game/ability/effects/PermanentCreatureEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PermanentNoncreatureEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardState.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-game/src/main/java/forge/game/spellability/LandAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellPermanent.java
Closes #7677 
Also:
- Fixes Disturb Auras need to target
- Changed the need for `clearFirstSpell`, the Only use for `NonBasicSpell` is Cleave make an extra PR for this
- Make Original CardState load LeftSplit/RightSplit CardStates too
> CardState: Refactor LandAbility/Aura/PermSpell

- forge-gui-desktop/src/main/java/forge/gui/framework/SDisplayUtil.java
When the "Visually Alert on Receipt of Priority" feature is enabled, the `showTab()` call at the beginning of `forge.gui.framework.SDisplayUtil.remind()` steals focus from the primary button whenever anything goes on the stack.
This change, previously suggested by pfps as probably not necessary, is indeed necessary after all to prevent that focus stealing by restoring focus to the previous owner only if the owner was an `FButton`.
fixes https://github.com/Card-Forge/forge/issues/7660
> fix: do not steal keyboard focus when "Visually Alert on Receipt of Priority" is enabled

- forge-gui/res/adventure/common/sprites/enemy/undead/deathknightidle.atlas
small fix to incorrect resource name, when loading a page with an idle deathknight the following exception will be thrown on repeat and the screen will not load:
```
com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: ../forge-gui/res/adventure/common/sprites/enemy/undead/Deathknightidle.png
at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:648)
at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:426)
at com.badlogic.gdx.assets.AssetManager.finishLoadingAsset(AssetManager.java:483)
at forge.assets.Assets$MemoryTrackingAssetManager.finishLoadingAsset(Assets.java:559)
at forge.adventure.util.Config.getAtlas(Config.java:267)
at …
```
> fix incorrect resource name (deathknightidle.png)

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/adventure/scene/DeckSelectScene.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui/res/adventure/common/ui/deck_selector.json
- forge-gui/res/adventure/common/ui/deck_selector_portrait.json
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
When playing Adventure for a while, it's possible to run out of deck slots when trying different builds. Currently the deck count is statically set to 10 due to the underlying structure of the data (array) and storage solution (trying to see if the user has deck of an index stored, for each index up till 10).
This MR replaces the underlying structure (with an ArrayList) and the save load mechanism to allow dynamic deck counts. I've extended the adventure deck editor scene/UI to support adding and deleting decks. The player is always bound to have at least 10 decks (trying to delete below the minimum limit just clears that deck, as was the case before). The save/load checks whether the deck count is saved and if so, loads decks up till the count, otherwise proceeds with the legacy load. …
> Adventure: added support for dynamic deck count

- forge-gui-mobile/src/forge/adventure/util/Controls.java
Altered the currency labels to display new values immediately and improve their animations.
This PR makes these changes to AccountingLabel:
1. Makes the currency labels have a quick 'bump' style animation immediately.
2. Makes the updated amount of currency display immediately instead of showing the old amount for 2 seconds.
3. After the two seconds of displaying the red or green change in currency next to it, the final label is just displayed and not animated.
4. Adds the 'isInitializing' variable to the class which lets me avoid an occurrence of the animation when the RewardScene is first displayed.
5. Refines the name of 'animationDelay' to be 'intermediateDuration'.
Note:
I intentionally did not adjust the layout of anything, and only updated the animations. This means the colored …
> Adventure: AccountingLabel animation update

- forge-gui/src/main/java/forge/model/CardCollections.java
_I am not a developer, but Forge is amazing, and I wanted to try to contribute. It was super fun to look at the history of these files going back 13 years ago when support for subfolders was added for Constructed decks. There appears to be an optional boolean flag to search subfolders. To fix this issue I will be submitting only a request to change the function for commander decks, but this could be added to other items in CardCollections.java._
This resolves #7811
Aug 19, 2013 **StorageImmediatelySerialized** was extended to support subfolders with a boolean. See **Commit ada5fa5**.
During this commit the boolean was added into **CardCollections**, but only with the "Constructed Decks".
For this issue I have added the same adjustment to the function that loads the Commander Decks.
> Update getCommander method to enable subfolders

- forge-gui-mobile/src/forge/adventure/pointofintrest/PointOfInterestChanges.java
- forge-gui-mobile/src/forge/adventure/scene/MapViewScene.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui/res/adventure/common/ui/map.json
- forge-gui/res/adventure/common/ui/map_portrait.json
Multiple Buttons which cycle Visibility when being pressed:
Details -> Events: Display Drafts/Jumpstarts at Inns
Events -> Reputation: Remove Labels. Display Town Reputation if != 0
Reputation -> Names: Remove Labels. Display Names of visited Dungeons (visited is saved in PointOfInterestChanges)
Names -> Details: Remove Labels
Zooming by creating a new ScrollPane without a ScrollListener and then attaching a new Input Listener which activates the Zoom methods
WorldMap image gets scaled and moved to maintain viewing position
Labels and MiniMapPlayer get moved as well
> Details Labels and Zooming on Adventure World Map

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/adventure/scene/MenuScene.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/scene/UIScene.java
- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/stage/GameStage.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/toolbox/FDisplayObject.java
- forge-gui/res/adventure/common/ui/items.json
This PR contains a number of UX improvements and bug fixes for menu navigation in Adventure Mode
The majority of these fixes are related to keybindings that only work when using game pads or Android devices, and do not have keyboard support.
* Change keybinding to exit the shop and other rewards screens from Use to Back. This is consistent with all other menus that let you press ESC to go back. It also prevents accidental purchase of cards when attempting to exit shop.
* Fix enter key not working to save game in save menu
* Fix enter key not working to load game in load menu
* Add support for ESC key to go back from deck editor screen
* Fix main menu flickering issue when opened
* Fix issue where main menu opens and closes with a single key press
* Enable ESC (Back KeyBinding) to dismiss …
> Fix several UX issues with menu navigation and dialog boxes

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
This PR:
1. Makes the autoSell buttons on card rewards semi-transparent unless auto-sell is enabled or being moused-over.
The intent is basically to both look a little nicer, and make text under it a little readable to see all the rules text without having to hover-over. 
3. Fixes some transparency issues that then became apparent. The transparency set for an Actor being drawn in a batch was not reset before drawing the next Actor in a batch, causing other things to be transparent that shouldn't be. Libgdx documentation says to set the batch color between drawing Actors, so I overrode two draw() methods affecting the rewards screen to do this.
See: https://libgdx.com/wiki/graphics/2d/scene2d/scene2d#drawing
4. Increased the card rewards' flip speed to better match the sound effect (and be …
> Adventure:  Made auto-sell buttons semi-transparent unless selected, fixed transparency issues, increased card flip speed

- forge-gui-mobile/src/forge/deck/FDeckEditor.java
Got several reports of drafts crashing at the very last pick because of a null pointer to the pool.  I couldn't replicate this myself but a refresh is being scheduled and then activated on the last pick, resulting in `draft.nextChoice()` returning null, and then finally `ImagePool.addAll()` throwing a null pointer exception.
> fix null pointer on refresh during last draft pick

- forge-gui/res/formats/Archived/Arena Standard/2025-06-30.txt
- forge-gui/res/formats/Archived/Historic/2025-06-30.txt
- forge-gui/res/formats/Archived/Standard/2025-06-30.txt
Historic:
- Counterspell is unbanned.
Standard:
- Abuelo's Awakening is banned.
- Cori-Steel Cutter is banned.
- Heartfire Hero is banned.
- Hopeless Nightmare is banned.
- Monstrous Rage is banned.
- This Town Ain't Big Enough is banned.
- Up the Beanstalk is banned.
_I didn't include the Alchemy suspension (because we don't do suspensions around here), or Arena Pioneer Bo1 ban (because we don't do that either)._
Effective Date:
- June 30, 2025
Source: https://magic.wizards.com/en/news/announcements/banned-and-restricted-june-30-2025
> Banned and Restricted Announcement for June 30, 2025

- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/deck/FDeckViewer.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
Adds new button to the adventure mode deck editor that enables users to copy full collection to clipboard.
This is useful when using external tools and websites for deck building.
PR includes translations for all supported languages.
> Add "Copy Collection to Clipboard" button to adventure mode deck editor

- forge-core/src/main/java/forge/util/ImageUtil.java
Should fix #7923 for Android, with fallback to old behavior.
> Encode collector number + fallback

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/cube/MTGO Vintage Cube 2025-04.dck
- forge-gui/res/editions/30th Anniversary Celebration Tokyo.txt
- forge-gui/res/editions/Amonkhet Invocations.txt
- forge-gui/res/editions/Commander Collection Black.txt
- forge-gui/res/editions/DCI Promos.txt
- forge-gui/res/editions/Dominaria United Promos.txt
- forge-gui/res/editions/Eighth Edition Promos.txt
- forge-gui/res/editions/Eternal Weekend.txt
- forge-gui/res/editions/Final Fantasy Regional Promos.txt
- forge-gui/res/editions/Game Day Promos.txt
- forge-gui/res/editions/Happy Holidays.txt
- forge-gui/res/editions/Japan Standard Cup.txt
- forge-gui/res/editions/Magic Player Rewards 2003.txt
- forge-gui/res/editions/Magic x Duel Masters Promos.txt
- forge-gui/res/editions/Masters Edition.txt
- forge-gui/res/editions/Mythic Edition - Guilds of Ravnica.txt
- forge-gui/res/editions/Mythic Edition - Ravnica Allegiance.txt
- forge-gui/res/editions/Mythic Edition - War of the Spark.txt
- forge-gui/res/editions/Rivals of Ixalan Promos.txt
- forge-gui/res/editions/Secret Lair Showdown.txt
- forge-gui/res/editions/Theros Beyond Death Promos.txt
- forge-gui/res/editions/URL Convention Promos.txt
- forge-gui/res/editions/Year of the Dragon 2024.txt
- forge-gui/res/editions/Year of the Ox 2021.txt
- forge-gui/res/editions/Year of the Rabbit 2023.txt
- forge-gui/res/editions/Year of the Snake 2025.txt
- forge-gui/res/editions/Zendikar Promos.txt
* Added missing cards.
* Changed Master Edition from MED to ME1 to reflect Scryfall's ID.
* Changed Masterpiece Series - Amonkhet from MPS_AKH to MP2 to reflect Scryfall's ID, as well as the set's name.
* Replaced 'unsupported' cards by their non-promo equivalent so they don't popup at every launch.
> Non-alchemy sets cleanup

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
TriggeredActivator not defined on AbilityUtils calculateAmount, hence produces ClassCastException (found on Sentry)
> Fix Crash for Rug of Smothering

- forge-core/src/main/java/forge/StaticData.java
- forge-core/src/main/java/forge/card/CardDb.java
- forge-core/src/main/java/forge/card/CardEdition.java
- forge-game/src/main/java/forge/game/GameFormat.java
- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui-mobile/src/forge/adventure/data/RewardData.java
- forge-gui/res/editions/Alchemy Dominaria.txt
- forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt
- forge-gui/res/editions/Jumpstart Historic Horizons.txt
- forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestPlane.java
- forge-gui/src/main/java/forge/gamemodes/quest/BoosterUtils.java
- forge-gui/src/main/java/forge/gamemodes/quest/QuestEventDraft.java
- forge-gui/src/main/java/forge/gamemodes/quest/QuestUtilCards.java
Fixes #7445 
* Try to use current set when creating a card from an effect
* Removed conjured-only cards from shops/rewards (Might need more testing)
* Fix CardDb fallback
> Try to use current set when creating a card from an effect

- forge-gui/release-files/ISSUES.txt
I'm a new player, installed and was looking through files. This git.cardforge.org URL no longer works, and I assume we want to use the GitHub issues list here.
> Update ISSUES.txt URL from git.cardforge.com to github.com

- forge-gui/res/adventure/common/maps/map/main_story/castles/red_castle_f1.tmx
Hard mode didn't have the defeat dialogue because it spawned a different version of Lathliss without the defeat code.
(I had to duplicate the defeat code, which means that it is a little more error-prone to maintain, but hopefully that won't actually come up too much)
> Fix for red castle

- forge-gui/res/adventure/Shandalar/world/quests.json
When I put in the code to delete quest items on a new game+ I forgot to re-add the colorless rune that lets you teleport to the center of the map in case you start without the main quest (you get it as part of the main quest). This fixes that.
> Re-adding item to New Game+ Adventure

- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
This should fix the broken ImageKey for DefinedName (Tarmagoyf)
> CopyPermanentEffect: fix DefinedName TokenKey

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/mana/ManaCostBeingPaid.java
- forge-gui/src/main/java/forge/gamemodes/match/input/InputPayManaOfCostPayment.java
I wouldn't do it if it only simplified the code again since this was changed in 726976f
but performance-wise I'm seeing nothing negative, especially since the extra guards for targeted SA or Ward don't have to be considered now :)
Also cherry-picked fix from #8229
> Streamline logic so canPlay always before canPay

- forge-gui/res/cardsfolder/a/abzan_falconer.txt
- forge-gui/res/cardsfolder/a/akroma_vision_of_ixidor.txt
- forge-gui/res/cardsfolder/c/chaos_terminator_lord.txt
- forge-gui/res/cardsfolder/c/conversion.txt
- forge-gui/res/cardsfolder/d/deathleaper_terror_weapon.txt
- forge-gui/res/cardsfolder/d/djeru_and_hazoret.txt
- forge-gui/res/cardsfolder/e/emberstrike_duo.txt
- forge-gui/res/cardsfolder/e/emerald_dragonfly.txt
- forge-gui/res/cardsfolder/f/fallaji_chaindancer.txt
- forge-gui/res/cardsfolder/g/gorilla_pack.txt
- forge-gui/res/cardsfolder/h/haunted_hellride.txt
- forge-gui/res/cardsfolder/j/jon_irenicus_shattered_one.txt
- forge-gui/res/cardsfolder/l/lance.txt
- forge-gui/res/cardsfolder/m/mardu_charm.txt
- forge-gui/res/cardsfolder/m/marton_stromgald.txt
- forge-gui/res/cardsfolder/n/naktamun_shines_again.txt
- forge-gui/res/cardsfolder/p/primeval_bounty.txt
- forge-gui/res/cardsfolder/r/restless_spire.txt
- forge-gui/res/cardsfolder/rebalanced/a-ancestral_katana.txt
- forge-gui/res/cardsfolder/s/sarevok_the_usurper.txt
- forge-gui/res/cardsfolder/s/sidequest_card_collection_magicked_card.txt
- forge-gui/res/cardsfolder/s/skanos_dragon_vassal.txt
- forge-gui/res/cardsfolder/s/skorpekh_destroyer.txt
- forge-gui/res/cardsfolder/s/skyserpent_seeker.txt
- forge-gui/res/cardsfolder/s/spitting_slug.txt
- forge-gui/res/cardsfolder/t/thunderous_orator.txt
- forge-gui/res/cardsfolder/u/unnatural_summons.txt
- forge-gui/res/cardsfolder/w/warzone_duplicator.txt
- forge-gui/res/cardsfolder/w/wilson_bear_comrade.txt
- Sundry typos, with a few arguably functional ones involving parameter capitalization
- Some `SubAbility$` argument/name standardization to follow existing patterns and ease future cleanup passes.
> Cleanup: 2025-07-25

- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Black.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Black_R.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Black_S.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Black_U.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Blue.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Blue_R.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Blue_S.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Blue_U.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Green.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Green_R.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Green_S.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Green_U.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Red.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Red_R.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Red_S.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_Red_U.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_White.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_White_R.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_White_S.dck
- forge-gui/res/adventure/Shandalar Old Border/decks/shops/landShop_White_U.dck
- forge-gui/res/adventure/Shandalar Old Border/world/shops.json
The land shops were desired to be a bit more mixed and random for Shandalar Old Border while RemusLord was working on it. When they were brought into the main system, the new shop logic he built was reliant on java files not in core forge. Instead of adding entirely new java files for something that was only being used by the one world. I built up a series of shop decks and accessed via it's own shops.json to use them, and Remus approved the final result. This will have zero impact outside Shandalar Old Border.
> Resolving the land shop issue in Shandalar Old World.

- forge-gui/res/cardsfolder/u/ultima_origin_of_oblivion.txt
Closes #8257 .
Confirmed AI behavior in bug report (2025-07-19 build):
- AI focuses targeting of attack trigger on own lands probably because the ramping self aspect is likely weighed well above denying other player resources.
- AI does this targeting non-systematically:
-> targeting lands they control that already have blight counters on them.
-> targeting nonbasic lands they control, especially ones with nonmana activated abilities as was reported as the main issue.
Iterating through fixes, some more or less strict, I came upon the argument for `AITgts$` herein which guides the AI into somewhat more strategic behavior. It, admittedly, doesn't completely avoid the nullification of nonbasic lands the AI controls but it does delay that eventuality substantially.
As for attempted fixes, …
> Fixing Ultima, Origin of Oblivion

- forge-gui/src/main/java/forge/itemmanager/AdvancedSearchParser.java
- forge-gui/src/main/java/forge/itemmanager/SFilterUtil.java
Fix for search such as `"Up to two"` or `o:"corrupt "`
> Fix exact search

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/screens/settings/SettingsPage.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java
Should fix longer startup time on mobile version instead of forcing to load custom drafts file at startup.
> add Preload Custom Drafts

- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
- forge-gui-mobile/src/forge/adventure/util/AdventureEventController.java
Fixes crash when previewing Jumpstart decks. Plugged in the wrong overload here when removing the back button callbacks.
Fixes an NPE when fighting an enemy without all possible extra sections. This one's probably worth refiring snapshots over.
> Fix some crashes from the new editor

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
Originally switched from `addGold` so the sound would play, but used `takeGold` instead of `giveGold`.
> Fix negative gold payouts from selling cards.

- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/deck/FDeckEditor.java
Addresses two issues when opening the context menu on a card in the Auto-Sell page while inside a shop. Namely: a ClassCastException that I don't think crashes the game but gets swallowed on some UI thread, and some error outputs for trying to generate an item to move cards to a non-existent destination section. Also ensures the Auto-Sell page's size is updated when it initializes, so it shows before any cards are added to or removed from it.
Doesn't seem urgent enough for yet another refiring of snapshots; nobody's reported these yet as far as I can tell and neither outright crashed the game in my tests.
> A few auto-sell section fixes

- forge-core/src/main/java/forge/deck/Deck.java
Apparently very old decks that were serialized for storage didn't have a `tags` field, even though it's effectively non-null these days. Added a `readResolve` method to account for that. But we *really* should move away from using Java serialization for anything. It easily breaks assumptions in ways that's difficult to account for.
Also reverses `tags.addAll(result.getTags());` to `result.tags.addAll(this.tags);`, because that seems more like the intended behavior for the `cloneFieldsTo` method.
> Fix NPE deserializing old decks

- forge-core/src/main/java/forge/card/CardEdition.java
no need to go over the Section Map twice
Also use CollectorNumber instead of index
also, i don't think `getPrintSheetsBySection` needs to be cached, or?
it isn't called that often
> CardEdition: getPrintSheetsBySection use collectorNumber

- forge-core/src/main/java/forge/deck/Deck.java
Apparently the name field could go missing as well? I'm not sure why that would happen but this should prevent it at least.
> Attempt to fix another NPE in deserializing decks

- forge-core/src/main/java/forge/card/CardRulesPredicates.java
- forge-core/src/main/java/forge/util/ImageUtil.java
- forge-gui/res/editions/Shadows over Innistrad Remastered.txt
- forge-gui/src/main/java/forge/itemmanager/AdvancedSearchParser.java
* Meld image fetching should be fixed. Tested with FIN, SIR, EMN and BRO.
* Added advanced search for split cards. (`is:meld`, `is:flip`, etc.)
> Fix meld + Add advanced search for split types

- forge-gui/res/cardsfolder/c/constricting_sliver.txt
- forge-gui/res/cardsfolder/d/dementia_sliver.txt
- forge-gui/res/cardsfolder/f/frenetic_sliver.txt
- forge-gui/res/cardsfolder/f/frenzy_sliver.txt
- forge-gui/res/cardsfolder/f/fungus_sliver.txt
- forge-gui/res/cardsfolder/h/harmonic_sliver.txt
- forge-gui/res/cardsfolder/l/lavabelly_sliver.txt
- forge-gui/res/cardsfolder/m/magma_sliver.txt
- forge-gui/res/cardsfolder/m/mesmeric_sliver.txt
- forge-gui/res/cardsfolder/m/mistform_sliver.txt
- forge-gui/res/cardsfolder/o/opaline_sliver.txt
- forge-gui/res/cardsfolder/p/plague_sliver.txt
- forge-gui/res/cardsfolder/p/psionic_sliver.txt
- forge-gui/res/cardsfolder/p/pulmonic_sliver.txt
- forge-gui/res/cardsfolder/r/regal_sliver.txt
- forge-gui/res/cardsfolder/s/sliv_mizzet_hivemind.txt
- forge-gui/res/cardsfolder/s/spiteful_sliver.txt
- forge-gui/res/cardsfolder/t/taunting_sliver.txt
- forge-gui/res/cardsfolder/t/tempered_sliver.txt
- forge-gui/res/cardsfolder/t/thorncaster_sliver.txt
- forge-gui/res/cardsfolder/v/vampiric_sliver.txt
I came across [Harmonic Sliver](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/h/harmonic_sliver.txt) with a trigger condition for itself and another for the other Slivers, something that I interpret as a remainder from an earlier state of the game engine. Tidied it according to [Constricting Sliver](https://github.com/Card-Forge/forge/blob/master/forge-gui/res/cardsfolder/c/constricting_sliver.txt), tested the new script version and it works as expected. 
Also, took the opportunity to standardize the `Sliver.Self` flourish in this and other cards.
As requested, removed `AddSVar$` from other trigger and ability-granting Silvers where it was found to be redundant. Salient cards were tested to confirm this removal didn't affect their function.
> Tidying trigger-granting Slivers

- forge-core/src/main/java/forge/card/CardRules.java
> The Doctor's companion ability allows you to have two commanders if one has the ability and the other is a legendary creature that is a Time Lord Doctor and has no other creature types. Creatures with the changeling ability, for example, can't be a second commander this way.
(2023-10-13)
This will ensure that it is both a Time Lord and Doctor, and nothing else.
> Fix IsDoctor check

- forge-installer/pom.xml
This bumps `izpack-maven-plugin`.
Tested with JDK 25.
Similar fix for another project:
https://github.com/lsc-project/lsc/pull/385
Original Error message:
`[ERROR] Failed to execute goal
org.codehaus.izpack:izpack-maven-plugin:5.2.3:izpack (standard-installer) on project forge-installer: Execution standard-installer of goal org.codehaus.izpack:izpack-maven-plugin:5.2.3:izpack failed: java.lang.ArrayIndexOutOfBoundsException: Index 70131 out of bounds for length 22674 -> [Help 1]`
> Fix build on JDK 21+

- forge-core/src/main/java/forge/card/CardRulesPredicates.java
- forge-gui/src/main/java/forge/itemmanager/AdvancedSearchParser.java
Added `is:vanilla` to return vanilla creatures and lands, and `is:custom` for custom cards.
> Add new card filters

- .gitignore
- forge-gui-android/pom.xml
- forge-gui-desktop/pom.xml
- forge-gui/release-files/CHANGES.txt
- forge-installer/pom.xml
- pom.xml
- Generate CHANGES.txt in forge-gui-desktop/target/ instead of source tree
- Update installer to copy from target directory for all build profiles
- Add CHANGES.txt to .gitignore since it's generated
- Remove hardcoded fromRef to use latest tag automatically
- Remove maven-release-plugin exclusion for untracked file
Fixes issue where CHANGES.txt appeared as modified after every build.
--
While working on #8378, I keep seeing changes to `forge-gui/release-files/CHANGES.txt`, and within that file it looked like it included a lot more changes than I expected (all the way back to 2011).  It likely shouldn't be in the codebase at all, so I removed it, and set the generated location to be in the target directory.  Further, the release related scripts that use this file were adjusted to refer to …
> fix: move CHANGES.txt generation to target directory

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/DeckSelectScene.java
Fixes #8582.
Did our best to keep this one short and sweet.
> Fix crash copying adventure decks with full slots

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
- forge-gui-mobile/src/forge/screens/match/MatchController.java
- forge-gui-mobile/src/forge/screens/match/views/VCardDisplayArea.java
- forge-gui-mobile/src/forge/screens/match/views/VField.java
- forge-gui-mobile/src/forge/screens/match/views/VManaPool.java
- forge-gui-mobile/src/forge/screens/match/views/VPlayerPanel.java
- forge-gui-mobile/src/forge/screens/match/views/VZoneDisplay.java
- forge-gui-mobile/src/forge/screens/settings/SettingsPage.java
Screenshots also enabled Alt Player Layout
- Off (Default Layout)
- Vertical (Alt Layout with old Vertical Scroll Card Display Area)
- Horizontal (Alt Layout with Horizontal Scroll Card Display Area)
- fix mouse scroll to scroll horizontall while ShiftKey is pressed
> update AltZoneLayout VCardDisplayArea for Landscape

- forge-game/src/main/java/forge/game/trigger/TriggerType.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/upcoming/monoist_gravliner.txt
- forge-gui/res/cardsfolder/upcoming/spirited_simulacrum.txt
- forge-gui/res/cardsfolder/upcoming/squadron_carrier.txt
- forge-gui/res/cardsfolder/upcoming/thought_partition.txt
- [Monoist Gravliner](https://scryfall.com/card/yeoe/11/monoist-gravliner) with functional trigger support
- [Spirited Simulacrum](https://scryfall.com/card/yeoe/30/spirited-simulacrum)
- [Squadron Carrier](https://scryfall.com/card/yeoe/2/squadron-carrier)
Needing engine update:
- [Thought Partition](https://scryfall.com/card/yeoe/4/thought-partition)
=> ~~The effect sequence works as far as changing the chosen card's color to white. Couldn't figure out how to change the mana cost on my own.~~ Functional engine support provided by https://github.com/Card-Forge/forge/pull/8504
> YEOE: 4 cards, batch 3

- forge-gui/src/main/java/forge/gamemodes/quest/BoosterUtils.java
- forge-gui/src/main/java/forge/gamemodes/quest/QuestEventDraft.java
* Fix a crash when you start a Quest using boosters in an Unsanctioned pool.
* Fix a crash when getting rewards for a draft.
> Fix Quest crashes
