Card-Forge/forge

- forge-gui-mobile/src/forge/adventure/data/PointOfInterestData.java
- forge-gui-mobile/src/forge/adventure/pointofintrest/PointOfInterest.java
- forge-gui-mobile/src/forge/adventure/pointofintrest/PointOfInterestChanges.java
- forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
- forge-gui-mobile/src/forge/adventure/util/SaveFileData.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- forge-gui/res/adventure/Shandalar/maps/main.tiled-session
- forge-gui/res/adventure/Shandalar/ui/save_load.json
- forge-gui/res/adventure/Shandalar/ui/save_load_mobile.json
Adventure Changes
-fixed saving poi data
-added date to load screen
> adventure: fixed saving poi data, added date to load screen

- forge-gui-mobile/src/forge/adventure/data/PointOfInterestData.java
- forge-gui-mobile/src/forge/adventure/pointofintrest/PointOfInterest.java
- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui/res/adventure/Shandalar/world/black.json
- forge-gui/res/adventure/Shandalar/world/blue.json
- forge-gui/res/adventure/Shandalar/world/green.json
- forge-gui/res/adventure/Shandalar/world/points_of_interest.json
- forge-gui/res/adventure/Shandalar/world/red.json
- forge-gui/res/adventure/Shandalar/world/waste.json
- forge-gui/res/adventure/Shandalar/world/white.json
Renamed, re-set and cherry-picked a few of the various PoIs and reverted placement behavior.
> Adventure mode PoI refactor.

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/keyword/KeywordWithAmount.java
- forge-gui/res/cardsfolder/upcoming/a_little_chat.txt
- forge-gui/res/cardsfolder/upcoming/anhelo_the_painter.txt
- forge-gui/res/cardsfolder/upcoming/cut_of_the_profits.txt
- forge-gui/res/cardsfolder/upcoming/cut_your_losses.txt
- forge-gui/res/cardsfolder/upcoming/dig_up_the_body.txt
- forge-gui/res/cardsfolder/upcoming/illicit_shipment.txt
- forge-gui/res/cardsfolder/upcoming/join_the_maestros.txt
- forge-gui/res/cardsfolder/upcoming/light_em_up.txt
- forge-gui/res/cardsfolder/upcoming/make_disappear.txt
- forge-gui/res/cardsfolder/upcoming/ob_nixilis_the_adversary.txt
- forge-gui/res/cardsfolder/upcoming/rob_the_archives.txt
- forge-gui/res/cardsfolder/upcoming/rooftop_nuisance.txt
- forge-gui/res/tokenscripts/b_4_3_ogre_warrior.txt
> SNC: Casualty

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardDamageHistory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/grisly_sigil.txt
Merge #1 first
This card required tracking of if a card was dealt non-combat damage this turn
> SNC: Grisly Sigil and support

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PermanentEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/upcoming/jaxis_the_troublemaker.txt
> SNC: Blitz keyword

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
- forge-gui/res/cardsfolder/upcoming/vivien_on_the_hunt.txt
- forge-gui/res/tokenscripts/g_4_4_rhino_warrior.txt
No real engine tweaks – just some StackDescription stuff and a token
> SNC Vivien and tweaks

- forge-gui/res/cardsfolder/upcoming/all_seeing_arbiter.txt
> SNC: All-Seeing Arbiter

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
Some paid costs are not copied / can't be found.
E.g. copying an evoked _Mulldrifter_ with _Lithoform Engine_ - the copy sacrifice won't trigger.
> 707.10: Copied spells incomplete

- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
Adds instructions to clarify what to do when this comes up
Requesting lots of reviews from people who speak languages :)
> clarify ChooseNColors prompt

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
> Some Keyword reminder text parsing tweaks (mostly Hideaway)

- forge-gui/res/adventure/Shandalar/maps/obj/block.tx
Added Dummy block template.
Was left behind accidentally.
> Big map update 8.6

- forge-gui/res/cardsfolder/upcoming/antagonize.txt
- forge-gui/res/cardsfolder/upcoming/big_score.txt
- forge-gui/res/cardsfolder/upcoming/black_market_tycoon.txt
- forge-gui/res/cardsfolder/upcoming/bootleggers_stash.txt
- forge-gui/res/cardsfolder/upcoming/brokers_initiate.txt
- forge-gui/res/cardsfolder/upcoming/cabaretti_initiate.txt
- forge-gui/res/cardsfolder/upcoming/civic_gardener.txt
- forge-gui/res/cardsfolder/upcoming/cleanup_crew.txt
- forge-gui/res/cardsfolder/upcoming/crew_captain.txt
- forge-gui/res/cardsfolder/upcoming/crooked_custodian.txt
- forge-gui/res/cardsfolder/upcoming/demons_due.txt
- forge-gui/res/cardsfolder/upcoming/glittermonger.txt
- forge-gui/res/cardsfolder/upcoming/goldhound.txt
- forge-gui/res/cardsfolder/upcoming/jackhammer.txt
- forge-gui/res/cardsfolder/upcoming/jewel_thief.txt
- forge-gui/res/cardsfolder/upcoming/midnight_assassin.txt
- forge-gui/res/cardsfolder/upcoming/obscura_initiate.txt
- forge-gui/res/cardsfolder/upcoming/ognis_the_dragons_lash.txt
- forge-gui/res/cardsfolder/upcoming/ready_to_rumble.txt
- forge-gui/res/cardsfolder/upcoming/riveteers_initiate.txt
- forge-gui/res/cardsfolder/upcoming/wrecking_crew.txt
Loads of easy ones for this PR
> SNC - 15 April

- forge-gui-mobile/src/forge/adventure/character/CharacterSprite.java
- forge-gui-mobile/src/forge/adventure/character/EnemySprite.java
- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/pointofintrest/PointOfInterestMap.java
- forge-gui-mobile/src/forge/adventure/stage/Console.java
- forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/stage/GameStage.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/util/Current.java
- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui/res/adventure/Shandalar/world/points_of_interest.json
removed the redundant id on EnemySprite and touched some files to support console commands
> added Console

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- fixes touchpad issues not working
> revert touchpad for adventure

- forge-game/src/main/java/forge/game/StaticEffect.java
- forge-game/src/main/java/forge/game/staticability/StaticAbility.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-gui/res/cardsfolder/upcoming/witness_protection.txt
Seems to be working well - just needed support for renaming the enchanted
> SNC: Witness Protection and support

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/PumpAllEffect.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
> Fix UntilYourNextTurn expiring too early

- forge-ai/src/test/java/.gitignore
- forge-core/src/test/java/.gitignore
They shouldn't have been ignored in the first place...
> .gitignore: stop ignoring test directories

- forge-gui-mobile/src/forge/adventure/data/DialogData.java
- forge-gui-mobile/src/forge/adventure/util/MapDialog.java
Nicer dialogs with word wrapping.
> Big map update 9

- forge-gui/res/cardsfolder/upcoming/angel_of_suffering.txt
- forge-gui/res/cardsfolder/upcoming/angelic_observer.txt
- forge-gui/res/cardsfolder/upcoming/aven_heartstabber.txt
- forge-gui/res/cardsfolder/upcoming/buy_your_silence.txt
- forge-gui/res/cardsfolder/upcoming/celebrity_fencer.txt
- forge-gui/res/cardsfolder/upcoming/extraction_specialist.txt
- forge-gui/res/cardsfolder/upcoming/giada_font_of_hope.txt
- forge-gui/res/cardsfolder/upcoming/incandescent_aria.txt
- forge-gui/res/cardsfolder/upcoming/knockout_blow.txt
- forge-gui/res/cardsfolder/upcoming/refuse_to_yield.txt
- forge-gui/res/cardsfolder/upcoming/tainted_indulgence.txt
- forge-gui/res/cardsfolder/upcoming/void_rend.txt
Thanks to Marvel, Suthro & SladeWilson for the scripts
> Some SNC scripts from Discord contributors

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/Streets of New Capenna.txt
> SNC Booster Draft

- forge-gui/res/cardsfolder/s/shoulder_to_shoulder.txt
> shoulder_to_shoulder.txt fixup

- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-gui/res/cardsfolder/b/boot_nipper.txt
- forge-gui/res/cardsfolder/c/crystalline_giant.txt
- forge-gui/res/cardsfolder/f/ferocious_tigorilla.txt
- forge-gui/res/cardsfolder/f/flycatcher_giraffid.txt
- forge-gui/res/cardsfolder/g/grimdancer.txt
- forge-gui/res/cardsfolder/h/helica_glider.txt
- forge-gui/res/cardsfolder/u/unexpected_fangs.txt
- forge-gui/res/cardsfolder/upcoming/elspeth_resplendent.txt
- forge-gui/res/cardsfolder/w/wingfold_pteron.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
This is one of those where one thing led to another and another... I am hoping the elimination of GenericChoice for stuff like this makes AI easier? @Agetian
> SNC: Elspeth Resplendent and support + refactoring various related IKO stuff

- forge-game/src/main/java/forge/game/ability/ApiType.java
- forge-game/src/main/java/forge/game/ability/effects/ConniveEffect.java
- forge-gui/res/cardsfolder/upcoming/body_launderer.txt
- forge-gui/res/cardsfolder/upcoming/echo_inspector.txt
- forge-gui/res/cardsfolder/upcoming/hypnotic_grifter.txt
- forge-gui/res/cardsfolder/upcoming/illuminator_virtuoso.txt
- forge-gui/res/cardsfolder/upcoming/kamiz_obscura_oculus.txt
- forge-gui/res/cardsfolder/upcoming/ledger_shredder.txt
- forge-gui/res/cardsfolder/upcoming/obscura_interceptor.txt
- forge-gui/res/cardsfolder/upcoming/psionic_snoop.txt
- forge-gui/res/cardsfolder/upcoming/psychic_pickpocket.txt
- forge-gui/res/cardsfolder/upcoming/raffine_scheming_seer.txt
- forge-gui/res/cardsfolder/upcoming/raffines_informant.txt
- forge-gui/res/cardsfolder/upcoming/raffines_silencer.txt
- forge-gui/res/cardsfolder/upcoming/revel_ruiner.txt
- forge-gui/res/cardsfolder/upcoming/security_bypass.txt
- forge-gui/res/cardsfolder/upcoming/toluz_clever_conductor.txt
Re-added "when it connives this way" cards - closes #34
> SNC: Make Connive effect

- forge-gui/res/cardsfolder/upcoming/sizzling_soloist.txt
May not get to any more until tomorrow...
> sizzling_soloist.txt

- forge-game/src/main/java/forge/game/GameAction.java
- forge-gui/res/cardsfolder/t/tatsumasa_the_dragons_fang.txt
- Fixes not gaining experience counters from Kelsien
- Fixes Tatsumasa not returning
> Fix IsTriggerRemembered for Tokens

- forge-game/src/main/java/forge/game/ability/effects/PeekAndRevealEffect.java
- forge-gui/res/cardsfolder/m/medomais_prophecy.txt
- forge-gui/res/cardsfolder/upcoming/case_the_joint.txt
No real mechanical changes, but some overhauls to PeekAndRevealEffect
Since Medomai's Prophecy didn't have `NoMove` I'm calling it a patch
> SNC: Case the Joint and support

- .github/workflows/test-build.yaml
- forge-gui-desktop/src/main/java/forge/toolbox/FSkin.java
This adds a workflow which runs tests in multiple java versions.
This is how it looks in action: https://github.com/pfirpfel/forge/actions/runs/2192175048
> Add gh testing workflow

- forge-gui/res/cardsfolder/f/flames_of_the_blood_hand.txt
Source: https://magic.wizards.com/en/articles/archive/news/oracle-changes-2022-04-20
> Flames of the Blood Hand Oracle update

- forge-game/src/main/java/forge/game/ability/effects/PeekAndRevealEffect.java
- forge-gui/res/cardsfolder/f/frost_augur.txt
String defined definition was causing NPE on lines with no Defined$
> PeekAndReveal stackDesc NPE fix

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/upcoming/luxior_giadas_gift.txt
- forge-gui/res/cardsfolder/upcoming/luxor_giadas_gift.txt
This is probably going to be a rules nightmare – seems to "work" in initial testing though
The part I'm least sure about is Card > canBeEquippedBy
> SNC: Luxior, Giada's Gift and support

- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-gui/res/cardsfolder/upcoming/exotic_pets.txt
> SNC: Exotic Pets and support

- forge-gui/res/cardsfolder/upcoming/angelic_sleuth.txt
> NCC Angelic Sleuth

- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
ChangeNum param always defaults to "1" in Effects that use it, so tweaking when AI looks for the param to reflect that.
> AI: "ChangeNum" defaults

- forge-gui/res/cardsfolder/upcoming/obscura_ascendancy.txt
- forge-gui/res/cardsfolder/upcoming/rocco_cabaretti_caterer.txt
- forge-gui/res/cardsfolder/upcoming/unlicensed_hearse.txt
- forge-gui/res/tokenscripts/w_2_2_spirit_flying.txt
May be a better way to do the Hearse?
> SNC: 25 April

- forge-gui/res/cardsfolder/upcoming/park_heights_pegasus.txt
Just the only one I did today that didn't require any engine tweaks 😅 
@Agetian - the AI for this seems... like more trouble than it's worth 😆
> park_heights_pegasus.txt

- forge-gui/res/cardsfolder/b/balan_wandering_knight.txt
- forge-gui/res/cardsfolder/upcoming/brass_knuckles.txt
- forge-gui/res/cardsfolder/upcoming/cabaretti_ascendancy.txt
- forge-gui/res/cardsfolder/upcoming/call_in_a_professional.txt
- forge-gui/res/cardsfolder/upcoming/celestial_regulator.txt
- forge-gui/res/cardsfolder/upcoming/endless_detour.txt
- forge-gui/res/cardsfolder/upcoming/even_the_score.txt
- forge-gui/res/cardsfolder/upcoming/fatal_grudge.txt
- forge-gui/res/cardsfolder/upcoming/freelance_muscle.txt
- forge-gui/res/cardsfolder/upcoming/hoard_hauler.txt
- forge-gui/res/cardsfolder/upcoming/patch_up.txt
- forge-gui/res/cardsfolder/upcoming/reservoir_kraken.txt
- forge-gui/res/cardsfolder/upcoming/riveteers_ascendancy.txt
- forge-gui/res/cardsfolder/upcoming/sanguine_spy.txt
- forge-gui/res/cardsfolder/upcoming/shadow_of_mortality.txt
- forge-gui/res/cardsfolder/upcoming/sleep_with_the_fishes.txt
- forge-gui/res/cardsfolder/upcoming/syndicate_infiltrator.txt
Bunch of cards that don't need engine changes
> SNC: 27 April

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
prevent crash for card Riveteers Overlook (and maybe others)
> fix stackoverflow

- forge-core/src/main/java/forge/item/FatPack.java
don't allow creation of FatPack if the set fails getting booster
> prevent Crash of FatPack generation

- forge-game/src/main/java/forge/game/cost/CostExile.java
Improvement for new Corpse Explosion and old stuff like Skaab Goliath
> CostExile > toString() improve

- forge-gui/res/cardsfolder/a/all_suns_dawn.txt
- Make the SpellDescription match the Oracle for card detail
- Other minor preference changes
> all_suns_dawn.txt tidy up

- forge-gui/res/cardsfolder/upcoming/corpse_explosion.txt
- forge-gui/res/cardsfolder/upcoming/rogues_gallery.txt
Few more cards that don't need engine updates
Feel like there should be a cleaner way to do Rogues' Gallery (and All Suns' Dawn) but that may be for another day
> SNC: 29 Apr

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/backstreet_bruiser.txt
- forge-gui/res/cardsfolder/upcoming/glittering_stockpile.txt
- forge-gui/res/cardsfolder/upcoming/soul_of_emancipation.txt
- forge-gui/res/cardsfolder/upcoming/structural_assault.txt
Some more cards that didn't need engine support
Structural Assault stack description for the DamageAll line is kind of bad, I wanted to look at that for Aggravate anyway - that would be a different PR though
Some scripts from @TheBlackMarvel too but I will admit to editing them pretty heavily 😅
> SNC: 30 April

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/SacrificeAllEffect.java
- forge-gui/res/cardsfolder/upcoming/hold_for_ransom.txt
This might be step one of moving all cards that sacrifice to SacrificeEffect and all cards that destroy to DestroyEffect
That is a bigger refactor for another day
> SNC: Hold for Ransom and support

- forge-gui/res/cardsfolder/upcoming/citizens_crowbar.txt
- forge-gui/res/cardsfolder/upcoming/pyre_sledge_arsonist.txt
Last few cards that don't need engine tweaks!
> SNC: 1 May

- forge-gui/res/cardsfolder/upcoming/kitt_kanto_mayhem_diva.txt
- forge-gui/res/cardsfolder/upcoming/phabine_bosss_confidant.txt
> NCC: 1 May

- forge-gui/res/cardsfolder/upcoming/kros_defense_contractor.txt
> NCC: kros_defense_contractor.txt

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/upcoming/perrie_the_pulverizer.txt
closes #194
May have had too much fun with AI hints on this one 😅
> NCC: Perrie and support

- forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/DeckController.java
Got broken by https://github.com/Card-Forge/forge/commit/e220d2157aa537bbb2b2fa9f2d8eafe65c3ac408
> Fix duplicating cards in quest mode

- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
https://discord.com/channels/267367946135928833/970503439605989376/970681255672819832
> NPE tweaks

- forge-gui-mobile/src/forge/itemmanager/ItemManager.java
- needs GUI Layout for Landscape mode
- needs override onclose event on internal EditScreen on AdvancedSearchFilter
> [Adventure] disables Advanced Search

- forge-game/src/main/java/forge/game/ability/effects/FightEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/boxing_ring.txt
> NCC: Boxing Ring and support

- forge-game/src/main/java/forge/game/ability/effects/CountersRemoveEffect.java
- forge-gui/res/cardsfolder/e/etrata_the_silencer.txt
- forge-gui/res/cardsfolder/upcoming/mari_the_killing_quill.txt
> NCC: Mari, the Killing Quill and support

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/upcoming/spiteful_repossession.txt
- forge-gui/res/cardsfolder/upcoming/swindlers_scheme.txt
- forge-gui/res/cardsfolder/upcoming/threefold_signal.txt
A few that don't seem to need engine changes!
closes #227 
closes #207
closes #228
> NCC: 2 May

- forge-gui/res/cardsfolder/c/cycle_of_life.txt
You should be able to target something you cast from stuff like Sen Triplets.
> Fix Cycle of Life

- forge-gui-mobile/src/forge/adventure/data/ConfigData.java
- forge-gui-mobile/src/forge/adventure/data/RewardData.java
- forge-gui/res/adventure/Shandalar/config.json
For now we just restrict the Power Nine. They can still be dropped explicitly.
> Adventure mode - Support to restrict cards from random pool

- forge-gui-mobile/src/forge/adventure/data/RewardData.java
Fix call that assumed MyRandom.
> Adventure mode - Revert RNG

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/a/akim_the_soaring_wind.txt
- forge-gui/res/cardsfolder/e/esix_fractal_bloom.txt
- forge-gui/res/cardsfolder/t/thalisse_reverent_medium.txt
- forge-gui/res/cardsfolder/upcoming/vazi_keen_negotiator.txt
> NCC: Vazi, Keen Negotiator and support

- forge-gui/res/cardsfolder/upcoming/angelic_sleuth.txt
- forge-gui/res/cardsfolder/upcoming/damning_verdict.txt
- forge-gui/res/cardsfolder/upcoming/resourceful_defense.txt
- forge-gui/res/cardsfolder/upcoming/skyboon_evangelist.txt
A few things that don't require engine changes
Closes #270 
Closes #269
> NCC: 6 April

- forge-game/src/main/java/forge/game/ability/effects/TokenEffect.java
I was working on this branch for some SNC token-making card – don't remember which. Anyway, the other process was creating a strange output, so I came up with this. For now, this only works for the activating player making tokens, but more support can be added later if/as needed
> TokenEffect > getStackDescription() try to catch more possibilities

- forge-gui/res/cardsfolder/upcoming/sewer_crocodile.txt
- forge-gui/res/cardsfolder/upcoming/shield_broker.txt
- forge-gui/res/cardsfolder/upcoming/storm_of_forms.txt
> Shield Broker (NCC) and AI for Sewer Crocodile

- forge-gui/res/cardsfolder/upcoming/sewer_crocodile.txt
So this line doesn't have the desired effect here. @tehdiplomat and @tool4ever are looking into debugging it elsewhere
> sewer_crocodile.txt remove bad NonStackingEffect line

- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-gui/res/cardsfolder/upcoming/bribe_taker.txt
> NCC: Bribe Taker and support

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/AbandonEffect.java
- forge-game/src/main/java/forge/game/ability/effects/BalanceEffect.java
- forge-game/src/main/java/forge/game/ability/effects/BidLifeEffect.java
> Fix casting card copies not being added to stack correctly

- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityPanharmonicon.java
- forge-gui/res/cardsfolder/upcoming/lagrella_the_magpie.txt
> NSC: Lagrella, the Magpie

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
> ComputerUtilMana: Fix payment fails with TapsForMana triggers

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui/res/adventure/Shandalar/maps/tileset/main.tsx
* Fixed hedge walls not having collisions.
* Variable timer added to reward scenes, it'll wait longer the more rewards are given. It can also be exited by activating the button again after 0.2 seconds (to prevent accidental double clicks).
> Adventure mode - Small fixes

- forge-gui/res/cardsfolder/upcoming/brokers_confluence.txt
- forge-gui/res/cardsfolder/upcoming/denry_klin_editor_in_chief.txt
- forge-gui/res/cardsfolder/upcoming/familys_favor.txt
- forge-gui/res/cardsfolder/upcoming/skyboon_evangelist.txt
A few that don't need any engine tweaks
closes #284 
closes #302
closes #301
> NCC: 8 April

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/card/CardPredicates.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-gui/res/cardsfolder/a/ambuscade_shaman.txt
- forge-gui/res/cardsfolder/f/farsight_adept.txt
- forge-gui/res/cardsfolder/f/flumph.txt
- forge-gui/res/cardsfolder/i/in_the_web_of_war.txt
- forge-gui/res/cardsfolder/m/marauding_raptor.txt
- forge-gui/res/cardsfolder/m/mercadian_atlas.txt
- forge-gui/res/cardsfolder/o/ogre_battledriver.txt
- forge-gui/res/cardsfolder/r/river_of_tears.txt
- forge-gui/res/cardsfolder/r/rock_jockey.txt
- forge-gui/res/cardsfolder/s/secret_rendezvous.txt
- forge-gui/res/cardsfolder/upcoming/kros_defense_contractor.txt
- forge-gui/res/cardsfolder/v/vorinclex_voice_of_hunger.txt
Mostly cleanup and minor tweaks to AiAttackController
> Cleanup some scripts

- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/upcoming/agents_toolkit.txt
I know K:etbCounter is getting close to end of life, so this is probably not a big deal
closes #291
> NCC: Agent's Toolkit and support

- forge-game/src/main/java/forge/game/zone/MagicStack.java
Is there anything we can test that this might break?
> Fix Slogurk not triggering when dying from SBA legendary

- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-gui/res/cardsfolder/upcoming/smugglers_buggy.txt
Just minor changes to PlayEffect: a little housekeeping and adding an option to imprint played cards
> NCC: Smuggler's Buggy and a little support

- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/upcoming/extravagant_replication.txt
- forge-gui/res/cardsfolder/upcoming/sinister_concierge.txt
- forge-gui/res/cardsfolder/upcoming/spellbinding_soprano.txt
- forge-gui/res/cardsfolder/upcoming/waste_management.txt
closes #313 
closes #312 
closes #320
> NCC: 10 April

- forge-gui/res/adventure/Shandalar/maps/map/main_story/colorless_castle.tmx
- forge-gui/res/adventure/Shandalar/maps/map/main_story/final_castle.tmx
- forge-gui/res/adventure/Shandalar/maps/map/waste_town.tmx
* Castle gates do not consume keys anymore.
* Prototype waste town update.
> Adventure mode - Small map updates

- forge-gui/res/cardsfolder/l/lilianas_standard_bearer.txt
- forge-gui/res/cardsfolder/t/the_grand_tour.txt
- forge-gui/res/cardsfolder/upcoming/aerial_extortionist.txt
- forge-gui/res/cardsfolder/upcoming/audacious_swap.txt
- forge-gui/res/cardsfolder/upcoming/bellowing_mauler.txt
- forge-gui/res/cardsfolder/upcoming/body_count.txt
A few that don't need engine changes and a few small tweaks to old cards
closes #328 
closes #325 
closes #322 
closes #323 - will either need to add StackDescription on the ChangeZone and Play lines, or mess with them a bit. This is OK for now though
> NCC: 11 April

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/bess_soul_nourisher.txt
Very non-invasive engine tweak here
Cool card design
closes #326
> NCC: Bess, Soul Nourisher and support

- forge-game/src/main/java/forge/game/ability/effects/PhasesEffect.java
- forge-gui/res/cardsfolder/upcoming/change_of_plans.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
> NCC: Change of Plans and support

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TokenEffect.java
- forge-gui/res/cardsfolder/upcoming/currency_converter.txt
> NCC Currency Converter and stackDesc tweaks

- forge-gui/res/cardsfolder/upcoming/determined_iteration.txt
- forge-gui/res/cardsfolder/upcoming/dodgy_jalopy.txt
- forge-gui/res/cardsfolder/upcoming/dogged_detective.txt
- forge-gui/res/cardsfolder/upcoming/false_floor.txt
- forge-gui/res/cardsfolder/upcoming/flawless_forgery.txt
- forge-gui/res/cardsfolder/upcoming/grand_crescendo.txt
- forge-gui/res/cardsfolder/upcoming/grime_gorger.txt
stuff that doesn't need engine tweaks
closes #348 
closes #346
closes #349
closes #347 
closes #357 
closes #358 
closes #356
> NCC: 13 April

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-gui/res/cardsfolder/upcoming/first_responder.txt
@tool4ever pointed out that this shouldn't use a Cost
seems like this would use LKI
> Fix NCC First Responder

- forge-gui/res/cardsfolder/c/crovax.txt
- forge-gui/res/cardsfolder/s/silhana_wayfinder.txt
- forge-gui/res/cardsfolder/upcoming/in_too_deep.txt
- forge-gui/res/cardsfolder/upcoming/industrial_advancement.txt
- forge-gui/res/cardsfolder/upcoming/jailbreak.txt
closes #369 
closes #367 
closes #366
> NCC: 16 April

- forge-gui-mobile/src/forge/GuiMobile.java
- forge-gui-mobile/src/forge/adventure/data/EnemyData.java
- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
- forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
- forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- Fantasy Mode will get Random Preconstructed Decks for Enemies and Player.
> [Adventure] Add Fantasy Mode on Deck Selector

- forge-gui-mobile/src/forge/adventure/data/EnemyData.java
- forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- Precons, Theme or Random Generated color decks for Enemies, Precons for Player deck on New Game
> [Adventure] Update Deck selector to Chaos Mode

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- add move action for GameHUD buttons
> [Android] GameHUD buttons action for adventure

- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-gui/res/cardsfolder/r/repository_skaab.txt
- forge-gui/res/cardsfolder/upcoming/killer_service.txt
- forge-gui/res/cardsfolder/upcoming/life_insurance.txt
- forge-gui/res/cardsfolder/upcoming/maestros_confluence.txt
- forge-gui/res/cardsfolder/upcoming/make_an_example.txt
- forge-gui/res/cardsfolder/upcoming/mask_of_the_schemer.txt
- forge-gui/res/cardsfolder/upcoming/master_of_ceremonies.txt
- forge-gui/res/cardsfolder/upcoming/mezzio_mugger.txt
- forge-gui/res/cardsfolder/upcoming/misfortune_teller.txt
more with no engine tweaks
closes #376 
closes #372 
closes #381
closes #383
closes #384
closes #385
closes #386 
closes #387
> NCC: 17 April

- forge-gui-mobile/src/forge/adventure/data/EnemyData.java
- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- longpress the GameHud or the avatar to open the console.
- fix monocolored decks for chaos mode
> add Console toggle for android

- forge-gui/res/cardsfolder/upcoming/next_of_kin.txt
- forge-gui/res/cardsfolder/upcoming/obscura_confluence.txt
couple cards that don't need engine updates
closes #388 
closes #389
> NCC: 18 April

- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
- forge-game/src/main/java/forge/game/ability/effects/GoadEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/upcoming/life_of_the_party.txt
support for Goad that lasts the rest of the game
closes #379
> NCC: Life of the Party and support

- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- merge theme and precons for more random deck on chaos mode
> update deckgen for adventure

- forge-gui/res/cardsfolder/upcoming/prosperous_partnership.txt
- forge-gui/res/cardsfolder/upcoming/protection_racket.txt
a few that don't need engine support
closes #411 
closes #412
> NCC: 19 May

- forge-gui-mobile/src/forge/adventure/data/EnemyData.java
- forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
- forge-gui/src/main/java/forge/deck/DeckProxy.java
- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- add dumpEnemyDeckList command
> add questevent decks for chaos mode

- forge-gui/res/cardsfolder/upcoming/riveteers_confluence.txt
- forge-gui/res/cardsfolder/upcoming/rose_room_treasurer.txt
- forge-gui/res/cardsfolder/upcoming/scepter_of_celebration.txt
a few that don't need engine stuff
closes #419 
closes #430 
closes #431
> NCC: 20 May

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseGenericEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DrainManaEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EncodeEffect.java
- forge-game/src/main/java/forge/game/ability/effects/FlipCoinEffect.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
- forge-gui/res/cardsfolder/a/archangel_of_strife.txt
- forge-gui/res/cardsfolder/h/hoarders_greed.txt
- forge-gui/res/cardsfolder/s/sea_troll.txt
- forge-gui/res/cardsfolder/s/sirens_ruse.txt
- forge-gui/res/cardsfolder/t/tezzeret_betrayer_of_flesh.txt
- forge-gui/res/cardsfolder/upcoming/spiteful_repossession.txt
- forge-gui/res/cardsfolder/v/vizkopa_confessor.txt
- forge-gui/res/cardsfolder/w/world_at_war.txt
This fixes a couple of cards, most notably maybe _Hoarder's Greed_ which didn't repeat at all.
> Card fixes

- forge-gui/res/cardsfolder/upcoming/riveteers_confluence.txt
> riveteers_confluence fix

- forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
-some phones don't like streams
> refactor deckgen for adventure

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/upcoming/smugglers_share.txt
seemed to need some player properties... maybe there's a better way to do this?
closes #436
> NCC: Smuggler's Share and support

- forge-game/src/main/java/forge/game/player/RegisteredPlayer.java
- forge-gui-mobile/src/forge/adventure/character/EnemySprite.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui/src/main/java/forge/deck/DeckProxy.java
- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- mimic (Doppelganger) will use random quest challenge decks on chaos mode. winning the challenge grants 1 life, random amount of gold, 2 rares, 2 uncommons and 3 common cards.
> added chaos battle on adventure

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/upcoming/skyway_robber.txt
Couldn't access the cost cards because the AbilityUtils wanted to look at the value for `Cost$`... this seems a good solution?
Another one for the pile to clean up a lot when Exile gets refactored
closes #435
> NCC: Skyway Robber and support

- forge-gui/res/cardsfolder/upcoming/viviens_stampede.txt
- forge-gui/res/cardsfolder/upcoming/writ_of_return.txt
- forge-gui/res/cardsfolder/upcoming/xanders_pact.txt
Last few that don't need engine updates (I think)!
closes #450 
closes #454 
closes #455
> NCC: 22 April

- forge-gui/res/cardsfolder/d/dragonscale_boon.txt
- forge-gui/res/cardsfolder/upcoming/bhaal_lord_of_murder.txt
- forge-gui/res/cardsfolder/upcoming/dread_linnorm_scale_deflection.txt
- forge-gui/res/cardsfolder/upcoming/monster_manual_zoological_study.txt
- forge-gui/res/cardsfolder/upcoming/stirge.txt
Added Dread Linnorm // Scale Deflection
Added Monster Manual // Zoological Study
Added Stirge
closes #444 
closes #445 
closes #446 
closes #447
> Dread Linnorm // Scale Deflection, Monster Manual // Zoological Study, Stirge

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/wave_of_rats.txt
these card properties would only look at cards, seemed logical to extend them to include players as well
closes #453
> NCC: Wave of Rats and support

- forge-game/src/main/java/forge/game/ability/effects/CountersRemoveEffect.java
Would crash when CounterType was "Any" or "All"
> CountersRemoveEffect fix possible NPE at prompt

- forge-gui/res/cardsfolder/t/teferis_time_twist.txt
> Teferi's Time Twist tweak

- forge-gui/res/cardsfolder/a/aerie_worshippers.txt
- forge-gui/res/cardsfolder/j/jeleva_nephalias_scourge.txt
- forge-gui/res/cardsfolder/t/the_hippodrome.txt
- forge-gui/res/cardsfolder/upcoming/elminsters_simulacrum.txt
- forge-gui/res/cardsfolder/upcoming/myrkul_lord_of_bones.txt
Couple that don't need engine updates and some random fixes
closes #471 
closes #464
> CLB: 23 May

- forge-gui/res/cardsfolder/h/hofri_ghostforge.txt
- forge-gui/res/cardsfolder/n/nightmare_shepherd.txt
- forge-gui/res/cardsfolder/upcoming/myrkul_lord_of_bones.txt
tweak for Nightmare Shepherd and CLB card Myrkul per @Hanmac
> TriggeredNewCardLKICopy -> Remembered

- forge-game/src/main/java/forge/game/ability/effects/ConniveEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/upcoming/lethal_scheme.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/gamemodes/match/input/InputSelectCardsForConvokeOrImprovise.java
> NCC: Lethal Scheme and ConniveEffect improvements

- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/upcoming/zevlor_elturel_exile.txt
> CLB: Zevlor, Elturel Exile and support

- forge-game/src/main/java/forge/game/card/Card.java
> Fix removeTempController

- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- add short delay to see player and mob attack animation before the duel starts
> Add delay to see attack animation on stage

- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/l/lavinia_azorius_renegade.txt
- forge-gui/res/cardsfolder/r/roiling_vortex.txt
- forge-gui/res/cardsfolder/upcoming/raggadragga_goreguts_boss.txt
> CLB: Raggadragga, Goreguts Boss and support

- forge-gui/res/cardsfolder/l/laurine_the_diversion.txt
- forge-gui/res/cardsfolder/upcoming/commander_liara_portyr.txt
- forge-gui/res/cardsfolder/upcoming/gorion_wise_mentor.txt
- forge-gui/res/cardsfolder/upcoming/lozhan_dragons_legacy.txt
- forge-gui/res/cardsfolder/upcoming/mazzy_truesword_paladin.txt
- forge-gui/res/cardsfolder/upcoming/raphael_fiendish_savior.txt
closes #476
closes #475 
closes #483 
closes #484
> CLB: 24 May

- forge-gui/res/cardsfolder/c/crackdown_construct.txt
- forge-gui/res/cardsfolder/r/reckless_amplimancer.txt
If something copies the Amplimancer's ability (like new Dynaheir) the stack descriptions would be identical +2/+2
Log is also of concern but probably for another time:
> various random fixes

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/combat/Combat.java
- forge-gui/res/cardsfolder/upcoming/nemesis_phoenix.txt
> CLB: Nemesis Phoenix and support

- forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
> Fix AI cheating when chaining dmg spells with DividedAsYouChoose

- forge-ai/src/main/java/forge/ai/ability/DrawAi.java
- forge-ai/src/main/java/forge/ai/ability/TapAiBase.java
- forge-ai/src/main/java/forge/ai/ability/UntapAi.java
- forge-game/src/main/java/forge/game/ability/effects/ControlGainEffect.java
AI would never confirm this trigger:
> Fix Tap trigger decisions

- forge-gui/res/cardsfolder/upcoming/baba_lysaga_night_witch.txt
- forge-gui/res/cardsfolder/upcoming/oji_the_exquisite_blade.txt
> Baba Lysaga, Night Witch and Oji, the Exquisite Blade

- pom.xml
For the upcoming release. Not sure if this is all that's necessary for the release process to function with the new repository.
> Update references to the git repo in pom.xml

- forge-adventure/pom.xml
- forge-adventure/src/main/config/forge-adventure.cmd
- forge-gui-android/proguard.cfg
- forge-gui-desktop/pom.xml
- forge-gui-desktop/src/main/config/forge.cmd
- forge-gui-desktop/src/main/config/forge.sh
- forge-gui/src/main/java/forge/gamemodes/net/ProtocolMethod.java
- forge-gui/src/main/java/forge/gamemodes/net/server/NetGuiGame.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
- added access options for Java 11 and up
- fix Netplay Crash on assignGenericAmount
> update ProtocolMethod & access options

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/cost/CostTap.java
- forge-game/src/main/java/forge/game/cost/CostUntap.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityActivateAbilityAsIfHaste.java
- forge-gui/res/cardsfolder/t/thousand_year_elixir.txt
- forge-gui/res/cardsfolder/upcoming/dynaheir_invoker_adept.txt
> CLB: Dynaheir, Inovker Adept and support (kills another non-keyword keyword)

- pom.xml
> Further update references to the git repo in pom.xml

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
I noticed all these triggers always being checked for every spell cast.
Seems to work fine with this limiting
> Add some missing TriggerZones

- forge-core/src/main/java/forge/card/CardRules.java
- forge-core/src/main/java/forge/deck/DeckFormat.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-gui/res/cardsfolder/upcoming/alora_merry_thief.txt
- forge-gui/res/cardsfolder/upcoming/cloakwood_hermit.txt
- forge-gui/res/cardsfolder/upcoming/halsin_emerald_archdruid.txt
- forge-gui/res/cardsfolder/upcoming/livaan_cultist_of_tiamat.txt
- forge-gui/res/cardsfolder/upcoming/master_chef.txt
- forge-gui/res/cardsfolder/upcoming/raised_by_giants.txt
- forge-gui/res/cardsfolder/upcoming/shameless_charlatan.txt
- forge-gui/res/lists/TypeLists.txt
- closes #535 
- closes #529 
- closes #530 
- closes #534 
- closes #531 
- closes #527 
- closes #526 
- closes #251
> CLB: Background mechanic and related cards

- forge-ai/src/main/java/forge/ai/ability/ImmediateTriggerAi.java
- forge-gui/res/cardsfolder/a/ajanis_comrade.txt
- forge-gui/res/cardsfolder/c/cemetery_desecrator.txt
1. AI plays first trigger now, even if nothing to target yet
2. give AI Birds of Paradise = it doesn't pay
3. give yourself Birds of Paradise = ai pays
Closes #578
> Fix AI not playing or confirming bad ImmediateTrigger

- forge-gui/res/cardsfolder/m/myrkul_lord_of_bones.txt
May require updates to CopyPermanentEffect as well
> myrkul_lord_of_bones.txt - copy card as it was in graveyard

- forge-gui/res/cardsfolder/h/hama_pashar_ruin_seeker.txt
- forge-gui/res/cardsfolder/upcoming/acolyte_of_bahamut.txt
- forge-gui/res/cardsfolder/upcoming/agent_of_the_iron_throne.txt
- forge-gui/res/cardsfolder/upcoming/candlekeep_sage.txt
- forge-gui/res/cardsfolder/upcoming/dungeon_delver.txt
- forge-gui/res/cardsfolder/upcoming/far_traveler.txt
- forge-gui/res/cardsfolder/upcoming/scion_of_halaster.txt
- closes #579
- closes #580 
- closes #581 
- closes #583 
- closes #596 
- closes #597
> CLB: Background type cards (30 May)

- forge-gui/res/cardsfolder/upcoming/abdel_adrian_gorions_ward.txt
- forge-gui/res/cardsfolder/upcoming/amber_gristle_omaul.txt
- forge-gui/res/cardsfolder/upcoming/erinis_gloom_stalker.txt
- forge-gui/res/cardsfolder/upcoming/faceless_one.txt
- forge-gui/res/cardsfolder/upcoming/gale_waterdeep_prodigy.txt
- closes #599 
- closes #606 
- closes #598 
- closes #605 
- closes #608
> CLB: Choose a Background cards (31 May)

- forge-game/src/main/java/forge/game/GlobalRuleChange.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCombatDamageToughness.java
- forge-gui/res/cardsfolder/a/ancient_lumberknot.txt
- forge-gui/res/cardsfolder/a/arcades_the_strategist.txt
- forge-gui/res/cardsfolder/a/assault_formation.txt
- forge-gui/res/cardsfolder/b/belligerent_brontodon.txt
- forge-gui/res/cardsfolder/d/doran_the_siege_tower.txt
- forge-gui/res/cardsfolder/e/e_honda_sumo_champion.txt
- forge-gui/res/cardsfolder/g/gauntlets_of_light.txt
- forge-gui/res/cardsfolder/h/high_alert.txt
- forge-gui/res/cardsfolder/h/huatli_the_suns_heart.txt
- forge-gui/res/cardsfolder/s/solid_footing.txt
- forge-gui/res/cardsfolder/t/the_great_forest.txt
- forge-gui/res/cardsfolder/t/treefolk_umbra.txt
- forge-gui/res/cardsfolder/upcoming/rasaad_yn_bashir.txt
- forge-gui/res/cardsfolder/w/weight_advantage.txt
closes #560 
needs #502 and maybe #532
> CLB: Rasaad yn Bashir and support ("combat damage from toughness" non-keyword keyword -> static)

- forge-game/src/main/java/forge/game/card/CardDamageMap.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamageAll.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamageDealtOnce.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamageDoneOnce.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamageDoneOnceByController.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamagePrevented.java
- forge-game/src/main/java/forge/game/trigger/TriggerType.java
For #502 and the The Initiative
> TriggerDamageDoneOnceByController

- forge-gui-mobile/src/forge/adventure/scene/StartScene.java
- forge-gui-mobile/src/forge/adventure/stage/MapSprite.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldBackground.java
- forge-gui-mobile/src/forge/assets/FSkinFont.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- forge-gui/res/adventure/Shandalar/ui/start_menu_portrait.json
-refactor some collection for FSkinFont & ImageCache
> Fix Continue button

- forge-core/src/main/java/forge/card/CardType.java
- forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
- forge-gui/res/lists/TypeLists.txt
- forge-gui/src/main/java/forge/model/FModel.java
adds Undercity as  as Dungeon SubType
adds some checks so Instant Token can't be created
> CardType: add Dungeon SubTypes

- forge-gui/res/cardsfolder/a/anje_maid_of_dishonor.txt
- forge-gui/res/cardsfolder/c/citanul_hierophants.txt
- forge-gui/res/cardsfolder/g/goldspan_dragon.txt
- forge-gui/res/cardsfolder/upcoming/ganax_astral_hunter.txt
- forge-gui/res/cardsfolder/upcoming/gut_true_soul_zealot.txt
- forge-gui/res/cardsfolder/upcoming/jaheira_friend_of_the_forest.txt
- forge-gui/res/cardsfolder/upcoming/karlach_fury_of_avernus.txt
- forge-gui/res/cardsfolder/upcoming/laezel_vlaakiths_champion.txt
- forge-gui/res/lists/TypeLists.txt
- forge-gui/res/tokenscripts/b_4_1_skeleton_menace.txt
Nothing too crazy here, I think!
- closes #609 
- closes #613 
- closes #629 
- closes #631 
- closes #630
> CLB: 5 more "Choose a Background" legends

- forge-gui/res/cardsfolder/rebalanced/a-goldspan_dragon.txt
This brings the rebalanced script of Goldspan Dragon in line with the change in #632
> Update A-Goldspan Dragon

- forge-gui/res/cardsfolder/e/etrata_the_silencer.txt
- forge-gui/res/cardsfolder/m/mari_the_killing_quill.txt
- forge-gui/res/cardsfolder/upcoming/avenging_hunter.txt
- forge-gui/res/cardsfolder/upcoming/bloodboil_sorceror.txt
- forge-gui/res/cardsfolder/upcoming/caves_of_chaos_adventurer.txt
- forge-gui/res/cardsfolder/upcoming/explore_the_underdark.txt
- forge-gui/res/cardsfolder/upcoming/feywild_caretaker.txt
- forge-gui/res/cardsfolder/upcoming/goliath_paladin.txt
- forge-gui/res/cardsfolder/upcoming/imoen_mystic_trickster.txt
- forge-gui/res/cardsfolder/upcoming/ravenloft_adventurer.txt
- forge-gui/res/cardsfolder/upcoming/safana_calimport.cutthroat.txt
- forge-gui/res/cardsfolder/upcoming/stirring_bard.txt
- forge-gui/res/cardsfolder/upcoming/tomb_of_horrors_adventurer.txt
- forge-gui/res/cardsfolder/upcoming/trailblazers_torch.txt
- forge-gui/res/cardsfolder/upcoming/underdark_explorer.txt
- forge-gui/res/cardsfolder/upcoming/undermountain_adventurer.txt
- forge-gui/res/cardsfolder/upcoming/vicious_battlerager.txt
- forge-gui/res/cardsfolder/upcoming/white_plume_adventurer.txt
needs #502 before merging
- closes #533 
- closes #547 
- closes #546 
- closes #545 
- closes #549
- closes #551
- closes #548
- closes #553
- closes #554
- closes #557
- closes #552
- closes #550
- closes #558 
- closes #573 
- closes #572 
- closes #571
> CLB: remaining initiative cards (until they add more anyway)

- forge-ai/src/main/java/forge/ai/SpellApiToAi.java
- forge-core/src/main/java/forge/card/CardRules.java
- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/ApiType.java
- forge-game/src/main/java/forge/game/ability/effects/BecomeMonarchEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RestartGameEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TakeInitiativeEffect.java
- forge-game/src/main/java/forge/game/ability/effects/VentureEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/PlayerProperty.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamageDoneOnce.java
- forge-game/src/main/java/forge/game/trigger/TriggerTakesInitiative.java
- forge-game/src/main/java/forge/game/trigger/TriggerType.java
- forge-gui/res/cardsfolder/upcoming/aarakocra_sneak.txt
- forge-gui/res/cardsfolder/upcoming/dungeoneers_pack.txt
- forge-gui/res/cardsfolder/upcoming/passageway_seer.txt
- forge-gui/res/cardsfolder/upcoming/rilsa_rael_kingpin.txt
- forge-gui/res/cardsfolder/upcoming/undercellar_sweep.txt
- forge-gui/res/cardsfolder/upcoming/undercity.txt
- forge-gui/res/tokenscripts/b_4_1_skeleton_menace.txt
- closes #252 
- closes #254 
- closes #503 
- closes #515 
- closes #516 
- closes #522
- closes #559 (required some more mechanics)
> CLB: Initiative and Undercity

- forge-game/src/main/java/forge/game/ability/effects/CountersPutAllEffect.java
- forge-gui/res/cardsfolder/b/breath_of_the_sleepless.txt
- forge-gui/res/cardsfolder/upcoming/fang_dragon_forktail_sweep.txt
- forge-gui/res/cardsfolder/upcoming/feywild_visitor.txt
- forge-gui/res/cardsfolder/upcoming/lulu_loyal_hollyphant.txt
- forge-gui/res/cardsfolder/upcoming/renari_merchant_of_marvels.txt
- forge-gui/res/cardsfolder/upcoming/scion_of_halaster.txt
- closes #521 
- closes #639 
- closes #640 
- closes #556 
also some minor fixes and typos and a default for CountersPutAllEffect "CounterNum"
> CLB: 10 June

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-gui/res/cardsfolder/upcoming/sarevok_deathbringer.txt
Thanks @tool4ever for the idea on how to wire this up
- closes #641
> CLB: Sarevok, Deathbringer and support

- forge-gui-mobile/src/forge/Forge.java
in case splashscreen is null during resume
> [mobile] default startup

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-gui/res/cardsfolder/upcoming/scion_of_halaster.txt
So apparently there were multiple things wrong with the replacement effect that I managed to miss in testing 😩 
Seems like `PlayerCountYou` should work, but it doesn't. 🤷‍♂️
> Scion of Halaster fix better

- forge-game/src/main/java/forge/game/player/Player.java
> Player: fix Commander Effect

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
-should fix stuck card background on RewardScene
> clear holdToolTip

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- add touch listener for RewardActor for android
> clear generated rewards

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/upcoming/master_chef.txt
Partly #668
this fixes the trigger part for ETB counter
> GameAction: fix timestamp and trigger for etb

- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
-fix Garth One-Eye activated ability crash
> refactor check

- forge-gui/res/cardsfolder/l/lupine_harbingers.txt
Doesn't feel super clean, but then again this one is Alchemy only so it's not like we have proper rules to explain it. So sorry not sorry? :P
> Fix Lupine Harbingers

- forge-gui/src/main/java/forge/deck/DeckgenUtil.java
- additional check for canBePartnerCommander
> update check for generateRandomCommanderDeck

- forge-game/src/main/java/forge/game/GameAction.java
> Fix controllerChangeZoneCorrection being applied during LKI checks

- forge-gui-mobile/src/forge/deck/FDeckChooser.java
fix crash when duplicating Commander decks
> fix duplicate deck storage

- forge-core/src/main/java/forge/util/Localizer.java
- forge-game/src/main/java/forge/game/GameRules.java
- forge-game/src/main/java/forge/game/GameType.java
- forge-gui-mobile/src/forge/screens/constructed/LobbyScreen.java
- forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java
- forge-gui/src/main/java/forge/localinstance/properties/PreferencesStore.java
- apply last used variants on LobbyScreen on startup
closes #627
> [Mobile] Update LobbyScreen variants

- forge-gui/res/cardsfolder/upcoming/druid_of_the_emerald_grove.txt
- forge-gui/res/cardsfolder/upcoming/earthquake_dragon.txt
- forge-gui/res/cardsfolder/upcoming/elturel_survivors.txt
- forge-gui/res/cardsfolder/upcoming/endless_evil.txt
- forge-gui/res/cardsfolder/upcoming/owlbear_shepherd.txt
-closes #693
-closes #742
-closes #752
-closes #755 
-closes #756
> 5squeecards

- forge-gui-mobile/src/forge/screens/constructed/LobbyScreen.java
- forge-gui-mobile/src/forge/screens/constructed/PlayerPanel.java
- forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java
- sort initialize method by last used variant on startup
> PlayerPanel sort by variant

- forge-gui/res/cardsfolder/upcoming/duke_ulder_ravenguard.txt
> CLD Duke Ulder Ravenguard

- forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
- forge-gui/res/adventure/Shandalar/sprites/items.atlas
* Fixed gold display on SpellSmithScene.java.
* Added Spirit Guard icon.
> Adventure mode - Adjustments

- forge-gui/res/cardsfolder/upcoming/ghastly_death_tyrant.txt
> CLB Ghastly Death Tyrant

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/Double Masters 2022.txt
> 2X2 Booster Draft

- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-gui/res/cardsfolder/s/scheming_fence.txt
- forge-gui/res/cardsfolder/upcoming/ghost_lantern_bind_spirit.txt
- forge-gui/res/cardsfolder/upcoming/githzerai_monk.txt
- forge-gui/res/cardsfolder/upcoming/green_slime.txt
- forge-gui/res/cardsfolder/upcoming/grell_philosopher.txt
- forge-gui/res/cardsfolder/upcoming/hammers_of_moradin.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
-closes #804 
-closes #544 
-closes #805 
-closes #806 
-closes #866
> 5moresqueecards

- forge-gui/res/cardsfolder/upcoming/banishment.txt
- forge-gui/res/cardsfolder/upcoming/wyll_blade_of_frontiers.txt
> CLB Banishment&Wyll Blade of Frontiers

- forge-gui/res/cardsfolder/rebalanced/a-baba_lysaga_night_witch.txt
- forge-gui/res/cardsfolder/rebalanced/a-earthquake_dragon.txt
- forge-gui/res/cardsfolder/rebalanced/a-minsc_boo_timeless_heroes.txt
- forge-gui/res/cardsfolder/rebalanced/a-monster_manual_zoological_study.txt
4 rebalanced cards from HBG (also -closes #760)
> HBG Rebalanced cards

- forge-gui/res/cardsfolder/upcoming/flaming_fist_officer.txt
- forge-gui/res/cardsfolder/upcoming/vogar_necropolis_tyrant.txt
- forge-gui/res/cardsfolder/upcoming/zamriel_seraph_of_steel.txt
> 2 GN cards 1 CLB card

- forge-game/src/main/java/forge/game/ability/effects/TokenEffect.java
The other work is now covered in #622
> TokenEffect getStackDescription enhancement (for Indulge // Excess)

- forge-gui/res/cardsfolder/upcoming/mold_folk.txt
- forge-gui/res/cardsfolder/upcoming/shadowheart_dark_justiciar.txt
- forge-gui/res/cardsfolder/upcoming/sivriss_nightmare_speaker.txt
- forge-gui/res/cardsfolder/upcoming/skanos_dragonheart.txt
- closes #708 
- closes #707 
- closes #709
> CLB: 3 July

- forge-gui/res/cardsfolder/upcoming/mirror_of_life_trapping.txt
> Add Mirror of Life Trapping

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/combat/AttackConstraints.java
- forge-game/src/main/java/forge/game/combat/AttackRequirement.java
- forge-game/src/main/java/forge/game/combat/GlobalAttackRestrictions.java
- forge-gui/res/cardsfolder/upcoming/firkraag_cunning_instigator.txt
A good start...
What other situations should be considered?
I know Trove of Temptation is lurking... I wonder if there is some way to refactor that keyword into the new MustAttack Static.
Closes #850
> CLB: Firkraag, Cunning Instigator and support

- forge-gui/res/cardsfolder/upcoming/bane_lord_of_darkness.txt
My first PR. Please don't hesitate to let me know how to improve upon it. Thanks!
> Card script for CLB - Bane Lord of Darkness

- forge-game/src/main/java/forge/game/trigger/TriggerAbilityTriggered.java
- forge-gui/res/cardsfolder/upcoming/aboleth_spawn.txt
- Wrote the card script for Aboleth Spawn
- Added 'TriggeredOwnAbility$' to TriggerAbilityTriggered following discussion [here](https://discord.com/channels/267367946135928833/402524622958100501/993591790231896196) regarding the need to provide specific functionality for this card.
> Card script for CLB - Aboleth Spawn and modifications to TriggerAbilityTriggered to make it work.

- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/d/domri_chaos_bringer.txt
- forge-gui/res/cardsfolder/g/generator_servant.txt
- forge-gui/res/cardsfolder/h/hall_of_the_bandit_lord.txt
- forge-gui/res/cardsfolder/upcoming/carnelian_orb_of_dragonkind.txt
Thanks @paulsnoops for the script
The engine stuff is probably more future-proofing than absolutely necessary at this moment, but I think it's fairly non-invasive
- closes #822
> CLB: Carnelian Orb of Dragonkind and support

- forge-gui/res/cardsfolder/rebalanced/a-armory_veteran.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_ceaseless_torment.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_dark_duress.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_deaths_legion.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_inner_weakness.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_mages_doom.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_noxious_nightmares.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_scoured_thoughts.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_syphoned_breath.txt
- forge-gui/res/cardsfolder/upcoming/hag_of_twisted_visions.txt
- forge-gui/res/cardsfolder/upcoming/the_hourglass_coven.txt
- forge-gui/res/editions/Warhammer 40,000.txt
> (YCLB) The Hourglass Coven and spellbook cards

- forge-gui/res/cardsfolder/upcoming/bonecaller_cleric.txt
- forge-gui/res/cardsfolder/upcoming/carefree_swinemaster.txt
- forge-gui/res/cardsfolder/upcoming/chain_devil.txt
closes [#823](https://github.com/Card-Forge/forge/issues/823)
closes [#816](https://github.com/Card-Forge/forge/issues/816)
closes [#821](https://github.com/Card-Forge/forge/issues/821)
> 3 CLB cards

- forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
Not sure how these got commented out, but obviously they broke the effect.
Since this is a simple hotfix, I'm pushing it through.
> DraftEffect fix bad comment lines

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/staticability/StaticAbility.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-game/src/main/java/forge/game/trigger/TriggerScry.java
- forge-gui/res/cardsfolder/upcoming/elminster.txt
- forge-gui/res/lists/TypeLists.txt
This one was fun.
- seems like Scry trigger needed to track ScryNum to make the big trigger work... not too hard to imagine more like this in future
- had fun adding a little parenthetical to the description on the static in the effect:
- needed a little tweak to make DigEffect getStackDesc more logical
- closes #395
> CLB: Elminster and support

- forge-gui/res/cardsfolder/upcoming/moonshae_pixie.txt
- forge-gui/res/cardsfolder/upcoming/myrkuls_edict.txt
> Moonshae Pixie & Myrkul's Edict

- Wilson Refined Grizzly.txt
> Card Script for Wilson, Refined Grizzly

- forge-gui-mobile/src/forge/assets/ImageCache.java
- forge-gui-mobile/src/forge/card/CardRenderer.java
-use the Queue as reference for removing old entries on the AssetManager
-fix cardArtCache storing forgeArt, should fix missing cardArt
> add EvictingQueue for loaded images

- Blur.txt
- forge-gui/res/cardsfolder/upcoming/blur.txt
> Card Script for Blur

- forge-game/src/main/java/forge/game/card/CardZoneTable.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/trigger/TriggerMilledAll.java
- forge-game/src/main/java/forge/game/trigger/TriggerType.java
> TriggerMilledAll (for Zellix [CLB])

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardDamageMap.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-gui/res/cardsfolder/upcoming/elminster.txt
- forge-gui/res/cardsfolder/upcoming/zangief_the_red_cyclone.txt
Seems to work fine, but might want to do your own tests just to be sure!
> Northmocs Zangief and support, round two

- forge-gui/res/cardsfolder/upcoming/earth_tremor.txt
- forge-gui/res/cardsfolder/upcoming/patron_of_the_arts.txt
> 2 more CLB cards

- forge-game/src/main/java/forge/game/ability/effects/ChooseCardEffect.java
- forge-gui/res/cardsfolder/upcoming/stick_together.txt
> CLB: Stick Together and support

- forge-gui/res/cardsfolder/upcoming/minthara_merciless_soul.txt
> CLB Minthara Merciless Soul

- forge-gui/res/cardsfolder/a/aerial_predation.txt
- forge-gui/res/cardsfolder/c/cathedral_sanctifier.txt
- forge-gui/res/cardsfolder/e/ephemerate.txt
> Fix typos/add AI

- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-gui/res/cardsfolder/upcoming/colossal_badger_dig_deep.txt
- forge-gui/res/cardsfolder/upcoming/ettercap_web_shot.txt
- forge-gui/res/cardsfolder/upcoming/gray_slaad_entropic_decay.txt
- forge-gui/res/cardsfolder/upcoming/guardian_naga_banishing_coils.txt
- forge-gui/res/cardsfolder/upcoming/hezrou_demonic_stench.txt
- forge-gui/res/cardsfolder/upcoming/pegasus_guardian_rescue_the_foal.txt
- forge-gui/res/cardsfolder/upcoming/sword_coast_serpent_capsizing_wave.txt
- closes #830 
-- did a bit of tweaking to CountersPutEffect.getStackDescription to better handle stuff like Dig Deep
- closes #848 
- closes #861 
- closes #863 
- closes #870 
- closes #922 
- closes #952
> CLB Adventure commons

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkin.java
- forge-gui-mobile/src/forge/assets/FSkinTexture.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- forge-gui-mobile/src/forge/deck/FDeckChooser.java
- forge-gui-mobile/src/forge/screens/LoadingOverlay.java
- forge-gui-mobile/src/forge/screens/constructed/LobbyScreen.java
- forge-gui-mobile/src/forge/screens/gauntlet/LoadGauntletScreen.java
- forge-gui-mobile/src/forge/screens/home/puzzle/PuzzleScreen.java
- forge-gui-mobile/src/forge/screens/limited/LoadDraftScreen.java
- forge-gui-mobile/src/forge/screens/limited/LoadSealedScreen.java
- forge-gui-mobile/src/forge/screens/limited/NewDraftScreen.java
- forge-gui-mobile/src/forge/screens/online/OnlineLobbyScreen.java
- forge-gui-mobile/src/forge/screens/planarconquest/ConquestMenu.java
- forge-gui-mobile/src/forge/screens/planarconquest/ConquestMultiverseScreen.java
- forge-gui-mobile/src/forge/screens/planarconquest/NewConquestScreen.java
- forge-gui-mobile/src/forge/screens/quest/NewQuestScreen.java
- forge-gui-mobile/src/forge/screens/quest/QuestDuelsScreen.java
- forge-gui-mobile/src/forge/screens/quest/QuestLaunchScreen.java
- forge-gui-mobile/src/forge/screens/quest/QuestMenu.java
- forge-gui-mobile/src/forge/screens/quest/QuestSpellShopScreen.java
- forge-gui-mobile/src/forge/screens/quest/QuestTournamentsScreen.java
- add seperate set to determine cards loaded
> use single assetmanager

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/SetStateEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/upcoming/illithid_harvester_plant_tadpoles.txt
- closes #253 
@Hanmac your notes in the issue were very helpful - thanks
> CLB: Illithid Harvester // Plant Tadpoles and support

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/assets/FSkinFont.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- update some variables, prevent NPE on font reload
> update ImageCache check

- forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
- forge-gui/res/cardsfolder/upcoming/battle_angels_of_tyr.txt
- forge-gui/res/cardsfolder/upcoming/neera_wild_mage.txt
> CLB: Battle Angels of Tyr + Neera, Wild Mage

- forge-core/src/main/java/forge/ImageKeys.java
- forge-core/src/main/java/forge/util/ThreadUtil.java
- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/Graphics.java
- forge-gui-mobile/src/forge/card/CardImageRenderer.java
- forge-gui/src/main/java/forge/util/ImageFetcher.java
- add stretchedArt for class/saga/dungeon
- update setlookup and Imagefetcher
- prevent NPE on resumed state
> stretchedArt for saga/class/dungeon, prevent NPE

- forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
- forge-gui/res/cardsfolder/upcoming/iron_mastiff.txt
I added "UseHighestRoll" to RollDiceEffect and wrote the card script Iron Mastiff (which requires UseHighestRoll).
-closes #877
> CardScript for Iron Mastiff and changes to RollDiceEffect

- forge-gui-mobile/src/forge/assets/FSkin.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
> Support for preferred Skin sleeves

- forge-gui/res/cardsfolder/upcoming/astral_dragon.txt
- forge-gui/res/cardsfolder/upcoming/ingenious_artillerist.txt
- forge-gui/res/cardsfolder/upcoming/jade_orb_of_dragonkind.txt
- forge-gui/res/cardsfolder/upcoming/marut.txt
- forge-gui/res/cardsfolder/upcoming/street_urchin.txt
- closes #811 
- closes #878 
- closes #808 
- closes #949 
- closes #807
> CLB: 9 July

- forge-game/src/main/java/forge/game/ability/effects/AnimateEffect.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/b/boreal_outrider.txt
- forge-gui/res/cardsfolder/o/olivia_crimson_bride.txt
> Fix multiple state trigger

- forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
- forge-gui-mobile/src/forge/adventure/scene/StartScene.java
- forge-gui-mobile/src/forge/adventure/scene/TileMapScene.java
If you save from a town, make sure to restore the town as the current scene
> Allow saving from towns.

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/card/CardZoneTable.java
Not sure if you wanted something bigger, but this seems to work for now...
My test case looks like this:
Exiling one Elf each, Bess now only triggers once.
Closes #1107
> Simultaneous untilHostLeavesPlay trigger

- forge-game/src/main/java/forge/game/ability/effects/DestroyEffect.java
- forge-gui/res/cardsfolder/upcoming/tabaxi_toucaneers.txt
- forge-gui/res/cardsfolder/upcoming/taunting_kobold.txt
- forge-gui/res/cardsfolder/upcoming/the_council_of_four.txt
- forge-gui/res/cardsfolder/upcoming/thunderwave.txt
- forge-gui/res/cardsfolder/upcoming/tiamats_fanatics.txt
- forge-gui/res/cardsfolder/upcoming/uchuulon.txt
- forge-gui/res/cardsfolder/upcoming/undercellar_myconid.txt
- forge-gui/res/cardsfolder/upcoming/vexing_puzzlebox.txt
- forge-gui/res/cardsfolder/upcoming/vrock.txt
- forge-gui/res/cardsfolder/upcoming/warehouse_thief.txt
- forge-gui/res/cardsfolder/upcoming/wild_magic_surge.txt
- forge-gui/res/cardsfolder/upcoming/winter_eladrin.txt
- forge-gui/res/cardsfolder/upcoming/wyrms_crossing_patrol.txt
- forge-gui/res/cardsfolder/upcoming/you_look_upon_the_tarrasque.txt
- forge-gui/res/cardsfolder/upcoming/your_temple_is_under_attack.txt
- forge-gui/res/cardsfolder/upcoming/youre_confronted_by_robbers.txt
- forge-gui/res/cardsfolder/upcoming/youve_been_caught_stealing.txt
- closes #976
- closes #977
- closes #978
- closes #979
- closes #695 
- closes #975 
- closes #972 
- closes #971 
- closes #970
- closes #967 
- closes #966
- closes #965 
- closes #961
- closes #958
- closes #956
- closes #954
- closes #953
> some CLB cards

- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-gui/res/cardsfolder/upcoming/nalfeshnee.txt
> CLB: Nalfeshnee & support

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/g/grixis_battlemage.txt
- forge-gui/res/cardsfolder/t/thallid.txt
- forge-gui/res/cardsfolder/upcoming/cut_a_deal.txt
- forge-gui/res/cardsfolder/upcoming/death_kiss.txt
- forge-gui/res/cardsfolder/upcoming/descent_into_avernus.txt
- forge-gui/res/cardsfolder/upcoming/dire_mimic.txt
- forge-gui/res/cardsfolder/upcoming/dragonborn_looter.txt
- closes #835 
- closes #836 
- closes #838 
- closes #839 
- closes #842
> CLB - 22 Jul

- forge-gui/res/cardsfolder/upcoming/mystery_key.txt
- forge-gui/res/cardsfolder/upcoming/nothic.txt
- forge-gui/res/cardsfolder/upcoming/oceanus_dragon.txt
- forge-gui/res/cardsfolder/upcoming/overwhelming_encounter.txt
- forge-gui/res/cardsfolder/upcoming/recruitment_drive.txt
- closes #904 
- closes #913 
- closes #915 
- closes #914 
- closes #929
> some CLB cards..

- forge-gui/res/cardsfolder/upcoming/journey_to_the_lost_city.txt
- forge-gui/res/cardsfolder/upcoming/laezels_acrobatics.txt
- forge-gui/res/cardsfolder/upcoming/loot_dispute.txt
- forge-gui/res/cardsfolder/upcoming/majestic_genesis.txt
- forge-gui/res/cardsfolder/upcoming/modify_memory.txt
- closes #882 
- closes #887 
- closes #890 
- closes #892 
- closes #898
> CLB - 22 Jul (even more)

- forge-gui/res/cardsfolder/s/selvalas_charge.txt
- forge-gui/res/cardsfolder/upcoming/nautiloid_ship.txt
- forge-gui/res/cardsfolder/upcoming/nefarious_imp.txt
- forge-gui/res/cardsfolder/upcoming/nimbleclaw_adept.txt
- forge-gui/res/cardsfolder/upcoming/owlbear_cub.txt
- forge-gui/res/cardsfolder/upcoming/pack_attack.txt
- closes #907 
- closes #909 
- closes #910 
- closes #916 
- closes #917
> CLB - 23 Jul (more)

- forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/PlayerFactoryUtil.java
- forge-gui/res/cardsfolder/e/eon_frolicker.txt
- forge-gui/res/cardsfolder/upcoming/noble_heritage.txt
> Protection from player display updates (CLB Noble Heritage)

- forge-gui/res/cardsfolder/upcoming/from_the_catacombs.txt
- forge-gui/res/cardsfolder/upcoming/guildsworn_prowler.txt
- forge-gui/res/cardsfolder/upcoming/horn_of_valhalla_ysgards_call.txt
- forge-gui/res/cardsfolder/upcoming/inspiring_leader.txt
- forge-gui/res/cardsfolder/upcoming/intellect_devourer.txt
- forge-gui/res/cardsfolder/upcoming/nalfeshnee.txt
- closes #856 
- closes #865 
- closes #871 
- closes #874 
- closes #876
> CLB - 23 Jul

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/b/barrowin_of_clan_undurr.txt
- forge-gui/res/cardsfolder/upcoming/drillworks_mole.txt
- forge-gui/res/cardsfolder/upcoming/druidic_ritual.txt
- forge-gui/res/cardsfolder/upcoming/emerald_dragon_dissonant_wave.txt
- forge-gui/res/cardsfolder/upcoming/flaming_fist.txt
- forge-gui/res/cardsfolder/upcoming/fraying_line.txt
- forge-gui/res/languages/en-US.properties
- closes #843 
- closes #844 (ended up needing tweaks to ChangeZoneEffect)
- closes #847 
- closes #851 
- closes #855
> CLB - 22 Jul (more)

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TwoPilesEffect.java
- forge-game/src/main/java/forge/game/trigger/Trigger.java
- forge-gui/res/cardsfolder/c/chimney_goyf.txt
- forge-gui/res/cardsfolder/c/chimney_imp.txt
- forge-gui/res/cardsfolder/c/chittering_rats.txt
- forge-gui/res/cardsfolder/e/emergent_ultimatum.txt
- forge-gui/res/cardsfolder/g/guided_passage.txt
- forge-gui/res/cardsfolder/p/prying_questions.txt
This fixes some "an opponent chooses" cards not giving you a choice for which one in multiplayer.
@Northmoc
already putting your EACH to good use!
> Fix Chooser$ defaults & Evolve for non-creatures

- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- fetched images online should update and appear immediately after download on Adventure mode on RewardScene (Shop, Loot)
> refactor RewardActor 

- forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
- forge-gui/res/cardsfolder/d/demonlord_belzenlok.txt
- forge-gui/res/cardsfolder/e/eldrazi_obligator.txt
- forge-gui/res/cardsfolder/i/illuna_apex_of_wishes.txt
- forge-gui/res/cardsfolder/u/undying_flames.txt
- forge-gui/res/cardsfolder/upcoming/sarevoks_tome.txt
> Sarevok's Tome (CLB) and related tweaks

- forge-game/src/main/java/forge/game/ability/effects/ChangeCombatantsEffect.java
- forge-gui/res/cardsfolder/p/portal_mage.txt
- forge-gui/res/cardsfolder/upcoming/windshaper_planetar.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
> CLB: Windshaper Planetar and support

- forge-game/src/main/java/forge/game/GameEntityCounterTable.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/ability/effects/GoadEffect.java
- forge-gui/res/cardsfolder/a/agitator_ant.txt
- forge-gui/res/cardsfolder/upcoming/spectacular_showdown.txt
> CLB: Spectacular Showdown and support

- forge-adventure/pom.xml
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkin.java
- forge-gui-mobile/src/forge/assets/FSkinImage.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- should fix the issue of not loading the images downloaded. This method should get directly from the assetmanager.
> fix onfetched for RewardActor

- forge-gui/res/cardsfolder/upcoming/two_handed_axe_sweeping_cleave.txt
- forge-gui/res/cardsfolder/upcoming/viconia_drow_apostate.txt
Last few unclaimed cards (other than Volo who will get his own PR)
- closes #964 
- closes #968
> CLB: 26 Jul (more)

- forge-ai/src/main/java/forge/ai/AiBlockController.java
This refactor removes some redundant calls (either fully identical or logic-wise result couldn't worsen) to `ComputerUtilCombat.lifeInDanger`, which would often run many further checks as its complexity depends a lot on size of boardstate:
1. In the main `assignBlockers`
- For entering the second approach the global boolean can be trusted unless `removeUnpayableBlocks` made a modification
- In the third approach avoid another one when the first If was already false
2. In `makeChumpBlocks` each when returning to the current approach
- Make first test when entering recursion actually possible to fail
- modify boolean directly, saves two more
3. In `makeChumpBlocksToSavePW`
4. In `makeTradeBlocks` the test can only ever be true if the boolean was also to begin with
Not all of them would have …
> AiBlockController: Performance

- forge-gui-mobile/src/forge/FrameRate.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui/res/easystarterdecks/Azorius.dck
- forge-gui/res/easystarterdecks/Boros.dck
- forge-gui/res/easystarterdecks/Dimir.dck
- forge-gui/res/easystarterdecks/Golgari.dck
- forge-gui/res/easystarterdecks/Gruul.dck
- forge-gui/res/easystarterdecks/Izzet.dck
- forge-gui/res/easystarterdecks/Mono Black.dck
- forge-gui/res/easystarterdecks/Mono Blue.dck
- forge-gui/res/easystarterdecks/Mono Green.dck
- forge-gui/res/easystarterdecks/Mono Red.dck
- forge-gui/res/easystarterdecks/Mono White.dck
- forge-gui/res/easystarterdecks/Orzhov.dck
- forge-gui/res/easystarterdecks/Rakdos.dck
- forge-gui/res/easystarterdecks/Selesnya.dck
- forge-gui/res/easystarterdecks/Simic.dck
compute the probable Texture usage
> fix memory tracking computation

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/DeckSelectScene.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- forge-gui/src/main/java/forge/deck/DeckProxy.java
- also update coloridentity based on selected deck
- highlight deck text for empty deck
> add switchbutton on HoldTooltip

- forge-core/src/main/java/forge/util/Lang.java
- forge-gui-mobile/src/forge/assets/Assets.java
- also adds probable usage of font texture for the fps display
> fix plural ends with "ds"

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- fix not clearing RewardActor upon exiting scene
- use direct loading from assetmanager to prevent black texture
- clear card textures upon exiting scene to save RAM
> fix some leaks on RewardActor

- forge-gui/src/main/java/forge/util/ImageFetcher.java
> support setlookup on ImageFetcher

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/e/errant_street_artist.txt
- forge-gui/res/cardsfolder/s/second_guess.txt
Card quite bad so probably nobody ever put it in his deck :P
> Fix Second Guess

- forge-gui/src/main/java/forge/player/HumanCostDecision.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
- to show relevant card and fix message title (removing "\n").
> update remaining confirm action for human decision

- forge-adventure/src/main/java/forge/adventure/Main.java
- forge-gui-android/src/forge/app/Main.java
- forge-gui-ios/src/forge/ios/Main.java
- forge-gui-mobile-dev/src/forge/app/Main.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui/src/main/java/forge/interfaces/IDeviceAdapter.java
- to check if the app renders different resolution and update the tooltips size
> get screensize for Android

- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
- forge-ai/src/main/java/forge/ai/ability/TokenAi.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigMultipleEffect.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/keyword/Trample.java
> Minor fixes

- forge-game/src/main/java/forge/game/staticability/StaticAbilityPanharmonicon.java
See also:
https://www.reddit.com/r/mtgrules/comments/vzymg4/veyran_voice_of_duality_whispering_wizard/
> Panharmonicon + "triggers only once"

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui/res/cardsfolder/upcoming/kenku_artificer.txt
also fixes manacost for Kenku Artificer
> minor adjustments

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-game/src/main/java/forge/trackable/TrackableProperty.java
- forge-gui/res/cardsfolder/upcoming/volo_itinerant_scholar.txt
- forge-gui/res/tokenscripts/volos_journal.txt
- forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
> CLB: Volo, Journal, support, etc.

- forge-gui/res/cardsfolder/s/spelldrain_assassin.txt
Hello, first time contributor here 
I've created a script for the card "Spelldrain Assassin" from the New Capenna Alchemy set.
I've tested it out and it worked fine. 
Since i'm new to this sort of thing, some feedback on the code would be welcome :)
-closes #802
> [YSNC] Spelldrain Assassin

- forge-gui/res/cardsfolder/s/syndicate_recruiter.txt
> YSNC Syndicate Recruiter

- forge-gui-mobile/src/forge/adventure/data/SettingData.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
- forge-gui-mobile/src/forge/adventure/util/Config.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- add support for various display aspect ratio
> setting for card display/tooltip on adventure rewards/shops

- forge-gui/res/cardsfolder/l/loose_in_the_park.txt
Card script for the card Loose in the Park from New Capenna Alchemy
https://scryfall.com/card/ysnc/14/loose-in-the-park
-closes #789
> YSNC Loose in the Park

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/assets/ImageCache.java
- needs to clear card art cache when unloading card textures
- minor speedup on startup on selector adventure settings
> fix black texture on card list view

- forge-gui/res/cardsfolder/m/menagerie_curator.txt
> YSNC Menagerie Curator

- forge-gui-mobile/src/forge/adventure/world/World.java
threaded WaveFunctionCollapse usage while generating a new world
> threaded WaveFunctionCollapse 

- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- fix color identity
- service pool is working good on android now so use it on generating map
> reformat code

- forge-gui/res/cardsfolder/upcoming/big_spender.txt
Did this one before last vacation, finally pushing...
- closes #785
> YSNC: big_spender.txt

- forge-gui/res/cardsfolder/a/ana_sanctuary.txt
- forge-gui/res/cardsfolder/c/ceta_sanctuary.txt
- forge-gui/res/cardsfolder/d/dark_temper.txt
- forge-gui/res/cardsfolder/d/dega_sanctuary.txt
- forge-gui/res/cardsfolder/g/gideons_triumph.txt
- forge-gui/res/cardsfolder/h/huatlis_spurring.txt
- forge-gui/res/cardsfolder/j/jaces_triumph.txt
- forge-gui/res/cardsfolder/n/necra_sanctuary.txt
- forge-gui/res/cardsfolder/n/nissas_triumph.txt
- forge-gui/res/cardsfolder/r/raka_sanctuary.txt
- forge-gui/res/cardsfolder/t/tezzerets_simulacrum.txt
- forge-gui/res/cardsfolder/w/winds_of_qal_sisma.txt
> Tidy up some old cards

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
- update colorid selector if chaos mode is chosen
> match color identity for random deck in chaos mode

- forge-gui/res/cardsfolder/w/waylay.txt
> waylay.txt fixup

- forge-ai/src/main/java/forge/ai/ability/ChooseGenericEffectAi.java
- forge-gui/res/cardsfolder/d/distant_memories.txt
- forge-gui/res/cardsfolder/n/nature_demands_an_offering.txt
- forge-gui/res/cardsfolder/s/sin_prodder.txt
> Distant Memories refactor and related

- forge-game/src/main/java/forge/game/staticability/StaticAbilityPanharmonicon.java
- forge-gui/res/cardsfolder/s/spelldrain_assassin.txt
> StaticAbilityPanharmonicon support ValidCause for Wulfgar

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/AddPhaseEffect.java
- forge-game/src/main/java/forge/game/ability/effects/AddTurnEffect.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DelayedTriggerEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ImmediateTriggerEffect.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/trigger/Trigger.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-gui/res/cardsfolder/b/brokers_confluence.txt
- forge-gui/res/cardsfolder/d/disallow.txt
- forge-gui/res/cardsfolder/l/lithoform_engine.txt
- forge-gui/res/cardsfolder/n/nimble_obstructionist.txt
- forge-gui/res/cardsfolder/s/stifle.txt
- forge-gui/res/cardsfolder/s/strionic_resonator.txt
- forge-gui/res/cardsfolder/s/sublime_epiphany.txt
- forge-gui/res/cardsfolder/t/tales_end.txt
- forge-gui/res/cardsfolder/t/trickbind.txt
- forge-gui/res/cardsfolder/upcoming/emerald_dragon_dissonant_wave.txt
- forge-gui/res/cardsfolder/v/voidslime.txt
Closes #1229
@Hanmac 
I couldn't find anything that breaks it yet, but maybe you will :P
> Fix some bugs related to delayed triggers

- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
- should fix crash when encountering doppelganger/copyplayerdeck AI
> revert multiplayer battle

- forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
> reverse check

- forge-gui/res/cardsfolder/k/kumano_faces_kakkazan_etching_of_kumano.txt
- forge-gui/res/cardsfolder/s/savage_summoning.txt
- forge-gui/res/cardsfolder/t/teyo_aegis_adept.txt
- forge-gui/res/cardsfolder/upcoming/brokers_safeguard.txt
- forge-gui/res/cardsfolder/upcoming/diviner_of_fates.txt
> YSNC - 9 Aug

- forge-game/src/main/java/forge/game/ability/effects/AscendEffect.java
- forge-game/src/main/java/forge/game/ability/effects/BondEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
- forge-gui/res/cardsfolder/m/my_laughter_echoes.txt
Closes #725
@Agetian feel free to tweak the Bond Effect AI more
> Bond effect cleanup

- forge-gui/res/cardsfolder/upcoming/choice_of_fortunes.txt
- closes #780 
Last YSNC to be added to a PR!
> YSNC: choice_of_fortunes.txt

- forge-gui-mobile/pom.xml
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
for Font Effects, Styles, etc..
> add TextraTypist

- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
- forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
- forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/CardUtil.java
- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
- add support loading custom starterdeck in adventure mode, custom->starterdecks on user folder before starting Forge. Genetic AI decks is automatically enabled for some enemies.
> Adventure Custom StarterDecks

- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
> show messages for doppelganger if player is using custom decks

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui/res/cardsfolder/t/tome_of_the_infinite.txt
- forge-gui/res/cardsfolder/upcoming/follow_the_tracks.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
Thanks @Simisays for getting the script started and catching the engine issues!
Thanks @Hanmac for pointing out a good solution
> HBG: Follow the Tracks and support

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/PlayerProperty.java
- forge-gui/res/cardsfolder/upcoming/ramses_assassin_lord.txt
> Ramses, Assassin Lord and support

- forge-gui-desktop/src/test/java/forge/card/CardDbCardMockTestCase.java
- forge-gui/res/editions/30th Anniversary History Promos.txt
This enables the failing test to pass for now but I will have to come back to it to fix properly.
> Temporary fix for failing CardDbCardMockTestCase

- forge-gui/res/cardsfolder/upcoming/ayesha_tanaka_armorer.txt
- forge-gui/res/cardsfolder/upcoming/moira_urborg_haunt.txt
- forge-gui/res/cardsfolder/upcoming/obsidian_obelisk.txt
- forge-gui/res/cardsfolder/upcoming/ramses_assassin_lord.txt
- forge-gui/res/cardsfolder/upcoming/tiller_engine.txt
- forge-gui/res/cardsfolder/upcoming/unite_the_coalition.txt
Probably my last PR in a while, to let the reviews catch up.
Obsidian Obelisk
Ayesha Tanaka, Armorer
Moira, Urborg Haunt
Tiller Engine
Unite the Coalition
> DMC 6 More

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
> Fix last state battlefield check on replacement abilities

- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-gui/res/cardsfolder/r/racketeer_boss.txt
Thanks @Simisays for the initial card script
- closes #798
> YSNC: Racketeer Boss

- forge-gui/res/editions/Dominaria United Commander.txt
- forge-gui/res/editions/Dominaria United.txt
DMC cards 49 and 50 are missing right now. Will add them in another PR once I see what they are.
> Update DMU & DMC editions

- forge-gui/res/cardsfolder/upcoming/bortuk_bonerattle.txt
- forge-gui/res/cardsfolder/upcoming/king_darien_xlviii.txt
- forge-gui/res/cardsfolder/upcoming/lagomos_hand_of_hatred.txt
- forge-gui/res/cardsfolder/upcoming/queen_allenal_of_ruadach.txt
- forge-gui/res/cardsfolder/upcoming/sphinx_of_clear_skies.txt
- forge-gui/res/cardsfolder/upcoming/uurg_spawn_of_turg.txt
- forge-gui/res/tokenscripts/r_2_1_elemental_trample_haste.txt
DMU: Add scripts for 6 new DMU cards, plus 1 token
- Bortuk Bonerattle
- King Darien XLVIII
- Lagomos, Hand of Hatred
- Queen Allenal of Ruadach
- Sphinx of Clear Skies
- Uurg, Spawn of Turg
Token:
- 2/1 red Elemental creature with trample and haste
> DMU: Queen Allenal of Ruadach + 5 cards, 1 token

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/GameEntity.java
- forge-game/src/main/java/forge/game/GameEntityCounterTable.java
- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/trigger/TriggerAbilityTriggered.java
- forge-game/src/main/java/forge/game/trigger/TriggerCounterAdded.java
- forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
- forge-gui/res/cardsfolder/upcoming/historians_boon.txt
- forge-gui/res/cardsfolder/upcoming/the_elder_dragon_war.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Close #1353
Close #1414 
Close #1415
This is the first version of "Read ahead" before the CR
i also added "Last Chapter" Flag for `Historian's Boon`
> Read ahead Saga Ability

- forge-gui/res/cardsfolder/upcoming/aether_channeler.txt
- forge-gui/res/cardsfolder/upcoming/cult_conscript.txt
- forge-gui/res/cardsfolder/upcoming/phoenix_chick.txt
- forge-gui/res/cardsfolder/upcoming/urborg_lhurgoyf.txt
- Aether Channeler
- Cult Conscript
- Phoenix Chick
- Urborg Lhurgoyf
> DMU: Implement 4 cards

- forge-gui/res/cardsfolder/upcoming/stangg_echo_warrior.txt
I think it works correctly now
> DMC Stangg Echo Warrior

- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui/res/cardsfolder/b/bone_rattler.txt
- forge-gui/res/cardsfolder/t/time_sidewalk.txt
Cards made by Conjure Alchemy mechanic should not be "token cards"
> delineate playtest "token card" from other MakeCard stuff

- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui/res/cardsfolder/upcoming/viconia_nightsingers_disciple.txt
Only new stuff is MakeCardEffect and Viconia
- closes #762
> HBG: Viconia, Nightsinger's Disciple and support

- forge-core/src/main/java/forge/card/CardEdition.java
- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/Dominaria United.txt
- forge-gui/tools/EditionTracking.py
> DMU Booster Draft

- forge-gui/res/cardsfolder/b/boggart_sprite_chaser.txt
- forge-gui/res/cardsfolder/t/taste_of_paradise.txt
- forge-gui/res/cardsfolder/upcoming/battlewing_mystic.txt
> Tidy up some cards

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityAttackVigilance.java
- forge-gui/res/cardsfolder/j/johan.txt
> Vigilance as StaticAbility for Johan

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/k/kitsune_loreweaver.txt
- forge-gui/res/cardsfolder/p/promise_of_power.txt
- forge-gui/res/cardsfolder/s/sea_gate_restoration_sea_gate_reborn.txt
- forge-gui/res/cardsfolder/upcoming/jon_irenicus_the_exile.txt
Didn't need any engine work after all
- closes #770
> HBG: Jon Irenicus, the Exile

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCastWithFlash.java
- forge-gui/res/cardsfolder/t/timely_ward.txt
- forge-gui/res/cardsfolder/upcoming/silver_scrutiny.txt
> silver_scrutiny.txt w/ support in StaticAbilityCastWithFlash

- forge-gui/res/cardsfolder/upcoming/goblin_picker.txt
- forge-gui/res/cardsfolder/upcoming/haunting_figment.txt
- forge-gui/res/cardsfolder/upcoming/inscribed_tablet.txt
- forge-gui/res/cardsfolder/upcoming/jayas_firenado.txt
- forge-gui/res/cardsfolder/upcoming/join_forces.txt
- forge-gui/res/cardsfolder/upcoming/juniper_order_rootweaver.txt
- forge-gui/res/cardsfolder/upcoming/karns_sylex.txt
- forge-gui/res/cardsfolder/upcoming/nael_avizoa_aeronaut.txt
- forge-gui/res/cardsfolder/upcoming/najal_the_storm_runner.txt
- forge-gui/res/cardsfolder/upcoming/nishoba_brawler.txt
- forge-gui/res/cardsfolder/upcoming/queen_allenal_of_ruadach.txt
- forge-gui/res/cardsfolder/upcoming/rith_liberated_primeval.txt
- forge-gui/res/cardsfolder/upcoming/rosnakht_heir_of_rohgahh.txt
> DMU 10 Cards + 3 card fixes

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-gui/res/cardsfolder/upcoming/gut_fanatical_priestess.txt
- forge-gui/res/cardsfolder/upcoming/rasaad_monk_of_selune.txt
Gut got a bit gnarly
The exiling source is the Effect, not Gut – but obviously Arena wants Gut to be the source here. Think this workaround is OK and may be useful for other stuff in the future?
> HBG: Gut, Fanatical Priestess and support (also Rasaad)

- forge-gui/res/cardsfolder/upcoming/karlach_raging_tiefling.txt
- forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt
- Fix Rasaad, Monk of Selune name
- Remove unneeded Specialize "sides"
- Add Cleanup to Karlach, Tiefling Spellrager
> Small HBG fixes

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
> allow for X=0 Ob Nix casualty corner case

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/upcoming/monstrous_war_leech.txt
> Fix Monstrous War-Leech

- forge-gui/res/cardsfolder/upcoming/klement_novice_acoltye.txt
- forge-gui/res/cardsfolder/upcoming/wyll_pact_bound_duelist.txt
- forge-gui/res/cardsfolder/w/war_falcon.txt
Just a few Specialize "cards"
- closes #758
> HBG: 6 Sep

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
- forge-gui/res/cardsfolder/upcoming/favored_enemy.txt
> HBG: Favored Enemy and support

- forge-gui/res/cardsfolder/upcoming/elvish_hydromancer.txt
- forge-gui/res/cardsfolder/upcoming/joint_exploration.txt
- forge-gui/res/cardsfolder/upcoming/vineshaper_prodigy.txt
DMU: Added card scripts for 3 DMU cards
- Elvish Hydromancer
- Joint Exploration
- Vineshaper Prodigy
> DMU: 3 kicker cards

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/cost/CostReveal.java
- forge-gui/src/main/java/forge/model/FModel.java
Got broken by 5d46763df90502ee78839595e23f4d736f134c27
Closes #1458
> Fix card name sorting ignoring other locale

- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/replacement/ReplaceGainLife.java
- forge-gui/res/cardsfolder/a/archfiend_of_spite.txt
- forge-gui/res/cardsfolder/a/awaken_the_sky_tyrant.txt
- forge-gui/res/cardsfolder/b/baral_chief_of_compliance.txt
- forge-gui/res/cardsfolder/f/farsight_mask.txt
- forge-gui/res/cardsfolder/f/flameblade_angel.txt
- forge-gui/res/cardsfolder/g/guile.txt
- forge-gui/res/cardsfolder/l/lullmage_mentor.txt
- forge-gui/res/cardsfolder/m/michiko_konda_truth_seeker.txt
- forge-gui/res/cardsfolder/r/rain_of_gore.txt
- forge-gui/res/cardsfolder/r/retaliator_griffin.txt
- forge-gui/res/cardsfolder/s/summoning_trap.txt
> This does not apply to life gain caused by combat damage from a creature with lifelink.
> Rain of Gore fix

- forge-gui/res/cardsfolder/h/herald_of_the_forgotten.txt
- forge-gui/res/cardsfolder/upcoming/laezel_githyanki_warrior.txt
- forge-gui/res/cardsfolder/upcoming/vhal_eager_scholar.txt
> HBG: 13 Sep

- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-gui/res/cardsfolder/b/bard_class.txt
- forge-gui/res/cardsfolder/e/edgewalker.txt
- forge-gui/res/cardsfolder/m/morophon_the_boundless.txt
- forge-gui/res/cardsfolder/r/ragemonger.txt
Part for #1519 and maybe the Defilers
> Fix some cost reductions ignoring generic mana

- forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
- forge-game/src/main/java/forge/game/cost/CostTapType.java
- forge-gui/res/cardsfolder/e/elven_bow.txt
- forge-gui/res/cardsfolder/upcoming/and_they_shall_know_no_fear.txt
- forge-gui/res/cardsfolder/upcoming/assault_intercessor.txt
- forge-gui/res/cardsfolder/upcoming/belisarius_cawl.txt
- forge-gui/res/cardsfolder/upcoming/birth_of_the_imperium.txt
some cards and some QoL odds and ends
> 40K: 18 Sep

- forge-game/src/main/java/forge/game/GameAction.java
- forge-gui/res/cardsfolder/upcoming/cryptic_spires.txt
Very simplistic initial approach
You have to re-pick for each copy each game, which could certainly be streamlined
This will allow people to draft the set a bit more realistically though
- closes #731
> 2X2: Cryptic Spires and support

- forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
- fix label color from white to black when overriding the label name
> fix colorlabel color

- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui/res/adventure/Shandalar/ui/items_portrait.json
fixed portrait reward scene
fixed TextraButton.getText with Override
> fixed portrait reward scene and  TextraButton.getText with Override

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-gui/res/cardsfolder/upcoming/aberrant.txt
- forge-gui/res/cardsfolder/upcoming/broodlord.txt
- forge-gui/res/cardsfolder/upcoming/exocrine.txt
- forge-gui/res/cardsfolder/upcoming/hormagaunt_horde.txt
- forge-gui/res/cardsfolder/upcoming/mawloc.txt
> 40K: Ravenous keyword

- forge-gui-mobile-dev/src/forge/app/Main.java
- forge-gui/pom.xml
- Forge mobile port can be run on either windowed or fullscreen via settings
> fix windowmode settings

- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeXEffect.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/a/azor_the_lawbringer.txt
- forge-gui/res/cardsfolder/d/dimensional_breach.txt
- forge-gui/res/cardsfolder/t/titans_nest.txt
- forge-gui/res/cardsfolder/upcoming/celestine_the_living_saint.txt
- forge-gui/res/cardsfolder/upcoming/epistolary_librarian.txt
- forge-gui/res/cardsfolder/upcoming/tyrannical_pitlord.txt
E. g. a kicked _Thieving Skydiver_
> Fix Unbound Flourishing triggering for additional X costs

- forge-gui/res/editions/Alchemy Dominaria.txt
- forge-gui/res/editions/Game Day Promos.txt
- forge-gui/res/editions/Game Night 2022.txt
- forge-gui/res/editions/Starter Commander Decks.txt
- forge-gui/res/editions/The Brothers War Commander.txt
- forge-gui/res/editions/The Brothers War.txt
Will add the archive cards in another PR because waiting to see where they fit into the set with collector numbering
> Edition files for YDMU, BRO, BRC & SCD and updates to GDY & GN3

- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/m/myr_superion.txt
- forge-gui/res/cardsfolder/p/path_of_ancestry.txt
- forge-gui/res/cardsfolder/p/primal_amulet_primal_wellspring.txt
- forge-gui/res/cardsfolder/p/pyromancers_goggles.txt
E. g. _Myr Welder_ that exiled _Lapis Orb of Dragonkind_.
> Fix crash when spending mana produced by a gained ability with triggers

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/trigger/Trigger.java
- forge-gui/res/cardsfolder/upcoming/verrak_warped_sengir.txt
not sure if the line in GameActionUtil is necessary...
> DMC: Verrak, Warped Sengir and support

- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui/res/cardsfolder/upcoming/oracle_of_the_alpha.txt
Thanks @paulsnoops for the script
> YDMC: Oracle of the Alpha and support

- forge-gui/res/cardsfolder/upcoming/neyam_shai_murad.txt
- forge-gui/res/cardsfolder/upcoming/the_first_tyrannic_war.txt
Thanks @Simisays for the getting the Saga started
@tool4ever that first Saga ability is a little spicy, seems to work fine with testing, see what you think
> 40K: 30 Sep

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/j/junk_winder.txt
- forge-gui/res/cardsfolder/upcoming/urza_chief_artificer.txt
thanks @Simisays for most of the script
> BRC: Urza, Chief Artificer and Affinity tweaks

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-ai/src/main/java/forge/ai/ability/ChooseGenericEffectAi.java
- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
This is mostly on par with what the AI did with the card before, but it'll now prefer Indestructible when it's a safer option. Can definitely be improved further later.
> Update Gideon Blackblade AI logic

- forge-game/src/main/java/forge/game/ability/effects/FlipCoinEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
- forge-gui/res/cardsfolder/upcoming/mutalith_vortex_beast.txt
- forge-gui/res/cardsfolder/y/yusri_fortunes_flame.txt
thanks @Simisays for starting the script
> 40K: Mutalith Vortex Beast and support

- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui/res/cardsfolder/upcoming/darigaaz_shivan_champion.txt
thanks @Simisays for getting the script started
> YDMU: Darigaaz, Shivan Champion and support

- forge-gui/res/cardsfolder/upcoming/the_mightstone_and_weakstone.txt
- forge-gui/res/cardsfolder/upcoming/urza_lord_protector_urza_planeswalker.txt
- forge-gui/res/tokenscripts/c_1_1_a_soldier.txt
BRO: Add working scripts for two BRO cards following the recent Meld engine changes, + one token script.
- Urza, Lord Protector
- The Mightstone and Weakstone
- 1/1 colorless artifact Soldier creature token
Big thanks to Friarsol and TRT for the engine help!
> BRO: Urza, Lord Protector + The Mightstone and Weakstone

- forge-gui/res/editions/Secret Lair Drop Series.txt
Orks, Age of Sigmar & Blood Bowl
Source:
https://www.magicspoiler.com/mtg-news/secret-lair-warhammer-40000/
https://www.youtube.com/watch?v=PekMZaYVvTU
> SLD: Warhammer

- forge-gui/res/editions/Unfinity.txt
> UNF edition

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- forge-ai/src/main/java/forge/ai/ability/EffectAi.java
- forge-ai/src/main/java/forge/ai/ability/EncodeAi.java
- forge-ai/src/main/java/forge/ai/ability/PumpAiBase.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-game/src/main/java/forge/game/staticability/StaticAbility.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCantAttackBlock.java
- forge-gui/res/cardsfolder/a/azorius_knight_arbiter.txt
- forge-gui/res/cardsfolder/g/gray_harbor_merfolk.txt
- forge-gui/res/cardsfolder/j/jhessian_infiltrator.txt
- forge-gui/res/cardsfolder/p/phantom_warrior.txt
- forge-gui/res/cardsfolder/p/plasma_elemental.txt
- forge-gui/res/cardsfolder/s/soulsworn_spirit.txt
- forge-gui/res/cardsfolder/t/triton_shorestalker.txt
- forge-gui/res/cardsfolder/v/vedalken_infiltrator.txt
The EffectAi logic to make something unblockable will still be pretty awful compared to before but it's not trivial to apply such static  to potential attackers for it to be recognized
> Unblockable fixes

- forge-gui/res/cardsfolder/a/ashiok_nightmare_weaver.txt
- forge-gui/res/cardsfolder/e/electropotence.txt
- forge-gui/src/main/java/forge/player/TargetSelection.java
> TargetSelection: improve check for enough targets

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
> Ravenous update for rules

- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-gui/res/cardsfolder/a/arbiter_of_the_ideal.txt
> Arbiter of the Ideal / DigEffect update

- forge-game/src/main/java/forge/game/StaticEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/staticability/StaticAbility.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-gui/res/cardsfolder/upcoming/priest_of_possibility.txt
It's an Alchemy card, but these tweaks might be useful in other situations too... and I don't think they do any harm
> YDMU: Priest of Possibility and support

- forge-gui/res/cardsfolder/a/amplifire.txt
- forge-gui/res/cardsfolder/t/threats_undetected.txt
- forge-gui/res/cardsfolder/u/underdark_beholder.txt
Wait, Threats undetetected need some more work
Closes #1682
Closes #1697
> Underdark Beholder & Amplifire & Threats Undetected

- forge-gui/res/editions/Secret Lair Drop Series.txt
> SLD number & artist fixes

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/b/beastbreaker_of_bala_ged.txt
- forge-gui/res/cardsfolder/b/brimstone_mage.txt
- forge-gui/res/cardsfolder/c/coralhelm_commander.txt
- forge-gui/res/cardsfolder/d/dire_fleet_captain.txt
- forge-gui/res/cardsfolder/e/echo_mage.txt
- forge-gui/res/cardsfolder/e/enclave_cryptologist.txt
- forge-gui/res/cardsfolder/g/guul_draz_assassin.txt
- forge-gui/res/cardsfolder/h/hada_spy_patrol.txt
- forge-gui/res/cardsfolder/h/halimar_wavewatch.txt
- forge-gui/res/cardsfolder/h/hedron_field_purists.txt
- forge-gui/res/cardsfolder/h/hexdrinker.txt
- forge-gui/res/cardsfolder/i/ikiral_outrider.txt
- forge-gui/res/cardsfolder/j/joraga_treespeaker.txt
- forge-gui/res/cardsfolder/k/kargan_dragonlord.txt
- forge-gui/res/cardsfolder/k/kazandu_tuskcaller.txt
- forge-gui/res/cardsfolder/k/knight_of_cliffhaven.txt
- forge-gui/res/cardsfolder/l/lighthouse_chronologist.txt
- forge-gui/res/cardsfolder/l/lord_of_shatterskull_pass.txt
- forge-gui/res/cardsfolder/n/null_champion.txt
- forge-gui/res/cardsfolder/s/skywatcher_adept.txt
- forge-gui/res/cardsfolder/t/transcendent_master.txt
- forge-gui/res/cardsfolder/z/zulaport_enforcer.txt
- forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
See discussion and pics here: https://discord.com/channels/267367946135928833/267681123864281088/1031916086976856085
> Level up improvements

- forge-game/src/main/java/forge/game/ability/effects/RevealEffect.java
- forge-gui/res/cardsfolder/l/lumbering_lightshield.txt
- forge-gui/res/cardsfolder/upcoming/teferis_contingency.txt
I think this is the last YDMU card other than Enlist stuff
> YDMU: Teferi's Contingency (+ Lumbering Lightshield fixes)

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/blaster_combat_dj_blaster_morale_booster.txt
- forge-gui/res/cardsfolder/upcoming/blitzwing_cruel_tormentor_blitzwing_adaptive_assailant.txt
- forge-gui/res/cardsfolder/upcoming/cyclonus_the_saboteur_cyclonus_cybertronian_fighter.txt
- forge-gui/res/cardsfolder/upcoming/flamewar_brash_veteran_flamewar_streetwise_operative.txt
- forge-gui/res/cardsfolder/upcoming/ratchet_field_medic_ratchet_rescue_racer.txt
- forge-gui/res/cardsfolder/upcoming/soundwave_sonic_spy_soundwave_superior_captain.txt
- forge-gui/res/cardsfolder/upcoming/starscream_power_hungry_starscream_seeker_leader.txt
- forge-gui/res/tokenscripts/laserbeak.txt
- forge-gui/res/tokenscripts/ravage.txt
Thanks for all the reviews, scripting these transformers cards have been quite the headache lol
> BOT Transformers 7 cards

- forge-gui/res/cardsfolder/upcoming/non_human_cannonball.txt
- forge-gui/res/cardsfolder/upcoming/one_clown_band.txt
- forge-gui/res/cardsfolder/upcoming/pair_o_dice_lost.txt
- forge-gui/res/cardsfolder/upcoming/priority_boarding.txt
- forge-gui/res/cardsfolder/upcoming/resolute_veggiesaur.txt
- forge-gui/res/cardsfolder/upcoming/slight_malfunction.txt
- forge-gui/res/cardsfolder/upcoming/strength_testing_hammer.txt
Probably the last easy Unfinity cards left. If some dev would find the time to implement the mechanics, I woudn't mind scripting more cards. 
Still in draft because Resolute Veggiesaur condition isn't working (is it even possible without engine changes?) and Pair o' Dice Lost changezone needs some more work. Though to just put it out there for some advice
> Unfinity 7 cards

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ReplaceEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ReplaceTokenEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/mana/ManaPool.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/l/lavinia_azorius_renegade.txt
- forge-gui/res/cardsfolder/m/mount_velus_manticore.txt
- forge-gui/res/cardsfolder/m/mourners_shield.txt
- forge-gui/res/cardsfolder/p/plague_reaver.txt
- forge-gui/res/cardsfolder/p/protective_sphere.txt
- forge-gui/res/cardsfolder/r/raggadragga_goreguts_boss.txt
- forge-gui/res/cardsfolder/r/roiling_vortex.txt
- forge-gui/res/cardsfolder/u/undead_slayer.txt
- forge-gui/res/cardsfolder/v/vazi_keen_negotiator.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
- forge-gui/src/main/java/forge/player/TargetSelection.java
> Fix BecomesTargetOnce multiple triggers + some others

- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseColorEffect.java
- forge-game/src/main/java/forge/game/mana/ManaPool.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/b/blood_divination.txt
- forge-gui/res/cardsfolder/c/charge_of_the_forever_beast.txt
- forge-gui/res/cardsfolder/e/evelyn_the_covetous.txt
- forge-gui/res/cardsfolder/s/swallow_whole.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
GUI and effect logic should not be mixed if possible to avoid such situations
This will also automatically make it work with `CostChooseColor`
> Fix color choice

- forge-gui/res/cardsfolder/upcoming/argoth_sanctum_of_nature.txt
- forge-gui/res/cardsfolder/upcoming/titania_voice_of_gaea_titania_gaea_incarnate.txt
Thanks to The Marvel From Mercury from Discord !
> BRO Titania, Voice of Gaea & Titania, Voice of Gaea

- forge-gui/res/editions/Online Promos.txt
> Update Online Promos.txt

- forge-gui/res/cardsfolder/upcoming/rootpath_purifier.txt
- forge-gui/res/cardsfolder/upcoming/the_brothers_war.txt
- forge-gui/res/cardsfolder/upcoming/urzas_workshop.txt
Still in draft because The Brother's War 2'nd ability still needs work. Any advise ?
> BRC 3 Cards

- forge-gui/res/cardsfolder/s/stromkirk_mentor.txt
- forge-gui/res/cardsfolder/upcoming/aeronaut_cavalry.txt
- forge-gui/res/cardsfolder/upcoming/air_marshal.txt
- forge-gui/res/cardsfolder/upcoming/airlift_chaplain.txt
- forge-gui/res/cardsfolder/upcoming/arbalest_engineers.txt
- forge-gui/res/cardsfolder/upcoming/argivian_avenger.txt
Just took the top 5 in the alphabet... nothing too tricky here
> BRO: 4 Nov

- forge-gui/res/cardsfolder/upcoming/blast_furnace_hellkite.txt
- forge-gui/res/cardsfolder/upcoming/sardian_avenger.txt
- forge-gui/res/cardsfolder/upcoming/staff_of_titania.txt
- forge-gui/res/cardsfolder/upcoming/the_archimandrite.txt
- forge-gui/res/cardsfolder/upcoming/titania_natures_force.txt
This should wrap up Brothers War Commander except those two cards that need engine changes
> BRC 5 Cards

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/s/sheltering_prayers.txt
> fix sheltering_prayers.txt / expand "ControllerControls" CardProperty

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-gui/res/cardsfolder/upcoming/transmogrants_crown.txt
just a little fussiness to get this to parse with the right format
> BRO: Transmogrant's Crown and parsing tweaks

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
- forge-gui/res/cardsfolder/upcoming/combat_thresher.txt
- forge-gui/res/cardsfolder/upcoming/cradle_clearcutter.txt
- forge-gui/res/cardsfolder/upcoming/goring_warplow.txt
closes #1748 
Seems to be working, ~~except ETB triggers are lost somehow when you cast with Prototype cost~~
> BRO: Prototype

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/cost/CostSacrifice.java
- forge-gui/res/cardsfolder/m/minthara_merciless_soul.txt
- forge-gui/res/cardsfolder/upcoming/mishra_tamer_of_mak_fawa.txt
- forge-gui/res/cardsfolder/upcoming/phyrexian_fleshgorger.txt
Big improvement for Minthara card detail
> BRO: Ward parsing updates

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
- forge-gui/res/cardsfolder/upcoming/blitz_automaton.txt
> Prototype is not AlternativeCost

- forge-gui/res/cardsfolder/upcoming/arcane_proxy.txt
- forge-gui/res/cardsfolder/upcoming/autonomous_assembler.txt
- forge-gui/res/cardsfolder/upcoming/boulderbranch_golem.txt
- forge-gui/res/cardsfolder/upcoming/hulking_metamorph.txt
- forge-gui/res/cardsfolder/upcoming/soundwave_sonic_spy_soundwave_superior_captain.txt
- forge-gui/res/cardsfolder/upcoming/woodcaller_automaton.txt
- 5 new Prototype cards – nothing too gnarly
- fixed some issues with a Transformer card
> BRO: 8 Nov

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/a/angelic_destiny.txt
- forge-gui/res/cardsfolder/c/crush_underfoot.txt
- forge-gui/res/cardsfolder/e/endless_evil.txt
- forge-gui/res/cardsfolder/g/genju_of_the_cedars.txt
- forge-gui/res/cardsfolder/g/genju_of_the_falls.txt
- forge-gui/res/cardsfolder/g/genju_of_the_fens.txt
- forge-gui/res/cardsfolder/g/genju_of_the_fields.txt
- forge-gui/res/cardsfolder/g/genju_of_the_realm.txt
- forge-gui/res/cardsfolder/g/genju_of_the_spires.txt
- forge-gui/res/cardsfolder/g/gift_of_immortality.txt
- forge-gui/res/cardsfolder/i/infectious_rage.txt
- forge-gui/res/cardsfolder/j/journey_to_eternity_atzal_cave_of_eternity.txt
- forge-gui/res/cardsfolder/n/necrotic_plague.txt
- forge-gui/res/cardsfolder/n/next_of_kin.txt
- forge-gui/res/cardsfolder/p/puppet_master.txt
- forge-gui/res/cardsfolder/r/radiant_grace_radiant_restraints.txt
- forge-gui/res/cardsfolder/s/screams_from_within.txt
- forge-gui/res/cardsfolder/s/skin_invasion_skin_shedder.txt
- forge-gui/res/cardsfolder/upcoming/draconic_destiny.txt
- forge-gui/res/cardsfolder/upcoming/nurgles_rot.txt
> Auras 400.7f

- forge-gui/res/cardsfolder/upcoming/depth_charge_colossus.txt
- forge-gui/res/cardsfolder/upcoming/fallaji_dragon_engine.txt
- forge-gui/res/cardsfolder/upcoming/iron_craw_crusher.txt
- forge-gui/res/cardsfolder/upcoming/rootwire_amalgam.txt
- forge-gui/res/cardsfolder/upcoming/rust_goliath.txt
- forge-gui/res/cardsfolder/upcoming/skitterbeam_battalion.txt
- forge-gui/res/cardsfolder/upcoming/spotter_thopter.txt
- forge-gui/res/tokenscripts/c_x_x_a_golem.txt
Coudn't get Rootwire Amalgam to work without the StoreSVar
> BRO remaining Prototype cards

- forge-gui/res/cardsfolder/a/all_hallows_eve.txt
Felt obliged to improve the AI behavior after I cheesed a win against the Griselbrand boss  in Adventure mode where the AI cast this card while my graveyard was full of creatures while they only had 2 Will-o'-the-Wisp :)
Set Max at 10 for multiplayer
> AI improvement for All Hallow's Eve

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerScry.java
- forge-gui/res/cardsfolder/k/king_narfis_betrayal.txt
- forge-gui/res/cardsfolder/upcoming/the_temporal_anchor.txt
The AI for this could be pretty wild... but honestly even just with regular Scry logic it should generate some interesting advantage that the AI could benefit from.
> BRO: The Temporal Anchor and support

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-gui/res/cardsfolder/a/all_hallows_eve.txt
- forge-gui/res/cardsfolder/c/chimney_goyf.txt
- forge-gui/res/cardsfolder/c/chimney_imp.txt
- forge-gui/res/cardsfolder/c/chittering_rats.txt
- forge-gui/res/cardsfolder/e/evolved_sleeper.txt
- forge-gui/res/cardsfolder/upcoming/mishras_research_desk.txt
- forge-gui/res/cardsfolder/upcoming/thran_spider.txt
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
> Some card fixes

- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityVariables.java
- forge-gui/res/cardsfolder/w/war_room.txt
> War Room fix

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/spellability/Spell.java
- forge-gui/res/cardsfolder/b/broken_visage.txt
- forge-gui/res/cardsfolder/g/gluntch_the_bestower.txt
- forge-gui/res/cardsfolder/i/ingenious_mastery.txt
- forge-gui/res/cardsfolder/j/jolene_the_plunder_queen.txt
- forge-gui/res/cardsfolder/t/trudge_garden.txt
> Prototype fix

- forge-gui/res/cardsfolder/upcoming/hurkyls_final_meditation.txt
- forge-gui/res/cardsfolder/upcoming/over_the_top.txt
- forge-gui/res/cardsfolder/upcoming/steel_exemplar.txt
- forge-gui/res/cardsfolder/upcoming/steel_seraph.txt
- forge-gui/res/cardsfolder/upcoming/swiftgear_drake.txt
5 BRO cards – nothing too wild, but some interesting stuff
> BRO – 11 Nov

- forge-gui-desktop/src/main/java/forge/gui/MenuScroller.java
- forge-gui-desktop/src/main/java/forge/screens/match/CMatchUI.java
> Desktop: Improve MouseWheel support in play choice popup

- forge-gui/res/cardsfolder/upcoming/captain_rex_nebula.txt
> UNF Captain Rex Nebula

- forge-gui/res/cardsfolder/e/ensoul_artifact.txt
- forge-gui/res/cardsfolder/upcoming/lorans_escape.txt
- forge-gui/res/cardsfolder/upcoming/machine_over_matter.txt
- forge-gui/res/cardsfolder/upcoming/mask_of_the_jadecrafter.txt
- forge-gui/res/cardsfolder/upcoming/mightstones_animation.txt
- forge-gui/res/cardsfolder/upcoming/military_discipline.txt
- forge-gui/res/tokenscripts/c_a_food_sac.txt
- forge-gui/res/tokenscripts/c_a_gold_sac.txt
> BRO: 13 Nov

- forge-gui/res/cardsfolder/upcoming/symmetry_matrix.txt
- forge-gui/res/cardsfolder/upcoming/take_flight.txt
- forge-gui/res/cardsfolder/upcoming/tawnoss_tinkering.txt
> BRO: 12 Nov

- forge-gui/res/cardsfolder/c/crypt_lurker.txt
- forge-gui/res/cardsfolder/upcoming/isu_the_abominable.txt
At first I tried to rig this up with AlternateCost stuff but I gave up 😅
> J22: Isu the Abominable

- forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
- forge-gui/res/cardsfolder/o/ochre_jelly.txt
- forge-gui/res/cardsfolder/p/preyseizer_dragon.txt
- forge-gui/res/cardsfolder/rebalanced/a-ochre_jelly.txt
- forge-gui/res/cardsfolder/upcoming/thopter_mechanic.txt
> Fix Ochre Jelly

- forge-game/src/main/java/forge/game/ability/effects/TwoPilesEffect.java
- forge-gui/res/cardsfolder/upcoming/hostile_negotiations.txt
A few tweaks to TwoPiles effect for this
> BRO: Hostile Negotiations and support

- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-gui/res/cardsfolder/a/akoum_flameseeker.txt
- forge-gui/res/cardsfolder/c/captains_maneuver.txt
> Fix canFaceDownBeShownTo

- forge-gui/res/cardsfolder/upcoming/depth_charge_colossus.txt
- forge-gui/res/cardsfolder/upcoming/energy_refractor.txt
- forge-gui/res/cardsfolder/upcoming/meticulous_excavation.txt
- forge-gui/res/cardsfolder/upcoming/the_fall_of_kroog.txt
- forge-gui/res/cardsfolder/upcoming/tower_worker.txt
- forge-gui/res/cardsfolder/upcoming/transmogrant_altar.txt
- forge-gui/res/cardsfolder/upcoming/trench_stalker.txt
- forge-gui/res/cardsfolder/upcoming/visions_of_phyrexia.txt
- forge-gui/res/quest/commanderprecons/Urza's Iron Alliance [BRC] [2022].dck
I've tested them all and they should be working now. Thanks for the help as usual
> BRO Last 6 Cards + 3 fix

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui/res/adventure/Shandalar/ui/hud.json
- forge-gui/res/adventure/Shandalar/ui/hud_landscape.json
- forge-gui/res/adventure/Shandalar/ui/hud_portrait.json
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
> [Adventure] add zoom button

- forge-gui/res/cardsfolder/upcoming/niambi_beloved_protector.txt
Source: https://magic.wizards.com/en/news/mtg-arena/mtg-arena-announcements-november-14-2022
"if you cast it" was added. As this is an Arena only card there is no need for a new script.
> Rebalance: Niambi, Beloved Protector

- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/d/domri_anarch_of_bolas.txt
- forge-gui/res/cardsfolder/h/heavy_arbalest.txt
- forge-gui/res/cardsfolder/h/heckling_fiends.txt
> Some fixes

- forge-gui/res/cardsfolder/a/azra_oddsmaker.txt
- forge-gui/res/cardsfolder/t/tamiyo_field_researcher.txt
> Fix Azra Oddsmaker

- forge-gui-desktop/src/main/java/forge/screens/match/TargetingOverlay.java
> Show combat arrow for attacked player on desktop

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/SpellApiToAi.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/ApiType.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseSectorEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/card/CardView.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/player/PlayerController.java
- forge-game/src/main/java/forge/trackable/TrackableProperty.java
- forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
- forge-gui/res/cardsfolder/a/alluring_scent.txt
- forge-gui/res/cardsfolder/upcoming/space_beleren.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Note that the AI for ChooseSector is currently completely random - with only 3 choices, the AI is kind of a drunken master when assigning its own creatures. Obviously we'll need some actual AI for the AI to be able to use the Space Beleren abilities with any effectiveness - my thought now is to leave the AI wiring as an issue for someone to do on a rainy day.
> UNF: space_beleren.txt and support

- forge-gui/res/cardsfolder/d/deathbringer_thoctar.txt
- forge-gui/res/cardsfolder/r/rumbling_slum_avatar.txt
- forge-gui/res/cardsfolder/upcoming/conductor_of_cacophony.txt
- forge-gui/res/cardsfolder/upcoming/dutiful_replicator.txt
- forge-gui/res/cardsfolder/upcoming/hold_for_questioning.txt
3 fairly straightforward new cards and some tidying of old ones
> J22: 21 Nov

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/infernal_idol.txt
- forge-gui/res/cardsfolder/upcoming/ingenious_leonin.txt
- forge-gui/res/cardsfolder/upcoming/magnanimous_magistrate.txt
- forge-gui/res/cardsfolder/upcoming/mild_mannered_librarian.txt
- forge-gui/res/cardsfolder/upcoming/primeval_herald.txt
- forge-gui/res/cardsfolder/upcoming/read_the_soul.txt
- forge-gui/res/cardsfolder/upcoming/rodolf_duskbringer.txt
- forge-gui/res/cardsfolder/upcoming/runadi_behemoth_caller.txt
- forge-gui/res/cardsfolder/upcoming/towering_gibbon.txt
- forge-gui/res/cardsfolder/upcoming/zask_skittering_swarmlord.txt
All cards are working during tests
> J22 10 Cards 

- forge-gui/res/cardsfolder/e/elkin_bottle.txt
- forge-gui/res/cardsfolder/upcoming/alandra_sky_dreamer.txt
- forge-gui/res/cardsfolder/upcoming/coalborn_entity.txt
- forge-gui/res/cardsfolder/upcoming/disciple_of_perdition.txt
- forge-gui/res/cardsfolder/upcoming/ingenious_leonin.txt
- forge-gui/res/cardsfolder/upcoming/rodolf_duskbringer.txt
- forge-gui/res/cardsfolder/upcoming/zask_skittering_swarmlord.txt
3 fairly straightforward ones (thanks @tool4ever for making Disciple of Perdition work) and some typo fixes
> J22: Nov 22

- forge-gui-mobile/src/forge/Graphics.java
- forge-gui-mobile/src/forge/Shaders.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/screens/TransitionScreen.java
> fix Adventure Rewards

- forge-gui-desktop/src/test/java/forge/card/CardDbCardMockTestCase.java
- forge-gui/res/editions/Jumpstart 2022.txt
The script didn't pull artists from Scryfall as they haven't listed them yet. Will add them when they're available.
> J22 edition update

- forge-gui/res/cardsfolder/b/bellowing_aegisaur.txt
- forge-gui/res/cardsfolder/b/bounty_hunter.txt
- forge-gui/res/cardsfolder/c/chevill_bane_of_monsters.txt
- forge-gui/res/cardsfolder/c/commit_memory.txt
- forge-gui/res/cardsfolder/m/mathas_fiend_seeker.txt
- forge-gui/res/cardsfolder/upcoming/planar_atlas.txt
- forge-gui/res/cardsfolder/upcoming/soul_read.txt
- forge-gui/res/cardsfolder/upcoming/synchronized_eviction.txt
- forge-gui/res/cardsfolder/upcoming/termination_facilitator.txt
3 straightforward new cards and some tweaks to old/related ones
> J22: 23 Nov

- forge-gui/res/cardsfolder/upcoming/giant_ladybug.txt
- forge-gui/res/cardsfolder/upcoming/goblin_researcher.txt
- forge-gui/res/cardsfolder/upcoming/skullslither_worm.txt
Just 3 fairly straightforward new cards
Maybe Goblin Researcher Effect should also have a static trigger that exiles it if EffectSource changes zone?
> J22: 23 Nov (more)

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/GameEntity.java
- forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/phase/Untap.java
- forge-gui/res/cardsfolder/upcoming/mishras_juggernaut.txt
> StrictAmount fix

- forge-gui/res/cardsfolder/g/galvanic_blast.txt
Fixed spell description and target prompt to match Oracle text and other similar spells (e.g. Lightning Bolt).
> Galvanic Blast spell description and target prompt

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/ability/AmassAi.java
- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/ability/AbilityFactory.java
- forge-game/src/main/java/forge/game/ability/effects/AmassEffect.java
- forge-game/src/main/java/forge/game/ability/effects/BalanceEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseCardEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChooseGenericEffect.java
- forge-gui/res/cardsfolder/a/archghoul_of_thraben.txt
- forge-gui/res/cardsfolder/b/bishop_of_binding.txt
- forge-gui/res/cardsfolder/upcoming/sarinth_steelseeker.txt
- forge-gui/res/cardsfolder/upcoming/the_temporal_anchor.txt
- forge-gui/src/main/java/forge/gamemodes/puzzle/Puzzle.java
> Fix Bishop of Binding

- forge-gui/res/cardsfolder/g/genasi_rabble_rouser.txt
Add missing power and toughness
See: https://scryfall.com/card/hbg/53/genasi-rabble-rouser
> Genasi Rabble-Rouser: add missing power and toughness

- forge-gui/res/cardsfolder/upcoming/rusko_clockmaker.txt
Source: https://pbs.twimg.com/media/Fi_I59nXgAE05o-?format=jpg&name=medium
> Rusko, Clockmaker fix

- forge-gui/res/cardsfolder/l/lizardfolk_librarians.txt
See: https://scryfall.com/card/hbg/35/lizardfolk-librarians
> Fix P/T of Lizardfolk Librarians

- forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerRolledDie.java
- forge-gui/res/cardsfolder/a/arlinn_the_packs_hope_arlinn_the_moons_fury.txt
- forge-gui/res/cardsfolder/a/aurification.txt
- forge-gui/res/cardsfolder/b/breeches_brazen_plunderer.txt
- forge-gui/res/cardsfolder/c/combine_guildmage.txt
- forge-gui/res/cardsfolder/d/dark_intimations.txt
- forge-gui/res/cardsfolder/d/dissipation_field.txt
- forge-gui/res/cardsfolder/d/dread.txt
- forge-gui/res/cardsfolder/e/essence_sliver.txt
- forge-gui/res/cardsfolder/g/greatbow_doyen.txt
- forge-gui/res/cardsfolder/j/justice.txt
- forge-gui/res/cardsfolder/m/malcolm_keen_eyed_navigator.txt
- forge-gui/res/cardsfolder/m/mangaras_equity.txt
- forge-gui/res/cardsfolder/n/no_mercy.txt
- forge-gui/res/cardsfolder/o/ohabi_caleria.txt
- forge-gui/res/cardsfolder/r/resolute_veggiesaur.txt
- forge-gui/res/cardsfolder/t/tephraderm.txt
- forge-gui/res/cardsfolder/v/vraska_swarms_eminence.txt
- forge-gui/res/cardsfolder/z/zameck_guildmage.txt
> Die roll fix

- forge-gui-mobile/src/forge/card/CardImageRenderer.java
- forge-gui/src/main/java/forge/util/ImageFetcher.java
- allow zoomed cards to fetch image if possible
> update ImageFetcher & CardImageRenderer

- forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
First commit to repository, totally open to review / revision / rejection if there's potential unintended side effects from this change.
> Add card previews when drafting from a spellbook

- forge-game/src/main/java/forge/game/player/PlayerProperty.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamageDone.java
- forge-gui/res/cardsfolder/h/hellish_rebuke.txt
- forge-gui/res/cardsfolder/s/satsuki_the_living_lore.txt
> Card fix + cleanup

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-gui-mobile/src/forge/Graphics.java
- forge-gui-mobile/src/forge/Shaders.java
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
> Cleanup effect card name

- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-gui/res/cardsfolder/upcoming/argothian_uprooting.txt
- forge-gui/res/cardsfolder/upcoming/foundry_groundbreaker.txt
> YBRO Argothian Uprooting & Foundry Groundbreaker

- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
- forge-core/src/main/java/forge/util/MyRandom.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
Uses a seeded deterministic random generator when simulating choices, which ensures  the same number of sub-choices are always used, which the code requires. Adds a test.
> Fix simulation AI exception with random effects.

- forge-core/src/main/java/forge/deck/generation/DeckGeneratorBase.java
- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DamageDealEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DraftEffect.java
- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamagePrevented.java
- forge-game/src/main/java/forge/game/trigger/TriggerDamagePreventedOnce.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
- forge-gui/res/cardsfolder/a/ashcoat_of_the_shadow_swarm.txt
- forge-gui/res/cardsfolder/d/district_guide.txt
- forge-gui/res/cardsfolder/d/djeru_with_eyes_open.txt
- forge-gui/res/cardsfolder/d/dread.txt
- forge-gui/res/cardsfolder/e/emrakul_the_aeons_torn.txt
- forge-gui/res/cardsfolder/h/hostility.txt
- forge-gui/res/cardsfolder/h/hunters_insight.txt
- forge-gui/res/cardsfolder/l/lord_of_tresserhorn.txt
- forge-gui/res/cardsfolder/m/mandate_of_abaddon.txt
- forge-gui/res/cardsfolder/n/nicol_bolas_dragon_god.txt
- forge-gui/res/cardsfolder/s/serra_avatar.txt
- forge-gui/res/cardsfolder/s/skyline_savior.txt
- forge-gui/res/cardsfolder/s/soul_of_emancipation.txt
- forge-gui/res/cardsfolder/s/squadron_hawk.txt
- forge-gui/res/cardsfolder/s/stalking_yeti.txt
- forge-gui/res/cardsfolder/v/vigor.txt
- forge-gui/res/cardsfolder/w/worldspine_wurm.txt
- Support ChangesZoneAll
- Handle "graveyard from anywhere" exception
> Hushbringer improvements

- forge-core/src/main/java/forge/util/ImageUtil.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/screens/match/views/VAvatar.java
- additional check for ImageUtil
> fix Adventure RewardActor crash

- forge-ai/src/main/java/forge/ai/ability/MillAi.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-gui/res/cardsfolder/a/amulet_of_quoz.txt
- forge-gui/res/cardsfolder/d/demonic_attorney.txt
- forge-gui/res/cardsfolder/r/rebirth.txt
- forge-gui/res/cardsfolder/t/timmerian_fiends.txt
> Fix ante cards

- forge-gui/res/cardsfolder/upcoming/gixian_recycler.txt
- forge-gui/res/cardsfolder/upcoming/hurkyls_prodigy.txt
- forge-gui/res/cardsfolder/upcoming/jarsyl_dark_age_scion.txt
- forge-gui/res/cardsfolder/upcoming/legion_of_clay.txt
- forge-gui/res/cardsfolder/upcoming/norns_disassembly.txt
- forge-gui/res/cardsfolder/upcoming/patchplate_resolute.txt
Had to use the inelegant DB Choosecard with Jarsyl, Dark Age Scion since it doesn't target.
> YBRO 6 cards

- forge-gui/res/cardsfolder/upcoming/mizzix_replica_rider.txt
Thanks to Squee for the script !
Don't know why the test failed, it worked during testing
> J22 Mizzix, Replica Rider

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ability/DamageAiBase.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/RestartGameEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/spellability/TargetRestrictions.java
> Improve damage check logic for losing + performance

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/upcoming/assemble_the_team.txt
> YBRO: Assemble the Team and support

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/Dominaria Remastered.txt
@Northmoc
The draft wants x1 showcase/oldframe card. Simply putting: 1 Any:fromSheet("DMR showcase") will only give you the original art so instead I made a sheet and went with 1 Any:fromSheet("DMR oldframes") which does give you the correct alternate art. Should I go with this or is there a better way of pulling one of those variations without the [oldframes] sheet?
> Booster Draft for DMR

- forge-gui/res/cardsfolder/r/reviving_vapors.txt
> Rework Reviving Vapors

- forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
- forge-gui/res/cardsfolder/s/scholar_of_the_lost_trove.txt
> add and support "ReplaceGraveyardValid" for scholar_of_the_lost_trove

- forge-gui-mobile/src/forge/assets/FSkin.java
- forge-gui-mobile/src/forge/screens/match/views/VAvatar.java
- fix avatar animation (some devices couldn't load warp animation on smaller texture)
> Fix texture loading check, Revert VAvatar splatter

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/GameAction.java
> Improve reuse of LKI for ChangeZone performance

- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-gui/res/cardsfolder/upcoming/bladed_ambassador.txt
- forge-gui/res/cardsfolder/upcoming/cankerbloom.txt
- forge-gui/res/cardsfolder/upcoming/rustvine_cultivator.txt
- forge-gui/res/cardsfolder/upcoming/urabrasks_anointer.txt
Some easy ones – since the leaked versions were showcase versions, will need to check for reminder text in Oracle once main version is spoiled
> ONE - 19 Dec (some leaked cards)

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
> Guard for case with empty collection

- forge-gui/res/cardsfolder/c/crimson_honor_guard.txt
- forge-gui/res/cardsfolder/k/kinsbaile_borderguard.txt
- forge-gui/res/cardsfolder/s/slithermuse.txt
- forge-gui/res/cardsfolder/upcoming/rusko_clockmaker.txt
- forge-gui/res/cardsfolder/v/vodalian_merchant.txt
Slithermuse is the most interesting because I don't think `IsPresent$` stuff actually works on a DB$ line... but since you can't draw 0 or negative number of cards it always slipped by
> Some card script tweaks

- forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
Fixes a crash when game score doesn't match due dashing.
> Simulated AI: Copy changed SVars when copying state.

- forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/upcoming/by_elspeths_command.txt
- forge-gui/res/cardsfolder/upcoming/yotian_courier.txt
> YBRO: By Elspeth's Command and Yotian Courier + support 

- forge-gui/res/cardsfolder/upcoming/bonepicker_skirge.txt
- forge-gui/res/cardsfolder/upcoming/furnace_punisher.txt
- forge-gui/res/cardsfolder/upcoming/quicksilver_fisher.txt
- forge-gui/res/cardsfolder/upcoming/sawblade_scamp.txt
- forge-gui/res/cardsfolder/upcoming/sinew_dancer.txt
Some new combinations, but no new wiring needed
These all seem like the Oracles might not need additional reminder text in the non-showcase version
> ONE – 21 Dec (leaked card scripts)

- forge-gui-desktop/src/main/java/forge/screens/match/controllers/CDev.java
- forge-gui-desktop/src/main/java/forge/screens/match/views/VDev.java
- forge-gui/res/languages/en-US.properties
- forge-gui/src/main/java/forge/interfaces/IDevModeCheats.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Also moves the setup/dump game state options at the end of the list, as they're different from the other ones and shouldn't just be in the middle.
Also makes the code a bit more concise for the different mouse listeners and a few other clean ups.
> Add "ask simulated ai" dev option.

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/zone/PlayerZone.java
> fix Adventure cards in exile lose "may be cast" when rewinding casting

- forge-gui/res/cardsfolder/c/captain_rex_nebula.txt
- forge-gui/res/cardsfolder/c/chromium_the_mutable.txt
- forge-gui/res/cardsfolder/c/creeping_tar_pit.txt
- forge-gui/res/cardsfolder/d/dimir_keyrune.txt
- forge-gui/res/cardsfolder/e/eye_of_singularity.txt
- forge-gui/res/cardsfolder/f/face_of_divinity.txt
- forge-gui/res/cardsfolder/f/farid_enterprising_salvager.txt
- forge-gui/res/cardsfolder/g/gurgling_anointer.txt
- forge-gui/res/cardsfolder/p/pirated_copy.txt
- forge-gui/res/cardsfolder/p/primal_amulet_primal_wellspring.txt
- forge-gui/res/cardsfolder/r/riverfall_mimic.txt
> Script fixes

- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigMultipleEffect.java
- forge-game/src/main/java/forge/util/MessageUtil.java
- forge-gui/res/cardsfolder/upcoming/green_suns_twilight.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
Some changes to DigMultipleEffect for this
> ONE: Green Sun's Twilight and support

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
Probably not 100% future-proof but since it's only a corner case I preferred less overhead
Closes #2174
> Fix NumLoyaltyAct counting limit and additional wrong together

- forge-gui/res/cardsfolder/b/bow_to_my_command.txt
- forge-gui/res/cardsfolder/m/moonshae_pixie.txt
> ValidCard$ Self to ValidCard$ Card.Self

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/AnimateAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
- forge-game/src/main/java/forge/game/replacement/ReplacementLayer.java
- forge-gui/res/cardsfolder/g/grafdiggers_cage.txt
- forge-gui/res/cardsfolder/g/greasefang_okiba_boss.txt
- forge-gui/res/cardsfolder/k/kunoros_hound_of_athreos.txt
- forge-gui/res/cardsfolder/o/olivia_crimson_bride.txt
- forge-gui/res/cardsfolder/s/swords_to_plowshares.txt
- forge-gui/res/cardsfolder/w/weathered_runestone.txt
- forge-gui/res/cardsfolder/w/worms_of_the_earth.txt
- forge-gui/src/main/java/forge/player/HumanPlay.java
> ReplacementLayer.CantHappen

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-ai/src/main/java/forge/ai/ability/ManaEffectAi.java
- forge-ai/src/main/java/forge/ai/ability/ManifestAi.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
Small part for #1249, generalizes the ``madnessWithoutCast`` logic so it can be used to track all discards
> Fix DiscardedThisTurn

- forge-gui-mobile/src/forge/adventure/world/WorldSave.java
Because of the bug "https://discord.com/channels/267367946135928833/1049248240786223154"
the fix https://github.com/Card-Forge/forge/pull/2041 was done ("fix ConcurrentModificationException and reloading WorldSave")
Now, after https://github.com/Card-Forge/forge/pull/2161 (Update PointOfInterestChanges.java) there is no need for https://github.com/Card-Forge/forge/pull/2041.
Here is a detail description of what is the problem:
The issue is that if you save the game and you have take a reward from cave, castle, factory etc... and that reward was
saved first in the list of POIChanges (see "1.save.png") then after loading the file, all the visited towns, caves, factories etc
will have same data as the first one (see "2.load.png)
For example if ID=57 was earn (will be deleted) then if you …
> Do not clear POI changes after reload

- forge-gui/res/cardsfolder/upcoming/argentum_masticore.txt
- forge-gui/res/cardsfolder/upcoming/kethek_crucible_goliath.txt
- forge-gui/res/cardsfolder/upcoming/migloz_maze_crusher.txt
- forge-gui/res/cardsfolder/upcoming/mindsplice_apparatus.txt
- forge-gui/res/cardsfolder/upcoming/zenith_chronicler.txt
Argentium Masticore isn't working yet
> ONE 5 cards

- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-game/src/main/java/forge/game/ability/effects/CountersProliferateEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/trigger/TriggerProliferate.java
- forge-game/src/main/java/forge/game/trigger/TriggerType.java
- forge-gui/res/cardsfolder/b/bitterblossom.txt
- forge-gui/res/cardsfolder/j/jiang_yanggu.txt
- forge-gui/res/cardsfolder/upcoming/blightbelly_rat.txt
- forge-gui/res/cardsfolder/upcoming/ezuri_stalker_of_spheres.txt
- forge-gui/res/cardsfolder/upcoming/mirrex.txt
- forge-gui/res/cardsfolder/upcoming/myr_convert.txt
- forge-gui/res/cardsfolder/upcoming/necrogen_rotpriest.txt
- forge-gui/res/cardsfolder/upcoming/skrelvs_hive.txt
- forge-gui/res/cardsfolder/upcoming/venser_corpse_puppet.txt
- forge-gui/res/lists/TypeLists.txt
- forge-gui/res/tokenscripts/b_1_1_bird_flying_noblock.txt
- forge-gui/res/tokenscripts/c_0_1_a_goblin_construct_noblock_ping.txt
- forge-gui/res/tokenscripts/c_1_1_a_phyrexian_mite_toxic_noblock.txt
- forge-gui/res/tokenscripts/c_4_4_a_robot_noblock.txt
- forge-gui/res/tokenscripts/r_1_1_goblin_noblock.txt
- forge-gui/res/tokenscripts/r_1_1_pirate_noblock_all_attack.txt
- forge-gui/res/tokenscripts/r_1_1_satyr_noblock.txt
- forge-gui/res/tokenscripts/the_hollow_sentinel.txt
Closes #2116 
Closes #2210
First card with Toxic
@Agetian does it need more AI logic? Like in places with Infect?
> ONE: Toxic Keyword

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-ai/src/main/java/forge/ai/CreatureEvaluator.java
- forge-ai/src/main/java/forge/ai/GameState.java
- forge-ai/src/main/java/forge/ai/simulation/MultiTargetSelector.java
- forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
- forge-game/src/main/java/forge/game/ability/effects/MutateEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/c/curse_of_echoes.txt
- forge-gui/res/cardsfolder/h/hive_mind.txt
- forge-gui/res/cardsfolder/j/jodah_the_unifier.txt
- forge-gui/res/cardsfolder/m/moritte_of_the_frost.txt
- forge-gui/src/main/java/forge/gamemodes/match/input/InputSelectEntitiesFromList.java
Really helps simulation more but doesn't hurt our old-school one either.
Gonna keep it Hand only on first iteration I think.
Closes #2218
> Performance: improve deduping

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/cost/CostExert.java
- forge-game/src/main/java/forge/game/cost/CostPutCardToLib.java
- forge-gui/res/cardsfolder/f/flayer_of_the_hatebound.txt
- forge-gui/res/cardsfolder/p/phyrexian_dragon_engine.txt
- forge-gui/res/cardsfolder/t/tamiyo_compleated_sage.txt
```
at forge.ai.ComputerUtilCost.canPayCost(ComputerUtilCost.java:637)
at forge.ai.ComputerUtilCombat.predictToughnessBonusOfBlocker(ComputerUtilCombat.java:1132)
at forge.ai.ComputerUtilCombat.canDestroyBlockerBeforeFirstStrike(ComputerUtilCombat.java:1834)
at forge.ai.ComputerUtilCombat.shieldDamage(ComputerUtilCombat.java:666)
at forge.ai.ComputerUtilCombat.totalShieldDamage(ComputerUtilCombat.java:646)
at forge.ai.ComputerUtilCombat.lifeThatWouldRemain(ComputerUtilCombat.java:332)
at forge.ai.ComputerUtilCombat.lifeInSeriousDanger(ComputerUtilCombat.java:517)
at forge.ai.ComputerUtilCombat.lifeInSeriousDanger(ComputerUtilCombat.java:491)
at forge.ai.ComputerUtil.getCardPreference(ComputerUtil.java:453)
at forge.ai.ComputerUtil.getCardPreference(ComputerUtil.java:362)
at …
```
> Fix Stack Overflow

- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
closes #2230
might remove more of SacrificeEndCombat in later MR
> remove use of AddHiddenKeyword

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-gui/res/cardsfolder/upcoming/blade_of_shared_souls.txt
- forge-gui/res/cardsfolder/upcoming/dragonwing_glider.txt
- forge-gui/res/tokenscripts/r_2_2_rebel.txt
> ONE For Mirrodin

- forge-ai/src/main/java/forge/ai/simulation/SimulationController.java
- forge-game/src/main/java/forge/game/cost/Cost.java
This makes sure we ignore decisions where the score doesn't improve.
@asvitkine
You might be interested
Could be reproduced easily on boardstates like this:
> Simulation: Fix including unjustified decisions

- forge-gui/res/editions/Portal.txt
Portal was merged with PPOD back in June 2022. Added those along with some missing variations.
> Edition update: POR

- forge-gui/res/cardsfolder/upcoming/urtet_remains_of_memnarch.txt
Credit to l30myr for the script.
Also could someone with white acces create a new project for All Will be One Commander ?
> [UNC] Urtet Remains of Memnarch

- forge-ai/src/main/java/forge/ai/GameState.java
- forge-gui/res/puzzle/PS_BRO1.pzl
- forge-gui/res/puzzle/PS_BRO2.pzl
- forge-gui/res/puzzle/PS_BRO3.pzl
- forge-gui/res/tokenscripts/u_2_2_spirit_vigilance_drawcounter.txt
- Added puzzles PS_BRO1 - PS_BRO3.
- Added a way to add tokens by script from GameState.
- Fixed u_2_2_spirit_vigilance_drawcounter token name capitalization.
> Add puzzles PS_BRO1 - PS_BRO3

- forge-gui/res/cardsfolder/upcoming/annex_sentry.txt
- forge-gui/res/cardsfolder/upcoming/bladehold_war_whip.txt
- forge-gui/res/cardsfolder/upcoming/experimental_augury.txt
- forge-gui/res/cardsfolder/upcoming/minor_misstep.txt
- forge-gui/res/cardsfolder/upcoming/mite_overseer.txt
- forge-gui/res/cardsfolder/upcoming/mondrak_glory_dominus.txt
- forge-gui/res/cardsfolder/upcoming/ossification.txt
- forge-gui/res/cardsfolder/upcoming/paladin_of_predation.txt
- forge-gui/res/cardsfolder/upcoming/resistance_reunited.txt
- forge-gui/res/cardsfolder/upcoming/rhuk_hexgold_nabber.txt
These common and uncommons are pretty straight forward.
> ONE 10 cards

- forge-core/src/main/java/forge/card/mana/ManaCost.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/upcoming/nissa_ascended_animist.txt
- forge-gui/res/tokenscripts/g_x_x_phyrexian_horror.txt
Easy card, mainly nailing down Compleated reminder text generation here –
> nissa_ascended_animist.txt and token

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-gui/res/cardsfolder/v/verrak_warped_sengir.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
Otherwise you can pay life on _Moltensteel Dragon_ ability once and then get always get the trigger even when paying mana.
> Fix Verrak

- forge-gui/res/cardsfolder/b/bouncers_beatdown.txt
- forge-gui/res/cardsfolder/b/bury_in_books.txt
- forge-gui/res/cardsfolder/h/hunters_mark.txt
- forge-gui/res/cardsfolder/k/knockout_blow.txt
- forge-gui/res/cardsfolder/m/mascot_interception.txt
- forge-gui/res/cardsfolder/m/mystical_dispute.txt
- forge-gui/res/cardsfolder/n/no_one_left_behind.txt
- forge-gui/res/cardsfolder/o/out_of_the_way.txt
- forge-gui/res/cardsfolder/p/price_of_fame.txt
- forge-gui/res/cardsfolder/s/savage_stomp.txt
- forge-gui/res/cardsfolder/t/titanic_brawl.txt
- forge-gui/res/cardsfolder/t/torch_breath.txt
- forge-gui/res/cardsfolder/w/whack.txt
> Cleanup some SVar

- forge-gui/res/cardsfolder/upcoming/contaminant_grafter.txt
- forge-gui/res/cardsfolder/upcoming/glistening_sphere.txt
- forge-gui/res/cardsfolder/upcoming/norns_choirmaster.txt
- forge-gui/res/cardsfolder/upcoming/norns_decree.txt
- forge-gui/res/cardsfolder/upcoming/phyresis_outbreak.txt
- forge-gui/res/cardsfolder/upcoming/vishgraz_the_doomhive.txt
This should wrap up the new cards from the commander decks. We are missing 7 of the 8 set booster exclusives though.
> ONC 6 cards

- forge-gui/res/cardsfolder/b/buy_your_silence.txt
- forge-gui/res/cardsfolder/rebalanced/a-buy_your_silence.txt
- forge-gui/res/cardsfolder/upcoming/apostle_of_invasion.txt
- forge-gui/res/cardsfolder/upcoming/hexgold_slash.txt
- forge-gui/res/cardsfolder/upcoming/slaughter_singer.txt
- forge-gui/res/cardsfolder/upcoming/vanish_into_eternity.txt
- forge-gui/res/cardsfolder/upcoming/vulshok_splitter.txt
five from one and fix a couple of typos
> five from one and fix a couple of typos

- .github/workflows/test-maven-settings.yml
- forge-game/src/main/java/forge/game/cost/CostExileFromStack.java
- forge-gui/res/cardsfolder/upcoming/chiss_goria_forge_tyrant.txt
- forge-gui/res/cardsfolder/upcoming/lux_artillery.txt
- forge-gui/res/cardsfolder/upcoming/mirage_mockery.txt
- forge-gui/res/cardsfolder/upcoming/monumental_corruption.txt
- forge-gui/res/cardsfolder/upcoming/skyhunter_strike_force.txt
- forge-gui/res/cardsfolder/upcoming/synthesis_pod.txt
- forge-gui/res/cardsfolder/upcoming/tangleweave_armor.txt
> ONC 7 set booster cards

- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-gui/res/cardsfolder/d/draugr_necromancer.txt
- forge-gui/res/cardsfolder/g/gisa_glorious_resurrector.txt
- forge-gui/res/cardsfolder/k/kalitas_traitor_of_ghet.txt
- forge-gui/res/cardsfolder/l/liesa_forgotten_archangel.txt
- forge-gui/res/cardsfolder/l/lorcan_warlock_collector.txt
- forge-gui/res/cardsfolder/m/miserys_shadow.txt
- forge-gui/res/cardsfolder/n/nemata_primeval_warden.txt
- forge-gui/res/cardsfolder/r/rayami_first_of_the_fallen.txt
- forge-gui/res/cardsfolder/v/valentin_dean_of_the_vein_lisette_dean_of_the_root.txt
- forge-gui/res/cardsfolder/v/void_maw.txt
> Better fix for CheckSelfLKIZone

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
This could still lead to wrong result in some cases:
E.g. with trigger from _Priest of the Blessed Graf_ on the stack -> _Donate_ him away -> now it would evaluate the opponents of the new controller
> AbilityUtils: Fix inconsistent controller

- forge-gui/res/cardsfolder/a/argivian_cavalier.txt
- forge-gui/res/cardsfolder/b/balduvian_berserker.txt
- forge-gui/res/cardsfolder/b/benalish_faithbonder.txt
- forge-gui/res/cardsfolder/b/benalish_knight_counselor.txt
- forge-gui/res/cardsfolder/c/coalition_skyknight.txt
- forge-gui/res/cardsfolder/c/coalition_warbrute.txt
- forge-gui/res/cardsfolder/h/hexbane_tortoise.txt
- forge-gui/res/cardsfolder/k/keldon_flamesage.txt
- forge-gui/res/cardsfolder/l/linebreaker_baloth.txt
- forge-gui/res/cardsfolder/y/yavimaya_steelcrusher.txt
This should wrap up the remaining enlist cards except Goblin Morale Sergeant
> DMU YDMU 10 enlist cards

- forge-gui/res/cardsfolder/upcoming/chittering_skitterling.txt
- forge-gui/res/cardsfolder/upcoming/compleat_devotion.txt
- forge-gui/res/cardsfolder/upcoming/feed_the_infection.txt
- forge-gui/res/cardsfolder/upcoming/furnace_skullbomb.txt
- forge-gui/res/cardsfolder/upcoming/gleeful_demolition.txt
- forge-gui/res/cardsfolder/upcoming/hexgold_halberd.txt
- forge-gui/res/cardsfolder/upcoming/incisor_glider.txt
- forge-gui/res/cardsfolder/upcoming/infested_fleshcutter.txt
- forge-gui/res/cardsfolder/upcoming/jawbone_duelist.txt
- forge-gui/res/cardsfolder/upcoming/maze_skullbomb.txt
- forge-gui/res/cardsfolder/upcoming/mesmerizing_dose.txt
- forge-gui/res/cardsfolder/upcoming/necrogen_communion.txt
- forge-gui/res/cardsfolder/upcoming/nimraiser_paladin.txt
- forge-gui/res/cardsfolder/upcoming/noxious_assault.txt
> ONE 14 cards

- forge-gui/src/main/java/forge/gamemodes/quest/QuestSpellShop.java
Things should cost at least 1 credit even if they're dirt cheap otherwise, or it doesn't make sense (to either get or to give away stuff for free in a shop).
> Quest mode: fix cards bought and sold for 0 credits

- forge-gui/tools/DeckConversionTools/mtgdecksnet_convert.py
- forge-gui/tools/DeckConversionTools/mtgdecksnet_decksort.py
- forge-gui/tools/DeckConversionTools/mtgdecksnet_decksort_EDH.py
- forge-gui/tools/ai_limitedplayable.lst
- forge-gui/tools/deckAiCompat.py
- forge-gui/tools/deckAiCompat_limext.py
- forge-gui/tools/scryfallPricesGenerator.py
Update the MTGDecksNet conversion and AI playability test toolchain to the latest version.
Python 3 compatible. Should work with the current MTGDecksNet .dec output and with the current upstream Forge.
Also added a new script to generate all-prices.txt from the Scryfall JSON bulk data.
> Update the MTGDecksNet conversion and AI playability test toolchain to the latest version

- forge-gui/res/cardsfolder/b/bag_of_devouring.txt
- forge-gui/res/cardsfolder/j/jihad.txt
- forge-gui/res/cardsfolder/l/lich.txt
- forge-gui/res/cardsfolder/t/teachings_of_the_kirin_kirin_touched_orochi.txt
- forge-gui/res/cardsfolder/upcoming/venser_corpse_puppet.txt
> Fix scripts

- forge-gui/res/cardsfolder/upcoming/against_all_odds.txt
- forge-gui/res/cardsfolder/upcoming/branchblight_stalker.txt
- forge-gui/res/cardsfolder/upcoming/bring_the_ending.txt
- forge-gui/res/cardsfolder/upcoming/charforger.txt
- forge-gui/res/cardsfolder/upcoming/drown_in_ichor.txt
- forge-gui/res/cardsfolder/upcoming/dune_mover.txt
- forge-gui/res/cardsfolder/upcoming/lukka_bound_to_ruin.txt
- forge-gui/res/cardsfolder/upcoming/tamiyos_logbook.txt
- forge-gui/res/cardsfolder/upcoming/viral_spawning.txt
> ONE 8 Cards

- forge-gui/res/cardsfolder/upcoming/apostle_of_invasion.txt
- forge-gui/res/cardsfolder/upcoming/bonepicker_skirge.txt
- forge-gui/res/cardsfolder/upcoming/vivisection_evangelist.txt
- forge-gui/res/cardsfolder/upcoming/vivisurgeons_insight.txt
- forge-gui/res/cardsfolder/upcoming/vraskas_fall.txt
- forge-gui/res/cardsfolder/upcoming/whisper_of_the_dross.txt
- forge-gui/res/cardsfolder/upcoming/zealots_conviction.txt
> ONE: 5 cards and related tweaks

- forge-gui/res/tokenscripts/the_hollow_sentinel.txt
> Venser token fix

- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
- forge-game/src/main/java/forge/game/trigger/TriggerImmediate.java
- forge-gui/res/cardsfolder/upcoming/melira_the_living_cure.txt
- forge-gui/res/cardsfolder/upcoming/vraska_betrayals_sting.txt
> ONE: Melira, the Living Cure (+tidy Vraska)

- forge-game/src/main/java/forge/game/GlobalRuleChange.java
- forge-game/src/main/java/forge/game/combat/GlobalAttackRestrictions.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityAttackRestrict.java
- forge-gui/res/cardsfolder/a/astral_arena.txt
- forge-gui/res/cardsfolder/c/caverns_of_despair.txt
- forge-gui/res/cardsfolder/c/crawlspace.txt
- forge-gui/res/cardsfolder/d/dueling_grounds.txt
- forge-gui/res/cardsfolder/g/grunn_the_lonely_king.txt
- forge-gui/res/cardsfolder/m/mirri_weatherlight_duelist.txt
- forge-gui/res/cardsfolder/s/silent_arbiter.txt
- forge-gui/res/cardsfolder/s/suppress.txt
- forge-gui/res/cardsfolder/t/teleportation_circle.txt
- forge-gui/res/cardsfolder/upcoming/the_eternal_wanderer.txt
> ONE: The Eternal Wanderer + support + tidy related cards

- .gitignore
- forge-ai/src/main/java/forge/ai/AIDeckStatistics.java
- forge-ai/src/main/java/forge/ai/simulation/GameStateEvaluator.java
- forge-core/src/main/java/forge/card/mana/ManaAtom.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
- Added manabase evaluation to improve the ability of the AI to evaluate their manabase.
- This fixes a bug where the AI values utility lands over building out their manabase.
- Also fixes a bug where filter lands were being overvalued.
> Fix issue where AI plays colorless utility lands first over building their manabase

- forge-gui/src/main/java/forge/gamemodes/quest/QuestSpellShop.java
> Quest mode: Fix selling math

- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/RegisteredPlayer.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
> fix starting cards on adventure mode with etb counters

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-gui/res/cardsfolder/d/desolation_angel.txt
- forge-gui/res/cardsfolder/d/desolation_giant.txt
- forge-gui/res/cardsfolder/m/magma_pummeler.txt
- forge-gui/res/cardsfolder/n/necromancy.txt
- forge-gui/res/cardsfolder/s/skizzik.txt
- forge-gui/res/cardsfolder/s/sphinx_of_lost_truths.txt
- forge-gui/src/main/java/forge/gui/card/CardScriptParser.java
Fixes cases like this where the kicked creature would copy something else and then have that cost count for the new abilities:
> Kicker Linked Lite

- forge-gui/res/adventure/Shandalar/decks/curselord.dck
- forge-gui/res/adventure/Shandalar/decks/kobold.dck
- forge-gui/res/adventure/Shandalar/maps/map/kobold_mine.tmx
- forge-gui/res/adventure/Shandalar/world/enemies.json
- forge-gui/res/adventure/Shandalar/world/points_of_interest.json
- forge-gui/res/adventure/Shandalar/world/red.json
- forge-gui/res/adventure/Shandalar/world/waste.json
- forge-gui/res/cardsfolder/r/rohgahh_kher_keep_overlord.txt
First dungeon
I've tested it on my IDE and it seems to work.
> Kobold dungeon for adventure mode

- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- forge-ai/src/main/java/forge/ai/ability/PermanentCreatureAi.java
- forge-ai/src/main/java/forge/ai/ability/PlayAi.java
- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
- forge-game/src/main/java/forge/game/ability/effects/SacrificeAllEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardState.java
- forge-game/src/main/java/forge/game/cost/CostRemoveCounter.java
- forge-game/src/main/java/forge/game/cost/CostSacrifice.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityVariables.java
- forge-game/src/main/java/forge/game/spellability/SpellPermanent.java
- forge-gui/res/cardsfolder/a/ajanis_aid.txt
- forge-gui/res/cardsfolder/a/animar_soul_of_elements.txt
- forge-gui/res/cardsfolder/b/blazing_crescendo.txt
- forge-gui/res/cardsfolder/c/chiss_goria_forge_tyrant.txt
- forge-gui/res/cardsfolder/j/jolene_the_plunder_queen.txt
- forge-gui/res/cardsfolder/p/primeval_spawn.txt
- forge-gui/res/cardsfolder/t/tahngarth_first_mate.txt
- forge-gui/res/cardsfolder/t/the_first_tyrannic_war.txt
- forge-gui/res/cardsfolder/upcoming/goblin_morale_sergeant.txt
- forge-gui/src/main/java/forge/player/HumanCostDecision.java
> Misc fixes

- forge-gui-mobile/src/forge/screens/TransitionScreen.java
> fix TransitionScreen runnable

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/MapDialog.java
- forge-gui/res/adventure/Shandalar/ui/hud_landscape.json
- forge-gui/res/adventure/Shandalar/ui/hud_portrait.json
- show deckbox if card art is available
- adjust lifepoints, shards, money position
> update deckaward dialog

- forge-ai/src/main/java/forge/ai/AiCostDecision.java
- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/AttachEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DamageAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/DamageEachEffect.java
- forge-game/src/main/java/forge/game/ability/effects/FightEffect.java
- forge-game/src/main/java/forge/game/cost/CostGainControl.java
- forge-game/src/main/java/forge/game/player/PlayerFactoryUtil.java
- forge-gui/res/cardsfolder/g/guardian_beast.txt
- forge-gui/src/main/java/forge/player/HumanCostDecision.java
- Fix NPE when trying to cast _Confiscate_ on card affected by _Guardian Beast_
- Fix ``attachAuraOnIndirectEnterBattlefield`` ignoring CantAttach static
- Fix _Herald of Leshrac_ ignoring _Guardian Beast_ effect
- Fix two more phased out bypasses
> Fixes related to Guardian Beast

- forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java
- forge-gui/res/cardsfolder/i/ivy_gleeful_spellthief.txt
> Fix Ivy checking targets with wrong player

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/t/the_ruinous_powers.txt
> Fix Ruinous Powers

- forge-ai/src/main/java/forge/ai/AiController.java
> Fix Evoke cheat

- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
This is just a bit code cleanup
No Card can gain Disturb and it doesn't work with Split cards, so we can make CardFactoryUtil generate it which is a bit cleaner
> CardFactoryUtil: move Disturb Keyword

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
- preload editions for faster loading of SpellSmithScene
> speedup SpellSmithScene

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- move the exit dungeon code to hide dialog action sequence to fix the stuttering dialog animation
> update GameHUD exitDungeonCallback

- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- fixes portrait mode cannot activate the flip button
> fix flip button

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-gui/res/cardsfolder/upcoming/prowl_stoic_strategist_prowl_pursuit_vehicle.txt
- forge-gui/res/cardsfolder/v/voltaic_visionary_volt_charged_berserker.txt
I tried to do it even cleaner but this seems the best possible, should be ok for now.
> Prowl & support

- forge-gui/res/cardsfolder/upcoming/jin_gitaxias_the_great_synthesis.txt
MOM: Add card script for new card Jin-Gitaxias // The Great Synthesis
> MOM: Jin-Gitaxias // The Great Synthesis

- forge-adventure/pom.xml
- forge-ai/pom.xml
- forge-core/pom.xml
- forge-game/pom.xml
- forge-gui-android/pom.xml
- forge-gui-desktop/pom.xml
- forge-gui-ios/pom.xml
- forge-gui-mobile-dev/pom.xml
- forge-gui-mobile/pom.xml
- forge-gui/pom.xml
- forge-lda/pom.xml
- pom.xml
> Release 1655

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-gui/res/cardsfolder/c/coastal_wizard.txt
- forge-gui/res/cardsfolder/l/lady_sun.txt
- forge-gui/res/cardsfolder/s/snow_hound.txt
- forge-gui/res/cardsfolder/w/wizard_mentor.txt
I'm not in love with the Param name but can't think of anything better at the moment 😅 
A few targeting oopsies on these cards, too...
> Allow Defined and Targets to coexist on one effect

- forge-gui/res/cardsfolder/upcoming/goro_goro_and_satoru.txt
- forge-gui/res/cardsfolder/upcoming/katilda_and_lier.txt
- forge-gui/res/cardsfolder/upcoming/slimefoot_and_squee.txt
- forge-gui/res/cardsfolder/upcoming/the_kenriths_royal_funeral.txt
- forge-gui/res/cardsfolder/upcoming/towashi.txt
@tool4ever I assume The Kenriths' Royal Funeral needs some sort of cleanup when it changes zones ?
> 4 MOC 1 MAT cards

- forge-game/src/main/java/forge/game/GameAction.java
> GameAction: cleanup card on the battlefield gaining Keyword from castSA

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCanAttackDefender.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCantAttackBlock.java
- forge-gui/res/cardsfolder/d/dragon_hunter.txt
try to reduce the amount of fake Keywords into Static and Replacement Effects
only Dragon Hunter has this ability, and no other card can gain it anyway
it is a small start for my next CantBlock refactor
> Dragon Hunter as StaticAbility instead of fake Keyword

- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
> Improve PumpAi for cards like Pearlspear Courier

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-game/src/main/java/forge/game/mana/ManaPool.java
- forge-gui/res/cardsfolder/c/cemetery_prowler.txt
- forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
> Improve payment test on hybrid shards

- forge-gui/res/cardsfolder/upcoming/breach_the_multiverse.txt
- forge-gui/res/cardsfolder/upcoming/chandra_hopes_beacon.txt
- forge-gui/res/cardsfolder/upcoming/heliod_the_radiant_dawn_heliod_the_warped_eclipse.txt
- forge-gui/res/cardsfolder/upcoming/moment_of_truth.txt
MOM: Added card scripts for the following cards:
- Heliod, the Radiant Dawn // Heliod, the Warped Eclipse
- Breach the Multiverse
- Chandra, Hope's Beacon
- Moment of Truth
Note: Thank you to @tool4ever for suggesting a tweak in Heliod's script that circumvents additional engine changes!
> MOM: Heliod, the Radiant Dawn + 3 cards

- forge-gui/res/cardsfolder/upcoming/arek_false_goldwarden.txt
- forge-gui/res/cardsfolder/upcoming/bladehold_cleaver.txt
- forge-gui/res/cardsfolder/upcoming/blightwing_whelp.txt
- forge-gui/res/cardsfolder/upcoming/march_toward_perfection.txt
- forge-gui/res/cardsfolder/upcoming/mephidross_slime.txt
> YONE 5 cards

- forge-gui/res/cardsfolder/g/golden_argosy.txt
Golden argosy should be legendary. So I add supertype Legendary to it. 
reference: [Golden Argosy](https://scryfall.com/card/dmu/230/golden-argosy)
> Updated golden_argosy.txt

- forge-gui/res/editions/Kamigawa Neon Dynasty.txt
- forge-gui/res/lists/net-decks-brawl.txt
- forge-gui/res/lists/net-decks.txt
Also changed token name in NEO edition due to #2576
> Add some net decks by gös

- forge-gui/res/cardsfolder/l/laezel_githyanki_warrior.txt
- forge-gui/res/cardsfolder/upcoming/magmatic_scorchwing.txt
- forge-gui/res/cardsfolder/upcoming/phyresis_roach.txt
Two straightforward ones I did before I got sucked into working on SeekEffect 😁
> magmatic_scorchwing.txt phyresis_roach.txt

- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkinFont.java
- add long dash to default chars
> move textrafonts to Assets

- forge-gui-mobile/src/forge/adventure/scene/ArenaScene.java
https://user-images.githubusercontent.com/9781539/222961748-c7b78af7-d411-412a-b2f3-470aaa947761.mp4
> update ArenaScene moveby action

- forge-gui/res/cardsfolder/upcoming/contagion_dispenser.txt
- forge-gui/res/cardsfolder/upcoming/skullpiercer_gnat.txt
YMOM: Added scripts for alchemy All Will Be One cards Contagion Dispenser and Skullpiercer Gnat.
- Contagion Dispenser
- Skullpiercer Gnat
> YONE: Contagion Dispenser + Skullpiercer Gnat

- forge-gui-mobile/src/forge/adventure/data/EffectData.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
-fix effectdata classcast startCardsInCommandZone
> adjust effect timing, center particle effect animation based on scale

- forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
- forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
- forge-gui/pom.xml
- forge-gui/res/adventure/Shandalar/ui/save_load.json
- forge-gui/res/adventure/Shandalar/ui/save_load_portrait.json
- fix layout, add table header and scrollable content
- update textratypist
> update SaveLoadScene, InventoryScene

- forge-gui-mobile/src/forge/adventure/scene/DeckSelectScene.java
- forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
- forge-gui-mobile/src/forge/adventure/scene/PlayerStatisticScene.java
- forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
- forge-gui/res/adventure/Shandalar/ui/deck_selector.json
- forge-gui/res/adventure/Shandalar/ui/deck_selector_portrait.json
- can use mouse wheel if availble to scroll
> update scrollable tables

- forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
- forge-core/src/main/java/forge/StaticData.java
- forge-game/src/main/java/forge/game/ability/effects/TwoPilesEffect.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityCanAttackDefender.java
- forge-game/src/main/java/forge/game/trigger/TriggerSacrificed.java
- forge-gui/res/cardsfolder/p/phyrexian_portal.txt
> Fix Make an Example

- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
- forge-ai/src/main/java/forge/ai/ability/DamagePreventAi.java
- forge-ai/src/main/java/forge/ai/ability/DebuffAi.java
- forge-ai/src/main/java/forge/ai/ability/ProtectAi.java
- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
- forge-ai/src/main/java/forge/ai/ability/SetStateAi.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/PumpAllEffect.java
- forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RepeatEffect.java
- forge-gui/res/cardsfolder/d/desolation.txt
- forge-gui/res/cardsfolder/w/wave_of_vitriol.txt
Most important fixes the last main place in AbilityUtils where changing the host controller of a triggered ability on the stack might mess up the results.
> Some cleanup

- forge-gui-mobile/src/forge/adventure/character/MapActor.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- move the offset calculation inside MapActor
> fix particle effect initial position

- forge-gui-mobile/pom.xml
- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/GuiMobile.java
- forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/util/UIActor.java
- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FDelayLoadImage.java
- forge-gui-mobile/src/forge/assets/FSkinTexture.java
- forge-gui-mobile/src/forge/screens/ClosingScreen.java
- forge-gui-mobile/src/forge/screens/SplashScreen.java
- forge-gui-mobile/src/forge/screens/TransitionScreen.java
- forge-gui/pom.xml
- move loading of textures directly to assetmanager
- move textratypist to gui-mobile
> refactor texture loading

- forge-gui-mobile/src/forge/Forge.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkin.java
- directly create texture if absolute path is not available
- dispose overridden texture
> update initial skin texture load

- forge-gui-mobile/src/forge/adventure/character/MapActor.java
- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/assets/FSkin.java
- forge-gui-mobile/src/forge/assets/FSkinImage.java
- forge-gui-mobile/src/forge/card/CardImageRenderer.java
- forge-gui-mobile/src/forge/screens/match/views/VAvatar.java
- forge-gui-mobile/src/forge/toolbox/FCardPanel.java
- this should clear up unused texture
- fix startup on empty res/skins folder
> refactor FSkin Texture loading

- forge-gui/res/cardsfolder/h/hurkyls_prodigy.txt
- forge-gui/res/cardsfolder/s/skyline_savior.txt
- forge-gui/res/cardsfolder/upcoming/mephidross_slime.txt
closes #2666
coses #2664 
closes #2663
> three alchemy fixes 

- forge-gui-mobile/src/forge/adventure/character/MapActor.java
- forge-gui-mobile/src/forge/assets/Assets.java
- forge-gui-mobile/src/forge/sound/AudioClip.java
- forge-gui-mobile/src/forge/sound/AudioMusic.java
- let AssetManager handle game audio
- unload particles and music after playing it to save RAM
> update AudioClip, AudioMusic

- forge-gui-desktop/src/main/java/forge/GuiDesktop.java
- forge-gui-mobile/src/forge/GuiMobile.java
- forge-gui-mobile/src/forge/screens/limited/LoadSealedScreen.java
- forge-gui-mobile/src/forge/screens/planarconquest/ConquestPlaneswalkersScreen.java
- forge-gui-mobile/src/forge/screens/planarconquest/NewConquestScreen.java
- forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestData.java
- forge-gui/src/main/java/forge/gui/interfaces/IGuiBase.java
- forge-gui/src/main/java/forge/localinstance/achievements/Achievement.java
- forge-gui/src/main/java/forge/localinstance/achievements/PlaneswalkerAchievements.java
- use PaperCard images as overlay if available for Achievement Trophies
> update Achievement Trophies

- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-core/src/main/java/forge/card/CardRulesPredicates.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/mana/ManaPool.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui-desktop/src/main/java/forge/screens/match/controllers/CField.java
- forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
This makes sure when canceling a SA the partial mana isn't sent back to pool in opposite order (which could lead to misplays when it has riders etc)
> Remove some obsolete stuff

- forge-ai/src/main/java/forge/ai/AiCostDecision.java
- forge-game/src/main/java/forge/game/cost/Cost.java
- forge-game/src/main/java/forge/game/cost/CostExile.java
- forge-gui/res/cardsfolder/t/thelon_of_havenwood.txt
- forge-gui/src/main/java/forge/player/HumanCostDecision.java
> Fix Thelon

- forge-gui/res/editions/Shadows of the Past.txt
- forge-gui/res/editions/Shadows over Innistrad Remastered.txt
- forge-gui/res/editions/The Lord of the Rings Tales of Middle-earth Commander.txt
- forge-gui/res/editions/The Lord of the Rings Tales of Middle-earth.txt
I know it makes no sense but the set code SIS for Shadows of the Past is confirmed from Arena data
> Edition updates: LTR, LTC, SIR, SIS (new)

- forge-gui/res/cardsfolder/upcoming/aragorn_and_arwen_wed.txt
- forge-gui/res/cardsfolder/upcoming/radagast_wizard_of_wilds.txt
- forge-gui/res/cardsfolder/upcoming/sam_loyal_attendant.txt
- forge-gui/res/cardsfolder/upcoming/sauron_the_lidless_eye.txt
- forge-gui/res/cardsfolder/upcoming/the_shire.txt
3 from main set 2 from commander set
> LOTR 5 cards

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-gui/res/cardsfolder/l/lethal_scheme.txt
- forge-gui/res/cardsfolder/v/venerated_loxodon.txt
> AbilityUtils: add Convoked as DefinedCards

- forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
in case of opponents Vorinclex, you could choose to put MORE counters on it, so when it is halved, you still get the amount you wanted
> CountersPutEffect: remove MaxFromEffect, let the CounterTable handle it

- forge-gui/res/cardsfolder/upcoming/mount_doom.txt
- forge-gui/res/cardsfolder/upcoming/reprieve.txt
- forge-gui/res/cardsfolder/upcoming/you_cannot_pass!.txt
LTR: Add card scripts for spoiled LTR cards Mount Doom, Reprieve, and You Cannot Pass!
- Mount Doom
- Reprieve
- You Cannot Pass!
> LTR: Mount Doom + 2 cards

- forge-gui-mobile/src/forge/Graphics.java
- forge-gui-mobile/src/forge/adventure/character/MapActor.java
- forge-gui-mobile/src/forge/adventure/data/SettingData.java
- forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
- forge-gui-mobile/src/forge/adventure/scene/UIScene.java
- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/MapDialog.java
- forge-gui-mobile/src/forge/adventure/util/UIActor.java
- forge-gui/res/cardsfolder/t/tyvar_jubilant_brawler.txt
- use delta time for fading volume while accessing dialog with audio.
- add optional day/night settings for title BG (based on device time)
- fix collision timing
- update tyvar jubilant brawler cost
> Fix Collision, Smoother Volume Fade, Add Night / Day settings for TitleBG

- forge-gui/res/cardsfolder/upcoming/wrenn_and_realmbreaker.txt
MOM: Add script for showcased card Wrenn and Realmbreaker.
- Wrenn and Realmbreaker
> MOM: Wrenn and Realmbreaker

- forge-gui/res/cardsfolder/upcoming/doric_natures_warden_doric_owlbear_avenger.txt
- forge-gui/res/cardsfolder/upcoming/edgin_larcenous_lutenist.txt
- forge-gui/res/cardsfolder/upcoming/forge_neverwinter_charlatan.txt
- forge-gui/res/cardsfolder/upcoming/holga_relentless_rager.txt
- forge-gui/res/cardsfolder/upcoming/simon_wild_magic_sorcerer.txt
- forge-gui/res/cardsfolder/upcoming/xenk_paladin_unbroken.txt
> SLD 6 new DND cards

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/GameEntity.java
- forge-game/src/main/java/forge/game/ability/effects/CountersProliferateEffect.java
- forge-game/src/main/java/forge/game/card/CounterEnumType.java
- forge-game/src/main/java/forge/game/cost/CostPayShards.java
- forge-game/src/main/java/forge/game/event/GameEventPlayerShardsChanged.java
- forge-game/src/main/java/forge/game/event/IGameEventVisitor.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-game/src/main/java/forge/game/player/PlayerView.java
- forge-game/src/main/java/forge/trackable/TrackableProperty.java
- forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
- forge-gui-mobile/src/forge/screens/match/views/VPlayerPanel.java
- forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
- forge-gui/src/main/java/forge/player/HumanCostDecision.java
- forge-gui/src/main/java/forge/player/HumanPlay.java
- remove Mana Shards as countertype
> refactor ManaShards

- forge-gui-mobile/src/forge/adventure/character/MapActor.java
- forge-gui-mobile/src/forge/adventure/stage/MapSprite.java
- some poi initial data are null so refactor how it parses the poi data to prevent blackscreen when the biome chunks are loaded
> fix blackscreen

- forge-game/src/main/java/forge/game/GameEntityCounterTable.java
- forge-gui/res/cardsfolder/o/one_with_the_multiverse.txt
- forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java
> Madness fix

- forge-gui/src/main/java/forge/gamemodes/match/input/InputConfirm.java
- show cardview if possible for playeffect card (regardless of zone)
> update inputconfirm cardview

- forge-game/src/main/java/forge/game/ability/effects/CountersProliferateEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
> Fix wasCastByYou

- forge-game/src/main/java/forge/game/ability/effects/InvestigateEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
- forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
- forge-gui/res/cardsfolder/h/haakon_stromgald_scourge.txt
- forge-gui/res/cardsfolder/m/malicious_affliction.txt
- forge-gui/res/cardsfolder/t/tempting_contract.txt
- Fix one opponent declining stopping the investigating on _Will the Wise_ completely
- Closes #2791
> Investigate fixes

- forge-gui/res/adventure/Shandalar/maps/map/magetower_13.tmx
removed threat range and patrols for all the doppelgangers
> Magetower_13 fix doppelganger

- forge-gui/res/cardsfolder/upcoming/orthion_hero_of_lavabrink.txt
- forge-gui/res/cardsfolder/upcoming/ravenous_sailback.txt
- forge-gui/res/cardsfolder/upcoming/ruins_recluse.txt
- forge-gui/res/cardsfolder/upcoming/surrak_and_goreclaw.txt
orthion_hero_of_lavabrink.txt
ravenous_sailback.txt
ruins_recluse.txt
surrak_and_goreclaw.txt
> MOM: 4 cards

- forge-gui/res/cardsfolder/upcoming/esper.txt
- forge-gui/res/cardsfolder/upcoming/gimbal_gremlin_prodigy.txt
- forge-gui/res/cardsfolder/upcoming/kasla_the_broken_halo.txt
- forge-gui/res/cardsfolder/upcoming/nyx.txt
- forge-gui/res/cardsfolder/upcoming/sidar_jabari_of_zhalfir.txt
- forge-gui/res/tokenscripts/r_0_0_a_gremlin.txt
Don't know if it's useful to assign deckhints to plane cards ?
> MOC 5 cards

- forge-gui/res/cardsfolder/upcoming/interdisciplinary_mascot.txt
- forge-gui/res/cardsfolder/upcoming/seer_of_stolen_sight.txt
- forge-gui/res/cardsfolder/upcoming/terror_of_towashi.txt
- forge-gui/res/cardsfolder/upcoming/zephyr_winder.txt
- forge-gui/res/cardsfolder/upcoming/zurgo_and_ojutai.txt
interdisciplinary_mascot.txt
seer_of_stolen_sight.txt
terror_of_towashi.txt
zephyr_winder.txt
zurgo_and_ojutai.txt
> MOM: 1 Apr (5 cards)

- forge-core/src/main/java/forge/item/PaperToken.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- set imagekey for transformable tokens using their name + set_code
> update PaperToken, CardFactory

- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui-mobile/src/forge/adventure/world/World.java
> fix rerun when POI placement failed

- forge-gui/res/cardsfolder/upcoming/kogla_and_yidaro.txt
- forge-gui/res/cardsfolder/upcoming/omen_hawker.txt
- forge-gui/res/cardsfolder/upcoming/oracle_of_tragedy.txt
- forge-gui/res/cardsfolder/upcoming/phyrexian_censor.txt
- forge-gui/res/cardsfolder/upcoming/pile_on.txt
- forge-gui/res/cardsfolder/upcoming/zimone_and_dina.txt
MOM: Add card scripts for six spoiled MOM cards:
- Kogla and Yidaro
- Omen Hawker
- Oracle of Tragedy
- Phyrexian Censor
- Pile On
- Zimone and Dina
> MOM: Kogla and Yidaro + 5 cards

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
> Fix incomplete replacement caching leading to StackOverflow

- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/Controls.java
- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui-mobile/src/forge/assets/Assets.java
> fix minimap generation, update textrafont property

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/trigger/TriggerCounterAddedOnce.java
- forge-gui/res/cardsfolder/upcoming/axgard_artisan.txt
- forge-gui/res/cardsfolder/upcoming/botanical_brawler.txt
Closes #2784
This adds `FirstTime` to the AddedOnce Trigger
> CounterAddedOnce add FirstTime

- forge-gui/res/cardsfolder/r/reckless_racer.txt
- forge-gui/res/cardsfolder/upcoming/bola_slinger.txt
- forge-gui/res/cardsfolder/upcoming/chomping_kavu.txt
- forge-gui/res/cardsfolder/upcoming/consuming_aetherborn.txt
- forge-gui/res/cardsfolder/upcoming/gloomfang_mauler.txt
- forge-gui/res/cardsfolder/upcoming/golden_scale_aeronaut.txt
- forge-gui/res/cardsfolder/upcoming/hangar_scrounger.txt
- forge-gui/res/cardsfolder/upcoming/redcap_heelslasher.txt
- forge-gui/res/cardsfolder/upcoming/saiba_cryptomancer.txt
- forge-gui/res/cardsfolder/upcoming/scorn_blade_berserker.txt
- forge-gui/res/cardsfolder/upcoming/serpent_blade_assailant.txt
- forge-gui/res/cardsfolder/upcoming/sigiled_sentinel.txt
Nothing wild, but I did not test each and every one of these so a quick scan for typos and whatnot! 😁
> last MOM backup cards

- forge-core/src/main/java/forge/util/ImageUtil.java
- forge-gui-desktop/src/main/java/forge/util/SwingImageFetcher.java
- forge-gui-mobile/src/forge/util/LibGDXImageFetcher.java
- forge-gui/res/editions/Planechase 2012.txt
- forge-gui/res/editions/Planechase Anthology.txt
- forge-gui/res/editions/Planechase.txt
- update imagefetcher to parse custom id for planes/phenomenon outside their original setcode
> update old planechase editions

- forge-gui/res/cardsfolder/c/cavalier_of_thorns.txt
- forge-gui/res/cardsfolder/e/epitaph_golem.txt
- forge-gui/res/cardsfolder/k/komas_faithful.txt
- forge-gui/res/cardsfolder/m/mistveil_plains.txt
- forge-gui/res/cardsfolder/s/sequestered_stash.txt
- forge-gui/res/cardsfolder/upcoming/cosmic_hunger.txt
- forge-gui/res/cardsfolder/upcoming/furnace_reins.txt
- forge-gui/res/cardsfolder/upcoming/halo_charged_skaab.txt
- forge-gui/res/cardsfolder/upcoming/into_the_fire.txt
- forge-gui/res/cardsfolder/upcoming/onakke_javelineer.txt
cosmic_hunger.txt
furnace_reins.txt
halo_charged_skaab.txt
into_the_fire.txt
onakke_javelineer.txt
…and some cleanup
> MOM: 5 easy ones and some related old card cleanup

- forge-gui/res/cardsfolder/upcoming/angelic_intervention.txt
- forge-gui/res/cardsfolder/upcoming/artistic_refusal.txt
- forge-gui/res/cardsfolder/upcoming/complete_the_circuit.txt
- forge-gui/res/cardsfolder/upcoming/crystal_carapace.txt
- forge-gui/res/cardsfolder/upcoming/disturbing_conversion.txt
- forge-gui/res/cardsfolder/upcoming/dreg_recycler.txt
- forge-gui/res/cardsfolder/upcoming/epharas_dispersal.txt
- forge-gui/res/cardsfolder/upcoming/etched_familiar.txt
- forge-gui/res/cardsfolder/upcoming/expedition_lookout.txt
- forge-gui/res/cardsfolder/upcoming/failed_conversion.txt
> MOM 10 cards

- forge-gui/res/cardsfolder/a/allure_of_the_unknown.txt
- forge-gui/res/cardsfolder/f/fevered_suspicion.txt
- forge-gui/res/cardsfolder/s/swindlers_scheme.txt
- forge-gui/res/cardsfolder/t/tibalts_trickery.txt
- forge-gui/res/cardsfolder/w/wand_of_wonder.txt
OptionalDecider is not wired up for this
> improve some old PlayEffect card scripts

- forge-adventure/src/main/java/forge/adventure/editor/QuestStageEdit.java
- forge-gui-mobile/src/forge/adventure/character/DialogActor.java
- forge-gui-mobile/src/forge/adventure/character/EnemySprite.java
- forge-gui-mobile/src/forge/adventure/data/AdventureQuestData.java
- forge-gui-mobile/src/forge/adventure/data/AdventureQuestStage.java
- forge-gui-mobile/src/forge/adventure/scene/ArenaScene.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- forge-gui-mobile/src/forge/adventure/util/AdventureQuestController.java
- forge-gui/res/adventure/Shandalar/maps/map/main_story/forest_capital.tmx
- forge-gui/res/adventure/Shandalar/maps/map/main_story/island_capital.tmx
- forge-gui/res/adventure/Shandalar/maps/map/main_story/mountain_capital.tmx
- forge-gui/res/adventure/Shandalar/maps/map/main_story/plains_capital.tmx
- forge-gui/res/adventure/Shandalar/maps/map/main_story/swamp_capital.tmx
- forge-gui/res/adventure/Shandalar/world/points_of_interest.json
- forge-gui/res/adventure/Shandalar/world/quests.json
Removed a cave with no enemies from potential targets for Clear quests
Town quest offer dialog will not be available again after accepting / declining it once.
Reordered Arena rewards, added rares to card pool (500 gold -> item -> 2 rare or mythic rares)
> Adventure updates

- forge-gui-mobile/src/forge/adventure/data/AdventureQuestData.java
- forge-gui-mobile/src/forge/adventure/data/AdventureQuestStage.java
- fix classcastexception-cannot-assign-instance-of since the old value is of UUID and changed to String, old file will not load...
> fix loading error classcastexception

- forge-game/src/main/java/forge/game/mana/Mana.java
- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
> Fix Autopay test selecting same mana multiple times

- forge-adventure/src/main/java/forge/adventure/editor/DialogTree.java
- forge-gui-mobile/src/forge/adventure/data/AdventureQuestData.java
- forge-gui-mobile/src/forge/adventure/data/AdventureQuestStage.java
- forge-gui-mobile/src/forge/adventure/util/AdventureQuestController.java
- forge-gui-mobile/src/forge/adventure/world/World.java
- forge-gui/res/adventure/Shandalar/world/quests.json
Arena quest stage objectives now available, one quest added. 
Removed extra trigger for accepting quest in "A Vision of Destruction" offer dialog. 
Minor dialog enhancements.
> Adventure quest updates

- forge-gui/res/lists/planeswalker-achievements.txt
Saga achievements need additional code support, so they will come in a separate PR.
> Marek14's achievements for MOM, part 1 (Planeswalkers)

- forge-game/src/main/java/forge/game/replacement/ReplaceDamage.java
extra check for ReplaceDamage to redirect damage to Battle
> Update ReplaceDamage with Battle checks

- forge-gui/res/cardsfolder/upcoming/scrollshift.txt
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=607051  
Confirmed that it doesnt draw card if the target gets instantly shrouded on the stack.
> upcoming card scripting for Scrollshift[MOM]

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/Commander Legends Battle for Baldur's Gate.txt
Simple implementation of CLB booster draft
> Booster Draft: CLB

- forge-gui/res/cardsfolder/upcoming/order_of_the_mirror_order_of_the_alabaster_host.txt
- forge-gui/res/cardsfolder/upcoming/placid_rottentail.txt
- forge-gui/res/cardsfolder/upcoming/pyretic_prankster_glistening_goremonger.txt
- forge-gui/res/cardsfolder/upcoming/rals_reinforcements.txt
- forge-gui/res/cardsfolder/upcoming/ramosian_greatsword.txt
- forge-gui/res/cardsfolder/upcoming/realmbreakers_grasp.txt
- forge-gui/res/cardsfolder/upcoming/render_inert.txt
- forge-gui/res/cardsfolder/upcoming/sandstalker_moloch.txt
- forge-gui/res/cardsfolder/upcoming/seed_of_hope.txt
- forge-gui/res/cardsfolder/upcoming/seraph_of_new_capenna_seraph_of_new_phyrexia.txt
- forge-gui/res/cardsfolder/upcoming/shivan_branch_burner.txt
This should wrap up the remaining MOM cards, nothing too hard here
> MOM 11 cards

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-ai/src/main/java/forge/ai/ability/RollPlanarDiceAi.java
- forge-game/src/main/java/forge/game/CardTraitBase.java
- forge-game/src/main/java/forge/game/GlobalRuleChange.java
- forge-game/src/main/java/forge/game/PlanarDice.java
- forge-game/src/main/java/forge/game/ability/AbilityKey.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ReplaceEffect.java
- forge-game/src/main/java/forge/game/ability/effects/RollPlanarDiceEffect.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/phase/PhaseHandler.java
- forge-game/src/main/java/forge/game/player/PlayerController.java
- forge-game/src/main/java/forge/game/replacement/ReplacePlanarDiceResult.java
- forge-game/src/main/java/forge/game/replacement/ReplaceRollPlanarDice.java
- forge-game/src/main/java/forge/game/replacement/ReplacementType.java
- forge-game/src/main/java/forge/util/MessageUtil.java
- forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
- forge-gui/res/cardsfolder/c/chaotic_aether.txt
- forge-gui/res/cardsfolder/f/fractured_powerstone.txt
- forge-gui/res/cardsfolder/k/krosa.txt
- forge-gui/res/cardsfolder/upcoming/ichor_elixir.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
> MOC: Ichor Elixir + support

- forge-gui/res/cardsfolder/upcoming/invasion_of_theros_ephara_ever_sheltering.txt
> Invasion of Theros

- forge-gui/res/cardsfolder/upcoming/elspeths_talent.txt
- forge-gui/res/cardsfolder/upcoming/lilianas_talent.txt
- forge-gui/res/cardsfolder/upcoming/rowans_talent.txt
- forge-gui/res/cardsfolder/upcoming/teferis_talent.txt
- forge-gui/res/cardsfolder/upcoming/viviens_talent.txt
MOC: Added five card scripts for spoiled MOM commander cards:
- Elspeth's Talent
- Liliana's Talent
- Rowan's Talent
- Teferi's Talent
- Vivien's Talent
> MOC: The Talent Cycle

- forge-gui/res/cardsfolder/upcoming/djeru_and_hazoret.txt
- forge-gui/res/cardsfolder/upcoming/kroxa_and_kunoros.txt
- forge-gui/res/cardsfolder/upcoming/rona_herald_of_invasion_rona_tolarian_obliterator.txt
- forge-gui/res/cardsfolder/upcoming/sheoldred_the_true_scriptures.txt
- forge-gui/res/cardsfolder/upcoming/urabrask_the_great_work.txt
MOM: Add card scripts for five spoiled MOM cards:
- Djeru and Hazoret
- Kroxa and Kunoros
- Rona, Herald of Invasion // Rona, Tolarian Obliterator
- Sheoldred // The True Scriptures
- Urabrask // The Great Work
> MOM: 5 more Legends

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/effects/DamageDealEffect.java
- forge-game/src/main/java/forge/game/card/CardDamageMap.java
- forge-gui/res/cardsfolder/l/lacerate_flesh.txt
- forge-gui/res/cardsfolder/m/megatron_tyrant_megatron_destructive_force.txt
- forge-gui/res/cardsfolder/r/ryu_world_warrior.txt
- forge-gui/res/cardsfolder/v/vikya_scorching_stalwart.txt
> Rework ExcessSVar

- forge-gui/res/cardsfolder/upcoming/open_the_way.txt
- forge-gui/res/cardsfolder/upcoming/pia_nalaar_consul_of_revival.txt
- forge-gui/res/cardsfolder/upcoming/plargg_and_nassari.txt
- forge-gui/res/cardsfolder/upcoming/rocco_street_chef.txt
- forge-gui/res/cardsfolder/upcoming/sigarda_font_of_blessings.txt
some of these were quite complicated
> MAT 5 cards

- forge-gui/res/adventure/Shandalar/custom_cards/slobad_boss_effect.txt
- forge-gui/res/cardsfolder/upcoming/kolaghan_warmonger.txt
- forge-gui/res/cardsfolder/upcoming/leyline_immersion.txt
- forge-gui/res/cardsfolder/upcoming/markov_baron.txt
- forge-gui/res/cardsfolder/upcoming/nahiri_forged_in_fury.txt
- forge-gui/res/cardsfolder/upcoming/nahiris_resolve.txt
- forge-gui/res/cardsfolder/upcoming/samut_vizier_of_naktamun.txt
- forge-gui/res/cardsfolder/upcoming/sarkhan_soul_aflame.txt
I think "if entered the battlefield" is an intervening trigger ?
> MAT 7 cards

- forge-game/src/main/java/forge/game/staticability/StaticAbility.java
> MayPlayLimit is not copiable

- forge-game/src/main/java/forge/game/card/Card.java
- forge-gui/res/cardsfolder/a/abaddon_the_despoiler.txt
- forge-gui/res/cardsfolder/upcoming/zhulodok_void_gorger.txt
When Multiple Keywords are added via StaticAbility, they all get an idx to makes duplicates possible
Closes #3077
> Stored kw idx

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/cost/CostReveal.java
- forge-gui/res/cardsfolder/a/aberrant_researcher_perfected_form.txt
- forge-gui/res/cardsfolder/d/devout_invocation.txt
- forge-gui/res/cardsfolder/m/minsc_boo_timeless_heroes.txt
This seems to fix the problems I've noted in #2512 in a pretty clean fashion.
A bigger rewrite can always be done another time if still needed.
> Tweak TextChange transformation

- forge-gui-mobile/src/forge/adventure/util/RewardActor.java
- forge-gui/res/adventure/Shandalar/world/quests.json
> fix quest completed crash

- forge-gui/res/cardsfolder/t/trygon_prime.txt
https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=580965
> Remove incorrect vigilance ability

- forge-core/src/main/java/forge/card/CardType.java
- forge-gui/res/lists/TypeLists.txt
- forge-gui/src/main/java/forge/model/FModel.java
Don't know if this is needed for now but might be usefull in the future ?
> Plane types to TypeList.txt

- forge-ai/src/main/java/forge/ai/ability/PlayAi.java
- forge-gui/res/cardsfolder/a/aetherworks_marvel.txt
- forge-gui/res/cardsfolder/z/zask_skittering_swarmlord.txt
- forge-gui/res/cardsfolder/z/ziatoras_envoy.txt
Support playing lands (e. g. _Gix, Yawgmoth Praetor_)
> PlayAi tweak

- forge-ai/src/main/java/forge/ai/AiAttackController.java
- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
- forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
- forge-ai/src/main/java/forge/ai/SpecialAiLogic.java
- forge-ai/src/main/java/forge/ai/ability/AnimateAi.java
- forge-ai/src/main/java/forge/ai/ability/AttachAi.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/CopyPermanentAi.java
- forge-ai/src/main/java/forge/ai/ability/DebuffAi.java
- forge-ai/src/main/java/forge/ai/ability/EffectAi.java
- forge-ai/src/main/java/forge/ai/ability/PlayAi.java
- forge-ai/src/main/java/forge/ai/ability/ProtectAi.java
- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
- forge-ai/src/main/java/forge/ai/ability/SetStateAi.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-gui/src/main/java/forge/player/PlayerControllerHuman.java
- forge-gui/src/main/java/forge/player/TargetSelection.java
> Use current shard when trying to pay with combo mana

- forge-core/src/main/java/forge/card/CardType.java
- forge-gui/src/main/java/forge/model/FModel.java
Closes #3117 
MultiwordTypes is now generated by the TypesList file looking for Subtypes with "` `"
> CardType: fill MultiwordTypes by TypeList

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
- forge-game/src/main/java/forge/game/keyword/KeywordInterface.java
This should fix the Henzie Bug mentioned in #3116
> KeywordInstance: store the idx to use it later

- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ConniveEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/combat/CombatUtil.java
- forge-gui/res/cardsfolder/i/invasion_of_fiora_marchesa_resolute_monarch.txt
- forge-gui/res/cardsfolder/l/lorehold_command.txt
- forge-gui/res/cardsfolder/n/nahiri_forged_in_fury.txt
- forge-gui/res/cardsfolder/n/niv_mizzet_supreme.txt
- forge-gui/res/cardsfolder/o/outlaws_merriment.txt
- forge-gui/res/cardsfolder/r/radha_heir_to_keld.txt
@Hanmac 
New _Niv-Mizzet, Supreme_ got future-broken by https://github.com/Card-Forge/forge/commit/9d2ecf
There's probably another way it could be fixed but I'm not sure how it could be done with castKeyword and the `OptionalCost.Jumpstart` that modifies the spell?
Closes #3115
> Some script and engine fixes

- forge-ai/src/main/java/forge/ai/ability/PlayAi.java
- forge-ai/src/main/java/forge/ai/ability/UntapAi.java
- forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
- forge-game/src/main/java/forge/game/trigger/Trigger.java
- forge-gui/res/cardsfolder/e/etali_primal_conqueror_etali_primal_sickness.txt
- forge-gui/res/cardsfolder/z/zareth_san_the_trickster.txt
Followup to #3031
This makes cards like _Lightfoot Rogue_ work again
> Treat replaceAbilityText bandaids

- forge-game/src/main/java/forge/game/replacement/ReplaceAddCounter.java
- forge-game/src/main/java/forge/game/replacement/ReplaceMoved.java
- forge-game/src/main/java/forge/game/replacement/ReplacementEffect.java
@Hanmac
I checked with past versions of ReplacementHandler and it seems like we never had code to handle this.
So I just took the logic you used for _Mowu_ and made it a helper.
> Fix Containment Priest exiling itself

- forge-game/src/main/java/forge/game/trigger/Trigger.java
> Fix Freeze

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
This should be fine even on Android?
> Fix PatternSyntaxException

- forge-ai/src/main/java/forge/ai/AiAttackController.java
Since we are now actually removing the creatures we guesstimated as profitable crew choices we really don't need this simple heuristic anymore for the most part.
Actually the whole thing was broken anyway because unanimated vehicles would have never ended up in the blockers array in the first place.
I kept the last remaining special logic block but ideally we can get rid of it later too, so it can be used to greater effect outside of assault evaluation.
> Clean up attack logic vs vehicles

- forge-gui/res/cardsfolder/upcoming/anduril_flame_of_the_west.txt
- forge-gui/res/cardsfolder/upcoming/arwen_mortal_queen.txt
- forge-gui/res/cardsfolder/upcoming/assault_on_osgiliath.txt
- forge-gui/res/cardsfolder/upcoming/banish_from_edoras.txt
- forge-gui/res/cardsfolder/upcoming/barad_dur.txt
- forge-gui/res/cardsfolder/upcoming/rivendell.txt
> LTR 5 cards

- forge-gui/res/puzzle/PS_MOM3.pzl
- forge-gui/res/puzzle/PS_MOM4.pzl
- forge-gui/res/puzzle/PS_MOM5.pzl
- Added puzzles PS_MOM4, PS_MOM5
- Fixed the name of PS_MOM3.
> Add puzzles PS_MOM4, PS_MOM5

- forge-core/src/main/java/forge/deck/DeckFormat.java
- forge-gui/src/main/java/forge/deck/DeckProxy.java
> update hasLegalCardsPredicate when deckconformance is turned off

- forge-gui/res/puzzle/MTGP_01.pzl
- forge-gui/res/puzzle/MTGP_02.pzl
- forge-gui/res/puzzle/MTGP_03.pzl
- forge-gui/res/puzzle/MTGP_04.pzl
- forge-gui/res/puzzle/MTGP_05.pzl
- forge-gui/res/puzzle/MTGP_06.pzl
- forge-gui/res/puzzle/MTGP_08.pzl.disabled
- forge-gui/res/puzzle/MTGP_09.pzl
Source: https://mtgpuzzles.com
Puzzle 7 is incompatible due to the use of substandard cards.
Puzzle 8 is currently disabled because the AI is very stupid with it due to the lack of AI support for Ashling the Pilgrim.
> Add several puzzles from MtgPuzzles.com

- forge-gui-android/AndroidManifest.xml
- forge-gui-android/src/forge/app/Main.java
- allow deck manager to import shared text intent
> [Android] support receiving text intent

- forge-core/src/main/java/forge/card/DeckHints.java
- forge-gui/res/cardsfolder/c/chandras_ignition.txt
- forge-gui/res/cardsfolder/d/death_by_dragons.txt
- forge-gui/res/cardsfolder/f/flame_fusillade.txt
- forge-gui/res/cardsfolder/f/flames_of_the_raze_boar.txt
- forge-gui/res/cardsfolder/f/fractured_identity.txt
- forge-gui/res/cardsfolder/h/hellish_rebuke.txt
- forge-gui/res/cardsfolder/k/kamiz_obscura_oculus.txt
- forge-gui/res/cardsfolder/k/karn_liberated.txt
- forge-gui/res/cardsfolder/k/kusari_gama.txt
- forge-gui/res/cardsfolder/m/mirrorweave.txt
- forge-gui/res/cardsfolder/p/plaguecrafter.txt
- forge-gui/res/cardsfolder/p/public_execution.txt
- forge-gui/res/cardsfolder/t/territorial_hellkite.txt
- forge-gui/res/cardsfolder/u/unexpected_allies.txt
- forge-gui/res/cardsfolder/upcoming/dunland_crebain.txt
> Script updates

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
- forge-gui-desktop/src/test/java/forge/ai/simulation/SpellAbilityPickerSimulationTest.java
- forge-gui/res/cardsfolder/b/balor.txt
- forge-gui/res/cardsfolder/p/prophetic_titan.txt
- forge-gui/res/cardsfolder/s/sakashimas_will.txt
- forge-gui/res/cardsfolder/s/szats_will.txt
- forge-gui/res/cardsfolder/upcoming/witch_king_bringer_of_ruin.txt
> Fix full replacement not reaching caller if chain contains update result

- forge-ai/src/main/java/forge/ai/ability/TwoPilesAi.java
- forge-gui/res/cardsfolder/e/esix_fractal_bloom.txt
- forge-gui/res/cardsfolder/p/protean_raider.txt
- forge-gui/res/cardsfolder/upcoming/peregrin_took.txt
https://www.reddit.com/r/askajudge/comments/14i7jhh/how_would_these_interact/
> Esix is copy layer

- forge-gui/res/blockdata/blocks.txt
- forge-gui/res/draft/rankings.txt
- forge-gui/res/editions/The Lord of the Rings Tales of Middle-earth.txt
- Added LTR draft along with MOM rankings updates
https://magic.wizards.com/en/news/feature/collecting-the-lord-of-the-rings-tales-of-middle-earth
> Booster Draft: LTR with MOM updates

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-gui/res/cardsfolder/a/aetherplasm.txt
- forge-gui/res/cardsfolder/b/brimaz_king_of_oreskos.txt
- forge-gui/res/cardsfolder/s/share_the_spoils.txt
> Fix wrong decider when copying trigger

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ability/SacrificeAi.java
- forge-gui/res/cardsfolder/m/minsc_boo_timeless_heroes.txt
This is slightly experimental, not sure if it can be somehow simplified to avoid the partial duplication of code, but this is the best I can do for now.
Fixes issue #3353
> AI logic for Minsc & Boo, Timeless Heroes.

- forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
- forge-gui-mobile/src/forge/adventure/stage/MapStage.java
- forge-gui-mobile/src/forge/adventure/stage/WorldStage.java
- add flicker effect when restoring player collision after map/world duel
> update player collision

- forge-gui/res/cardsfolder/upcoming/stew_the_coneys.txt
https://scryfall.com/card/ltr/189/stew-the-coneys
> Fix LTR Stew The Coneys mana cost

- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/SacrificeAi.java
- forge-gui/res/cardsfolder/c/consecrate_consume.txt
- forge-gui/res/cardsfolder/g/gales_redirection.txt
- forge-gui/res/cardsfolder/s/serras_emissary.txt
Fixes #500 
Fixes #3370 
Fixes #3378 when it comes to Serra's Adversary (can definitely use further AI logic improvements for ChooseType in general)
> Basic AI for Gale's Redirection, Consecrate // Consume, Serra's Emissary

- forge-ai/src/main/java/forge/ai/AiBlockController.java
- forge-ai/src/main/java/forge/ai/SpecialCardAi.java
- forge-ai/src/main/java/forge/ai/ability/FightAi.java
- forge-game/src/main/java/forge/game/player/Player.java
- forge-gui/res/cardsfolder/b/bog_down.txt
- forge-gui/res/cardsfolder/c/caligo_skin_witch.txt
- forge-gui/res/cardsfolder/g/grothama_all_devouring.txt
- forge-gui/res/cardsfolder/h/hypnotic_cloud.txt
- forge-gui/res/cardsfolder/k/khorvaths_fury.txt
- forge-gui/res/cardsfolder/p/probe.txt
- forge-gui/res/cardsfolder/t/tempting_wurm.txt
Fixes #3406 
Fixes #3407 
Fixes #3408
Improves Banding AI vs. Trample.
> AI: Various logic fixes and improvements

- forge-ai/src/main/java/forge/ai/AiController.java
- forge-ai/src/main/java/forge/ai/ComputerUtil.java
- forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
- forge-ai/src/main/java/forge/ai/ability/PumpAi.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-gui/res/cardsfolder/c/congregation_at_dawn.txt
- forge-gui/res/cardsfolder/d/dwarven_recruiter.txt
- forge-gui/res/cardsfolder/g/goblin_recruiter.txt
- forge-gui/res/cardsfolder/i/insidious_dreams.txt
- forge-gui/res/cardsfolder/l/lim_duls_vault.txt
- forge-gui/res/cardsfolder/n/nova_pentacle.txt
- forge-gui/res/cardsfolder/s/scouting_trek.txt
- forge-gui/res/cardsfolder/u/ulvenwald_tracker.txt
> Fix missing reorder

- forge-gui/res/editions/Jumpstart.txt
Fixes the rarity for Angelic Page (JMP).
> Angelic Page (JMP) was printed at common, not uncommon.

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/cost/CostPayment.java
- forge-gui/src/main/java/forge/gamemodes/match/input/InputAttack.java
> Banding fix

- forge-gui/src/main/java/forge/gamemodes/match/input/InputSelectTargets.java
> InputSelectTargets: able to remove Target

- forge-gui/res/cardsfolder/c/composer_of_spring.txt
- forge-gui/res/editions/Commander Masters.txt
> Implemented Composer of Spring

- forge-gui/res/cardsfolder/n/nyxborn_behemoth.txt
- forge-gui/res/cardsfolder/o/onakke_oathkeeper.txt
- forge-gui/res/cardsfolder/o/ondu_spiritdancer.txt
> Implemented Ondu Spiritdancer, Nyxborn Behemoth and Onakke Oathkeeper

- forge-gui/res/cardsfolder/upcoming/calamity_of_the_titans.txt
- forge-gui/res/cardsfolder/upcoming/darksteel_monolith.txt
- forge-gui/res/cardsfolder/upcoming/omarthis_ghostfire_initiate.txt
- forge-gui/res/cardsfolder/upcoming/rise_of_the_eldrazi.txt
- forge-gui/res/cardsfolder/upcoming/skittering_cicada.txt
- forge-gui/res/cardsfolder/upcoming/ugins_mastery.txt
Don't really know any deckhints for these colorless cards
> CMM 6 cards 21-7

- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
Closes  #3414
@tool4ever can you test this?
> Card: store created CardTraits by Text Change: Volrath’s Shapeshifter

- forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
-should fix ai effect logic
-translation should be done somewhere
> remove translation

- forge-gui/res/cardsfolder/upcoming/faramir_prince_of_ithilien.txt
SVar:X:PlayerCountDefinedChosenPlayer$HasPropertyattackedYouTheirCurrentTurn isn't currently working
> LTR Faramir Prince of Ithilien

- forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
- forge-game/src/main/java/forge/game/cost/Cost.java
- forge-game/src/main/java/forge/game/cost/CostAdjustment.java
- forge-gui/res/cardsfolder/k/knight_rampager.txt
> Fix Carth the Lion not affecting X loyalty abilities

- forge-gui/res/lists/altwin-achievements.txt
- forge-gui/res/lists/planeswalker-achievements.txt
- forge-gui/res/puzzle/PS_LTR1.pzl
- forge-gui/res/puzzle/PS_LTR2.pzl
- Add LTR/LTC achievements by Marek
- Added puzzles PS_LTR1 and PS_LTR2.
> Add LTR/LTC achievements by Marek + add two LTR puzzles.

- forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
- forge-game/src/main/java/forge/game/GameAction.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeXEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
- forge-game/src/main/java/forge/game/ability/effects/ControlSpellEffect.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardFactory.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/card/CardUtil.java
- forge-game/src/main/java/forge/game/combat/Combat.java
- forge-game/src/main/java/forge/game/cost/CostExileFromStack.java
- forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java
- forge-game/src/main/java/forge/game/staticability/StaticAbility.java
- forge-game/src/main/java/forge/game/trigger/TriggerBecomesTarget.java
- forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
- forge-game/src/main/java/forge/game/zone/MagicStack.java
- forge-gui/res/cardsfolder/o/of_one_mind.txt
- forge-gui/src/main/java/forge/player/TargetSelection.java
First cleanup run for StackInstances.
OptionalCosts don't need to be stored in the Card and will just be checked via castSA.
> Remove some obsolete code

- forge-gui-mobile/src/forge/adventure/data/RewardData.java
- forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
- forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
- forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
- forge-gui-mobile/src/forge/adventure/util/UIActor.java
- forge-gui/res/adventure/common/ui/items.json
- forge-gui/res/adventure/common/ui/items_portrait.json
- forge-gui/res/adventure/common/ui/shardtrader.json
> show quantity of items on Adventure Shop

- forge-game/src/main/java/forge/game/ability/effects/RepeatEachEffect.java
- forge-game/src/main/java/forge/game/ability/effects/VoteEffect.java
- forge-game/src/main/java/forge/util/MessageUtil.java
- forge-gui/res/cardsfolder/b/buzzing_whack_a_doodle.txt
- forge-gui/res/cardsfolder/t/tivit_seller_of_secrets.txt
- forge-gui/res/cardsfolder/upcoming/cirdan_the_shipwright.txt
- forge-gui/res/cardsfolder/upcoming/elrond_of_the_white_council.txt
- forge-gui/res/cardsfolder/upcoming/trap_the_trespassers.txt
- forge-gui/res/cardsfolder/v/vonas_hunger.txt
- forge-gui/res/languages/de-DE.properties
- forge-gui/res/languages/en-US.properties
- forge-gui/res/languages/es-ES.properties
- forge-gui/res/languages/fr-FR.properties
- forge-gui/res/languages/it-IT.properties
- forge-gui/res/languages/ja-JP.properties
- forge-gui/res/languages/pt-BR.properties
- forge-gui/res/languages/zh-CN.properties
> Secret Council mechanic and cards

- forge-gui/res/cardsfolder/b/breaking_of_the_fellowship.txt
https://scryfall.com/card/ltr/117/breaking-of-the-fellowship
Probably was copied from [Mutiny](https://scryfall.com/card/rix/106/mutiny)
> Breaking of the Fellowship: Fix mana cost

- forge-gui/res/adventure/common/maps/map/fort/fort_white_1.tmx
- forge-gui/res/adventure/common/maps/map/fort/fort_white_2.tmx
- forge-gui/res/adventure/common/maps/map/fort/fort_white_3.tmx
- forge-gui/res/adventure/common/maps/map/fort/fort_white_4.tmx
These must have been removed somehow during a previous revamp
> Fix for white castles not loading

- forge-game/src/main/java/forge/game/Game.java
- forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
- forge-game/src/main/java/forge/game/player/PlayerCollection.java
- forge-gui/res/cardsfolder/a/approach_of_the_second_sun.txt
- forge-gui/res/cardsfolder/upcoming/gollum_obsessed_stalker.txt
Just a little tweaking of some old code in EffectEffect to get this to work tidily.
> gollum_obsessed_stalker.txt and support

- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/combat/AttackConstraints.java
- forge-game/src/main/java/forge/game/combat/AttackRequirement.java
- forge-game/src/main/java/forge/game/staticability/StaticAbilityMustAttack.java
- forge-gui/res/cardsfolder/s/seeker_of_slaanesh.txt
- forge-gui/res/cardsfolder/t/trove_of_temptation.txt
Probably corner cases left, though that's more related to the overall implemenation of attack requirements.
But the AI will actually be less suicidal against it, compared to before:
> Seeker of Slaanesh

- forge-gui/res/editions/Secret Lair Drop Series.txt
- forge-gui/res/quest/commanderprecons/Angels They're Just Like Us, but Cooler and with Wings [SLD] [2023].dck
- forge-gui/res/quest/commanderprecons/Eldrazi Unbound [CMM] [2023].dck
- forge-gui/res/quest/commanderprecons/Elven Council [LTC] [2023].dck
- forge-gui/res/quest/commanderprecons/Enduring Enchantments [CMM] [2023].dck
- forge-gui/res/quest/commanderprecons/Food and Fellowship [LTC] [2023].dck
- forge-gui/res/quest/commanderprecons/From Cute to Brute [SLD] [2023].dck
- forge-gui/res/quest/commanderprecons/Planeswalker Party [CMM] [2023].dck
- forge-gui/res/quest/commanderprecons/Riders of Rohan [LTC] [2023].dck
- forge-gui/res/quest/commanderprecons/Sliver Swarm [CMM] [2023].dck
- forge-gui/res/quest/commanderprecons/The Host of Mordor [LTC] [2023].dck
- forge-gui/res/quest/commanderprecons/The Ruinous Powers [40K] [2022].dck
The SLD set file needs to be changed for the Angel deck to work.
> Update Commander Precons

- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/ability/effects/StoreSVarEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TokenEffect.java
- forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
- forge-gui/res/cardsfolder/p/plague_of_vermin.txt
- closes #1216 
No counters or effects
> plague_of_vermin.txt refactor + support

- forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
- forge-ai/src/main/java/forge/ai/ability/ManaEffectAi.java
- forge-gui/res/cardsfolder/t/tyvar_the_bellicose.txt
> Logic for Tyvar the Bellicose

- forge-gui/res/editions/Magic 2019.txt
- forge-gui/res/editions/Magic 2020.txt
Boosters did include cards from the precon decks and the buy a box card.
> Fix Core Set 2019/2020 booster

- forge-game/src/main/java/forge/game/ForgeScript.java
- forge-game/src/main/java/forge/game/GameActionUtil.java
- forge-game/src/main/java/forge/game/ability/AbilityUtils.java
- forge-game/src/main/java/forge/game/card/Card.java
- forge-game/src/main/java/forge/game/card/CardProperty.java
- forge-game/src/main/java/forge/game/keyword/Keyword.java
- forge-game/src/main/java/forge/game/spellability/OptionalCost.java
- forge-game/src/main/java/forge/game/spellability/SpellAbility.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityCondition.java
- forge-game/src/main/java/forge/game/spellability/SpellAbilityVariables.java
- forge-gui/res/cardsfolder/upcoming/realm_scorcher_hellkite.txt
- forge-gui/res/cardsfolder/upcoming/torch_the_tower.txt
First Bargain card
others might need more with Condition Params
> WOE: Bargain

- forge-gui-desktop/src/main/java/forge/view/arcane/PlayArea.java
- forge-gui-mobile/src/forge/screens/match/TargetingOverlay.java
- forge-gui-mobile/src/forge/screens/match/views/VCardDisplayArea.java
> fix GUI for attached panels with each other
