Card-Forge/forge

forge-gui/res/adventure/common/maps/map/magetower/magetower_14.tmx
forge-gui/res/adventure/common/maps/map/magetower/magetower_8.tmx
forge-gui/res/adventure/common/sprites/enemy/beast/wolf.atlas

Removed extra collisions including those causing player to get stuck on 2nd level, cleaned up walls, added additional dialog to gate interaction.

Adventure - Blue Mage Tower updates

---

forge-game/src/main/java/forge/game/ability/effects/ChangeCombatantsEffect.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/d/dwarven_landslide.txt
forge-gui/res/cardsfolder/p/portal_mage.txt
forge-gui/res/cardsfolder/t/triumph_of_saint_katherine.txt
forge-gui/res/cardsfolder/w/windshaper_planetar.txt
forge-gui/res/cardsfolder/w/wulfgar_of_icewind_dale.txt

Commander Masters Update Bulletin

---

forge-gui/res/cardsfolder/upcoming/a_tale_for_the_ages.txt
forge-gui/res/cardsfolder/upcoming/archon_of_the_wild_rose.txt
forge-gui/res/cardsfolder/upcoming/armory_mice.txt
forge-gui/res/cardsfolder/upcoming/ashioks_reaper.txt
forge-gui/res/cardsfolder/upcoming/back_for_seconds.txt
forge-gui/res/cardsfolder/upcoming/belligerent_of_the_ball.txt
forge-gui/res/cardsfolder/upcoming/bitter_chill.txt
forge-gui/res/cardsfolder/upcoming/boundary_lands_ranger.txt
forge-gui/res/cardsfolder/upcoming/bramble_familiar_fetch_quest.txt
forge-gui/res/cardsfolder/upcoming/brave_the_wilds.txt
forge-gui/res/cardsfolder/upcoming/chancellor_of_tales.txt
forge-gui/res/cardsfolder/upcoming/three_blind_mice.txt

Back for Seconds was a pain but I think I got it working

WOE 12 cards

---

forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/gamemodes/match/AbstractGuiGame.java
forge-gui/src/main/java/forge/gamemodes/match/input/InputLockUI.java

prevent UI lockup

---

forge-ai/src/main/java/forge/ai/simulation/GameStateEvaluator.java
forge-core/src/main/java/forge/card/CardRules.java
forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityActivateAbilityAsIfHaste.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityAssignCombatDamageAsUnblocked.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantBeCopied.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantBecomeMonarch.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityIgnoreLegendRule.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityUnspentMana.java
forge-gui-desktop/src/main/java/forge/toolbox/imaging/FCardImageRenderer.java
forge-gui/src/main/java/forge/gui/card/CardScriptInfo.java

Luckily without the SplitType no new objects were created because of this but still pretty nasty

CardRules: fix specialize faces on regular cards

---

forge-ai/src/main/java/forge/ai/ability/ImmediateTriggerAi.java
forge-gui/res/cardsfolder/g/grist_the_hunger_tide.txt
forge-gui/res/puzzle/PS_LTR3.pzl

A simple solution, but works so far :)
Also added PS_LTR3 (the puzzle), since it seemed a quick and easy addition.

AI improvement for Grist, the Hunger Tide + puzzle PS_LTR3.

---

forge-gui/res/cardsfolder/upcoming/sweettooth_witch.txt
forge-gui/res/cardsfolder/upcoming/syr_ginger_the_meal_ender.txt
forge-gui/res/cardsfolder/upcoming/taken_by_nightmares.txt
forge-gui/res/cardsfolder/upcoming/talions_messenger.txt
forge-gui/res/cardsfolder/upcoming/tanglespan_lookout.txt
forge-gui/res/cardsfolder/upcoming/tempest_hart_scan_the_clouds.txt
forge-gui/res/cardsfolder/upcoming/the_apprentices_folly.txt
forge-gui/res/cardsfolder/upcoming/the_end.txt
forge-gui/res/cardsfolder/upcoming/the_huntsmans_redemption.txt
forge-gui/res/cardsfolder/upcoming/the_irencrag.txt
forge-gui/res/cardsfolder/upcoming/threadbind_clique_rip_the_seams.txt
forge-gui/res/cardsfolder/upcoming/twining_twins_swift_spiral.txt
forge-gui/res/cardsfolder/upcoming/two_headed_hunter_twice_the_rage.txt
forge-gui/res/cardsfolder/upcoming/virtue_of_courage_embereth_blaze.txt
forge-gui/res/cardsfolder/upcoming/virtue_of_strength_garenbrig_growth.txt
forge-gui/res/cardsfolder/upcoming/woodland_acolyte_mend_the_wilds.txt

WOE 16 cards

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameEntity.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerDamageDone.java
forge-gui/res/cardsfolder/upcoming/imodane_the_pyrohammer.txt

TriggerDamageDone: add Cause and targetedBy

---

forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
forge-ai/src/main/java/forge/ai/ability/UntapAi.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/cost/Cost.java
forge-game/src/main/java/forge/game/cost/CostPartMana.java
forge-game/src/main/java/forge/game/cost/CostPayment.java
forge-game/src/main/java/forge/game/mana/ManaCostBeingPaid.java
forge-game/src/main/java/forge/game/mana/ManaPool.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-gui/res/cardsfolder/c/confounding_conundrum.txt
forge-gui/res/cardsfolder/h/hogaak_arisen_necropolis.txt
forge-gui/res/cardsfolder/i/imperiosaur.txt
forge-gui/res/cardsfolder/m/myr_superion.txt
forge-gui/res/cardsfolder/rebalanced/a-security_rhox.txt
forge-gui/res/cardsfolder/s/security_rhox.txt
forge-gui/res/cardsfolder/upcoming/beseech_the_mirror.txt
forge-gui/res/cardsfolder/upcoming/restless_spire.txt
forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
forge-gui/src/main/java/forge/player/HumanPlay.java

- Closes #3755
- Fix restrictions getting lost (e.g. paying mana for _Hogaak_ cost raise after `MayPlayWithOutManaCost$`)

Support for Throne of Eldraine

---

forge-gui/res/cardsfolder/upcoming/loamcrafter_faun.txt
forge-gui/res/cardsfolder/upcoming/tegwyll_duke_of_splendor.txt
forge-gui/res/cardsfolder/upcoming/tegwylls_scouring.txt
forge-gui/res/cardsfolder/upcoming/throne_of_eldraine.txt
forge-gui/res/cardsfolder/upcoming/timber_paladin.txt
forge-gui/res/cardsfolder/upcoming/unfinished_business.txt
forge-gui/res/editions/Wilds of Eldraine Commander.txt
forge-gui/res/quest/commanderprecons/Fae Dominion [WOC] [2023].dck
forge-gui/res/quest/commanderprecons/Virtue and Valor [WOC] [2023].dck

Throne of Eldraine cost of the draw ability not working

WOC last 6 cards + WOC Commander decks

---

forge-ai/src/main/java/forge/ai/ability/PlayAi.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java

Seems it only worked before 866c096 because we weren't using the wrong passed card source.

Cascade fix

---

forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/ability/effects/RegenerationEffect.java

I feel like at this point they're just using your questions to patch the corner cases 💩 
Does it need more cleanup?

Regeneration: controller always taps

---

forge-game/src/main/java/forge/game/card/Card.java

skip adventure spell if card is already onadventure

---

forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/DamagePreventEffectBase.java
forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndCombatPhaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndTurnEffect.java
forge-game/src/main/java/forge/game/ability/effects/FogEffect.java
forge-game/src/main/java/forge/game/ability/effects/HauntEffect.java
forge-game/src/main/java/forge/game/ability/effects/MeldEffect.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/ability/effects/RegenerateBaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/ReplaceDamageEffect.java
forge-game/src/main/java/forge/game/ability/effects/ReplaceSplitDamageEffect.java
forge-game/src/main/java/forge/game/ability/effects/SkipPhaseEffect.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/cost/CostExile.java
forge-game/src/main/java/forge/game/cost/CostExileFromStack.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/replacement/ReplacePayLife.java
forge-game/src/main/java/forge/game/replacement/ReplacementType.java
forge-gui/res/cardsfolder/upcoming/ashiok_wicked_manipulator.txt
forge-gui/res/tokenscripts/b_1_1_nightmare_exile_counter.txt
forge-gui/src/main/java/forge/gamemodes/match/input/InputConfirmMulligan.java
forge-gui/src/main/java/forge/player/HumanPlay.java

i still have some questions about the Cause Param or if the exile function should get more move Params

Player: first step for Ashiok

---

forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java

Fix Lion's Eye Diamond check

---

forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/mana/ManaCostBeingPaid.java
forge-gui/res/cardsfolder/p/primitive_justice.txt

- Closes #3775
- Fix _Morophon, the Boundless_ reducing cost of _Emblazoned Golem_

Improve cost reduction logic for X shards with color restriction

---

forge-gui-mobile/src/forge/adventure/data/SettingData.java
forge-gui-mobile/src/forge/adventure/scene/RewardScene.java
forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
forge-gui-mobile/src/forge/adventure/util/Controls.java
forge-gui-mobile/src/forge/adventure/util/RewardActor.java
forge-gui-mobile/src/forge/assets/Assets.java
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties

add Display Shop Item names option

---

forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/staticability/StaticAbility.java
forge-gui/res/cardsfolder/s/spawnsire_of_ulamog.txt

~~@Hanmac~~
~~what you think about this approach to avoid always calculating sideboard?~~
~~Or maybe I should just add Sideboard to `forEachCardInGame` when called there 🤔~~

Allow Spawnsire of Ulamog to cast changelings

---

forge-gui/res/puzzle/PS_WOE1.pzl

- Added puzzle PS_WOE1 - Possibility Storm: Wilds of Eldraine #01

Add puzzle PS_WOE1

---

forge-gui/res/adventure/common/maps/map/catlair/catlair_white_1_lionden.tmx

Catlair tile fix

---

forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

- mobileGUI confirm handles null cardview

prevent NPE

---

forge-game/src/main/java/forge/game/card/Card.java

needed for Questing Druid // Seek the Beast (WOE)

additional check

---

forge-gui/res/adventure/common/decks/standard/banditleader_hellbent.dck
forge-gui/res/adventure/common/decks/standard/flame_elemental.dck
forge-gui/res/adventure/common/decks/standard/merfolk_lord2.dck
forge-gui/res/adventure/common/decks/standard/whitewizard_medium_aggro.dck
forge-gui/res/adventure/common/world/enemies.json

Thanks to @kevlahnota for fixing the card script.

fix Tibalt's item amount + removal P9 from loottables

---

forge-game/src/main/java/forge/game/card/CardUtil.java
forge-gui/res/cardsfolder/c/carnival_carnage.txt
forge-gui/res/cardsfolder/upcoming/ruby_daring_tracker.txt

LKI: fix wrong state on stack

---

forge-gui-mobile/src/forge/assets/FSkin.java

fixes black screen on startup if somehow the preffered skin folder is not accessible or missing

update theme check

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/effects/ZoneExchangeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/cost/CostPayment.java
forge-gui/res/cardsfolder/b/braidss_frightful_return.txt
forge-gui/res/cardsfolder/p/path_of_the_ghosthunter.txt
forge-gui/src/main/java/forge/player/HumanPlay.java

- Fix missing ChangesZoneAll trigger for Offering/Emerge/Aura swap
- Fix so spell copies can find objects that convoked original

Some tweaks related to KW costs

---

forge-core/src/main/java/forge/card/CardType.java
forge-game/src/main/java/forge/game/ability/effects/ChooseCardNameEffect.java
forge-gui/res/cardsfolder/s/syr_carah_the_bold.txt
forge-gui/res/cardsfolder/s/syr_elenora_the_discerning.txt
forge-gui/res/cardsfolder/s/syr_faren_the_hengehammer.txt
forge-gui/res/cardsfolder/y/yorvo_lord_of_garenbrig.txt

Fix MultiwordType parsing

---

forge-core/src/main/java/forge/util/Aggregates.java
forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
forge-gui/res/cardsfolder/l/long_list_of_the_ents.txt
forge-gui/res/cardsfolder/r/realms_befitting_my_majesty.txt
forge-gui/res/cardsfolder/u/undercity_plunder.txt

-closes #3754 
Long List of the Ents seem to work in my testing

LTC Long List of the Ents + two card fixes

---

forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java
forge-gui/res/cardsfolder/a/astral_cornucopia.txt
forge-gui/res/cardsfolder/c/chrome_courier.txt
forge-gui/res/cardsfolder/f/faiths_shield.txt
forge-gui/res/cardsfolder/s/skull_storm.txt
forge-gui/res/cardsfolder/s/spectral_shield.txt
forge-gui/res/cardsfolder/upcoming/mosswood_dreadknight_dread_whispers.txt
forge-gui/res/cardsfolder/v/verazol_the_split_current.txt
forge-gui/res/cardsfolder/y/yannik_scavenging_sentinel.txt
forge-gui/res/cardsfolder/y/yorion_sky_nomad.txt

Support for Display of Power

---

forge-ai/src/main/java/forge/ai/SpellApiToAi.java
forge-ai/src/main/java/forge/ai/ability/TimeTravelAi.java
forge-game/src/main/java/forge/game/ability/ApiType.java
forge-game/src/main/java/forge/game/ability/effects/TimeTravelEffect.java
forge-game/src/main/java/forge/game/card/CardPredicates.java
forge-gui/res/cardsfolder/upcoming/wibbly-wobbly_timey-wimey.txt

Closes #3503 
i wanted to add the Tenth Doctor, but the AttackTrigger is a bit to tricky right now

add Timetravel Effect

---

forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
forge-gui/res/cardsfolder/c/city_of_brass.txt

AI shouldn't kill itself when tapping City of Brass.

Improve AI logic for City of Brass.

---

forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/b/braidss_frightful_return.txt
forge-gui/res/cardsfolder/upcoming/clockwork_droid.txt

MagicStack: don't leave old targets on card ability

---

forge-game/src/main/java/forge/game/TriggerReplacementBase.java

ChangeText: Pass intrinsic to overridingAbility

---

forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
forge-gui/res/cardsfolder/b/bruna_light_of_alabaster.txt
forge-gui/res/cardsfolder/upcoming/stormkeld_curator_giant_secrets.txt

script credit @Simisays (note there were a couple extra lines on the Curator I removed)

YWOE stormkeld_curator_giant_secrets.txt + support

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/cost/CostPayment.java
forge-gui/res/cardsfolder/upcoming/adipose_offspring.txt
forge-gui/res/tokenscripts/w_2_2_alien.txt
forge-gui/src/main/java/forge/player/HumanPlay.java

Closes #3888 
Does AI need some tests or Logic for this?

AbilityUtils: add Emerged for Adipose Offering

---

forge-ai/src/main/java/forge/ai/ability/DamageAiBase.java
forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
forge-ai/src/main/java/forge/ai/ability/EffectAi.java

Improve AI for Sorin, Vengeful Broodlord and similar + Fix Roiling Vortex AI logic

---

forge-game/src/main/java/forge/game/ability/effects/ChooseCardEffect.java
forge-gui/res/cardsfolder/upcoming/gallifrey_falls_no_more.txt
forge-gui/res/cardsfolder/upcoming/gardens_of_tranquil_repose.txt
forge-gui/res/cardsfolder/upcoming/heaven_sent.txt
forge-gui/res/cardsfolder/upcoming/hotel_of_fears.txt
forge-gui/res/cardsfolder/upcoming/karvanista_loyal_lupari_lupari_shield.txt
forge-gui/res/cardsfolder/upcoming/kate_stewart.txt
forge-gui/res/cardsfolder/upcoming/laser_screwdriver.txt
forge-gui/res/cardsfolder/upcoming/last_night_together.txt
forge-gui/res/cardsfolder/upcoming/lunar_hatchling.txt
forge-gui/res/cardsfolder/upcoming/me_the_immortal.txt
forge-gui/res/lists/TypeLists.txt

Last Night Together is not working as intended. The duration is not correct

WHO 10 cards

---

forge-core/src/main/java/forge/card/CardRules.java
forge-core/src/main/java/forge/deck/DeckFormat.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/CEditorConstructed.java
forge-gui/res/cardsfolder/upcoming/amy_pond.txt
forge-gui/res/cardsfolder/upcoming/donna_noble.txt
forge-gui/res/cardsfolder/upcoming/romana_ii.txt
forge-gui/res/cardsfolder/upcoming/rory_williams.txt
forge-gui/res/cardsfolder/upcoming/sarah_jane_smith.txt
forge-gui/src/main/java/forge/deck/DeckgenUtil.java

WHO - Doctor's companion and support

---

forge-gui/res/cardsfolder/upcoming/kate_stewart.txt
forge-gui/res/cardsfolder/upcoming/run_for_your_life.txt
forge-gui/res/cardsfolder/upcoming/sally_sparrow.txt
forge-gui/res/cardsfolder/upcoming/sergeant_john_benton.txt
forge-gui/res/cardsfolder/upcoming/sibyllin_soothsayer.txt
forge-gui/res/cardsfolder/upcoming/sisterhood_of_karn.txt
forge-gui/res/cardsfolder/upcoming/sonic_screwdriver.txt
forge-gui/res/cardsfolder/upcoming/sontaran_general.txt
forge-gui/res/cardsfolder/upcoming/star_whale.txt
forge-gui/res/cardsfolder/upcoming/start_the_tardis.txt
forge-gui/res/cardsfolder/upcoming/the_cyber_controller.txt

WHO 9 cards + 2 fixes

---

forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/ReplaceEffect.java
forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardView.java
forge-game/src/main/java/forge/game/player/PlayerController.java
forge-game/src/main/java/forge/game/replacement/ReplaceRollDice.java
forge-game/src/main/java/forge/game/replacement/ReplacementType.java
forge-game/src/main/java/forge/trackable/TrackableProperty.java
forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
forge-gui/res/cardsfolder/b/bamboozling_beeble.txt
forge-gui/res/cardsfolder/b/barbarian_class.txt
forge-gui/res/cardsfolder/c/centaur_of_attention.txt
forge-gui/res/cardsfolder/p/pixie_guide.txt
forge-gui/res/cardsfolder/w/wyll_blade_of_frontiers.txt
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

bamboozling_beeble.txt and centaur_of_attention.txt and Support

---

forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/player/PlayerController.java
forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
forge-gui/res/cardsfolder/c/catalyst_stone.txt
forge-gui/res/cardsfolder/f/fluctuator.txt
forge-gui/res/cardsfolder/m/mana_matrix.txt
forge-gui/res/cardsfolder/p/planar_gate.txt
forge-gui/res/cardsfolder/s/stone_calendar.txt
forge-gui/res/cardsfolder/u/urzas_filter.txt
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/gamemodes/match/input/InputPassPriority.java
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

One of the few good ideas I've seen from some other experimental project 😜 
While I do suck at GUI stuff I feel like clicking/tapping your player portrait actually makes it work quite smoothly: hidden enough to not confuse new players and still quick to toggle for power user... 🤹‍♂️ 
Closes #1519

Full Control

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CounterEnumType.java

Might need Different Color
and need some Card examples

LCI: Finality counter

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
forge-ai/src/main/java/forge/ai/SpecialCardAi.java
forge-ai/src/main/java/forge/ai/ability/ChooseTypeAi.java
forge-ai/src/main/java/forge/ai/ability/CountersPutAi.java
forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java
forge-ai/src/main/java/forge/ai/ability/EffectAi.java
forge-gui/res/cardsfolder/a/aether_vial.txt
forge-gui/res/cardsfolder/r/ratchet_bomb.txt
forge-gui/res/cardsfolder/v/vanquishers_banner.txt

Fixes #3995.
Fixes #3996.
Fixes #4001.
Fixes #3989.
Slight refactoring.

Improve several AI routines.

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/upcoming/sovereign_okinec_ahau.txt

LCI: sovereign_okinec_ahau.txt + support

---

forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
forge-game/src/main/java/forge/game/ability/effects/CleanUpEffect.java
forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardUtil.java
forge-gui/res/cardsfolder/b/braidss_frightful_return.txt
forge-gui/res/cardsfolder/i/ironclaw_curse.txt
forge-gui/res/cardsfolder/upcoming/doomsday_confluence.txt
forge-gui/res/cardsfolder/upcoming/the_huntsmans_redemption.txt
forge-gui/res/cardsfolder/upcoming/yenna_redtooth_regent.txt
forge-gui/src/main/java/forge/player/HumanPlay.java
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Doomsday Confluence and support

---

forge-gui/res/cardsfolder/upcoming/weeping_angel.txt

Credit to Glorax for the script
closes #4016

WHO Weeping Angel

---

forge-game/src/main/java/forge/game/card/Card.java
forge-gui/res/cardsfolder/c/cavalier_of_flame.txt
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties

add (Transforms from X.) to Card Detail

---

forge-gui-desktop/src/main/java/forge/deckchooser/FDeckChooser.java
forge-gui-desktop/src/main/java/forge/screens/home/quest/DialogChooseFormats.java
forge-gui-desktop/src/main/java/forge/screens/home/quest/DialogChoosePoolDistribution.java
forge-gui-desktop/src/main/java/forge/screens/match/VAssignCombatDamage.java
forge-gui-desktop/src/main/java/forge/screens/match/VAssignGenericAmount.java
forge-gui-desktop/src/main/java/forge/screens/match/views/VPrompt.java
forge-gui-mobile/src/forge/adventure/scene/DeckSelectScene.java
forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
forge-gui-mobile/src/forge/adventure/scene/StartScene.java
forge-gui-mobile/src/forge/screens/online/OnlineLobbyScreen.java
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/gamemodes/gauntlet/GauntletWinLoseController.java
forge-gui/src/main/java/forge/gamemodes/match/input/InputAttack.java
forge-gui/src/main/java/forge/gamemodes/match/input/InputLondonMulligan.java
forge-gui/src/main/java/forge/gamemodes/match/input/InputPassPriority.java
forge-gui/src/main/java/forge/gamemodes/tournament/TournamentWinLoseController.java
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

Watching the `k` switch between upper and lower case has been a pet peeve of mine for a while.
Looks like for most languages the two entries were identical anyway.

merge lblOk and lblOK

---

forge-gui/res/cardsfolder/a/aesi_tyrant_of_gyre_strait.txt
forge-gui/res/cardsfolder/a/architect_of_the_untamed.txt
forge-gui/res/cardsfolder/c/courser_of_kruphix.txt
forge-gui/res/cardsfolder/d/druid_class.txt
forge-gui/res/cardsfolder/e/evolution_sage.txt
forge-gui/res/cardsfolder/g/greensleeves_maro_sorcerer.txt
forge-gui/res/cardsfolder/m/maja_bretagard_protector.txt
forge-gui/res/cardsfolder/o/omnath_locus_of_the_roil.txt
forge-gui/res/cardsfolder/p/primeval_bounty.txt
forge-gui/res/cardsfolder/r/roaring_earth.txt
forge-gui/res/cardsfolder/rebalanced/a-druid_class.txt
forge-gui/res/cardsfolder/s/stone_seeder_hierophant.txt
forge-gui/res/cardsfolder/t/tatyova_benthic_druid.txt
forge-gui/res/cardsfolder/t/tireless_tracker.txt
forge-gui/res/cardsfolder/t/toggo_goblin_weaponsmith.txt
forge-gui/res/cardsfolder/t/trench_behemoth.txt
forge-gui/res/cardsfolder/v/vinelasher_kudzu.txt

Updated 17 cards that were retroactively given the Landfall ability word. I've tested the changes I made and believe they are the only ones necessary, but if more needs to be done. let me know and I can do another request, or someone else can handle it.

Landfall updates

---

forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-gui/res/cardsfolder/upcoming/psychic_paper.txt

WHO Psychic Paper and support

---

forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
forge-gui/res/cardsfolder/c/charnel_troll.txt
forge-gui/res/cardsfolder/n/nylea_keen_eyed.txt
forge-gui/res/cardsfolder/upcoming/dinotomaton.txt
forge-gui/res/cardsfolder/upcoming/kellan_daring_traveler_journey_on.txt
forge-gui/res/cardsfolder/upcoming/pit_of_offerings.txt
forge-gui/res/cardsfolder/upcoming/rampaging_spiketail.txt
forge-gui/res/cardsfolder/upcoming/sinuous_benthisaur.txt
forge-gui/res/lists/TypeLists.txt

Added DestZone2Optional to DigEffect for Kellan and Nylea
Needed to add a Cave so I could test Sinuous - all the other caves are in other PRs still

LCI: Kellan (DigEffect) and some dinos (and a cave)

---

forge-gui/src/main/java/forge/gamemodes/gauntlet/GauntletIO.java
forge-gui/src/main/java/forge/gamemodes/gauntlet/GauntletWinLoseController.java
forge-gui/src/main/java/forge/gamemodes/tournament/TournamentIO.java
forge-gui/src/main/java/forge/gamemodes/tournament/TournamentWinLoseController.java

fix loading/crash from earlier gauntlet/tournament save

---

forge-gui-mobile/src/forge/card/CardRenderer.java

move status symbol

---

forge-ai/src/main/java/forge/ai/ability/SurveilAi.java

fix Consider

---

forge-gui/res/adventure/common/maps/map/garruk/garruk.tmx

Fixed collision under bridge, moved all river tiles to layer "Lowest Background"

Adventure - Garruk river cleanup

---

forge-game/src/main/java/forge/game/ability/effects/PeekAndRevealEffect.java

fix pools of becoming

---

forge-gui/res/cardsfolder/upcoming/an_unearthly_child.txt
forge-gui/res/cardsfolder/upcoming/dan_lewis.txt
forge-gui/res/cardsfolder/upcoming/ian_chesterton.txt
forge-gui/res/cardsfolder/upcoming/jo_grant.txt
forge-gui/res/cardsfolder/upcoming/spectrox_mines.txt
forge-gui/res/cardsfolder/upcoming/the_caves_of_androzani.txt
forge-gui/res/cardsfolder/upcoming/the_day_of_the_doctor.txt
forge-gui/res/cardsfolder/upcoming/the_dining_car.txt
forge-gui/res/cardsfolder/upcoming/truth_or_consequences.txt
forge-gui/res/cardsfolder/upcoming/unit_headquarters.txt
forge-gui/res/lists/TypeLists.txt
forge-gui/res/tokenscripts/b_2_2_human_rogue.txt

The Day of the Doctor probably needs some cleanup on the last ability. Thoughts ?

10 more WHO

---

forge-gui-mobile/src/forge/assets/FSkinTexture.java

- resets texture to null to reload

fix missing planes not downloading

---

forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/effects/ExploreEffect.java
forge-game/src/main/java/forge/game/trigger/TriggerExplores.java
forge-gui/res/cardsfolder/upcoming/nicanzil_current_conductor.txt
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties

seems correct in the case of Exploring with no cards in library

LCI: nicanzil_current_conductor.txt + support

---

forge-gui-mobile/src/forge/toolbox/FChoiceList.java

fix manacost parsing, add NPE guard

fix DefaultItemRenderer

---

forge-gui-mobile/src/forge/toolbox/FChoiceList.java

- support spaces on ability/title with cost

update DefaultItemRenderer title/ability name

---

forge-game/src/main/java/forge/game/card/CardDamageMap.java
forge-game/src/main/java/forge/game/trigger/TriggerExcessDamageAll.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java
forge-gui/res/cardsfolder/upcoming/magmatic_galleon.txt

TriggerExcessDamageAll: add new trigger for Magmatic Galleon

---

forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-gui/res/cardsfolder/m/mausoleum_secrets.txt
forge-gui/src/main/java/forge/gamemodes/match/input/InputConfirm.java

Makes it platform independent...
Closes #4120

Clean up card to play display

---

forge-game/src/main/java/forge/game/card/CardFactory.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityPanharmonicon.java
forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-gui/res/cardsfolder/o/obuun_mul_daya_ancestor.txt
forge-gui/res/cardsfolder/t/titania_voice_of_gaea_titania_gaea_incarnate.txt

Judges seemed pretty sure:
https://www.reddit.com/r/askajudge/comments/17lmope/can_naban_dean_of_iteration_double_a_trigger_with/
Closes #4109

Panharmonicon: improve filtering of cause for complex trigger

---

forge-ai/src/main/java/forge/ai/SpecialCardAi.java
forge-ai/src/main/java/forge/ai/ability/BranchAi.java

This is an ugly hack that only works for a very specific implementation, there needs to be a better implementation in the future (a followup issue will be posted later), possibly a more generic BranchAi implementation in general, though it's pretty tricky to figure out.

Move the Bring the Ending logic into SpecialCardAi until it's rewritten

---

forge-gui/res/cardsfolder/upcoming/abuelos_awakening.txt
forge-gui/res/cardsfolder/upcoming/acolyte_of_aclazotz.txt
forge-gui/res/cardsfolder/upcoming/acrobatic_leap.txt
forge-gui/res/cardsfolder/upcoming/adaptive_gemguard.txt
forge-gui/res/cardsfolder/upcoming/ancestors_aid.txt
forge-gui/res/cardsfolder/upcoming/ancestral_reminiscence.txt
forge-gui/res/cardsfolder/upcoming/anim_pakal_thousandth_moon.txt
forge-gui/res/cardsfolder/upcoming/another_chance.txt
forge-gui/res/cardsfolder/upcoming/armored_kincaller.txt
forge-gui/res/cardsfolder/upcoming/attentive_sunscribe.txt
forge-gui/res/cardsfolder/upcoming/basking_capybara.txt
forge-gui/res/cardsfolder/upcoming/gargantuan_leech.txt
forge-gui/res/cardsfolder/upcoming/threefold_thunderhulk.txt
forge-gui/res/lists/TypeLists.txt

LCI 13 cards 4/11

---

forge-ai/src/main/java/forge/ai/AiController.java
forge-ai/src/main/java/forge/ai/SpecialAiLogic.java
forge-ai/src/main/java/forge/ai/SpecialCardAi.java
forge-ai/src/main/java/forge/ai/ability/AnimateAi.java
forge-ai/src/main/java/forge/ai/ability/BranchAi.java
forge-gui/res/cardsfolder/w/workshop_elders.txt

Improve AI for Workshop Elders + fix AI paying Cycling PayLife costs in presence of Living End

---

forge-gui/res/cardsfolder/upcoming/ironpaw_aspirant.txt
forge-gui/res/cardsfolder/upcoming/itzquinth_firstborn_of_gishath.txt
forge-gui/res/cardsfolder/upcoming/join_the_dead.txt
forge-gui/res/cardsfolder/upcoming/kitesail_larcenist.txt
forge-gui/res/cardsfolder/upcoming/kutzil_malamet_exemplar.txt
forge-gui/res/cardsfolder/upcoming/malamet_battle_glyph.txt
forge-gui/res/cardsfolder/upcoming/malamet_brawler.txt
forge-gui/res/cardsfolder/upcoming/malamet_veteran.txt
forge-gui/res/cardsfolder/upcoming/malicious_eclipse.txt
forge-gui/res/cardsfolder/upcoming/marauding_brinefang.txt

some of these uncommons are more complicated that I expected

LCI 10 cards

---

forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/a/agent_of_erebos.txt
forge-gui/res/cardsfolder/a/angel_of_finality.txt
forge-gui/res/cardsfolder/j/jirina_dauntless_general.txt
forge-gui/res/cardsfolder/s/syrix_carrier_of_the_flame.txt
forge-gui/res/cardsfolder/upcoming/kutzils_flanker.txt

add Left Battlefield this turn and left Graveyard this turn
Closes #4139

Game: add LeftBattlefieldThisTurn & LeftGraveyardThisTurn

---

forge-ai/src/main/java/forge/ai/SpecialCardAi.java
forge-ai/src/main/java/forge/ai/ability/DrawAi.java
forge-gui/res/cardsfolder/v/veil_of_summer.txt

AI logic for Veil of Summer

---

forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-gui/res/cardsfolder/e/expand_the_sphere.txt
forge-gui/res/cardsfolder/r/rabble_rousing.txt
forge-gui/res/cardsfolder/s/screaming_swarm.txt
forge-gui/res/cardsfolder/t/the_ur_dragon.txt
forge-gui/res/cardsfolder/v/varina_lich_queen.txt

Revert view update (problematic for LKI checks)

---

forge-gui/res/cardsfolder/upcoming/mephitic_draught.txt
forge-gui/res/cardsfolder/upcoming/merfolk_cave_diver.txt
forge-gui/res/cardsfolder/upcoming/might_of_the_ancestors.txt
forge-gui/res/cardsfolder/upcoming/mineshaft_spider.txt
forge-gui/res/cardsfolder/upcoming/molten_collapse.txt
forge-gui/res/cardsfolder/upcoming/nurturing_bristleback.txt
forge-gui/res/cardsfolder/upcoming/oaken_siren.txt
forge-gui/res/cardsfolder/upcoming/oltec_archaeologists.txt
forge-gui/res/cardsfolder/upcoming/orazca_puzzle_door.txt
forge-gui/res/cardsfolder/upcoming/out_of_air.txt
forge-gui/res/cardsfolder/upcoming/pathfinding_exejaw.txt
forge-gui/res/cardsfolder/upcoming/petrify.txt
forge-gui/res/cardsfolder/upcoming/pirate_hat.txt
forge-gui/res/cardsfolder/upcoming/plundering_pirate.txt
forge-gui/res/cardsfolder/upcoming/poetic_ingenuity.txt
forge-gui/res/cardsfolder/upcoming/poison_dart_frog.txt
forge-gui/res/cardsfolder/upcoming/preacher_of_the_schism.txt
forge-gui/res/cardsfolder/upcoming/promising_vein.txt
forge-gui/res/cardsfolder/upcoming/pugnacious_hammerskull.txt
forge-gui/res/cardsfolder/upcoming/queens_bay_paladin.txt

LCI 20 more

---

forge-game/src/main/java/forge/game/card/CounterEnumType.java
forge-gui/res/cardsfolder/upcoming/lara_croft_tomb_raider.txt

The card everyone's been waiting for

SLD Lara Croft !

---

forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/ExploreEffect.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java
forge-gui/res/cardsfolder/c/chefs_kiss.txt

CopySpellAbility: Improve targeting sub detection

---

forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java

There can be only one (engine source of information)

---

forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
forge-game/src/main/java/forge/game/player/Player.java

Support for Starving Revenant

---

forge-ai/src/main/java/forge/ai/AiBlockController.java
forge-gui/res/cardsfolder/s/sakura_tribe_elder.txt
forge-gui/res/cardsfolder/v/visions_of_dread.txt

The Sakura Tribe-Elder hint can probably be reused for more stuff, but I'm not sure which stuff off the top of my head...

AI hint for Sakura Tribe-Elder blocking + AI hint for Visions of Dread

---

forge-gui/res/cardsfolder/upcoming/redemption_choir.txt
forge-gui/res/cardsfolder/upcoming/ripples_of_potential.txt
forge-gui/res/cardsfolder/upcoming/scion_of_calamity.txt
forge-gui/res/cardsfolder/upcoming/singer_of_swift_rivers.txt
forge-gui/res/cardsfolder/upcoming/skeleton_crew.txt
forge-gui/res/cardsfolder/upcoming/storm_fleet_negotiator.txt
forge-gui/res/cardsfolder/upcoming/sunfrill_imitator.txt

Should wrap up the scriptable ones

LCC 7 cards

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-game/src/main/java/forge/game/trigger/TriggerTapAll.java
forge-gui/res/cardsfolder/c/cosmic_intervention.txt
forge-gui/res/cardsfolder/d/death_rattle_oni.txt
forge-gui/res/cardsfolder/g/gishath_suns_avatar.txt
forge-gui/res/cardsfolder/h/holga_relentless_rager.txt
forge-gui/res/cardsfolder/l/lozhan_dragons_legacy.txt
forge-gui/res/cardsfolder/s/sakashimas_will.txt
forge-gui/res/cardsfolder/upcoming/zygon_infiltrator.txt

Update undo logic

---

forge-game/src/main/java/forge/game/card/CounterEnumType.java
forge-gui/res/cardsfolder/upcoming/alpha_deathclaw.txt
forge-gui/res/cardsfolder/upcoming/caesar_legions_emperor.txt
forge-gui/res/cardsfolder/upcoming/dogmeat_ever_loyal.txt
forge-gui/res/cardsfolder/upcoming/dr_madison_li.txt
forge-gui/res/cardsfolder/upcoming/gary_clone.txt
forge-gui/res/cardsfolder/upcoming/idolized.txt
forge-gui/res/cardsfolder/upcoming/intelligence_bobblehead.txt
forge-gui/res/cardsfolder/upcoming/nuka_cola_vending_machine.txt
forge-gui/res/cardsfolder/upcoming/overencumbered.txt
forge-gui/res/cardsfolder/upcoming/radstorm.txt
forge-gui/res/cardsfolder/upcoming/rex_cyber_hound.txt
forge-gui/res/cardsfolder/upcoming/vault_101_birthday_party.txt
forge-gui/res/lists/TypeLists.txt
forge-gui/res/tokenscripts/c_a_junk_sac_exileplay.txt

@paulsnoops what you think about the Junk token name ?

PIP 12 cards

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/FlipCoinEffect.java
forge-game/src/main/java/forge/game/ability/effects/GoadEffect.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
forge-gui/src/main/java/forge/player/HumanPlay.java

 Fix Krark's Thumb 

---

forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/replacement/ReplaceLifeReduced.java
forge-gui/res/cardsfolder/a/ali_from_cairo.txt
forge-gui/res/cardsfolder/a/angel_of_grace.txt
forge-gui/res/cardsfolder/a/angels_grace.txt
forge-gui/res/cardsfolder/e/elderscale_wurm.txt
forge-gui/res/cardsfolder/f/fortune_thief.txt
forge-gui/res/cardsfolder/s/serra_the_benevolent.txt
forge-gui/res/cardsfolder/s/sustaining_spirit.txt
forge-gui/res/cardsfolder/upcoming/bloodletter_of_aclazotz.txt
forge-gui/res/cardsfolder/w/worship.txt

Update of old Code for Bloodletter

ReplaceLifeReduced: update for Bloodletter

---

forge-gui/res/editions/Coldsnap Theme Decks.txt

rarity fix

---

forge-gui/res/blockdata/blocks.txt
forge-gui/res/draft/rankings.txt
forge-gui/res/editions/March of the Machine.txt
forge-gui/res/editions/The Lost Caverns of Ixalan.txt

- Added LCI draft along with LTR & WOE rankings updates
https://magic.wizards.com/en/news/feature/collecting-the-lost-caverns-of-ixalan

Booster Draft: LCI with LTR & WOE updates

---

forge-gui/res/lists/altwin-achievements.txt
forge-gui/res/lists/planeswalker-achievements.txt

Needs some of the cards implemented.
Also, some ideas from Marek14 for the potential implementation that are currently unrealized:
```
If you satisfy [the Doctors achievement] the "real" way, with First to Thirteenth Doctor:
The Thirteen Doctors
The greatest reunion the Universe has ever seen!
Plus, I feel like there should be a hidden achievement for triggering that ability with exactly 2012 time counters.
```

WHO, LCI, LCC achievements by Marek14

---

forge-gui/res/cardsfolder/upcoming/malamet_scythe.txt
forge-gui/res/cardsfolder/upcoming/ruin_lurker_bat.txt
forge-gui/res/cardsfolder/upcoming/rumbling_rockslide.txt
forge-gui/res/cardsfolder/upcoming/vault_101_birthday_party.txt
forge-gui/res/cardsfolder/upcoming/vitos_inquisitor.txt
forge-gui/res/editions/Doctor Who Commander.txt

Should wrap up LCI except the one remaining craft card

LCI 3 cards

---

forge-gui/res/cardsfolder/e/eiganjo_seat_of_the_empire.txt
forge-gui/res/cardsfolder/g/gust_of_wind.txt
forge-gui/res/cardsfolder/j/jaces_ruse.txt
forge-gui/res/cardsfolder/m/maraleaf_pixie.txt
forge-gui/res/cardsfolder/w/wedding_announcement_wedding_festivity.txt

Typos Patch

---

forge-ai/src/main/java/forge/ai/ability/AttachAi.java
forge-ai/src/main/java/forge/ai/ability/FogAi.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameLogFormatter.java
forge-game/src/main/java/forge/game/PlanarDice.java
forge-game/src/main/java/forge/game/TriggerReplacementBase.java
forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-gui/res/cardsfolder/b/blood_for_bones.txt
forge-gui/res/cardsfolder/t/timothar_baron_of_bats.txt

Closes #4346
Closes #4374
Closes #4380

Fix facedown permanent with adventure

---

forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerCycled.java
forge-game/src/main/java/forge/game/trigger/TriggerSurveil.java
forge-gui/res/cardsfolder/e/erdwal_illuminator.txt
forge-gui/res/cardsfolder/v/valiant_rescuer.txt
forge-gui/res/cardsfolder/w/whispering_snitch.txt
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

Fix new plane overwritten with old card

---

forge-gui/res/adventure/common/decks/miniboss/slimefoot.dck

Slimefoot deck fix 

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-gui/res/cardsfolder/t/the_matrix_of_time.txt

Should be ready to merge once #4385 is in

WHO the_matrix_of_time.txt + support

---

forge-gui/res/cardsfolder/s/stormkeld_curator_giant_secrets.txt
forge-gui/res/cardsfolder/t/the_wedding_of_river_song.txt

Fixed mana cost of Stormkeld Curator and added time travel to wedding of river song.

Stormkeld curator and wedding of river song

---

forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
forge-gui/res/puzzle/PS_LCI3.pzl

Prevent AI from sacrificing powerful creatures via an obtained Sakura-Tribe Elder ability

---

forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/phase/Untap.java

The property would be wrong if Untap step gets skipped.

Rasputin Dreamweaver fix

---

forge-ai/src/main/java/forge/ai/SpellApiToAi.java
forge-game/src/main/java/forge/game/StaticEffect.java
forge-game/src/main/java/forge/game/ability/AbilityFactory.java
forge-game/src/main/java/forge/game/ability/ApiType.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/player/PlayerProperty.java
forge-game/src/main/java/forge/game/player/PlayerView.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-game/src/main/java/forge/trackable/TrackableProperty.java
forge-gui/res/cardsfolder/d/davros_dalek_creator.txt
forge-gui/res/cardsfolder/g/great_intelligences_plan.txt
forge-gui/res/cardsfolder/t/the_valeyard.txt
forge-gui/res/tokenscripts/b_a_3_3_dalek_menace.txt

Villanous choice initial implementation

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ability/TapAiBase.java
forge-ai/src/main/java/forge/ai/ability/UntapAi.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardPredicates.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/cost/CostEnlist.java
forge-game/src/main/java/forge/game/cost/CostTap.java
forge-game/src/main/java/forge/game/cost/CostTapType.java
forge-game/src/main/java/forge/game/replacement/ReplaceTap.java
forge-gui/res/cardsfolder/upcoming/ood_sphere.txt
forge-gui/res/lists/TypeLists.txt
forge-gui/src/main/java/forge/player/HumanCostDecision.java
forge-gui/src/main/java/forge/player/HumanPlay.java
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

WHO: add can't tap check

---

forge-game/src/main/java/forge/game/GameAction.java

fixes Dark Depths Always trigger

GameAction: stop always trigger before etb counter

---

forge-game/src/main/java/forge/game/ability/effects/ProtectEffect.java
forge-gui/res/cardsfolder/m/magmatic_galleon.txt
forge-gui/res/cardsfolder/p/pippin_guard_of_the_citadel.txt

Fix ProtectEffect

---

forge-gui/res/editions/Commander Anthology Vol. II.txt

Update Commander Anthology Vol. II.txt

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Fix Genesis of the Daleks

---

forge-gui/res/cardsfolder/a/artisan_of_kozilek.txt
forge-gui/res/cardsfolder/s/skarrgan_skybreaker.txt
forge-gui/res/cardsfolder/v/vulshok_replica.txt

Pretty sure these are not functional changes, just getting in-game card text in line with oracle.

Minor patch

---

forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java

fix relic_of_progenitus stackdesc

---

forge-ai/src/main/java/forge/ai/SpecialCardAi.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/DrawEffect.java
forge-game/src/main/java/forge/game/ability/effects/FightEffect.java
forge-game/src/main/java/forge/game/ability/effects/LifeGainEffect.java
forge-gui/res/cardsfolder/a/adeline_resplendent_cathar.txt
forge-gui/res/cardsfolder/a/angel_of_destiny.txt
forge-gui/res/cardsfolder/c/conjured_currency.txt
forge-gui/res/cardsfolder/c/cunning_strike.txt
forge-gui/res/cardsfolder/d/diviner_spirit.txt
forge-gui/res/cardsfolder/e/ezuris_predation.txt
forge-gui/res/cardsfolder/f/first_volley.txt
forge-gui/res/cardsfolder/g/grothama_all_devouring.txt
forge-gui/res/cardsfolder/h/hans_eriksson.txt
forge-gui/res/cardsfolder/h/hungry_flames.txt
forge-gui/res/cardsfolder/l/lunge.txt
forge-gui/res/cardsfolder/n/neonates_rush.txt
forge-gui/res/cardsfolder/p/psionic_entity.txt
forge-gui/res/cardsfolder/s/sergeant_john_benton.txt
forge-gui/res/cardsfolder/s/shauku_endbringer.txt
forge-gui/res/cardsfolder/s/shower_of_sparks.txt
forge-gui/res/cardsfolder/s/skophos_maze_warden.txt
forge-gui/res/cardsfolder/t/tahngarth_first_mate.txt
forge-gui/res/cardsfolder/x/xyris_the_writhing_storm.txt
forge-gui/res/cardsfolder/z/zara_renegade_recruiter.txt

Support duplicate objects per effect

---

forge-gui/res/cardsfolder/upcoming/kaya_spirits_justice.txt

MKM: Add script for new MKM planeswalker Kaya, Spirits' Justice.
- Kaya, Spirits' Justice
Planeswalkers are getting more and more complicated...

MKM: Kaya, Spirits' Justice

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-ai/src/main/java/forge/ai/SpellApiToAi.java
forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/ability/ApiType.java
forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/card/CardUtil.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityVariables.java
forge-gui-mobile/src/forge/card/CardRenderer.java
forge-gui/res/cardsfolder/upcoming/case_of_the_filched_falcon.txt
forge-gui/res/lists/TypeLists.txt

Initial checkin for Solved/Cases

---

forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/LandAbility.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCastWithFlash.java
forge-gui/res/cardsfolder/s/scouts_warning.txt
forge-gui/src/main/java/forge/player/HumanPlay.java

A sneaky interaction 🧙 
Closes #4554

Make Flash interact with Dryad Arbor

---

forge-gui/res/cardsfolder/upcoming/assemble_the_players.txt
forge-gui/res/cardsfolder/upcoming/delney_streetwise_lookout.txt
forge-gui/res/cardsfolder/upcoming/kellan_inquisitive_prodigy_tail_the_suspect.txt
forge-gui/res/cardsfolder/upcoming/massacre_girl_known_killer.txt
forge-gui/res/cardsfolder/upcoming/tomik_wielder_of_law.txt

MKM: Add script for MKM card Kellan, Inquisitive Prodigy, + 4 other cards:
- Assemble the Players
- Delney, Streetwise Lookout
- Kellan, Inquisitive Prodigy // Tail the Suspect
- Massacre Girl, Known Killer
- Tomik, Wielder of Law

MKM: Kellan, Inquisitive Prodigy + 4 cards

---

forge-game/src/main/java/forge/game/ability/effects/DestroyAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/DestroyEffect.java
forge-game/src/main/java/forge/game/ability/effects/SacrificeAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
forge-game/src/main/java/forge/game/card/CardZoneTable.java
forge-game/src/main/java/forge/game/cost/CostExile.java
forge-game/src/main/java/forge/game/cost/CostPartWithList.java
forge-game/src/main/java/forge/game/cost/CostSacrifice.java
forge-game/src/main/java/forge/game/zone/MagicStack.java

Use fresh LastState for costs

---

forge-gui/res/cardsfolder/upcoming/archdruids_charm.txt
forge-gui/res/cardsfolder/upcoming/krenko_baron_of_tin_street.txt
forge-gui/res/cardsfolder/upcoming/no_witnesses.txt
forge-gui/res/cardsfolder/upcoming/pick_your_poison.txt
forge-gui/res/cardsfolder/upcoming/profts_eidetic_memory.txt
forge-gui/res/cardsfolder/upcoming/trostani_three_whispers.txt

MKM: Add card scripts for 6 new MKM cards:
- Archdruid's Charm
- Krenko, Baron of Tin Street
- No Witnesses
- Pick Your Poison
- Proft's Eidetic Memory
- Trostani, Three Whispers

MKM: Krenko, Baron of Tin Street + 5 cards

---

forge-gui/res/cardsfolder/upcoming/festerleech.txt

Festerleech - spoiled 1/20/2024

MKM add 1 card

---

forge-game/src/main/java/forge/game/trigger/TriggerDamageDoneOnce.java
forge-gui/res/cardsfolder/upcoming/innocent_bystander.txt

slightly new templating on this

MKM: innocent_bystander.txt + support

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/card/CardUtil.java
forge-game/src/main/java/forge/game/combat/CombatUtil.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantBeSuspected.java

Closes #4533 
we might have some AI logic later to decide if "Suspected" is good or bad
the "can't block" is currently hard-wired into the CombatUtil logic, might be updated when CR is released

MKM: add Suspected

---

forge-gui/res/cardsfolder/l/lord_skitters_butcher.txt
forge-gui/res/cardsfolder/t/territorial_kavu.txt
forge-gui/res/cardsfolder/upcoming/gearbane_orangutan.txt
forge-gui/res/cardsfolder/upcoming/get_a_leg_up.txt
forge-gui/res/cardsfolder/upcoming/goblin_maskmaker.txt
forge-gui/res/cardsfolder/upcoming/harried_dronesmith.txt
forge-gui/res/cardsfolder/upcoming/jaded_analyst.txt

refactored a few old cards that are similar to the orangutan to use UnlessCost – tidier IMO

MKM: 5 cards 21/22 Jan

---

forge-ai/src/main/java/forge/ai/simulation/SpellAbilityPicker.java
forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/CountersPutAllEffect.java
forge-game/src/main/java/forge/game/cost/Cost.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/cost/CostPartMana.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/AbilityActivated.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityCondition.java
forge-gui/res/cardsfolder/b/back_from_the_brink.txt
forge-gui/res/cardsfolder/c/consecrate_consume.txt
forge-gui/res/cardsfolder/l/leafkin_avenger.txt
forge-gui/res/cardsfolder/m/merseine.txt
forge-gui/res/cardsfolder/t/tegwyll_duke_of_splendor.txt
forge-gui/res/cardsfolder/t/tegwylls_scouring.txt
forge-gui/res/cardsfolder/t/tempt_with_glory.txt

Merseine fixes

---

forge-gui/res/cardsfolder/upcoming/insidious_roots.txt

Insidious Roots

---

forge-game/src/main/java/forge/game/ability/effects/ClashEffect.java
forge-gui/res/cardsfolder/upcoming/marvo_deep_operative.txt
forge-gui/res/cardsfolder/v/vaevictis_asmadi_the_dire.txt

MKC: marvo_deep_operative.txt + support

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/n/norns_decree.txt
forge-gui/res/cardsfolder/upcoming/absolving_lammasu.txt
forge-gui/res/cardsfolder/upcoming/case_of_the_stashed_skeleton.txt
forge-gui/res/cardsfolder/upcoming/hot_pursuit.txt
forge-gui/res/cardsfolder/upcoming/nelly_borca_impulsive_accuser.txt
forge-gui/res/cardsfolder/upcoming/repeat_offender.txt
forge-gui/res/tokenscripts/b_2_1_skeleton.txt

Only engine tweak is for Hot Pursuit phase trigger

MKM/MKC - 5 sus cards

---

forge-gui/res/cardsfolder/e/emberwilde_augur.txt
forge-gui/res/cardsfolder/f/frostling.txt
forge-gui/res/cardsfolder/m/mogg_fanatic.txt
forge-gui/res/cardsfolder/m/molten_monstrosity.txt
forge-gui/res/cardsfolder/m/moonglove_extract.txt
forge-gui/res/cardsfolder/u/undercellar_myconid.txt

Typo patch

---

forge-gui/res/cardsfolder/upcoming/glint_weaver.txt
forge-gui/res/cardsfolder/upcoming/hedge_whisperer.txt
forge-gui/res/cardsfolder/upcoming/incinerator_of_the_guilty.txt
forge-gui/res/cardsfolder/upcoming/inside_source.txt
forge-gui/res/cardsfolder/upcoming/it_doesnt_add_up.txt
forge-gui/res/cardsfolder/upcoming/izoni_center_of_the_web.txt
forge-gui/res/cardsfolder/upcoming/krovod_haunch.txt
forge-gui/res/tokenscripts/bg_2_1_spider_menace_reach.txt

I think Incinerator of the Guilty needs more support for the `count$xpaid`

MKM 7 cards

---

forge-game/src/main/java/forge/game/ability/effects/DrawEffect.java
forge-game/src/main/java/forge/game/ability/effects/RevealEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/player/Player.java
forge-gui/res/cardsfolder/a/academy_loremaster.txt
forge-gui/res/cardsfolder/a/alms_collector.txt
forge-gui/res/cardsfolder/a/ancient_excavation.txt
forge-gui/res/cardsfolder/c/cut_a_deal.txt
forge-gui/res/cardsfolder/e/explosion_of_riches.txt
forge-gui/res/cardsfolder/f/force_away.txt
forge-gui/res/cardsfolder/h/hordewing_skaab.txt
forge-gui/res/cardsfolder/k/kwain_itinerant_meddler.txt
forge-gui/res/cardsfolder/l/laquatuss_creativity.txt
forge-gui/res/cardsfolder/m/messenger_jays.txt
forge-gui/res/cardsfolder/r/read_the_runes.txt
forge-gui/res/cardsfolder/t/the_royal_scions.txt
forge-gui/src/main/java/forge/player/HumanCostDecision.java
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Draw: use Cause if able

---

forge-game/src/main/java/forge/game/cost/CostCollectEvidence.java
forge-gui/res/cardsfolder/upcoming/fae_flight.txt
forge-gui/res/cardsfolder/upcoming/kyloxs_voltstrider.txt
forge-gui/res/cardsfolder/upcoming/lamplight_phoenix.txt
forge-gui/res/cardsfolder/upcoming/marketwatch_phantom.txt
forge-gui/res/cardsfolder/upcoming/public_thoroughfare.txt
forge-gui/src/main/java/forge/player/HumanPlay.java

Unlesscost doesn't seem to be working ?

MKM 5 cards

---

forge-gui/res/cardsfolder/upcoming/aurelias_vindicator.txt
forge-gui/res/cardsfolder/upcoming/etrata_deadly_fugitive.txt
forge-gui/res/cardsfolder/upcoming/urgent_necropsy.txt

Should Aurelia's Vindicator be scripted using exiledwith ? 
Also Urgent Necropsy doesn't need me to pay the Collect Evidence

MKM last 3 mythics

---

forge-game/src/main/java/forge/game/trigger/Trigger.java
forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-gui/res/cardsfolder/c/chainer_nightmare_adept.txt
forge-gui/res/cardsfolder/r/renewed_faith.txt

Because of new _Teysa, Opulent Oligarch_ rechecking the ActivationLimit is a must.
Might rework the trigger types in a followup.
Closes #4633

Always recheck ActivationLimit

---

forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/ability/effects/AmassEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactory.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-game/src/main/java/forge/game/trigger/Trigger.java
forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-game/src/main/java/forge/game/zone/MagicStack.java

E. g. _Artificial Evolution_ on _Perimeter Sergeant_

Fix ChangeText not being fully applied for trigger effects + traits gained by static

---

forge-adventure/src/main/java/forge/adventure/editor/EditorMainWindow.java
forge-adventure/src/main/java/forge/adventure/editor/QuestStageEdit.java
forge-gui-mobile/src/forge/adventure/data/AdventureQuestData.java
forge-gui-mobile/src/forge/adventure/data/AdventureQuestStage.java
forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
forge-gui-mobile/src/forge/adventure/util/AdventureQuestController.java
forge-gui-mobile/src/forge/adventure/util/AdventureQuestEvent.java
forge-gui/res/adventure/Shandalar/world/quests.json

Editor is not feature complete, but is now closer to it for quests than it was before. It also launches again now without crashing, which is an improvement.

Adventure - Editor fix, minor quest updates

---

forge-ai/src/main/java/forge/ai/ability/AmassAi.java
forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/ability/effects/AmassEffect.java
forge-gui/res/editions/Commander Masters.txt
forge-gui/res/editions/Innistrad Midnight Hunt Commander.txt
forge-gui/res/editions/Modern Horizons 2.txt
forge-gui/res/editions/Starter Commander Decks.txt
forge-gui/res/editions/The Lord of the Rings Tales of Middle-earth.txt
forge-gui/res/editions/War of the Spark.txt
forge-gui/res/puzzle/PS_LTR2.pzl
forge-gui/res/puzzle/PS_M204.pzl
forge-gui/res/puzzle/PS_WAR0.pzl
forge-gui/res/puzzle/PS_WAR1.pzl
forge-gui/res/tokenscripts/b_0_0_army.txt
forge-gui/res/tokenscripts/b_0_0_orc_army.txt
forge-gui/res/tokenscripts/b_0_0_sliver_army.txt
forge-gui/res/tokenscripts/b_0_0_zombie_army.txt

Amass Tokens not using the appropriate names for images

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
forge-game/src/main/java/forge/game/combat/Combat.java
forge-gui/res/cardsfolder/a/anoint_with_affliction.txt
forge-gui/res/cardsfolder/c/cybership.txt
forge-gui/res/cardsfolder/m/mishra_claimed_by_gix_mishra_lost_to_phyrexia.txt
forge-gui/res/cardsfolder/upcoming/yarus_roar_of_the_old_gods.txt
forge-gui/res/cardsfolder/w/wilfred_mott.txt

Cybership fix

---

forge-gui/res/cardsfolder/upcoming/outrageous_robbery.txt
forge-gui/res/cardsfolder/upcoming/watcher_of_hours.txt

MKM + MKC: Add card scripts for last two earmarked MKM/MKC cards under my name. Apologies for delay.
- Outrageous Robbery
- Watcher of Hours

MKM/MKC: Outrageous Robbery + Watcher of Hours

---

forge-gui/res/adventure/common/custom_cards/jace_boss_effect.txt
forge-gui/res/adventure/common/maps/map/emrakul/emrakul_legacy.tmx
forge-gui/res/adventure/common/maps/map/fort/fort_green_3_forestcastle.tmx
forge-gui/res/adventure/common/maps/map/grove/grove_8_hydra.tmx

* moved the homarid in the Emrakul boss zone
* Cleaned up the collision of the Forest Castle
* Fixed jace's boss card
* removed the duplicate spawn location of the Hydra

4 small adventure fixes

---

forge-ai/src/main/java/forge/ai/AiController.java
forge-ai/src/main/java/forge/ai/ComputerUtilAbility.java
forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
forge-ai/src/main/java/forge/ai/ability/DiscoverAi.java
forge-ai/src/main/java/forge/ai/ability/PlayAi.java
forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-game/src/main/java/forge/game/ability/effects/DiscoverEffect.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/combat/Combat.java
forge-game/src/main/java/forge/game/spellability/Spell.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
forge-gui/res/cardsfolder/i/inventive_iteration_living_breakthrough.txt
forge-gui/res/cardsfolder/k/karn_the_great_creator.txt
forge-gui/res/cardsfolder/l/linvala_keeper_of_silence.txt
forge-gui/res/cardsfolder/p/press_the_enemy.txt
forge-gui/src/main/java/forge/gamemodes/match/input/InputPayMana.java
forge-gui/src/main/java/forge/player/HumanCostDecision.java
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

Closes #4636
There are probably some corner cases where it won't work, but that will be more of a general MayPlay problem.
This also fixes being able to cast fused spells via _Oskar, Rubbish Reclaimer_.
Closes #4648

PlayEffect: support AltCosts

---

forge-ai/src/main/java/forge/ai/ability/CloakAi.java
forge-ai/src/main/java/forge/ai/ability/ManifestAi.java
forge-ai/src/main/java/forge/ai/ability/ManifestBaseAi.java
forge-game/src/main/java/forge/game/ability/effects/CloakEffect.java
forge-game/src/main/java/forge/game/ability/effects/ManifestBaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/ManifestEffect.java

Close #4643 
this simply the Manifest and Cloak Effects and AI

Simplyfy Cloak and Manifest Effects

---

forge-gui/res/cardsfolder/upcoming/take_the_bait.txt

MKC: added Take The Bait

---

forge-gui/res/cardsfolder/s/sontaran_general.txt

Made that the target creatures cant block, instead of the previous unblockable attribute

Fixed Sontaran General (#4451)

---

forge-game/src/main/java/forge/game/ability/effects/DamageDealEffect.java
forge-game/src/main/java/forge/game/ability/effects/SetStateEffect.java
forge-game/src/main/java/forge/game/cost/CostDiscard.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/c/conundrum_sphinx.txt
forge-gui/res/cardsfolder/s/sunder_the_gateway.txt
forge-gui/res/cardsfolder/u/ugins_mastery.txt
forge-gui/res/cardsfolder/upcoming/hustle_bustle.txt
forge-gui/src/main/java/forge/player/HumanPlay.java

 Few fixes

---

forge-game/src/main/java/forge/game/trigger/TriggerHandler.java

This check is part of the very first commit...
I don't see it preventing anything useful? 🤔

Fix Disguise Ward not triggering

---

forge-gui/res/cardsfolder/u/unruly_krasis.txt
forge-gui/res/cardsfolder/v/vernal_sovereign.txt

Card scripts for [Vernal Sovereign](https://scryfall.com/card/clu/51/vernal-sovereign) and [Unruly Krasis](https://scryfall.com/card/clu/50/unruly-krasis). Both passed reasonable testing with flying colors.

CLU: Adding Vernal Sovereign & Unruly Krasis

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/upcoming/pompous_gadabout.txt

MKM: add hasNoName

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
forge-gui/res/cardsfolder/upcoming/airtight_alibi.txt
forge-gui/res/cardsfolder/upcoming/bite_down_on_crime.txt
forge-gui/res/cardsfolder/upcoming/case_of_the_burning_masks.txt
forge-gui/res/cardsfolder/upcoming/deadly_cover_up.txt
forge-gui/res/cardsfolder/upcoming/hide_in_plain_sight.txt
forge-gui/res/cardsfolder/upcoming/projektor_inspector.txt
forge-gui/res/cardsfolder/upcoming/push_pull.txt
forge-gui/res/cardsfolder/upcoming/soul_search.txt
forge-gui/res/cardsfolder/upcoming/sudden_setback.txt
forge-gui/res/cardsfolder/upcoming/suspicious_detonation.txt
forge-gui/res/cardsfolder/upcoming/vitu_ghazi_inspector.txt

I think the last cards that don't require engine changes ?

MKM 11 cards

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/upcoming/niv_Mizzet_guildpact.txt
forge-gui/res/cardsfolder/upcoming/niv_mizzet_guildpact.txt

add Engine Change for new Niv-Mizzet

AbilityUtils: add DifferentColorPair

---

forge-gui/res/puzzle/PS_MKM1.pzl

- Added puzzle PS_MKM1 - Possibility Storm - Murder at Karlov Manor 01.

Add puzzle PS_MKM1

---

forge-game/src/main/java/forge/game/ability/effects/SurveilEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/player/Player.java
forge-gui/res/cardsfolder/upcoming/eye_of_duskmantle.txt

Card: add surveilledThisTurn

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardUtil.java
forge-game/src/main/java/forge/game/combat/CombatUtil.java

Card: Suspected use 'CARDNAME can't block' StaticAbility

---

forge-gui/res/cardsfolder/upcoming/amzu_swarms_hunger.txt
forge-gui/res/cardsfolder/upcoming/boros_strike_captain.txt
forge-gui/res/cardsfolder/upcoming/carnage_interpreter.txt
forge-gui/res/cardsfolder/upcoming/conclave_evangelist.txt
forge-gui/res/cardsfolder/upcoming/corporeal_projection.txt
forge-gui/res/cardsfolder/upcoming/covetous_elegy.txt
forge-gui/res/cardsfolder/upcoming/ecstatic_electromancer.txt
forge-gui/res/cardsfolder/upcoming/emissary_green.txt
forge-gui/res/cardsfolder/upcoming/forum_familiar.txt
forge-gui/res/cardsfolder/upcoming/frenzied_gorespawn.txt
forge-gui/res/cardsfolder/upcoming/mastermind_plum.txt

Seems like the MKM was accidently set as merged

CLUE 10 cards + 1 MKM

---

forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/b/breena_the_demagogue.txt
forge-gui/res/cardsfolder/c/confront_the_past.txt
forge-gui/res/cardsfolder/c/crawling_sensation.txt
forge-gui/res/cardsfolder/d/doomsday_confluence.txt
forge-gui/res/cardsfolder/f/frontier_warmonger.txt
forge-gui/res/cardsfolder/l/lord_of_the_nazgul.txt
forge-gui/res/cardsfolder/o/orcus_prince_of_undeath.txt
forge-gui/res/cardsfolder/p/profane_command.txt
forge-gui/res/cardsfolder/s/stonebinders_familiar.txt
forge-gui/src/main/java/forge/gamemodes/puzzle/Puzzle.java
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Fix Profane Command

---

forge-ai/src/main/java/forge/ai/ability/FightAi.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-game/src/main/java/forge/game/ability/effects/ConniveEffect.java
forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndCombatPhaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndTurnEffect.java
forge-game/src/main/java/forge/game/ability/effects/HauntEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardZoneTable.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/trigger/TriggerChangesZoneAll.java
forge-game/src/main/java/forge/game/zone/Zone.java
forge-gui/res/cardsfolder/c/crawling_sensation.txt
forge-gui/res/cardsfolder/g/graceful_takedown.txt
forge-gui/res/cardsfolder/l/last_night_together.txt
forge-gui/res/cardsfolder/upcoming/assaultron_dominator.txt
forge-gui/res/cardsfolder/w/warlords_elite.txt

Unlike its newer cousin (_Crawling Infestation_) the trigger on _Crawling Sensation_ should see the past with "for the first time" - so perhaps might never be able to trigger on the turn it ETB.

Fix Crawling Sensation + related tweaks

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-game/src/main/java/forge/game/ability/effects/ConniveEffect.java
forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
forge-game/src/main/java/forge/game/ability/effects/DestroyAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/DestroyEffect.java
forge-game/src/main/java/forge/game/ability/effects/DigEffect.java
forge-game/src/main/java/forge/game/ability/effects/EncodeEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndCombatPhaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndTurnEffect.java
forge-game/src/main/java/forge/game/ability/effects/HauntEffect.java
forge-game/src/main/java/forge/game/ability/effects/ManifestBaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/MeldEffect.java
forge-game/src/main/java/forge/game/ability/effects/SacrificeAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardUtil.java
forge-game/src/main/java/forge/game/card/CardZoneTable.java
forge-game/src/main/java/forge/game/combat/Combat.java
forge-game/src/main/java/forge/game/cost/CostExileFromStack.java
forge-game/src/main/java/forge/game/cost/CostMill.java

Fixes Meld not triggering "one or more ETB"
Closes #2076

Consolidate CardZoneTable logic

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/upcoming/slime_against_humanity.txt

Convoked fix

---

forge-gui/res/cardsfolder/upcoming/ajani_nacatl_pariah_ajani_nacatl_avenger.txt
forge-gui/res/cardsfolder/upcoming/flare_of_cultivation.txt
forge-gui/res/cardsfolder/upcoming/snow_covered_wastes.txt
forge-gui/res/tokenscripts/w_2_1_cat_warrior.txt

Well, turns out any cleanup I might have wanted to do regarding this [pull request](https://github.com/Card-Forge/forge/pull/4754)'s commits is a non-starter. So, lesson learned, once more with feeling, etc. Regardless, I hope to have satisfactorily addressed comments on the previous pull request
- [Flare of Cultivation](https://scryfall.com/card/mh3/154/flare-of-cultivation)
- [Snow-Covered Wastes](https://scryfall.com/card/mh3/309/snow-covered-wastes)
- [Ajani, Nacatl Pariah // Ajani, Nacatl Avenger](https://scryfall.com/card/mh3/237/ajani-nacatl-pariah-ajani-nacatl-avenger)

Three MH3 cards

---

forge-gui/res/cardsfolder/upcoming/white_glove_gourmand.txt
forge-gui/res/cardsfolder/upcoming/wild_wasteland.txt

- [Wild Wasteland](https://scryfall.com/card/pip/71/wild-wasteland)
- [White Glove Gourmand](https://scryfall.com/card/pip/124/white-glove-gourmand)

PIP: Wild Wasteland & White Glove Gourmand

---

forge-game/src/main/java/forge/game/cost/CostExile.java
forge-game/src/main/java/forge/game/cost/CostPayEnergy.java
forge-gui/res/cardsfolder/upcoming/cass_hand_of_vengeance.txt
forge-gui/res/cardsfolder/upcoming/codsworth_handy_helper.txt
forge-gui/res/cardsfolder/upcoming/ed_e_lonesome_eyebot.txt
forge-gui/res/cardsfolder/upcoming/elder_arthur_maxson.txt
forge-gui/res/cardsfolder/upcoming/elder_owyn_lyons.txt
forge-gui/res/cardsfolder/upcoming/electrosiphon.txt
forge-gui/res/cardsfolder/upcoming/grim_reapers_sprint.txt
forge-gui/res/cardsfolder/upcoming/gunner_conscript.txt
forge-gui/res/cardsfolder/upcoming/hancock_ghoulish_mayor.txt
forge-gui/res/cardsfolder/upcoming/helios_one.txt
forge-gui/res/cardsfolder/upcoming/ian_the_reckless.txt
forge-gui/res/cardsfolder/upcoming/inventory_management.txt
forge-gui/res/cardsfolder/upcoming/james_wandering_dad_follow_him.txt
forge-gui/res/cardsfolder/upcoming/junktown.txt
forge-gui/res/cardsfolder/upcoming/kellogg_dangerous_mind.txt
forge-gui/res/cardsfolder/upcoming/legate_lanius_caesars_ace.txt
forge-gui/res/cardsfolder/upcoming/lily_bowen_raging_grandma.txt
forge-gui/res/cardsfolder/upcoming/maccready_lamplight_mayor.txt
forge-gui/res/cardsfolder/upcoming/marcus_mutant_mayor.txt
forge-gui/res/cardsfolder/upcoming/mariposa_military_base.txt

PIP 20 cards

---

forge-gui/res/cardsfolder/f/fragment_reality.txt
forge-gui/res/cardsfolder/rebalanced/a-geological_appraiser.txt
forge-gui/res/editions/Alchemy Karlov Manor.txt
forge-gui/res/editions/Ravnica Clue Edition.txt
forge-gui/res/editions/The Lost Caverns of Ixalan.txt

Source: https://magic.wizards.com/en/news/mtg-arena/mtg-arena-announcements-march-4-2024

Alchemy Rebalancing for March 04, 2024

---

forge-gui/res/cardsfolder/upcoming/wasteland_raider.txt
forge-gui/res/cardsfolder/upcoming/well_rested.txt

- [Well Rested](https://scryfall.com/card/pip/88/well-rested)
- [Wasteland Raider](https://scryfall.com/card/pip/52/wasteland-raider)

PIP: Well Rested & Wasteland Raider

---

forge-gui-desktop/src/main/java/forge/view/Main.java

This seems to be causing problems with users

Disable opengl acceleration

---

forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-gui/res/cardsfolder/upcoming/shifting_grift.txt

Closes #4813 
i think it is already functional?
it might just need some GUI love for the generated Charm Description

Keyword: Spree

---

forge-gui/res/lists/altwin-achievements.txt
forge-gui/res/puzzle/PS_MKM3.pzl

- Added MKM alt wincon achievement by Marek14.
- Added puzzle PS_MKM3.

Add MKM alt wincon achievement + add puzzle PS_MKM3.

---

forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/DigUntilEffect.java
forge-gui/res/cardsfolder/c/collision_of_realms.txt
forge-gui/res/cardsfolder/c/crypt_incursion.txt
forge-gui/res/cardsfolder/d/detention_sphere.txt
forge-gui/res/cardsfolder/d/duplicity.txt
forge-gui/res/cardsfolder/h/honor_the_fallen.txt
forge-gui/res/cardsfolder/l/legions_initiative.txt
forge-gui/res/cardsfolder/l/living_death.txt
forge-gui/res/cardsfolder/s/scrap_mastery.txt

Improve simultaneous handling with ChangeZoneAll

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-ai/src/main/java/forge/ai/SpellApiToAi.java
forge-ai/src/main/java/forge/ai/ability/AlterAttributeAi.java
forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardCopyService.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java
forge-gui/res/cardsfolder/upcoming/drover_grizzly.txt
forge-gui/res/lists/TypeLists.txt

Keyword: Saddle

---

forge-ai/src/main/java/forge/ai/ability/ChangeZoneAllAi.java
forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/cost/CostDiscard.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerDiscardedAll.java
forge-gui/res/cardsfolder/g/godo_bandit_warlord.txt
forge-gui/res/cardsfolder/upcoming/three_dog_galaxy_news_dj.txt
forge-gui/res/cardsfolder/upcoming/veronica_dissident_scribe.txt
forge-gui/res/cardsfolder/upcoming/vexing_radgull.txt

- [Three Dog, Galaxy News DJ](https://scryfall.com/card/pip/120/three-dog-galaxy-news-dj)
- [Veronica, Dissident Scribe](https://scryfall.com/card/pip/70/veronica-dissident-scribe)
- [Vexing Radgull](https://scryfall.com/card/pip/41/vexing-radgull)

PIP: Three Dog, Veronica, Vexing Radgull

---

forge-core/src/main/java/forge/card/CardType.java
forge-core/src/main/java/forge/card/CardTypeView.java
forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/card/Card.java

Closes #4805 
no cards for Outlaw yet
the closest effect we could make right now is "Boneyard Desecrator" but it has incomplete PT

CardType: add isOutlaw

---

forge-gui/res/adventure/common/maps/map/barbariancamp/barbariancamp_goblin_3.tmx
forge-gui/res/adventure/common/maps/map/cave/cave_snake.tmx
forge-gui/res/adventure/common/maps/map/lavaforge/lavaforge_3_vulcanodragon.tmx
forge-gui/res/adventure/common/maps/map/tibalt/tibalt_f3.tmx
forge-gui/res/adventure/common/world/enemies.json

It seems like by using the editor it rearranged the "gamespermatch" param. I've tested against Kiora and it seems to still be working

Adventure minor patches

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/trigger/TriggerChangesZone.java
forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
forge-gui/res/cardsfolder/a/ajanis_last_stand.txt
forge-gui/res/cardsfolder/d/dingus_egg.txt
forge-gui/res/cardsfolder/g/gorilla_tactics.txt
forge-gui/res/cardsfolder/g/guerrilla_tactics.txt
forge-gui/res/cardsfolder/m/mangaras_blessing.txt
forge-gui/res/cardsfolder/m/metrognome.txt
forge-gui/res/cardsfolder/o/orvar_the_all_form.txt
forge-gui/res/cardsfolder/p/psychic_purge.txt
forge-gui/res/cardsfolder/p/pure_intentions.txt
forge-gui/res/cardsfolder/q/quagnoth.txt
forge-gui/res/cardsfolder/s/sand_golem.txt
forge-gui/res/cardsfolder/s/spiritual_focus.txt

Fix Pure Intentions

---

forge-gui/res/quest/commanderprecons/Deep Clue Sea [MKC] [2024].dck
forge-gui/res/quest/commanderprecons/Mutant Menace [PIP] [2024].dck

Also added Deep Clue Sea (MKC)

Added the Mutant Menace (PIP) deck

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/a/astarions_thirst.txt
forge-gui/res/cardsfolder/c/chastise.txt
forge-gui/res/cardsfolder/d/deaths_caress.txt
forge-gui/res/cardsfolder/d/devour_in_shadow.txt
forge-gui/res/cardsfolder/e/essence_vortex.txt
forge-gui/res/cardsfolder/e/exile.txt
forge-gui/res/cardsfolder/g/garruk_apex_predator.txt
forge-gui/res/cardsfolder/g/garruk_the_slayer.txt
forge-gui/res/cardsfolder/g/grisly_spectacle.txt
forge-gui/res/cardsfolder/o/orzhov_charm.txt
forge-gui/res/cardsfolder/p/pyrotechnic_performer.txt
forge-gui/res/cardsfolder/r/rashida_scalebane.txt
forge-gui/res/cardsfolder/s/sever_soul.txt
forge-gui/res/cardsfolder/s/swords_to_plowshares.txt
forge-gui/res/cardsfolder/u/urza_academy_headmaster.txt
forge-gui/res/cardsfolder/v/vendetta.txt
forge-gui/res/cardsfolder/v/vraskas_stoneglare.txt
forge-gui/res/cardsfolder/w/weed_strangle.txt

@Hanmac 
here's your case of #4830 fixed now
lots of cards like _Swords to Plowshares_ could be refactored the same way with this

AbilityUtils LKI support

---

forge-gui/res/cardsfolder/upcoming/mysterious_stranger.txt

Tested card script for [Mysterious Stranger](https://scryfall.com/card/pip/63/mysterious-stranger).

PIP: Mysterious Stranger

---

forge-game/src/main/java/forge/game/trigger/Trigger.java
forge-gui/res/cardsfolder/t/transmute_artifact.txt
forge-gui/res/cardsfolder/upcoming/suppressor_skyguard.txt

Suppressor Skyguard and support

---

forge-gui/res/cardsfolder/upcoming/memory_vampire.txt
forge-gui/res/cardsfolder/upcoming/ordruun_mentor.txt

- [Memory Vampire](https://scryfall.com/card/clu/38/memory-vampire)
- [Ordruun Mentor](https://scryfall.com/card/clu/39/ordruun-mentor)

CLU: Memory Vampire & Ordruun Mentor

---

forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerCommitCrime.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/upcoming/raven_of_fell_omens.txt

OTJ: Commit Crime

---

forge-gui/res/cardsfolder/upcoming/conduit_pylons.txt
forge-gui/res/cardsfolder/upcoming/creosote_heath.txt
forge-gui/res/cardsfolder/upcoming/festering_gulch.txt

- [Conduit Pylons](https://www.magicspoiler.com/mtg-spoiler/conduit-pylons/)
- [Creosote Heath](https://www.magicspoiler.com/mtg-spoiler/creosote-heath/)
- [Festering Gulch](https://www.magicspoiler.com/mtg-spoiler/festering-gulch/)

OTJ: Conduit Pylons, Creosote Heath, Festering Gulch

---

forge-gui/res/cardsfolder/upcoming/rodeo_pyromancers.txt
forge-gui/res/cardsfolder/upcoming/rooftop_assassin.txt
forge-gui/res/cardsfolder/upcoming/wanted_griffin.txt
forge-gui/res/tokenscripts/r_1_1_mercenary_tappump.txt

- [Rodeo Pyromancers](https://www.magicspoiler.com/mtg-spoiler/rodeo-pyromancers/)
- [Rooftop Assassin](https://www.magicspoiler.com/mtg-spoiler/rooftop-assassin/)
- [Wanted Griffin](https://www.magicspoiler.com/mtg-spoiler/wanted-griffin/) and respective token

OTJ: Rodeo Pyromancers, Rooftop Assassin, Wanted Griffin

---

forge-gui/res/cardsfolder/upcoming/canyon_crab.txt
forge-gui/res/cardsfolder/upcoming/neutralize_the_guards.txt
forge-gui/res/cardsfolder/upcoming/stop_cold.txt

- [Canyon Crab](https://www.magicspoiler.com/mtg-spoiler/canyon-crab/)
- [Neutralize the Guards](https://www.magicspoiler.com/mtg-spoiler/neutralize-the-guards/)
- [Stop Cold](https://www.magicspoiler.com/mtg-spoiler/stop-cold/)

OTJ: Canyon Crab, Neutralize the Guards, Stop Cold

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardCopyService.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityPlotZone.java
forge-gui/res/cardsfolder/upcoming/fblthp_lost_on_the_range.txt
forge-gui/res/cardsfolder/upcoming/irascible_wolverine.txt

Closes #4802 
Closes #4743 
Updated Plot logic for `Fblthp, Lost on the Range`

Keyword: Plot

---

forge-gui/res/cardsfolder/upcoming/bristlepack_sentry.txt
forge-gui/res/cardsfolder/upcoming/lavaspur_boots.txt
forge-gui/res/cardsfolder/upcoming/malcolm_the_eyes.txt

- [Bristlepack Sentry](https://www.magicspoiler.com/mtg-spoiler/bristlepack-sentry/)
- [Lavaspur Boots](https://www.magicspoiler.com/mtg-spoiler/lavaspur-boots/)
- [Malcolm, the Eyes](https://www.magicspoiler.com/mtg-spoiler/malcolm-the-eyes/)

OTJ: Bristlepack Sentry, Lavaspur Boots, Malcolm, the Eyes

---

forge-gui/res/cardsfolder/upcoming/ankle_biter.txt
forge-gui/res/cardsfolder/upcoming/deadeye_duelist.txt
forge-gui/res/cardsfolder/upcoming/reckless_lackey.txt

- [Ankle Biter](https://www.magicspoiler.com/mtg-spoiler/ankle-biter/)
- [Deadeye Duelist](https://www.magicspoiler.com/mtg-spoiler/deadeye-duelist/)
- [Reckless Lackey](https://www.magicspoiler.com/mtg-spoiler/reckless-lackey/)

OTJ: Ankle Biter, Deadeye Duelist, Reckless Lackey

---

forge-game/src/main/java/forge/game/player/PlayerProperty.java

Fix Rose, Cutthroat Raider

---

forge-gui/res/cardsfolder/upcoming/at_knifepoint.txt
forge-gui/res/cardsfolder/upcoming/ghired_mirror_of_the_wilds.txt
forge-gui/res/cardsfolder/upcoming/selvala_eager_trailblazer.txt
forge-gui/res/cardsfolder/upcoming/sterling_supplier.txt
forge-gui/res/cardsfolder/upcoming/wanted_griffin.txt

Tested card scripts for my best reckoning of:
- [Ghired, Mirror of the Wilds](https://www.magicspoiler.com/mtg-spoiler/ghired-mirror-of-the-wilds/)
- [Selvala, Eager Trailblazer](https://www.magicspoiler.com/mtg-spoiler/selvala-eager-trailblazer/)
- [Sterling Supplier](https://www.magicspoiler.com/mtg-spoiler/sterling-supplier/)
Minor fixes:
- Updating AI deckbuilding tags on Selvala, ~At Knifepoint~, and Wanted Griffin as requested.

OTJ: Ghired, Selvala, Sterling Supplier

---

forge-gui/res/cardsfolder/upcoming/duelist_of_the_mind.txt
forge-gui/res/cardsfolder/upcoming/hell_to_pay.txt

- [Duelist of the Mind](https://scryfall.com/card/otj/45/duelist-of-the-mind)
- [Hell to Pay](https://scryfall.com/card/otj/126/hell-to-pay)

OTJ: Duelist of the Mind, Hell to Pay

---

forge-gui/res/cardsfolder/upcoming/cleopatra_exiled_pharaoh.txt
forge-gui/res/cardsfolder/upcoming/eivor_battle_ready.txt
forge-gui/res/cardsfolder/upcoming/ezio_blade_of_vengeance.txt

- [Cleopatra, Exiled Pharaoh](https://scryfall.com/card/acr/52/cleopatra-exiled-pharaoh)
- [Eivor, Battle-Ready](https://scryfall.com/card/acr/274/eivor-battle-ready)
- [Ezio, Blade of Vengeance](https://scryfall.com/card/acr/275/ezio-blade-of-vengeance)

ACR: Cleopatra, Ezio (Blade), Eivor

---

forge-gui/res/cardsfolder/v/vault_21_house_gambit.txt

Ended up not needing engine changes despite someone tagging it that way in the project.
Seems like this could be a real black hole to get the AI to play well, but it might be a fun rainy day project.

PIP: vault_21_house_gambit

---

forge-gui/res/cardsfolder/upcoming/rakdos_the_muscle.txt
forge-gui/res/cardsfolder/upcoming/satoru_the_infiltrator.txt
forge-gui/res/cardsfolder/upcoming/vraska_the_silencer.txt

- [Rakdos, the Muscle](https://scryfall.com/card/otj/226/rakdos-the-muscle)
- [Satoru, the Infiltrator](https://www.magicspoiler.com/mtg-spoiler/satoru-the-infiltrator/)
- [Vraska, the Silencer](https://scryfall.com/card/otj/237/vraska-the-silencer)

OTJ: Rakdos, Satoru, Vraska

---

forge-gui/res/cardsfolder/upcoming/ertha_jo_frontier_mentor.txt
forge-gui/res/cardsfolder/upcoming/marchesa_dealer_of_death.txt
forge-gui/res/cardsfolder/upcoming/vial_smasher_gleeful_grenadier.txt

- [Ertha Jo, Frontier Mentor](https://scryfall.com/card/otj/203/ertha-jo-frontier-mentor)
- [Marchesa, Dealer of Death](https://scryfall.com/card/otj/220/marchesa-dealer-of-death)
- [Vial Smasher, Gleeful Grenadier](https://scryfall.com/card/otj/235/vial-smasher-gleeful-grenadier)

OTJ: Ertha Jo, Marchesa, Vial Smasher

---

forge-gui/res/cardsfolder/upcoming/geralf_the_fleshwright.txt
forge-gui/res/cardsfolder/upcoming/unscrupulous_contractor.txt
forge-gui/res/cardsfolder/upcoming/vadmir_new_blood.txt

- [Geralf, the Fleshwright](https://www.reddit.com/r/magicTCG/comments/1bpwov6/otj_geralf_the_fleshwright_tcgplayer/)
- [Unscrupulous Contractor](https://www.magicspoiler.com/mtg-spoiler/unscrupulous-contractor/)
- [Vadmir, New Blood](https://www.magicspoiler.com/mtg-spoiler/vadmir-new-blood/)

OTJ: Geralf, Unscrupulous Contractor, Vadmir

---

forge-gui/res/cardsfolder/upcoming/visage_bandit.txt
forge-gui/res/cardsfolder/upcoming/voracious_varmint.txt
forge-gui/res/cardsfolder/upcoming/wrangler_of_the_damned.txt

- [Visage Bandit](https://scryfall.com/card/otj/76/visage-bandit)
- [Voracious Varmint](https://scryfall.com/card/otj/188/voracious-varmint)
- [Wrangler of the Damned](https://scryfall.com/card/otj/238/wrangler-of-the-damned)

OTJ: Visage Bandit, Voracious Varmint, Wrangler of the Damned

---

forge-game/src/main/java/forge/game/trigger/TriggerChangesZone.java
forge-gui/res/cardsfolder/b/boneyard_scourge.txt

This fixes a regression from #4840 with engine logic

Fix Boneyard Scourge triggering from itself dying

---

forge-gui/res/cardsfolder/upcoming/junk_jet.txt

Seems like I forgot about this one

PIP Junk Jet

---

forge-gui/res/cardsfolder/m/miming_slime.txt
forge-gui/res/cardsfolder/upcoming/tumbleweed_rising.txt
forge-gui/res/cardsfolder/upcoming/unfortunate_accident.txt
forge-gui/res/cardsfolder/upcoming/vengeful_townsfolk.txt

- [Tumbleweed Rising](https://scryfall.com/card/otj/187/tumbleweed-rising)
- [Unfortunate Accident](https://scryfall.com/card/otj/111/unfortunate-accident)
- [Vengeful Townsfolk](https://scryfall.com/card/otj/37/vengeful-townsfolk)
Minor fixes:
- Updated AI deckbuilding tags on Miming Slime.

OTJ: Tumbleweed Rising, Unfortunate Accident, Vengeful Townsfolk

---

forge-gui/res/cardsfolder/upcoming/tomb_trawler.txt
forge-gui/res/cardsfolder/upcoming/trash_the_town.txt
forge-gui/res/cardsfolder/upcoming/treasure_dredger.txt

- [Tomb Trawler](https://scryfall.com/card/otj/250/tomb-trawler)
- [Trash the Town](https://scryfall.com/card/otj/186/trash-the-town)
- [Treasure Dredger](https://scryfall.com/card/otj/110/treasure-dredger)

OTJ: Tomb Trawler, Trash the Town, Treasure Dredger

---

forge-game/src/main/java/forge/game/ability/effects/MakeCardEffect.java
forge-gui/res/cardsfolder/b/brazen_boarding.txt
forge-gui/res/cardsfolder/upcoming/tajic_legions_valor.txt

@Simisays @dracontes thought you might be interested in the new "Filter" capability

YMKM: tajic_legions_valor + support

---

forge-gui/res/cardsfolder/upcoming/it_that_heralds_the_end.txt

https://scryfall.com/card/mh3/9/it-that-heralds-the-end

Add an unreleased card from MH3

---

forge-game/src/main/java/forge/game/card/Card.java

- closes #4911 
This should be fairly future-proof 🤞 
OLD
NEW!

tweak for Ward keyword display

---

forge-gui/res/cardsfolder/upcoming/omenport_vigilante.txt
forge-gui/res/cardsfolder/upcoming/slickshot_vault_buster.txt
forge-gui/res/cardsfolder/upcoming/stoic_sphinx.txt
forge-gui/res/cardsfolder/upcoming/take_for_a_ride.txt
forge-gui/res/cardsfolder/upcoming/take_the_fall.txt
forge-gui/res/cardsfolder/upcoming/throw_from_the_saddle.txt

- [Omenport Vigilante](https://scryfall.com/card/otj/21/omenport-vigilante)
- [Slickshot Vault-Buster](https://scryfall.com/card/otj/68/slickshot-vault-buster)
- [Stoic Sphinx](https://scryfall.com/card/otj/71/stoic-sphinx)
- [Take for a Ride](https://scryfall.com/card/otj/148/take-for-a-ride)
- [Take the Fall](https://scryfall.com/card/otj/73/take-the-fall)
- [Throw from the Saddle](https://scryfall.com/card/otj/185/throw-from-the-saddle)

OTJ: Omenport Vigilante, Slickshot Vault-Buster, Stoic Sphinx, Take for a Ride, Take the Fall, Throw from the Saddle

---

forge-gui/res/editions/Mystery Booster Playtest Cards.txt

Apply P- prepend to another duped name cards

Update Mystery Booster Playtest Cards.txt

---

forge-gui/res/editions/Breaking News.txt
forge-gui/res/editions/Outlaws of Thunder Junction Commander.txt
forge-gui/res/editions/Outlaws of Thunder Junction.txt
forge-gui/res/editions/Secret Lair Drop Series.txt
forge-gui/res/editions/The Big Score.txt

Excluded bountry tokens for now until I know how they're handled

Edition updates: BIG, OTC, OTJ, OTP, SLD

---

forge-gui/res/cardsfolder/upcoming/sheriff_of_safe_passage.txt
forge-gui/res/cardsfolder/upcoming/shoot_the_sheriff.txt
forge-gui/res/cardsfolder/upcoming/silver_deputy.txt
forge-gui/res/cardsfolder/upcoming/slickshot_lockpicker.txt
forge-gui/res/cardsfolder/upcoming/spinewoods_armadillo.txt
forge-gui/res/cardsfolder/upcoming/step_between_worlds.txt

- [Sheriff of Safe Passage](https://scryfall.com/card/otj/29/sheriff-of-safe-passage)
- [Shoot the Sheriff](https://scryfall.com/card/otj/106/shoot-the-sheriff)
- [Silver Deputy](https://scryfall.com/card/otj/248/silver-deputy)
- [Slickshot Lockpicker](https://scryfall.com/card/otj/67/slickshot-lockpicker)
- [Spinewoods Armadillo](https://scryfall.com/card/otj/182/spinewoods-armadillo)
- [Step Between Worlds](https://scryfall.com/card/otj/70/step-between-worlds)

OTJ: Sheriff of Safe Passage, Shoot the Sheriff, Silver Deputy, Slickshot Lockpicker, Spinewoods Armadillo, Step Between Worlds

---

forge-gui/res/puzzle/PS_PIP1.pzl

Added puzzle PS_PIP1 - Possibility Storm - Fallout #01

Add puzzle PS_PIP1

---

forge-gui/res/cardsfolder/upcoming/raucous_entertainer.txt
forge-gui/res/cardsfolder/upcoming/reach_for_the_sky.txt
forge-gui/res/cardsfolder/upcoming/redrock_sentinel.txt
forge-gui/res/cardsfolder/upcoming/resilient_roadrunner.txt

Added Resilient Roadrunner, Raucous Entertainer, Reach for the Sky, and Redrock Sentinel.

Four new OTJ cards

---

forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-game/src/main/java/forge/game/zone/MagicStack.java

Caused by the freeze changes in #4794
Maybe there's a better long term fix if you can find one?

Fix mana doublers not working during payment

---

forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
forge-gui/res/cardsfolder/h/herald_of_anafenza.txt

one of the cleanups to use Keyword instead of Flags

Outlast: use Keyword for check

---

forge-gui/res/cardsfolder/upcoming/heartless_conscription.txt
forge-gui/res/cardsfolder/upcoming/rumbleweed.txt

added rumbleweed and heartless conscription

2 otc cards

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardUtil.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/b/bruenor_battlehammer.txt
forge-gui/res/cardsfolder/f/forge_anew.txt
forge-gui/res/cardsfolder/g/gavi_nest_warden.txt
forge-gui/res/cardsfolder/s/spellpyre_phoenix.txt

Closes #5007 
i chose to use MagicStack similar to ThisTurnCast
removed YouCycledThisTurn, and YouEquippedThisTurn
The Cards might be later updated for CyclingForZero and the Equip one, this can be a separate MR
@tool4ever feel free to update _Tezzeret, Betrayer of Flesh_

MagicStack: ThisTurnActivated

---

forge-gui/res/cardsfolder/upcoming/bria_riptide_rogue.txt
forge-gui/res/cardsfolder/upcoming/byrke_long_ear_of_the_law.txt
forge-gui/res/cardsfolder/upcoming/mabel_heir_to_cragflame.txt
forge-gui/res/tokenscripts/cragflame.txt

Submitting on behalf of **xanxer6rB** over on Discord, tested card scripts for:
- [Bria, Riptide Rogue](https://scryfall.com/card/blb/379/bria-riptide-rogue)
- [Byrke, Long Ear of the Law](https://scryfall.com/card/blb/380/byrke-long-ear-of-the-law)
- [Mabel, Heir to Cragflame](https://scryfall.com/card/blb/224/mabel-heir-to-cragflame) and the Cragflame token

BLB: Bria, Byrke, Mabel

---

forge-game/src/main/java/forge/game/GameAction.java

GameAction: fix facedown spells via CopyCard$ not changing zone

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityAlternativeCost.java
forge-gui/res/cardsfolder/k/kentaro_the_smiling_cat.txt
forge-gui/res/cardsfolder/m/marshland_bloodcaster.txt
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Remove Alternative Cost KW

---

forge-gui/res/cardsfolder/c/collective_effort.txt
forge-gui/res/cardsfolder/l/lord_xander_the_collector.txt
forge-gui/res/cardsfolder/upcoming/phantom_interference.txt
forge-gui/res/cardsfolder/upcoming/requisition_raid.txt
forge-gui/res/cardsfolder/upcoming/return_the_favor.txt
forge-gui/res/cardsfolder/upcoming/rush_of_dread.txt
forge-gui/res/cardsfolder/upcoming/rustler_rampage.txt
forge-gui/res/cardsfolder/upcoming/smugglers_surprise.txt

Added a little UI tweak for Spree targeting since sometimes we're selecting a target for each mode
Just in case the human doing the targeting forgets what they are doing 😁

OTJ: more spree cards and polish

---

forge-gui/res/puzzle/PS_MKM4.pzl

Added puzzle PS_MKM4 - Murder at Karlov Manor 04.

Add puzzle PS_MKM4

---

forge-gui/res/cardsfolder/b/blazing_salvo.txt
forge-gui/res/cardsfolder/b/book_burning.txt
forge-gui/res/cardsfolder/b/breaking_point.txt
forge-gui/res/cardsfolder/b/browbeat.txt
forge-gui/res/cardsfolder/e/essence_vortex.txt
forge-gui/res/cardsfolder/g/grip_of_amnesia.txt
forge-gui/res/cardsfolder/l/lava_blister.txt
forge-gui/res/cardsfolder/m/merchant_of_the_vale_haggle.txt
forge-gui/res/cardsfolder/m/molten_influence.txt
forge-gui/res/cardsfolder/p/perplex.txt
forge-gui/res/cardsfolder/r/risk_factor.txt
forge-gui/res/cardsfolder/s/skullscorch.txt
forge-gui/res/cardsfolder/t/tyrannize.txt

Starting off this cleanup by dealing with a few items by hand first so I don't have to account for them later when searching and replacing thousands of files.

Cost$ cleanup: straggler pass #1

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-gui/res/cardsfolder/a/ancestral_vision.txt
forge-gui/res/cardsfolder/c/crashing_footfalls.txt
forge-gui/res/cardsfolder/e/evermind.txt
forge-gui/res/cardsfolder/r/restore_balance.txt

Remove obsolete logic

---

forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardProperty.java

CardFactoryUtil: fix Squad Trigger for Copy

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/e/embiggen.txt

The fourth attempt at cherry-picking the contents of the Embiggen branch after a failed merge. Hopefully fourth time is the charm and all that.

UNF Embiggen - take four

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/cost/CostDiscard.java
forge-game/src/main/java/forge/game/cost/CostSacrifice.java
forge-gui/res/cardsfolder/t/transmutation_font.txt
forge-gui/src/main/java/forge/player/HumanCostDecision.java

The Cost Decision for AI still needs to be updated
and I'm not that happy with the Message for "1 left" when there are still 3 left (even if you choose 1 at a time)

Transmuation Font

---

forge-gui/res/cardsfolder/p/phyrexian_dragon_engine.txt
forge-gui/res/cardsfolder/upcoming/herigast_erupting_hellkite.txt
forge-gui/src/main/java/forge/player/HumanCostDecision.java

MH3: Herigast, Erupting Nullkite

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/b/bloatfly_swarm.txt
forge-gui/res/cardsfolder/v/vexing_puzzlebox.txt

Fix Vexing Puzzlebox

---

forge-gui/res/cardsfolder/upcoming/twins_of_discord.txt

M3C Twins of Discord

---

forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/mana/ManaPool.java
forge-gui/res/cardsfolder/m/make_your_own_luck.txt
forge-gui/res/cardsfolder/rebalanced/a-thran_spider.txt
forge-gui/res/cardsfolder/v/venerated_loxodon.txt
forge-gui/src/main/java/forge/gamemodes/match/input/InputPayManaOfCostPayment.java
forge-gui/src/main/java/forge/player/HumanPlay.java

Fixes Autopay not working with Emerged

Clean up some obsolete payment checks

---

forge-gui/res/adventure/common/custom_cards/xira_boss_effect.txt

Missed the train on this pull request by mere seconds, https://github.com/Card-Forge/forge/pull/5201 , so once more, with feeling.

Fixing card text capitalization on the Adventure Mode custom card Xira's Boss Effect

---

forge-gui/res/adventure/Amonkhet/world/quests.json
forge-gui/res/adventure/Shandalar/world/quests.json

As requested on https://github.com/Card-Forge/forge/pull/5212 , mostly grammar and typos, along with my best reckoning of a slightly more developed standard formatting. Those more into the nuts and bolts of Adventure Mode, do tell if there's something you'd do otherwise.

Adventure Mode cleanup: quest.json files

---

forge-gui/res/cardsfolder/upcoming/flare_of_duplication.txt

MH3: Flare of Duplication

---

forge-ai/src/main/java/forge/ai/AiController.java

Fix plague of vermin crash

---

forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/GlobalRuleChange.java
forge-game/src/main/java/forge/game/ability/effects/DayTimeEffect.java
forge-game/src/main/java/forge/game/phase/Untap.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantChangeDayTime.java
forge-gui/res/cardsfolder/a/angel_of_eternal_dawn.txt

That removes one of the GlobalRule
i wanted a ReplacementEffect.CantHappen, but without "Affected" it wouldn't be nice

CantChangeDayTime: StaticAbility instead of GlobalRule

---

forge-gui/res/cardsfolder/d/deb_thomas.txt
forge-gui/res/editions/Celebration Cards.txt
forge-gui/res/editions/Modern Horizons 3.txt
forge-gui/res/lists/TypeLists.txt
forge-gui/res/tokenscripts/r_1_1_employee.txt

Source: https://scryfall.com/card/pcel/9/deb-thomas

PCEL: Deb Thomas

---

forge-game/src/main/java/forge/game/ability/effects/ChangeZoneAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-gui/res/cardsfolder/c/counterbore.txt
forge-gui/res/cardsfolder/c/cranial_extraction.txt
forge-gui/res/cardsfolder/e/eradicate.txt
forge-gui/res/cardsfolder/e/extirpate.txt
forge-gui/res/cardsfolder/h/haunting_echoes.txt
forge-gui/res/cardsfolder/k/kotose_the_silent_spider.txt
forge-gui/res/cardsfolder/l/lobotomy.txt
forge-gui/res/cardsfolder/m/memoricide.txt
forge-gui/res/cardsfolder/n/necromentia.txt
forge-gui/res/cardsfolder/q/quash.txt
forge-gui/res/cardsfolder/s/scour.txt
forge-gui/res/cardsfolder/s/shimian_specter.txt
forge-gui/res/cardsfolder/s/sowing_salt.txt
forge-gui/res/cardsfolder/s/splinter.txt
forge-gui/res/cardsfolder/t/test_of_talents.txt
forge-gui/res/cardsfolder/t/the_end.txt
forge-gui/res/cardsfolder/t/thought_hemorrhage.txt
forge-gui/res/cardsfolder/u/unmoored_ego.txt

Panglacial Wurm: support altcosts

---

forge-ai/src/main/java/forge/ai/ability/TokenAi.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantAttackBlock.java

Closes #3790 
AI doesn't create Tokens in response to attack, if the Token can't block any of the Attacker
but because of the high percentage, AI might create the token later anyway

TokenAi: do not create Token that can't block in Response

---

forge-gui/res/cardsfolder/upcoming/emrakul_the_world_anew.txt
forge-gui/res/cardsfolder/upcoming/grist_voracious_larva_grist_the_plague_swarm.txt
forge-gui/res/cardsfolder/upcoming/phlage_titan_of_fires_fury.txt

MH3: Add card scripts for three MH3 cards:
- Emrakul, the World Anew
- Grist, Voracious Larva // Grist, the Plague Swarm
- Phlage, Titan of Fire's Fury

MH3: Emrakul, the World Anew + 2 cards

---

forge-ai/src/main/java/forge/ai/ability/ChooseGenericEffectAi.java
forge-gui/res/cardsfolder/t/tireless_provisioner.txt

To be improved/generalized as needed, but works for the basic use cases.

Basic AI logic for Tireless Provisioner

---

forge-gui/res/cardsfolder/upcoming/ral_monsoon_mage_ral_leyline_prodigy.txt
forge-gui/res/cardsfolder/upcoming/sorin_of_house_markov_sorin_ravenous_neonate.txt
forge-gui/res/cardsfolder/upcoming/tamiyo_inquisitive_student_tamiyo_seasoned_scholar.txt

MH3: Add card scripts for the last three leaked flipwalker cards:
- Ral, Monsoon Mage // Ral, Leyline Prodigy
- Sorin of House Markov // Sorin, Ravenous Neonate
- Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar

MH3: 3 new Flipwalkers

---

forge-game/src/main/java/forge/game/TriggerReplacementBase.java
forge-game/src/main/java/forge/game/ability/effects/DigMultipleEffect.java
forge-game/src/main/java/forge/game/replacement/ReplaceMill.java
forge-game/src/main/java/forge/game/trigger/WrappedAbility.java

Fix Mirror-Shield Hoplite

---

forge-gui/res/editions/Arena League 1999.txt

Update Arena League 1999.txt

---

forge-gui/res/cardsfolder/upcoming/kozileks_unsealing.txt

I didn't see this card among the currently implemented MH3 cards or in the pending PR queue, so here's my attempt at it.

MH3: Kozilek's Unsealing

---

forge-gui/res/cardsfolder/a/architect_of_the_untamed.txt
forge-gui/res/cardsfolder/upcoming/fetid_gargantua.txt
forge-gui/res/cardsfolder/upcoming/sage_of_the_unknowable.txt

Card Gallery update filled in costs for Sage of the Unknowable and Fetid Gargantua.

Two MH3 cards

---

forge-game/src/main/java/forge/game/ability/effects/ManifestBaseEffect.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-gui/res/cardsfolder/a/aether_tide.txt
forge-gui/res/cardsfolder/t/the_toymakers_trap.txt
forge-gui/res/cardsfolder/upcoming/white_orchid_phantom.txt
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Looks like doing #2472 will matter now so "X" parts of costs are properly assigned.
Closes #5346
Closes #5334

Fix Conflagrate

---

forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
forge-game/src/main/java/forge/game/ability/effects/ImmediateTriggerEffect.java
forge-gui/res/cardsfolder/s/synth_eradicator.txt
forge-gui/res/cardsfolder/upcoming/etched_slith.txt
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

Etched Slith and support

---

forge-gui/res/cardsfolder/upcoming/etherium_pteramander.txt

Added Etherium Pteramander Script

One MH3 Card

---

forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/player/Player.java

Closes #5376 
@tool4ever that should be a good enough start to code `Blaster Hulk` and `Izzet Generatorium`
for `{E} paid or lost this turn`

Player counters removed this turn

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/card/Card.java
forge-gui/res/cardsfolder/h/hunting_velociraptor.txt

Not pretty but works:
Closes #4725

Support MayPlay on extrinsic AltCost

---

forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java
forge-gui/res/cardsfolder/upcoming/exterminator_magmarch.txt

Is there an easier way to filter `all` or `candidates` ?

M3C: exterminator_magmarch

---

forge-gui/res/editions/Planeswalker Championship Promos.txt

Update Planeswalker Championship Promos.txt

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChooseGenericEffect.java
forge-gui/res/cardsfolder/b/borderland_explorer.txt
forge-gui/res/cardsfolder/r/ruin_grinder.txt
forge-gui/res/cardsfolder/upcoming/wheel_of_potential.txt
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/player/HumanPlay.java

MH3: wheel_of_potential + support

---

forge-game/src/main/java/forge/game/ability/effects/DebuffEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-gui/res/cardsfolder/a/akromas_will.txt
forge-gui/res/cardsfolder/e/etched_champion.txt
forge-gui/res/cardsfolder/f/favor_of_the_mighty.txt
forge-gui/res/cardsfolder/i/iridescent_angel.txt
forge-gui/res/cardsfolder/p/pristine_angel.txt
forge-gui/res/cardsfolder/s/spectra_ward.txt
forge-gui/res/cardsfolder/upcoming/eldritch_immunity.txt

Keyword: Protection from each color

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/keyword/Emerge.java
forge-game/src/main/java/forge/game/keyword/Keyword.java

closes #5370 
needed for `Crabomination` => `K:Emerge:5 B B:Artifact`

MH3: Emerge From

---

forge-core/src/main/java/forge/card/CardRules.java
forge-core/src/main/java/forge/card/ColorSet.java
forge-core/src/main/java/forge/deck/DeckFormat.java
forge-core/src/main/java/forge/item/PaperCard.java

The objective of this PR is to address the concern associated with https://discord.com/channels/267367946135928833/1175324774067613716/1175324774067613716.  This will theoretically allow Clara Oswald, Faceless One, and The Prismatic Piper to be used as commanders and/or partners.

Piper-like card update

---

forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityRestriction.java

Some Simplification for Prowl to use `sharesCreatureTypeWith` (with might be better for Changeling effects)

Prowl: use sharesCreatureTypeWith

---

forge-game/src/main/java/forge/game/GlobalRuleChange.java
forge-game/src/main/java/forge/game/combat/CombatUtil.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityBlockRestrict.java
forge-gui/res/cardsfolder/a/astral_arena.txt
forge-gui/res/cardsfolder/c/caverns_of_despair.txt
forge-gui/res/cardsfolder/d/dueling_grounds.txt
forge-gui/res/cardsfolder/m/mirri_weatherlight_duelist.txt
forge-gui/res/cardsfolder/s/silent_arbiter.txt

@Northmoc @tool4ever just one GlobalRule remaining

StaticAbilityBlockRestict: remove Global Rules

---

forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java

Fixed AI ignoring Mogg Bombers damage trigger

---

forge-gui/res/cardsfolder/upcoming/arna_kennerud_skycaptain.txt
forge-gui/res/cardsfolder/upcoming/genku_future_shaper.txt
forge-gui/res/cardsfolder/upcoming/thraben_charm.txt
forge-gui/res/tokenscripts/b_1_1_rat_lifelink.txt
forge-gui/res/tokenscripts/u_1_2_moonfolk_flying.txt
forge-gui/res/tokenscripts/w_2_2_fox_vigilance.txt

MH3: Add card scripts for three MH3 cards, including token scripts:
- Arna Kennerüd, Skycaptain
- Genku, Future Shaper
- Thraben Charm
- 1/1 black Rat creature token with lifelink
- 1/2 blue Moonfolk creature token with flying
- 2/2 white Fox creature token with vigilance

MH3: Arna Kennerüd, Skycaptain + 2 cards

---

forge-core/src/main/java/forge/item/PaperCard.java
forge-gui-desktop/src/main/java/forge/screens/deckeditor/controllers/CEditorDraftingProcess.java
forge-gui-desktop/src/test/java/forge/BoosterDraftTest.java
forge-gui/res/cardsfolder/a/archdemon_of_paliano.txt
forge-gui/res/cardsfolder/c/canal_dredger.txt
forge-gui/res/cardsfolder/d/deal_broker.txt
forge-gui/res/cardsfolder/l/lore_seeker.txt
forge-gui/res/editions/Conspiracy Take the Crown.txt
forge-gui/res/editions/Conspiracy.txt
forge-gui/src/main/java/forge/gamemodes/limited/BoosterDraft.java
forge-gui/src/main/java/forge/gamemodes/limited/CardRanker.java
forge-gui/src/main/java/forge/gamemodes/limited/IBoosterDraft.java
forge-gui/src/main/java/forge/gamemodes/limited/LimitedPlayer.java
forge-gui/src/main/java/forge/gamemodes/limited/LimitedPlayerAI.java

- Archdemon of Paliano
- Canal Dredger
- Deal Broker
- Lore Seeker

Add remaining Conspiracy cards

---

forge-game/src/main/java/forge/game/card/CounterEnumType.java
forge-gui/res/cardsfolder/upcoming/anthem_of_champions.txt
forge-gui/res/cardsfolder/upcoming/nine_lives_familiar.txt

Tested card scripts developed with initial assistance from [ForgeScribeGPT4](https://chatgpt.com/g/g-TGeM8rWuF-forgescribegpt4):
- [Anthem of Champions](https://scryfall.com/card/fdn/116/anthem-of-champions)
- [Nine-Lives Familiar](https://scryfall.com/card/fdn/66/nine-lives-familiar), with the associated aesthetic counter added to `CounterEnumType.java`

FDN: Anthem of Champions, Nine-Lives Familiar

---

forge-gui/res/draft/rankings/mh3.rnk

Generated by forge-gui/tools/RankingScraper.py

Add draft rankings for MH3

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-gui/res/cardsfolder/upcoming/escape_detection.txt
forge-gui/res/cardsfolder/upcoming/monastery_raid.txt

Freerunning as calculateAmount

---

forge-gui-mobile/src/forge/adventure/data/AdventureEventData.java
forge-gui-mobile/src/forge/adventure/util/AdventureEventController.java

- Decreased the minimum amount of cards needed for a draft to be valid 
- Increased the chance of nonstandard sets showing up
- decreased the chance of jumpstart

Draft changes

---

forge-game/src/main/java/forge/game/ability/effects/ReplaceEffect.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/upcoming/havi_the_all_father.txt

Fix Bamboozling Beebles

---

forge-gui/res/cardsfolder/upcoming/come_back_wrong.txt

Tested card script for:
- [Come Back Wrong](https://scryfall.com/card/dsk/86/come-back-wrong)

DSK: Come Back Wrong

---

forge-game/src/main/java/forge/game/ability/effects/LifeGainEffect.java

Fix Gerrard Capashen

---

forge-gui/res/cardsfolder/upcoming/tempest_angler.txt
forge-gui/res/cardsfolder/upcoming/tidecaller_mentor.txt
forge-gui/res/cardsfolder/upcoming/valley_questcaller.txt
forge-gui/res/cardsfolder/upcoming/valley_rotcaller.txt
forge-gui/res/cardsfolder/upcoming/veteran_guardmouse.txt
forge-gui/res/cardsfolder/upcoming/ygra_eater_of_all.txt

All I can do from what the current spoilers

6 BLB cards

---

forge-gui/res/cardsfolder/upcoming/bello_bard_of_the_brambles.txt
forge-gui/res/cardsfolder/upcoming/beza_the_bounding_spring.txt
forge-gui/res/cardsfolder/upcoming/brave_kin_duo.txt
forge-gui/res/cardsfolder/upcoming/cindering_cutthroat.txt
forge-gui/res/cardsfolder/upcoming/clement_the_worrywort.txt
forge-gui/res/cardsfolder/upcoming/dreamdew_entrancer.txt
forge-gui/res/cardsfolder/upcoming/fell.txt
forge-gui/res/cardsfolder/upcoming/finneas_ace_archer.txt
forge-gui/res/cardsfolder/upcoming/flubs_the_fool.txt
forge-gui/res/cardsfolder/upcoming/glarb_calamitys_augur.txt

Would Glarb work correctly with X-spells like that?

10 BLB cards

---

forge-gui/res/cardsfolder/upcoming/persistent_marshstalker.txt

(Only new English card I could see.)

Added Persistent Marshstalker

---

forge-gui/res/editions/Alchemy Thunder Junction.txt

This brings the YOTJ edition file in line with #5582

Edition updates: YOTJ

---

forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerLifeChanged.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java
forge-gui/res/cardsfolder/upcoming/moonstone_harbinger.txt

Moonstone Harbinger and support

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/PhasesEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/phase/Untap.java

CantPhase checks need to happen simultaneously

---

forge-gui-desktop/src/main/java/forge/toolbox/FSkin.java
forge-gui-desktop/src/main/java/forge/view/SplashFrame.java
forge-gui-mobile/src/forge/Forge.java
forge-gui-mobile/src/forge/assets/Assets.java
forge-gui-mobile/src/forge/assets/FSkin.java
forge-gui/src/main/java/forge/gui/GuiBase.java
forge-gui/src/main/java/forge/model/FModel.java

mobile version will use default theme if invalid theme is detected

[Mobile] prevent crash using invalid theme

---

forge-game/src/main/java/forge/game/card/CardZoneTable.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityPanharmonicon.java
forge-game/src/main/java/forge/game/trigger/TriggerChangesZoneAll.java

ChangesZoneAll: support multiple destination filtering

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameEntity.java
forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardCopyService.java

Fix Captain's Hook

---

forge-ai/src/main/java/forge/ai/AiCostDecision.java
forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-game/src/main/java/forge/game/cost/Cost.java
forge-game/src/main/java/forge/game/cost/CostForage.java
forge-game/src/main/java/forge/game/cost/ICostVisitor.java
forge-game/src/main/java/forge/game/trigger/TriggerForage.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java
forge-gui/res/cardsfolder/upcoming/treetop_sentries.txt
forge-gui/src/main/java/forge/player/HumanCostDecision.java

Add Forage Cost

---

forge-gui/res/cardsfolder/upcoming/fishers_talent.txt
forge-gui/res/cardsfolder/upcoming/gourmands_talent.txt
forge-gui/res/cardsfolder/upcoming/lilypad_village.txt
forge-gui/res/cardsfolder/upcoming/lupinflower_village.txt
forge-gui/res/cardsfolder/upcoming/mudflat_village.txt
forge-gui/res/cardsfolder/upcoming/oakhollow_village.txt
forge-gui/res/cardsfolder/upcoming/rockface_village.txt
forge-gui/res/cardsfolder/upcoming/rolling_hamsphere.txt
forge-gui/res/cardsfolder/upcoming/sword_of_the_squeak.txt
forge-gui/res/tokenscripts/g_3_3_raccoon.txt
forge-gui/res/tokenscripts/r_1_1_hamster.txt
forge-gui/res/tokenscripts/u_3_3_shark.txt

I can't get Fisher's Talent to produce Fish... there's a bug there somewhere.

BLC cards + Villages

---

forge-gui/src/main/java/forge/gamemodes/match/input/InputSelectTargets.java
forge-gui/src/main/java/forge/player/TargetSelection.java

Changing targets shouldn't allow different numbers

---

forge-gui/res/cardsfolder/upcoming/corpseberry_cultivator.txt
forge-gui/res/cardsfolder/upcoming/curious_forager.txt
forge-gui/res/cardsfolder/upcoming/feed_the_cycle.txt
forge-gui/res/cardsfolder/upcoming/osteomancer_adept.txt
forge-gui/res/cardsfolder/upcoming/thornvault_forager.txt

Not tested since snapshot doesn't have forage yet.

3 Forage BLB cards

---

forge-game/src/main/java/forge/game/TriggerReplacementBase.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/trigger/Trigger.java
forge-gui/res/cardsfolder/upcoming/zinnia_valleys_voice.txt

Text change support for Class + Saga

---

forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/o/overwhelming_splendor.txt
forge-gui/res/cardsfolder/s/scheming_fence.txt

MagicStack: apply statics before storing LKI

---

forge-game/src/main/java/forge/game/trigger/TriggerSpellAbilityCastOrCopy.java

Add ActivatorThisTurnCastEach

---

forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/upcoming/coiling_rebirth.txt
forge-gui/res/cardsfolder/upcoming/consumed_by_greed.txt
forge-gui/res/cardsfolder/upcoming/cruelclaws_heist.txt
forge-gui/res/cardsfolder/upcoming/crumb_and_get_it.txt
forge-gui/res/cardsfolder/upcoming/dawns_truce.txt
forge-gui/res/cardsfolder/upcoming/dewdrop_cure.txt
forge-gui/res/cardsfolder/upcoming/into_the_flood_maw.txt
forge-gui/res/cardsfolder/upcoming/long_rivers_pull.txt
forge-gui/res/cardsfolder/upcoming/longstalk_brawl.txt
forge-gui/res/cardsfolder/upcoming/mind_spiral.txt
forge-gui/res/cardsfolder/upcoming/nocturnal_hunger.txt
forge-gui/res/cardsfolder/upcoming/octomancer.txt
forge-gui/res/cardsfolder/upcoming/parting_gust.txt
forge-gui/res/cardsfolder/upcoming/peerless_recycling.txt
forge-gui/res/cardsfolder/upcoming/perch_protection.txt
forge-gui/res/cardsfolder/upcoming/sazacaps_brew.txt
forge-gui/res/cardsfolder/upcoming/scrapshooter.txt
forge-gui/res/cardsfolder/upcoming/starfall_invocation.txt
forge-gui/res/cardsfolder/upcoming/starforged_sword.txt
forge-gui/res/cardsfolder/upcoming/valley_rally.txt
forge-gui/res/cardsfolder/upcoming/wear_down.txt
forge-gui/res/cardsfolder/upcoming/wildfire_howl.txt
forge-gui/res/lists/TypeLists.txt

The gift cards of BLB/BLC

---

forge-game/src/main/java/forge/game/GameSnapshot.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerManaExpend.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/upcoming/teapot_slinger.txt

Closes https://github.com/Card-Forge/forge/issues/5554

Add Expend and Teapot Slinger

---

forge-game/src/main/java/forge/game/ability/ApiType.java

No more unique effect classes for each SA lol...

TokenEffect no longer has state

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/effects/BalanceEffect.java
forge-game/src/main/java/forge/game/ability/effects/SacrificeAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
forge-game/src/main/java/forge/game/card/CardCopyService.java
forge-game/src/main/java/forge/game/cost/CostForage.java
forge-game/src/main/java/forge/game/cost/CostPayment.java
forge-game/src/main/java/forge/game/cost/CostSacrifice.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-game/src/main/java/forge/game/trigger/TriggerSacrificedOnce.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java
forge-gui/res/cardsfolder/upcoming/camellia_the_seedmiser.txt
forge-gui/src/main/java/forge/player/HumanPlay.java

Some things i need to consider:
- ~~[ ] For Cost, i don't know, but i feel we need to handle them different for stuff that does "Sacrifice itself AND other", for this special case, maybe it shouldn't trigger there :(~~
Closes #5674

SacrificeOnce Trigger

---

forge-gui/res/lists/TypeLists.txt

Add missing Raccoon creature type to TypeLists

Add Raccoon creature type

---

forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-gui/res/cardsfolder/upcoming/heirloom_epic.txt

Heirloom Epic and support

---

forge-gui/res/cardsfolder/m/myra_the_magnificent.txt

Seems like my previous script did work just fine but I forget an $

UNF Myra the Magnificent

---

forge-gui/res/editions/Sega Dreamcast Cards.txt

Brings the PSDG edition in line with: #5816

Edition updates: PSDG

---

forge-game/src/main/java/forge/game/GameActionUtil.java

Split off from https://github.com/Card-Forge/forge/pull/5720

ETB update: Java code: `GameActionUtil.java`

---

forge-ai/src/main/java/forge/ai/AiController.java

Split off from https://github.com/Card-Forge/forge/pull/5720

ETB update: Java code: `AiController.java`

---

forge-gui/src/main/java/forge/gamemodes/puzzle/Puzzle.java

Split off from https://github.com/Card-Forge/forge/pull/5720

ETB update: Java code: `Puzzle.java`

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java

Split off from https://github.com/Card-Forge/forge/pull/5720

ETB update: Java code: `Card.java`, `CardFactoryUtil.java`

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java

Fix missing LTB trigger of devoured creature

---

forge-gui/res/cardsfolder/b/black_hole.txt
forge-gui/res/cardsfolder/c/charred_graverobber.txt
forge-gui/res/cardsfolder/c/coming_attraction.txt
forge-gui/res/cardsfolder/d/deal_broker.txt
forge-gui/res/cardsfolder/d/down_for_repairs.txt
forge-gui/res/cardsfolder/m/myra_the_magnificent.txt
forge-gui/res/cardsfolder/p/phyrexian_portal.txt
forge-gui/res/cardsfolder/r/razorgrass_ambush_razorgrass_field.txt
forge-gui/res/cardsfolder/r/reckless_pyrosurfer.txt
forge-gui/res/cardsfolder/s/storybook_ride.txt
forge-gui/res/cardsfolder/upcoming/chainsaw.txt
forge-gui/res/cardsfolder/upcoming/clifftop_lookout.txt
forge-gui/res/cardsfolder/upcoming/fall_of_the_first_civilization.txt
forge-gui/res/cardsfolder/upcoming/finneas_ace_archer.txt
forge-gui/res/cardsfolder/upcoming/jacob_frye.txt
forge-gui/res/cardsfolder/upcoming/kassandra_eagle_bearer.txt
forge-gui/res/cardsfolder/upcoming/loyal_inventor.txt
forge-gui/res/cardsfolder/upcoming/mjolnir_storm_hammer.txt
forge-gui/res/cardsfolder/upcoming/ral_crackling_wit.txt
forge-gui/res/cardsfolder/upcoming/shaun_and_rebecca_agents.txt
forge-gui/res/cardsfolder/upcoming/sokrates_athenian_teacher.txt
forge-gui/res/cardsfolder/upcoming/treetop_sentries.txt
forge-gui/res/cardsfolder/upcoming/wick_the_whorled_mind.txt

Mostly dealing with duplicated and missing whitespace wherever relevant. Inevitably there were also some incidental edits more or less germane with the main objective of this pass.

Whitespace cleanup for August 2024

---

forge-game/src/main/java/forge/game/card/CardFactory.java

This is for using the Special Offspring Token Image

CardFactory: add offspring imagekey

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java

@tool4ever i moved the amount from the trigger object, into the CastSA info
might need a better name for "CastSAOptKeyword"

GameActionUtil: store OptionalKeywordAmount in CastSA

---

forge-gui/res/cardsfolder/f/fabled_path_of_searo_point.txt

Tested card script for [Fabled Path of Searo Point](https://scryfall.com/card/ph19/7/fabled-path-of-searo-point).

PH19: Fabled Path of Searo Point

---

forge-gui/res/cardsfolder/f/ferris_wheel.txt
forge-gui/res/cardsfolder/s/swinging_ship.txt
forge-gui/res/cardsfolder/t/tunnel_of_love.txt

Tunnel of Love needs some more work, it doesn't seem to exile the card chosen by

UNF last 3 attractions

---

forge-gui/res/cardsfolder/f/fabled_path_of_searo_point.txt
forge-gui/res/editions/Alchemy Bloomburrow.txt
forge-gui/res/editions/Foundations.txt
forge-gui/res/editions/Secret Lair Drop Series.txt

Also fixed Fabled Path of Searo Point having no mana cost

Edition updates: FDN, SLD, YBLB

---

forge-gui/res/cardsfolder/a/ajani_nacatl_pariah_ajani_nacatl_avenger.txt
forge-gui/res/cardsfolder/s/spirited_companion.txt
forge-gui/res/cardsfolder/upcoming/felidar_savior.txt
forge-gui/res/cardsfolder/upcoming/helpful_hunter.txt
forge-gui/res/cardsfolder/upcoming/prideful_parent.txt
forge-gui/res/cardsfolder/upcoming/vengeful_bloodwitch.txt

Tested card scripts for the following, [recently revealed](https://articles.starcitygames.com/magic-the-gathering/first-two-foundation-jumpstart-decks-previewed/) cards:
- Felidar Savior
- Helpful Hunter
- Prideful Parent
- Vengeful Bloodwitch

FDN: Felidar Savior, Helpful Hunter, Prideful Parent, Vengeful Bloodwitch

---

forge-game/src/main/java/forge/game/ability/effects/IncubateEffect.java
forge-game/src/main/java/forge/game/ability/effects/SkipPhaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/SkipTurnEffect.java
forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardState.java
forge-game/src/main/java/forge/game/player/PlayerProperty.java
forge-gui/res/cardsfolder/m/mindstorm_crown.txt
forge-gui/res/cardsfolder/u/undercity.txt

This fixes messing with the CardState when it isn't needed.
Toggo Rock continues to work.

Improve resetOriginalHost

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ComputerUtilMana.java
forge-ai/src/main/java/forge/ai/ability/PermanentAi.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardCopyService.java
forge-game/src/main/java/forge/game/card/CardFactory.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
forge-gui/res/cardsfolder/c/comet_storm.txt
forge-gui/res/cardsfolder/s/strength_of_the_tajuru.txt
forge-gui/src/main/java/forge/player/HumanPlay.java
forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

GameActionUtil: use Multikicker as KeywordExtraCost

---

forge-ai/src/main/java/forge/ai/ability/TokenAi.java

Fix AI assuming no token created for non-creature tokens

---

forge-ai/src/main/java/forge/ai/ability/ScryAi.java

Fix Scry AI that requires targeting (Kozilek's Command)

---

forge-gui/res/cardsfolder/upcoming/new_master_of_arms.txt
forge-gui/res/cardsfolder/upcoming/teferi_druid_of_argoth.txt
forge-gui/res/cardsfolder/upcoming/wisedrafters_will.txt

- [New Master of Arms](https://scryfall.com/card/mb2/284/new-master-of-arms)
- [Teferi, Druid of Argoth](https://scryfall.com/card/mb2/348/teferi-druid-of-argoth) (submitted on behalf of **i0brendan0** on Discord)
- [Wisedrafter's Will](https://scryfall.com/card/mb2/303/wisedrafters-will)

MB2: New Master of Arms; Teferi, Druid of Argoth; Wisedrafter's Will

---

forge-ai/src/main/java/forge/ai/ability/DamageDealAi.java

Might need a refinement, since I'm not sure if the other if branches are also broken now and need similar treatment (e.g. the InYourHand if branch), and also I'm not sure if we need to keep the previous checks, which are no longer relevant at least for Fireball and Shatterskull Smashing.
Fixes #5899

Fix AI for Fireball and Shatterskull Smashing

---

forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
forge-gui-mobile/src/forge/adventure/scene/PlayerStatisticScene.java
forge-gui-mobile/src/forge/util/BlurUtils.java
forge-gui/res/adventure/common/ui/statistic.json
forge-gui/res/adventure/common/ui/statistic_portrait.json

update PlayerStatisticScene, BlurUtils

---

forge-ai/src/main/java/forge/ai/AiController.java
forge-ai/src/main/java/forge/ai/ComputerUtilAbility.java
forge-game/src/main/java/forge/game/GameLogFormatter.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardPredicates.java
forge-gui/res/cardsfolder/i/ignite_the_future.txt
forge-gui/res/cardsfolder/n/nahiris_lithoforming.txt
forge-gui/res/cardsfolder/n/nyssa_of_traken.txt
forge-gui/res/cardsfolder/w/wheel_of_potential.txt

Fix Wheel of Potential

---

forge-core/src/main/java/forge/card/CardRarity.java
forge-core/src/main/java/forge/item/PaperToken.java
forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
forge-gui/res/cardsfolder/d/disa_the_restless.txt
forge-gui/res/cardsfolder/p/peacekeeper_avatar.txt
forge-gui/res/cardsfolder/r/ral_and_the_implicit_maze.txt
forge-gui/res/cardsfolder/t/tarmogoyf_nest.txt
forge-gui/res/tokenscripts/spellgorger_weird.txt
forge-gui/res/tokenscripts/tarmogoyf.txt

CopyPermanentEffect: use DefinedName for special copies

---

forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
forge-gui-mobile/src/forge/adventure/stage/MapStage.java
forge-gui/res/adventure/common/ui/hud.json
forge-gui/res/adventure/common/ui/hud_landscape.json
forge-gui/res/adventure/common/ui/hud_portrait.json

- closes #5986 
- utilizes TypingLabel for effects

update GameHUD items

---

forge-gui-mobile/src/forge/adventure/stage/GameHUD.java

Fixed missing elements from HUD when not on world map (now translucent instead of invisible)

Fixed missing elements from HUD in towns/dungeons/etc

---

forge-gui/res/cardsfolder/upcoming/slumbering_waterways.txt
forge-gui/res/cardsfolder/upcoming/temur_elevator.txt
forge-gui/res/cardsfolder/upcoming/under_construction_skyscraper.txt
forge-gui/res/cardsfolder/upcoming/wrenn_and_one.txt

~(To be made ready for review when I've accumulated a reasonable number of scripts in this PR [3 to 5].)~
- [Slumbering Waterways](https://scryfall.com/card/mb2/381/slumbering-waterways)
- [Temur Elevator](https://scryfall.com/card/mb2/382/temur-elevator)
- [Under-Construction Skyscraper](https://scryfall.com/card/mb2/383/under-construction-skyscraper)
- [Wrenn and One](https://scryfall.com/card/mb2/385/wrenn-and-one)

MB2: Slumbering Waterways, Temur Elevator, Under-Construction Skyscraper, Wrenn and One

---

forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
forge-gui-mobile/src/forge/adventure/util/Config.java
forge-gui-mobile/src/forge/adventure/world/WorldSaveHeader.java
forge-gui-mobile/src/forge/util/BlurUtils.java

- add hud transluscency via avatar/gamehud double click/tap

fix actor placement GameHUD -> currentStage

---

forge-gui/res/cardsfolder/c/champions_of_archery_join_the_group.txt

Adding onto and tested to satisfaction within https://github.com/Card-Forge/forge/pull/5933 :
- [Champions of Archery // Join the Group](https://scryfall.com/card/ph19/4/champions-of-archery-join-the-group)

PH19: Champions of Archery

---

forge-ai/src/main/java/forge/ai/ComputerUtilAbility.java
forge-core/src/main/java/forge/card/CardType.java
forge-core/src/main/java/forge/item/IPaperCard.java
forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/ability/effects/HauntEffect.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java

I also changed it so it avoids adding empty traits in this case.
Closes #5420

Fix Conspiracy removing types without choice for new one

---

forge-gui-mobile/src/forge/itemmanager/views/ImageView.java

Disable autosell/nosell labels

---

forge-ai/src/main/java/forge/ai/AiAttackController.java
forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardLists.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/card/CardZoneTable.java
forge-game/src/main/java/forge/game/phase/Untap.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCrewValue.java
forge-gui/res/cardsfolder/d/domesticated_mammoth.txt
forge-gui/res/cardsfolder/e/eomer_marshal_of_rohan.txt
forge-gui/res/cardsfolder/g/garna_bloodfist_of_keld.txt
forge-gui/res/cardsfolder/g/generated_horizons.txt
forge-gui/res/cardsfolder/upcoming/rootcast_apprenticeship.txt
forge-gui/res/cardsfolder/w/waste_land.txt
forge-gui/res/tokenscripts/c_l_forest.txt
forge-gui/res/tokenscripts/c_l_wastes.txt
forge-gui/res/tokenscripts/pacifism.txt
forge-gui/res/tokenscripts/role_cursed.txt

Fixed Phasing triggers to fully wait with their checks until the whole process is done:
> If King of the Oathbreakers phases in at the same time as one or more other Spirits you control, King of the Oathbreakers's last ability will trigger for each of them. 
Closes #6025

Some cleaning brought with smaller fixes

---

forge-gui-mobile/src/forge/adventure/data/ItemData.java
forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
forge-gui-mobile/src/forge/adventure/scene/DuelScene.java
forge-gui-mobile/src/forge/adventure/scene/InventoryScene.java
forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
forge-gui-mobile/src/forge/adventure/stage/GameStage.java
forge-gui-mobile/src/forge/adventure/stage/MapStage.java
forge-gui-mobile/src/forge/adventure/util/Current.java
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties

- random armor crack (unusable)
- add difficulty indicator in load game preview (red - insane, gold - hard, green - normal, cyan - easy)

update adventure defeat penalty

---

forge-game/src/main/java/forge/game/ability/effects/ManifestBaseEffect.java
forge-gui/res/cardsfolder/upcoming/unwanted_remake.txt

Manifest Dread

---

forge-game/src/main/java/forge/game/trigger/TriggerFullyUnlock.java
forge-game/src/main/java/forge/game/trigger/TriggerType.java

Trigger that will be used For Room.
Early commit so Eerie cards can be scripted.

TriggerFullyUnlock: Trigger used for Eerie

---

forge-game/src/main/java/forge/game/card/Card.java

Fix Pawprint in Compleated

---

forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardState.java

I only patched the places that can give extrinsic alternative with defined cost.
Closes #6064

Fix transformed backside cast failing when some AltCost apply

---

forge-gui/res/cardsfolder/upcoming/irreverent_gremlin.txt

Do we really have no better way to implement "Do this only once each turn" than this?

Irreverent Gremlin

---

forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
forge-gui/res/cardsfolder/t/tin_street_gossip.txt

This one should be safe to refactor out.

Support for Overgrown Zealot

---

forge-gui/res/cardsfolder/upcoming/overgrown_zealot.txt

Note that wording is a bit different than on Tin Street Gossip, "permanents" vs. "creatures". This would matter for Yedora, Grave Gardener.

Overgrown Zealot (DSK)

---

forge-gui/src/main/java/forge/gamemodes/match/AbstractGuiGame.java

check awaitNextInputTimer

---

forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-gui/res/lists/TypeLists.txt

added Room type and Helper function for "Unlock Room" check

Add Room Helper functions

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java

Closes #5481 
This makes Impending use Effect for the "last Time counter removed" trigger to work

Impending: use Effect for Last Time counter removed

---

forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-game/src/main/java/forge/game/ability/effects/CloneEffect.java
forge-game/src/main/java/forge/game/ability/effects/ControlGainEffect.java
forge-game/src/main/java/forge/game/ability/effects/DebuffEffect.java
forge-game/src/main/java/forge/game/ability/effects/ProtectAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/ProtectEffect.java
forge-game/src/main/java/forge/game/ability/effects/PumpAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
forge-game/src/main/java/forge/game/keyword/KeywordInterface.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-gui/res/cardsfolder/f/fumiko_the_lowblood.txt

Closes #6075
i couldn't get Soulshift working yet, because that should use LKI

Keyword: link StaticAbility into it

---

forge-gui/res/cardsfolder/upcoming/erratic_apparition.txt

This is causing the deck editor to crash

Fix Erratic Apparition

---

.github/workflows/test-build.yaml

@kevlahnota extra MR for #6103
Mh it isn't much better for the Test builds

Drop Java 8 Test

---

forge-ai/src/main/java/forge/ai/ComputerUtilCard.java

Fix MDFC NPE

---

forge-gui/res/cardsfolder/upcoming/seized_from_slumber.txt

This should be the last new card, all unimplemented cards are now in the project.

Seized from Slumber (DSK)

---

forge-gui/res/cardsfolder/upcoming/a_premonition_of_your_demise.txt
forge-gui/res/cardsfolder/upcoming/cathartic_parting.txt
forge-gui/res/cardsfolder/upcoming/duskmourns_domination.txt
forge-gui/res/cardsfolder/upcoming/enduring_vitality.txt
forge-gui/res/cardsfolder/upcoming/lets_play_a_game.txt
forge-gui/res/cardsfolder/upcoming/metamorphosis_fanatic.txt
forge-gui/res/cardsfolder/upcoming/my_followers_ascend.txt
forge-gui/res/cardsfolder/upcoming/my_wealth_will_bury_you.txt
forge-gui/res/cardsfolder/upcoming/only_i_know_what_awaits.txt
forge-gui/res/cardsfolder/upcoming/osseous_sticktwister.txt
forge-gui/res/cardsfolder/upcoming/phenomenon_investigators.txt
forge-gui/res/cardsfolder/upcoming/redress_fate.txt
forge-gui/res/cardsfolder/upcoming/soaring_lightbringer.txt
forge-gui/res/cardsfolder/upcoming/the_master_of_keys.txt
forge-gui/res/cardsfolder/upcoming/you_cannot_hide_from_me.txt
forge-gui/res/cardsfolder/z/zoyowa_lava_tongue.txt
forge-gui/res/tokenscripts/b_2_2_e_horror.txt

I noticed an issue with Because I Have Willed It, but not sure how to correct: it should only count spells cast by the triggered player, not all spells you don't control.

2 DSK cards, some DSC cards, 5 Schemes

---

forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

https://sentry.cardforge.org/organizations/forge/issues/37832

Fix Mutate + Unexpectedly Absent

---

forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

fix netplay crash

---

forge-game/src/main/java/forge/game/card/CardFactoryUtil.java

Impending NonCreature as StaticAbility

---

forge-game/src/main/java/forge/game/ability/effects/CopyPermanentEffect.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/mana/ManaCostBeingPaid.java
forge-gui/res/cardsfolder/d/doomsday.txt
forge-gui/res/cardsfolder/s/saw_in_half.txt
forge-gui/res/cardsfolder/upcoming/valgavoth_terror_eater.txt

Make Myriad optional for each player again

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-game/src/main/java/forge/game/card/Card.java

Fix GameStates starting with frozen stack if RE executes

---

forge-gui/res/editions/Anthologies.txt

Collectors number were not the good ones. 
Pictures are still displaying correctly.

Re-arange Anthologies edition txt file according to Scryfall

---

forge-gui/res/cardsfolder/upcoming/star_athlete.txt

[Star Athlete](https://scryfall.com/card/dsc/29/star-athlete)

Add Star Athelete (DSC) card script

---

forge-gui/res/editions/Anthologies.txt

Just realize I had remove the L rarity for lands. Here is the fix

Restore Anthologies.txt L rarity for lands

---

forge-gui/res/adventure/common/maps/map/aerie/aerie_0.tmx

Aerie Typo Fix

---

forge-gui/res/cardsfolder/s/snakeskin_veil.txt

Added missing text "It gains hexproof until end of turn." to the spell description.

Fixed spell description of snakeskin_veil

---

forge-gui/res/cardsfolder/upcoming/disorienting_choice.txt

A lot of revisions to get here but would take any and all suggestions for changes.

Added Disorienting Choice

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/player/Player.java
forge-gui/res/cardsfolder/upcoming/mine_is_the_only_truth.txt

Added supporting member variables and accessors To Player.java
Added supporting check to AbilityUtils.xCount()

Add Mine Is the Only Truth

---

forge-gui/res/cardsfolder/upcoming/your_plans_mean_nothing.txt

Tested with teammates to ensure that if a teammate is targeted they do not get to draw cards but they do discard their hand.

Added Your Plans Mean Nothing

---

forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/upcoming/rendmaw_creaking_nest.txt
forge-gui/res/tokenscripts/b_2_2_bird_flying.txt

Added a Black 2/2 Bird Creature with Flying token
Added a property to check for number of types a card has

Add Rendmaw Creaking Nest and supporting changes

---

forge-gui/res/cardsfolder/upcoming/enter_the_enigma.txt

Updated Enter The Enigma DSK

---

forge-gui/res/cardsfolder/upcoming/smoky_lounge_misty_salon.txt

Sorry I thought I updated my other commit you commented on but I guess not. Still learning how github works. This one is fixed with updated triggerdescription and restrictvalid.

Added Smoky Lounge//Misty Salon DSK

---

forge-ai/src/main/java/forge/ai/ability/SetStateAi.java
forge-game/src/main/java/forge/game/ability/AbilityFactory.java
forge-game/src/main/java/forge/game/ability/effects/VillainousChoiceEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/spellability/AbilityStatic.java
forge-gui/res/cardsfolder/upcoming/ghostly_dancers.txt
forge-gui/res/tokenscripts/w_3_1_spirit_flying.txt

@TwentyToedToad
your Room should be scriptable with this now

Ghostly Dancers and support

---

forge-game/src/main/java/forge/game/phase/PhaseHandler.java

Fix CardZoneTable not using the LastStates before moving

---

forge-ai/src/main/java/forge/ai/AiController.java

AI aura targeting fix

---

forge-gui/res/cardsfolder/upcoming/experimental_lab_staff_room.txt
forge-gui/res/cardsfolder/upcoming/solitary_study_endless_corridor.txt

Creating this PR at the request of @tool4ever <3

Add Experimental Lab // Staff Room

---

forge-gui/res/editions/Commander 2021.txt

g_4_4_phyrexian_beast -> g_4_4_fungus_beast_trample

Fix token name in C21

---

forge-gui/res/adventure/common/maps/map/vampirecastle/vampirecastle_4C.tmx
forge-gui/res/adventure/common/world/enemies.json

I'll do a more detailed rework of the boss effect on my main WIP Adventure branch

Sorin tweaks

---

forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java

Aligns the default menu options with the default new player experience.
Players will expect that constructed is the default/normal mode for first time play.

Adventure: Constructed as default mode

---

forge-gui/res/editions/Modern Horizons 2.txt
forge-gui/res/editions/Wilds of Eldraine Commander.txt
forge-gui/res/editions/Zendikar Rising Commander.txt

w_1_1_pegasus_flying -> w_2_2_pegasus_flying

WOC : Fix token name

---

forge-gui-desktop/src/main/java/forge/control/KeyboardShortcuts.java
forge-gui-desktop/src/main/java/forge/gui/ListChooser.java
forge-gui-desktop/src/main/java/forge/toolbox/FOptionPane.java
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/localinstance/properties/ForgePreferences.java

Revert "gui-desktop : add keyboard shortcut to press OK/Yes button"

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-gui/res/puzzle/PS_DSK3.pzl

Also implements code support for unlocked rooms in GameState.

Add puzzle PS_DSK3 - Possibility Storm - Duskmourn: House of Horrors 03

---

forge-gui-android/pom.xml
forge-gui-mobile/src/forge/assets/AssetsDownloader.java

- copy build.txt to assets (gdx.files.internal looks only inside assets folder)

fix android updater, add fallback to android check

---

forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-game/src/main/java/forge/game/ability/effects/ManifestBaseEffect.java
forge-game/src/main/java/forge/game/card/CardDamageMap.java
forge-gui/res/cardsfolder/a/anurid_barkripper.txt
forge-gui/res/cardsfolder/c/centaur_chieftain.txt
forge-gui/res/cardsfolder/c/cephalid_sage.txt
forge-gui/res/cardsfolder/c/chlorophant.txt
forge-gui/res/cardsfolder/g/gloomdrifter.txt
forge-gui/res/cardsfolder/h/hunting_grounds.txt
forge-gui/res/cardsfolder/m/mind_drill_assailant.txt
forge-gui/res/cardsfolder/n/nomad_decoy.txt
forge-gui/res/cardsfolder/p/pardic_arsonist.txt
forge-gui/res/cardsfolder/p/persistent_marshstalker.txt
forge-gui/res/cardsfolder/t/terohs_vanguard.txt
forge-gui/res/cardsfolder/t/thought_shucker.txt
forge-gui/res/cardsfolder/t/tidecaller_mentor.txt

I think this matters since _Idris, Soul of the TARDIS_ exiling _Chlorophant_ should only provide its first trigger to her :p

Fix some scripts

---

forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/GameSnapshot.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/PlayEffect.java
forge-game/src/main/java/forge/game/card/CardDamageMap.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityCondition.java
forge-game/src/main/java/forge/game/zone/MagicStack.java
forge-gui/res/cardsfolder/c/copycrook.txt
forge-gui/res/cardsfolder/h/hell_to_pay.txt
forge-gui/res/cardsfolder/l/lacerate_flesh.txt
forge-gui/res/cardsfolder/s/shakedown_heavy.txt
forge-gui/res/cardsfolder/s/sword_of_hours.txt
forge-gui/res/cardsfolder/t/torch_the_witness.txt

Goodbye mandatory suspend casting

---

forge-gui/res/cardsfolder/upcoming/squad_rallier.txt
forge-gui/res/cardsfolder/upcoming/stab.txt

These belong to set Foundations (FDN).

Added script text for Squad Rallier and Stab cards.

---

forge-gui-mobile/src/forge/adventure/scene/GameScene.java
forge-gui-mobile/src/forge/adventure/scene/TileMapScene.java

fix infinite collision on Worldstage

---

forge-ai/src/main/java/forge/ai/ability/ScryAi.java

Improve AI for Scry when X payment is necessary (avoid X=0)

---

forge-gui-mobile/src/forge/adventure/data/HeroListData.java
forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
forge-gui-mobile/src/forge/adventure/scene/NewGameScene.java
forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
forge-gui-mobile/src/forge/screens/CoverScreen.java

refactor HeroListData, update CoverScreen

---

forge-game/src/main/java/forge/game/ability/effects/DrawEffect.java
forge-game/src/main/java/forge/game/ability/effects/LifeGainEffect.java
forge-gui/res/cardsfolder/c/cut_a_deal.txt
forge-gui/res/cardsfolder/m/malignant_growth.txt
forge-gui/res/cardsfolder/t/temporary_truce.txt
forge-gui/res/cardsfolder/t/truce.txt
forge-gui/res/cardsfolder/w/whispering_madness.txt

Fix Windfall

---

forge-gui/res/editions/Foundations.txt

We now know FDN #319
J25 #350 doesn't exist

Edition updates: FDN

---

forge-gui-mobile/src/forge/deck/FDeckEditor.java
forge-gui-mobile/src/forge/screens/limited/NewSealedScreen.java

bind directly the back button to open the LoadSealedScreen on Sealed Editor

fix SealedScreen

---

forge-core/src/main/java/forge/StaticData.java
forge-core/src/main/java/forge/util/RSSReader.java

Support older Android

---

forge-gui-mobile/src/forge/itemmanager/views/ImageView.java
forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java

use `MagicColor::toSymbol` to turn `white` into `{W}` and then join the Stream

ColorSet: use Stream to map ManaSymbol

---

forge-gui-android/res/values-v35/styles.xml
forge-gui-android/res/values/styles.xml

add note to edge-to-edge enforcement on android 15

set navigation bar color

---

forge-game/src/main/java/forge/game/ability/effects/SeekEffect.java
forge-game/src/main/java/forge/game/trigger/TriggerSeekAll.java
forge-gui/res/cardsfolder/l/lurker_in_the_deep.txt

YDSK: lurker_in_the_deep.txt + support

---

forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-gui/res/cardsfolder/h/harrowing_swarm.txt

YDSK: harrowing_swarm.txt + support

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java

magar_of_the_magic_strings.txt bug fix

---

forge-gui/res/cardsfolder/a/anax_and_cymede_and_kynaios_and_tiro.txt
forge-gui/res/cardsfolder/m/myojin_of_nights_reach_and_grim_betrayal.txt
forge-gui/res/editions/Unknown Event.txt

Some cards in DA1 edition were duplicated due to incorrect names, I have removed them and corrected relevant scripts.

Fix DA1 edition and related cards

---

forge-ai/src/main/java/forge/ai/SpellApiToAi.java
forge-ai/src/main/java/forge/ai/ability/ClassLevelUpAi.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java

Closes #6531 
@Agetian @tool4ever first try for basic ClassLevelUp Ai?
It is mostly for catching stuff like `When this Class becomes level X` for now

Class level ai

---

forge-ai/src/main/java/forge/ai/AiAttackController.java
forge-ai/src/main/java/forge/ai/AiController.java
forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/Game.java
forge-gui-desktop/src/test/java/forge/ai/simulation/SimulationTest.java
forge-gui-mobile/src/forge/screens/settings/SettingsPage.java
forge-gui/src/main/java/forge/gamemodes/match/HostedMatch.java

Completablefuture -> completeOnTimeout

prevent crash on Android 11 and below

---

forge-game/src/main/java/forge/game/ability/effects/ClassLevelUpEffect.java
forge-game/src/main/java/forge/game/card/CardFactory.java

Fully unlocked room traits should still be the same (for once per turn)

---

forge-gui/res/editions/MagicFest 2025.txt
forge-gui/res/editions/Media Inserts.txt
forge-gui/res/editions/Pioneer Masters.txt

Will correct numbers and add artists to PIO once Scryfall has updated

Edition updates: PF25, PIO, PMEI

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-game/src/main/java/forge/game/player/Player.java

Imo this method is so rarely called that removing via Iterator seems pointless (vs. readability).

Fix ConcurrentModificationException

---

forge-ai/src/main/java/forge/ai/CreatureEvaluator.java
forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
forge-gui/res/cardsfolder/f/first_responder.txt
forge-gui/res/cardsfolder/s/sakura_tribe_elder.txt

Slightly better decision making for First Responder. Fixes #6667.
Fixes #4025 .

Improve AI for First Responder, improve evaluation for self-sac abilities e.g. Sakura-Tribe Elder.

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ComputerUtilCard.java
forge-game/src/main/java/forge/game/ability/effects/ChooseTypeEffect.java
forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java

Aims to stop "Sliver" being the default option.
Closes #4693

Fix for noted types for Volo's journal

---

forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java

Fix draft rankings not showing in Adventure Mode on the first pick of a draft

---

forge-gui-mobile/src/forge/adventure/scene/MapViewScene.java
forge-gui-mobile/src/forge/adventure/scene/SaveLoadScene.java
forge-gui-mobile/src/forge/adventure/world/BiomeStructure.java
forge-gui-mobile/src/forge/adventure/world/ColorMap.java
forge-gui-mobile/src/forge/adventure/world/WorldSave.java

clear bookmarks

---

forge-game/src/main/java/forge/game/ability/effects/TokenEffect.java
forge-game/src/main/java/forge/game/ability/effects/TokenEffectBase.java
forge-gui/res/cardsfolder/g/giant_inheritance.txt
forge-gui/res/cardsfolder/l/liege_of_the_hollows.txt
forge-gui/res/cardsfolder/q/questing_cosplayer.txt
forge-gui/res/cardsfolder/t/the_rani.txt

Cherry pick full control fix

---

forge-gui/res/cardsfolder/t/the_roaring_toeclaws.txt

Fix to check Mana Value rather than power

The Roaring Toeclaws fix

---

forge-gui/res/cardsfolder/h/harold_and_bob_first_numens.txt

Adds missing keywords to Harold and Bob, First Numen's oracle text.

Harold and Bob: Oracle fix

---

forge-gui-mobile/src/forge/screens/match/views/VManaPool.java

Addresses #6672
Not too familiar with this system, but I replicated the logic from the desktop UI (`CField.java`). Seems to fix the problem and I haven't encountered any side effects.

Fix Hotseat Mana Selection

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
forge-ai/src/main/java/forge/ai/GameState.java
forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
forge-ai/src/main/java/forge/ai/SpellAbilityAi.java
forge-ai/src/main/java/forge/ai/ability/CharmAi.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/player/PlayerController.java
forge-game/src/main/java/forge/game/spellability/LandAbility.java
forge-game/src/main/java/forge/game/spellability/Spell.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java

Cleanup run

---

forge-gui-desktop/pom.xml

Fix AddOpen for launch4j Exe until https://github.com/orphan-oss/launch4j-maven-plugin/issues/423 finds something better

Fix addOpen for Exe

---

forge-game/src/main/java/forge/game/card/CardView.java

CardView: added extra check for Ward and Annihilator icons

---

forge-gui/src/main/java/forge/player/HumanPlaySpellAbility.java

Don't update reveal from library when paying with mana ability

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java

Reconfigure: use StaticLayer

---

forge-gui-android/pom.xml

Straightforward, add ${androidBuildTools} so the Android Build Tools version can updated via the variable

Add ${androidBuildTools} to pom.xml

---

forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/player/Player.java
forge-gui/res/cardsfolder/r/rose_cutthroat_raider.txt
forge-gui/res/cardsfolder/t/the_chain_veil.txt

Clean + fix combo

---

forge-game/src/main/java/forge/game/ability/effects/ReplaceTokenEffect.java
forge-gui/res/cardsfolder/a/academy_manufactor.txt
forge-gui/res/cardsfolder/a/adrix_and_nev_twincasters.txt
forge-gui/res/cardsfolder/a/anointed_procession.txt
forge-gui/res/cardsfolder/b/bloodsplatter_vampire.txt
forge-gui/res/cardsfolder/c/case_of_the_pilfered_proof.txt
forge-gui/res/cardsfolder/c/chatterfang_squirrel_general.txt
forge-gui/res/cardsfolder/c/crafty_cutpurse.txt
forge-gui/res/cardsfolder/d/divine_visitation.txt
forge-gui/res/cardsfolder/d/doubling_season.txt
forge-gui/res/cardsfolder/f/fishers_talent.txt
forge-gui/res/cardsfolder/h/halving_season.txt
forge-gui/res/cardsfolder/j/jolene_the_plunder_queen.txt
forge-gui/res/cardsfolder/k/kaya_geist_hunter.txt
forge-gui/res/cardsfolder/m/mondrak_glory_dominus.txt
forge-gui/res/cardsfolder/o/ojer_taq_deepest_foundation_temple_of_civilization.txt
forge-gui/res/cardsfolder/p/parallel_lives.txt
forge-gui/res/cardsfolder/p/peregrin_took.txt
forge-gui/res/cardsfolder/q/queen_allenal_of_ruadach.txt
forge-gui/res/cardsfolder/w/worldwalker_helm.txt
forge-gui/res/cardsfolder/x/xorn.txt

ReplaceToken: use Param from ReplacementEffect

---

forge-ai/src/main/java/forge/ai/AiAttackController.java
forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/card/CardLists.java
forge-game/src/main/java/forge/game/cost/CostTapType.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityTapPowerValue.java
forge-gui/res/cardsfolder/d/dragonfly_pilot.txt
forge-gui/res/cardsfolder/e/experimental_pilot.txt
forge-gui/res/cardsfolder/g/giant_ox.txt
forge-gui/res/cardsfolder/h/heart_of_kiran.txt
forge-gui/res/cardsfolder/h/hotshot_mechanic.txt
forge-gui/res/cardsfolder/upcoming/cloudspire_captain.txt
forge-gui/res/tokenscripts/c_1_1_pilot_crewbuff.txt
forge-gui/res/tokenscripts/c_1_1_pilot_crewsaddlebuff.txt
forge-gui/src/main/java/forge/gamemodes/match/input/InputSelectEntitiesFromList.java
forge-gui/src/main/java/forge/player/HumanCostDecision.java

StaticAbilityTapPowerValue: saddles Mounts and crews Vehicles

---

forge-gui/res/cardsfolder/s/shorikai_genesis_engine.txt
forge-gui/res/cardsfolder/upcoming/back_on_track.txt
forge-gui/res/cardsfolder/upcoming/cloudspire_captain.txt
forge-gui/res/cardsfolder/upcoming/cloudspire_coordinator.txt
forge-gui/res/cardsfolder/upcoming/country_roads.txt
forge-gui/res/cardsfolder/upcoming/defend_the_rider.txt
forge-gui/res/cardsfolder/upcoming/foul_roads.txt
forge-gui/res/cardsfolder/upcoming/interface_ace.txt
forge-gui/res/cardsfolder/upcoming/reef_roads.txt
forge-gui/res/cardsfolder/upcoming/rocky_roads.txt
forge-gui/res/cardsfolder/upcoming/valors_flagship.txt
forge-gui/res/cardsfolder/upcoming/wild_roads.txt

cards that need the new TapPower stuff

---

forge-gui/res/cardsfolder/upcoming/outpace_oblivion.txt

outpace_oblivion.txt

---

forge-gui/res/cardsfolder/upcoming/risen_necroregent.txt
forge-gui/res/cardsfolder/upcoming/sundial_dawn_tyrant.txt

Changed mana cost for Sundial, trigger for Necroregent

DFT Card Cleanup

---

adventure-editor/src/main/java/forge/adventure/editor/BiomeStructureDataMappingEditor.java
adventure-editor/src/main/java/forge/adventure/editor/DialogOptionEditor.java
adventure-editor/src/main/java/forge/adventure/editor/ItemsEditor.java
adventure-editor/src/main/java/forge/adventure/editor/QuestEditor.java
adventure-editor/src/main/java/forge/adventure/editor/QuestStageEditor.java
adventure-editor/src/main/java/forge/adventure/editor/WorldEditor.java
forge-ai/src/main/java/forge/ai/AiAttackController.java
forge-ai/src/main/java/forge/ai/AiBlockController.java
forge-ai/src/main/java/forge/ai/ComputerUtilCombat.java
forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
forge-ai/src/main/java/forge/ai/SpellAbilityAi.java
forge-core/src/main/java/forge/deck/Deck.java
forge-core/src/main/java/forge/item/generation/BoosterGenerator.java
forge-core/src/main/java/forge/util/ItemPool.java
forge-gui-mobile/src/forge/assets/TextRenderer.java
forge-gui-mobile/src/forge/screens/FScreen.java

Changes to files to use `instanceof` pattern variable. Since it was used in one place already, it sounds like it should work everywhere.
After testing the Android build and running it, I found that it works as intended on my device. I suggest that further tests be conducted by others to confirm its reliability.

`instanceof` Pattern variable changes

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-gui/res/cardsfolder/t/tezzeret_betrayer_of_flesh.txt

Fix Elvish Refueler

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java

closes #6931 
Defined List should be faster than using a Valid over all cards

StaticAbilityContinous now have AffectedDefined for card list

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/EffectEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardCopyService.java

suspected as Static Effect

---

forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java

@tool4ever small fix extracted

Update CounterEffect, remove extra Aftermath check

---

forge-game/src/main/java/forge/game/GameLogFormatter.java
forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/event/GameEventCardForetold.java
forge-game/src/main/java/forge/game/event/GameEventDoorChanged.java
forge-game/src/main/java/forge/game/event/IGameEventVisitor.java

Adds Event for Logging Door Changes

Add GameEventDoorChanged for log

---

forge-ai/src/main/java/forge/ai/ComputerUtil.java

This should make AI play their "Start your Engine" Cards in Main1, so when the AI attacks, it can get up to Speed 2

Make AI start their engine in Main1

---

forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
forge-game/src/main/java/forge/game/card/Card.java

fix issue #7007 (Double Team)

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameView.java
forge-game/src/main/java/forge/game/ability/effects/CounterEffect.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityLayer.java
forge-game/src/main/java/forge/trackable/TrackableProperty.java
forge-gui-desktop/src/main/java/forge/gui/framework/EDocID.java
forge-gui-desktop/src/main/java/forge/screens/match/CMatchUI.java
forge-gui-desktop/src/main/java/forge/screens/match/controllers/CDependencies.java
forge-gui-desktop/src/main/java/forge/screens/match/views/VDependencies.java
forge-gui/res/defaults/match.xml
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties
forge-gui/src/main/java/forge/gamemodes/match/AbstractGuiGame.java
forge-gui/src/main/java/forge/gui/control/FControlGameEventHandler.java
forge-gui/src/main/java/forge/gui/interfaces/IGuiGame.java

I also evaluated graph drawing options but it seemed pretty complex to obtain nice looking results so copyable text felt like the better approach in the end.

Dependency tab

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/GameEndReason.java
forge-game/src/main/java/forge/game/ability/effects/AlterAttributeEffect.java
forge-game/src/main/java/forge/game/ability/effects/AttachEffect.java
forge-game/src/main/java/forge/game/ability/effects/GameWinEffect.java
forge-game/src/main/java/forge/game/player/Player.java

Fix corner case with Jace, Wielder of Mysteries

---

forge-gui/res/cardsfolder/upcoming/mox_jasper.txt
forge-gui/res/cardsfolder/upcoming/shiko_paragon_of_the_way.txt
forge-gui/res/cardsfolder/upcoming/skirmish_rhino.txt
forge-gui/res/cardsfolder/upcoming/smile_at_death.txt
forge-gui/res/cardsfolder/upcoming/stormscale_scion.txt

TDM: 5 cards

---

forge-gui/res/cardsfolder/upcoming/betor_ancestors_voice.txt

[As revealed officially.](https://www.reddit.com/r/magicTCG/comments/1ivyq3j/tdc_betor_ancestors_voice_brian_kiblercommander/)

TDC:  Betor, Ancestor's Voice

---

forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java

Don't update view of LKI instead of real Card

---

forge-ai/src/main/java/forge/ai/AiCostDecision.java
forge-game/src/main/java/forge/game/cost/Cost.java
forge-game/src/main/java/forge/game/cost/CostBehold.java
forge-game/src/main/java/forge/game/cost/CostReveal.java
forge-game/src/main/java/forge/game/cost/ICostVisitor.java
forge-gui/res/cardsfolder/upcoming/sarkhan_dragon_ascendant.txt
forge-gui/src/main/java/forge/player/HumanCostDecision.java

Currently done as specialized CostReveal
needed extra Cost Decision because this line was messing with me:
https://github.com/Card-Forge/forge/blob/608d4c5bdaff9c7bd02dbb3bbd8f15128833bacd/forge-gui/src/main/java/forge/player/HumanCostDecision.java#L919-L921

CostBehold: add Special Reveal Cost

---

forge-gui-desktop/src/main/java/forge/util/SwingImageFetcher.java
forge-gui-mobile/src/forge/util/LibGDXImageFetcher.java
forge-gui/src/main/java/forge/localinstance/properties/ForgeConstants.java
forge-gui/src/main/java/forge/util/ImageFetcher.java

Don't try to redownload if it fails during a session

Reroute card images to scryfall.

---

forge-gui/res/cardsfolder/b/begin_anew.txt
forge-gui/res/cardsfolder/upcoming/arius_flyby_trawler.txt
forge-gui/res/cardsfolder/upcoming/mitotic_ultimus.txt
forge-gui/res/cardsfolder/upcoming/naktamun_shines_again.txt

As revealed recently;
- [**Naktamun Shines Again**](https://www.reddit.com/r/MagicAlchemy/comments/1ix9j3k/adft_naktamun_shines_again/): Tested to satisfaction.
- [**Arius, Flyby Trawler**](https://www.reddit.com/r/MagicAlchemy/comments/1ix9k6w/adft_arius_flyby_trawler/): Tested to satisfaction.
- [**Mitotic Ultimus**](https://www.reddit.com/r/MagicArena/comments/1iy8yrk/adft_mitotic_ultimus/): Tested to satisfaction.
Incidental fixes
- **Begin Anew**: It was affecting opponent's cards.

YDFT: 3 cards

---

forge-gui/res/cardsfolder/upcoming/doc_ock_evil_inventor.txt
forge-gui/res/cardsfolder/upcoming/grasping_tentacles.txt
forge-gui/res/cardsfolder/upcoming/green_goblin_nemesis.txt
forge-gui/res/cardsfolder/upcoming/pumpkin_bombs.txt
forge-gui/res/cardsfolder/upcoming/venom_deadly_devourer.txt
forge-gui/res/lists/TypeLists.txt

[As teased recently.](https://www.reddit.com/r/MagicArena/comments/1j12bx2/spe_spiderman_panorama/)

SPE: 5 cards

---

forge-gui/res/cardsfolder/upcoming/sensational_spider_man.txt

With support provided by https://github.com/Card-Forge/forge/pull/7110 .

SPE: Sensational Spider-Man

---

forge-gui/res/cardsfolder/upcoming/highway_reaver.txt

As requested [here](https://github.com/Card-Forge/forge/pull/7090#discussion_r1979239154), replacing `Animate` with `Pump`,

Highway Reaver fix

---

forge-gui/res/cardsfolder/upcoming/celes_rune_knight.txt

[As recently revealed](https://x.com/FinalFantasy/status/1899007572218380468). Tested to satisfaction: in working order.

FIC: Celes, Rune Knight

---

forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/ability/effects/AddPhaseEffect.java
forge-game/src/main/java/forge/game/ability/effects/FlipCoinEffect.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityTurnPhaseReversed.java
forge-gui-desktop/src/test/java/forge/ai/simulation/GameSimulationTest.java
forge-gui/res/cardsfolder/t/topsy_turvy.txt

part of #4760 
also reduce the amount of `getAmountOfKeyword(string)`

Use StaticAbility for Topsy Turvy

---

forge-game/src/main/java/forge/game/combat/CombatUtil.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityBlockTapped.java
forge-gui/res/cardsfolder/m/masako_the_humorless.txt

part of #3307 
uses Static instead of hidden keyword

Masako the humorless as Static

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/card/CounterEnumType.java
forge-gui/res/cardsfolder/upcoming/bail_out.txt
forge-gui/res/cardsfolder/upcoming/chomping_mastasaur.txt
forge-gui/res/cardsfolder/upcoming/deviant_skytech.txt
forge-gui/res/cardsfolder/upcoming/goblin_crash_pilot.txt
forge-gui/res/cardsfolder/upcoming/hangarback_assembler.txt
forge-gui/res/cardsfolder/upcoming/motivated_muralist.txt
forge-gui/res/cardsfolder/upcoming/smog_smasher.txt
forge-gui/res/cardsfolder/upcoming/spectacle_of_destruction.txt
forge-gui/res/cardsfolder/upcoming/speedbrood_stalker.txt
forge-gui/res/cardsfolder/upcoming/surge_of_acclaim.txt
forge-gui/res/cardsfolder/upcoming/trackhand_trainer.txt
forge-gui/res/cardsfolder/upcoming/tsagan_raider_warlord.txt
forge-gui/res/cardsfolder/upcoming/turbocharged_escape.txt
forge-gui/res/cardsfolder/upcoming/unforgiving_overtake.txt

As revealed recently:
- [**Chomping Mastasaur**](https://www.reddit.com/r/MagicArena/comments/1j0cs4e/ydft_chomping_mastasaur/): tested to satisfaction
- [**Goblin Crash Pilot**](https://www.reddit.com/r/MagicArena/comments/1j0cspr/ydft_goblin_crash_pilot/): tested to satisfaction
- [**Motivated Muralist**](https://www.reddit.com/r/MagicArena/comments/1j0ct46/ydft_motivated_muralist/): tested to satisfaction
- [**Smog Smasher**](https://www.reddit.com/r/MagicArena/comments/1j0ctoh/ydft_smog_smasher/): tested to satisfaction
- [**Unforgiving Overtake**](https://www.reddit.com/r/MagicArena/comments/1j0crmp/ydft_unforgiving_overtake/): tested to satisfaction
- [**Speedbrood Stalker**](https://www.reddit.com/r/MagicArena/comments/1j0cr4n/ydft_speedbrood_stalker/): tested to satisfaction
- …

YDFT: 14 cards

---

forge-gui/res/cardsfolder/upcoming/zell_dincht.txt

[As revealed recently](https://x.com/FinalFantasy/status/1901529189901307962). Tested to satisfaction.

FIN: Zell Dincht

---

forge-gui/res/cardsfolder/a/aluren.txt
forge-gui/res/cardsfolder/upcoming/dracogenesis.txt
forge-gui/res/cardsfolder/upcoming/eshki_dragonclaw.txt
forge-gui/res/cardsfolder/upcoming/felothar_dawn_of_the_abzan.txt

As revealed recently ( [Magic's Official Youtube Channel](https://www.youtube.com/watch?v=je60wRpgRUk), [LRRMTG](https://www.youtube.com/watch?v=EUU0fmqIviQ) ):
- Dracogenesis
- Eshki Dragonclaw
- Felothar, Dawn of the Abzan

TDM: 3 cards

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-gui/res/cardsfolder/t/tune_up.txt
forge-gui/res/cardsfolder/upcoming/zurgo_thunders_decree.txt

[As recently revealed](https://www.youtube.com/watch?v=je60wRpgRUk). Tested to satisfaction. 
I'll note the second ability was a bit difficult to get a fix on: I opted for the terseness allowed by a static animating trigger even if I'm not sure it's strictly accurate to the rules text. Works as expected, at least.
Incidental fixes
- Tune Up: whitespace

TDM: Zurgo, Thunder's Decree and mobilize support

---

forge-gui/res/cardsfolder/upcoming/betor_kin_to_all.txt
forge-gui/res/cardsfolder/upcoming/boulderborn_dragon.txt
forge-gui/res/cardsfolder/upcoming/elspeth_storm_slayer.txt
forge-gui/res/cardsfolder/upcoming/kotis_the_fangkeeper.txt
forge-gui/res/cardsfolder/upcoming/neriv_heart_of_the_storm.txt
forge-gui/res/cardsfolder/upcoming/teval_arbiter_of_virtue.txt
forge-gui/res/cardsfolder/upcoming/ugin_eye_of_the_storms.txt
forge-gui/res/cardsfolder/upcoming/ureni_the_song_unending.txt

- Betor, Kin to All
- Boulderborn Dragon
- Elspeth, Storm Slayer
- Kotis, the Fangkeeper
- Neriv, Heart of the Storm
- Teval, Arbiter of Virtue
- Ugin, Eye of the Storms
- Ureni, the Song Unending

TDM: 8 cards

---

forge-gui/res/cardsfolder/upcoming/awaken_the_honored_dead.txt
forge-gui/res/cardsfolder/upcoming/magmatic_hellkite.txt

- Awaken the Honored Dead
- Magmatic Hellkite

TDM: 2 cards

---

forge-gui/res/cardsfolder/upcoming/ureni_of_the_unwritten.txt
forge-gui/res/cardsfolder/upcoming/zurgo_stormrender.txt

- Ureni of the Unwritten
- Zurgo Stormrender

TDC: 2 cards

---

forge-ai/src/main/java/forge/ai/AiController.java

This was painful to debug, but it turns out `CompletableFuture` has an important implementation detail that leads to its task continuing to run even when the result gets obtained before (in our case via timeout) as e.g. discussed here:
https://stackoverflow.com/questions/79192493/interrupting-a-thread-thats-running-a-completablefuture
Hopefully Closes #7212

Fix AI running into timeout keeping thread running

---

forge-gui/res/cardsfolder/upcoming/attuned_hunter.txt
forge-gui/res/cardsfolder/upcoming/embermouth_sentinel.txt
forge-gui/res/cardsfolder/upcoming/lie_in_wait.txt
forge-gui/res/cardsfolder/upcoming/shock_brigade.txt
forge-gui/res/cardsfolder/upcoming/underfoot_underdogs.txt
forge-gui/res/cardsfolder/upcoming/unrooted_ancestor.txt

- Attuned Hunter
- Embermouth Sentinel
- Lie in Wait
- Shock Brigade
- Underfoot Underdogs
- Unrooted Ancestor

TDM: 6 cards

---

forge-gui/res/cardsfolder/upcoming/ainok_strike_leader.txt
forge-gui/res/cardsfolder/upcoming/goldlust_triad.txt
forge-gui/res/cardsfolder/upcoming/ironwill_forger.txt
forge-gui/res/cardsfolder/upcoming/redoubled_stormsinger.txt

- Ainok Strike Leader
- Goldlust Triad
- Ironwill Forger
- Redoubled Stormsinger

TDC: 4 cards

---

forge-gui/res/cardsfolder/upcoming/afterlife_from_the_loam.txt
forge-gui/res/cardsfolder/upcoming/bone_cairn_butcher.txt
forge-gui/res/cardsfolder/upcoming/colossal_grave_reaver.txt
forge-gui/res/cardsfolder/upcoming/dragonologist.txt
forge-gui/res/cardsfolder/upcoming/effortless_master.txt
forge-gui/res/cardsfolder/upcoming/essence_anchor.txt
forge-gui/res/cardsfolder/upcoming/tevals_judgment.txt
forge-gui/res/cardsfolder/upcoming/will_of_the_sultai.txt

- Afterlife from the Loam
- Bone-Cairn Butcher
- Colossal Grave-Reaver
- Dragonologist
- Effortless Master
- Essence Anchor
- Teval's Judgment
- Will of the Sultai
~~(More to come)~~

TDM/TDC: 8 cards

---

forge-game/src/main/java/forge/game/card/CounterEnumType.java
forge-game/src/main/java/forge/game/card/CounterType.java
forge-gui/res/cardsfolder/upcoming/rot_curse_rakshasa.txt

Tested to satisfaction, including the keyword counter support in Java.

TDM: Rot-Curse Rakshasa

---

forge-gui/res/cardsfolder/upcoming/dragons_prey.txt
forge-gui/res/cardsfolder/upcoming/lightfoot_technique.txt
forge-gui/res/cardsfolder/upcoming/revival_of_the_ancestors.txt
forge-gui/res/cardsfolder/upcoming/temur_tawnyback.txt

- Dragon's Prey
- Lightfoot Technique
- Revival of the Ancestors
- Temur Tawnyback

TDM: 4 cards

---

forge-gui/res/cardsfolder/upcoming/anafenza_unyielding_lineage.txt
forge-gui/res/cardsfolder/upcoming/descendant_of_storms.txt
forge-gui/res/cardsfolder/upcoming/dusyut_earthcarver.txt
forge-gui/res/cardsfolder/upcoming/fortress_kin_guard.txt
forge-gui/res/cardsfolder/upcoming/krumar_initiate.txt

- Anafenza, Unyielding Lineage
- Descendant of Storms
- Dusyut Earthcarver
- Fortress Kin-Guard
- Krumar Initiate

TDM: 5 endure cards

---

forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/effects/SkipPhaseEffect.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java
forge-game/src/main/java/forge/game/replacement/ReplaceBeginPhase.java
forge-game/src/main/java/forge/game/replacement/ReplacementHandler.java
forge-gui/res/cardsfolder/c/colfenors_plans.txt
forge-gui/res/cardsfolder/d/damia_sage_of_stone.txt
forge-gui/res/cardsfolder/d/desolation_angel.txt
forge-gui/res/cardsfolder/d/desolation_giant.txt
forge-gui/res/cardsfolder/d/dragon_appeasement.txt
forge-gui/res/cardsfolder/e/eon_hub.txt
forge-gui/res/cardsfolder/f/fasting.txt
forge-gui/res/cardsfolder/g/gibbering_descent.txt
forge-gui/res/cardsfolder/i/infernal_sovereign.txt
forge-gui/res/cardsfolder/m/monstrous_war_leech.txt
forge-gui/res/cardsfolder/n/necrodominance.txt
forge-gui/res/cardsfolder/n/necropotence.txt
forge-gui/res/cardsfolder/n/necropotence_avatar.txt
forge-gui/res/cardsfolder/n/null_profusion.txt
forge-gui/res/cardsfolder/p/psychic_possession.txt
forge-gui/res/cardsfolder/r/recycle.txt
forge-gui/res/cardsfolder/s/sands_of_time.txt
forge-gui/res/cardsfolder/s/solitary_confinement.txt
forge-gui/res/cardsfolder/s/stasis.txt
forge-gui/res/cardsfolder/s/symbiotic_deployment.txt
forge-gui/res/cardsfolder/t/taigam_sidisis_hand.txt
forge-gui/res/cardsfolder/t/the_eon_fog.txt
forge-gui/res/cardsfolder/w/wild_wasteland.txt
forge-gui/res/cardsfolder/y/yawgmoths_bargain.txt

Hopefully this one's enough. :/

Replace first withContext call with more stable AI prediction

---

forge-gui/res/cardsfolder/upcoming/become_the_avalanche.txt
forge-gui/res/cardsfolder/upcoming/broodcaller_scourge.txt
forge-gui/res/cardsfolder/upcoming/sunpearl_kirin.txt
forge-gui/res/cardsfolder/upcoming/thundermane_dragon.txt

Should cards like Conspicuous Snoop be changed similar to this Thundermane Dragon? I'm not sure they would work correctly with things like Adventures or MDFC.

3 TDC + 1 TDM cards

---

forge-gui/res/cardsfolder/o/oyaminartok_polar_werebear.txt
forge-gui/res/cardsfolder/p/palladia_mors_the_ruiner.txt
forge-gui/res/cardsfolder/upcoming/armament_dragon.txt
forge-gui/res/cardsfolder/upcoming/deceptive_frostkite.txt
forge-gui/res/cardsfolder/upcoming/frontline_rush.txt
forge-gui/res/cardsfolder/upcoming/hammerhead_tyrant.txt
forge-gui/res/cardsfolder/upcoming/jeskai_shrinekeeper.txt
forge-gui/res/cardsfolder/upcoming/karakyk_guardian.txt
forge-gui/res/cardsfolder/upcoming/kin_tree_severance.txt
forge-gui/res/cardsfolder/upcoming/parapet_thrasher.txt
forge-gui/res/cardsfolder/upcoming/reverberating_summons.txt
forge-gui/res/cardsfolder/upcoming/will_of_the_temur.txt

- Deceptive Frostkite
- Frontline Rush
- Hammerhead Tyrant
- Kin-Tree Severance
- Parapet Thrasher
- Will of the Temur
- Reverberating Summons
- Armament Dragon
- Karakyk Guardian
- Jeskai Shrinekeeper

TDM/TDC: 10 cards

---

forge-gui/res/cardsfolder/upcoming/sinkhole_surveyor.txt

TDM: Sinkhole Surveyor (endure)

---

forge-gui/res/cardsfolder/upcoming/ambling_stormshell.txt
forge-gui/res/cardsfolder/upcoming/jeskai_brushmaster.txt
forge-gui/res/cardsfolder/upcoming/kheru_goldkeeper.txt
forge-gui/res/cardsfolder/upcoming/shocking_sharpshooter.txt
forge-gui/res/cardsfolder/upcoming/starry_eyed_skyrider.txt
forge-gui/res/cardsfolder/upcoming/stillness_in_motion.txt
forge-gui/res/cardsfolder/upcoming/traveling_botanist.txt
forge-gui/res/cardsfolder/upcoming/wail_of_war.txt
forge-gui/res/cardsfolder/upcoming/wayspeaker_bodyguard.txt
forge-gui/res/cardsfolder/upcoming/wingspan_stride.txt
forge-gui/res/cardsfolder/upcoming/zurgos_vanguard.txt

- Ambling Stormshell
- Jeskai Brushmaster
- Shocking Sharpshooter
- Starry-Eyed Skyrider
- Stillness in Motion
- Traveling Botanist
- Wail of War
- Wayspeaker Bodyguard
- Wingspan Stride
- Zurgo's Vanguard
Incidental fixes:
- Kheru Goldkeeper: minor standartizing cleanup

TDM: 10 cards

---

forge-ai/src/main/java/forge/ai/SpellApiToAi.java
forge-ai/src/main/java/forge/ai/ability/EndureAi.java
forge-game/src/main/java/forge/game/ability/ApiType.java
forge-game/src/main/java/forge/game/ability/effects/EndureEffect.java
forge-gui/res/cardsfolder/upcoming/anafenza_unyielding_lineage.txt
forge-gui/res/cardsfolder/upcoming/descendant_of_storms.txt
forge-gui/res/cardsfolder/upcoming/dusyut_earthcarver.txt
forge-gui/res/cardsfolder/upcoming/fortress_kin_guard.txt
forge-gui/res/cardsfolder/upcoming/krumar_initiate.txt
forge-gui/res/cardsfolder/upcoming/sinkhole_surveyor.txt
forge-gui/res/languages/en-US.properties

Endure effect

---

forge-gui/res/cardsfolder/upcoming/mardu_siegebreaker.txt

TDM: Mardu Siegebreaker

---

forge-gui/res/adventure/Shandalar/world/quests.json

This fixes the bug where the objective to free the wizard from the red castle doesn't complete.

Fix for main quest

---

forge-gui/res/cardsfolder/upcoming/avenger_of_the_fallen.txt

TDM: Avenger of the Fallen

---

forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/token/TokenInfo.java
forge-game/src/main/java/forge/game/keyword/KeywordInstance.java
forge-game/src/main/java/forge/game/keyword/KeywordInterface.java
forge-gui/res/cardsfolder/upcoming/infantry_shield.txt

the other Mobilize X card should be easy without this MR

Mobilize X: enable the keyword to pass the SVars to the static

---

forge-gui-mobile/src/forge/adventure/util/KeyBinding.java

Now actually putting the keybinds back in. Forgot to unrevert previously.

WASD Adventure take 3

---

forge-gui/res/cardsfolder/upcoming/glacial_dragonhunt.txt
forge-gui/res/cardsfolder/upcoming/mammoth_bellow.txt
forge-gui/res/cardsfolder/upcoming/natures_rhythm.txt
forge-gui/res/cardsfolder/upcoming/roamers_routine.txt
forge-gui/res/cardsfolder/upcoming/songcrafter_mage.txt
forge-gui/res/cardsfolder/upcoming/synchronized_charge.txt
forge-gui/res/cardsfolder/upcoming/unending_whisper.txt
forge-gui/res/cardsfolder/upcoming/urenis_rebuff.txt
forge-gui/res/cardsfolder/upcoming/wild_ride.txt
forge-gui/res/cardsfolder/upcoming/winternight_stories.txt
forge-gui/res/cardsfolder/upcoming/zenith_festival.txt

Tested to satisfaction. Linked with https://github.com/Card-Forge/forge/pull/7321 .
(Unfortunately, I updated my master before creating this pull request so this one's a bit ahead of the linked PR as concerns commit history.)

TDM/TDC: 11 harmonize cards

---

forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
forge-game/src/main/java/forge/game/spellability/OptionalCostValue.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-gui/res/cardsfolder/upcoming/channeled_dragonfire.txt
forge-gui/res/cardsfolder/upcoming/glacial_dragonhunt.txt
forge-gui/res/cardsfolder/upcoming/mammoth_bellow.txt
forge-gui/res/cardsfolder/upcoming/natures_rhythm.txt
forge-gui/res/cardsfolder/upcoming/roamers_routine.txt
forge-gui/res/cardsfolder/upcoming/songcrafter_mage.txt
forge-gui/res/cardsfolder/upcoming/synchronized_charge.txt
forge-gui/res/cardsfolder/upcoming/unending_whisper.txt
forge-gui/res/cardsfolder/upcoming/urenis_rebuff.txt
forge-gui/res/cardsfolder/upcoming/wild_ride.txt
forge-gui/res/cardsfolder/upcoming/winternight_stories.txt
forge-gui/res/cardsfolder/upcoming/zenith_festival.txt

The Raise Cost doesn't work yet
but that is the easiest way right now to code Harmonize without extra java code

Harmonize first try

---

forge-game/src/main/java/forge/game/ability/effects/CountersPutEffect.java
forge-gui/res/cardsfolder/c/call_the_spirit_dragons.txt

it was easier to add it to CounterPut instead of using RepeatEach
@Agetian AI might need some logic for ForColor so it doesn't crash?
The card itself might need some Needs Dragon in Play param

Put ForColor  for Call of the Spirit Dragons

---

forge-gui/res/cardsfolder/a/alchemists_assistant.txt

Changed the Renew cost from B to 1 B to reflect the cost on the card

Fixed Renew cost in alchemists_assistant.txt

---

forge-gui/res/cardsfolder/a/aligned_heart.txt
forge-gui/res/cardsfolder/d/dedicated_dollmaker.txt
forge-gui/res/cardsfolder/f/felling_blow.txt
forge-gui/res/cardsfolder/s/sojourners_enforcermite.txt

Dealing with extraneous repeats.

Cleanup: April 2025, pass 3

---

forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/spellability/AbilitySub.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java

@tool4ever can you check this out?
And if possible, add a TestCase for Flashback + Adventure?
Closes #7383

Svar fallback changes

---

forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java

Until it can be implemented in a better fashion...

Fix Licids being able to reattach without ending the effect first

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/card/Card.java

Fix Old-Growth Troll

---

forge-ai/src/main/java/forge/ai/ability/TokenAi.java

Update TokenAi, remove getFirstAttachSpell

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/effects/CloneEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardZoneTable.java

Fix World rule

---

forge-game/src/main/java/forge/game/trigger/WrappedAbility.java

Fix some triggered abilities not finding SVars from effect

---

forge-game/src/main/java/forge/game/card/CardFactory.java
forge-gui/src/main/java/forge/player/TargetSelection.java

Fix always targeting Graveyard with Aura

---

forge-game/src/main/java/forge/game/zone/MagicStack.java

https://discord.com/channels/267367946135928833/1362293555283890276

Fix missing LTB trigger

---

forge-gui/res/adventure/common/maps/map/main_story_explore/frostbitten_cavern_1.tmx

This piece of code didn't work and produced a fallback dialog. Fixed the formatting to make it work as it was supposed to.
(There is a dead flower in that cave that is kind of hard to notice, but this part of the code was supposed to do something there. It works now).

[Adventure] Fixing fallback dialog in flower cave

---

forge-core/src/main/java/forge/StaticData.java
forge-core/src/main/java/forge/card/CardEdition.java
forge-core/src/main/java/forge/item/PaperCard.java
forge-core/src/main/java/forge/item/PaperToken.java
forge-gui/res/editions/Tarkir Dragonstorm.txt

First part for #7288 
This allows the Token Scripts to be added with CollectorNumber and Artist in the CardEdition
next steps are TokenDb and PaperToken

CardEdition: add TokenInSet

---

forge-gui/res/cardsfolder/b/bestow_greatness.txt
forge-gui/res/cardsfolder/b/burner_rocket.txt
forge-gui/res/cardsfolder/j/jumbo_cactuar.txt
forge-gui/res/cardsfolder/r/rally_the_monastery.txt
forge-gui/res/cardsfolder/r/reigning_victor.txt
forge-gui/res/cardsfolder/r/riling_dawnbreaker_signaling_roar.txt
forge-gui/res/cardsfolder/s/sarkhans_resolve.txt

Following up on https://github.com/Card-Forge/forge/pull/6878 , dealing with newer cards.

Cleanup: NumAtt$ & NumDef$, new cards

---

forge-ai/src/main/java/forge/ai/GameState.java
forge-ai/src/main/java/forge/ai/ability/CloakAi.java
forge-ai/src/main/java/forge/ai/ability/ManifestAi.java
forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-game/src/main/java/forge/game/GameSnapshot.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardView.java
forge-game/src/main/java/forge/trackable/TrackableProperty.java
forge-gui/src/main/java/forge/player/HumanPlay.java

This adds set codes to different face-down images
in the future, this can be used for set specific token images

Card: add FacedownImageKey for better logic and set codes

---

forge-gui/res/editions/Commander Anthology Volume II.txt
forge-gui/res/editions/Commander Anthology.txt
forge-gui/res/editions/Commander Legends Battle for Baldur's Gate.txt
forge-gui/res/editions/Commander Legends.txt
forge-gui/res/editions/Commander Masters.txt
forge-gui/res/editions/Modern Horizons 2.txt
forge-gui/res/editions/Murders at Karlov Manor Commander.txt
forge-gui/res/editions/Tarkir Dragonstorm Commander.txt
forge-gui/res/editions/Tarkir Dragonstorm.txt

Didn't do any research on Scryfall or anything just removed some obvious stuff I noticed

Edition token section fixes

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantAttackBlock.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantBeCast.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityContinuous.java
forge-gui/res/cardsfolder/d/damping_engine.txt
forge-gui/res/cardsfolder/l/lost_in_thought.txt
forge-gui/res/cardsfolder/v/volraths_curse.txt

Combines the Modes with Continuous for IgnoreEffectCost

Volrath's Curse and Lost in Thought with Modes and IgnoreEffectCost

---

forge-gui/res/adventure/common/custom_cards/hall_of_flame.txt
forge-gui/res/adventure/common/maps/map/grolnok/grolnok_f1.tmx
forge-gui/res/adventure/common/maps/map/main_story_explore/bandit_cave.tmx

-closes #7384 
-closes #7482 
-closes #7154

Adventure 3 small fixes

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-gui/res/cardsfolder/upcoming/dragonsoul_prodigy.txt
forge-gui/res/cardsfolder/upcoming/song_of_seasons.txt
forge-gui/res/cardsfolder/upcoming/stonehide_ancient_warning_tremor.txt
forge-gui/res/cardsfolder/upcoming/swiftspears_teachings.txt

[As revealed recently](https://scryfall.com/sets/ytdm); Tested to satisfaction:
- [Dragonsoul Prodigy](https://scryfall.com/card/ytdm/11/dragonsoul-prodigy) and support for `AtEOT$ Library`
- [Song of Seasons](https://scryfall.com/card/ytdm/25/song-of-seasons)
- [Stonehide Ancient // Warning Tremor](https://scryfall.com/card/ytdm/26/stonehide-ancient-warning-tremor)
- [Swiftspear's Teachings](https://scryfall.com/card/ytdm/14/swiftspears-teachings)

YTDM: 4 cards

---

forge-gui/res/cardsfolder/upcoming/graha_tia_scion_reborn.txt
forge-gui/res/cardsfolder/upcoming/yuna_grand_summoner.txt
forge-gui/res/tokenscripts/c_1_1_hero.txt

[As revealed recently](https://www.reddit.com/r/magicTCG/comments/1ki6k5b/yuna_and_graha/); tested to satisfaction.

FIC: Yuna, G'raha and new token

---

forge-game/src/main/java/forge/game/ability/effects/CharmEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/cost/CostAdjustment.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-gui/res/cardsfolder/c/caught_in_the_crossfire.txt
forge-gui/res/cardsfolder/d/dance_of_the_tumbleweeds.txt
forge-gui/res/cardsfolder/e/explosive_derailment.txt
forge-gui/res/cardsfolder/f/final_showdown.txt
forge-gui/res/cardsfolder/g/getaway_glamer.txt
forge-gui/res/cardsfolder/g/great_train_heist.txt
forge-gui/res/cardsfolder/i/insatiable_avarice.txt
forge-gui/res/cardsfolder/j/jailbreak_scheme.txt
forge-gui/res/cardsfolder/l/lively_dirge.txt
forge-gui/res/cardsfolder/m/metamorphic_blast.txt
forge-gui/res/cardsfolder/o/one_last_job.txt
forge-gui/res/cardsfolder/p/phantom_interference.txt
forge-gui/res/cardsfolder/r/requisition_raid.txt
forge-gui/res/cardsfolder/r/return_the_favor.txt
forge-gui/res/cardsfolder/r/rush_of_dread.txt
forge-gui/res/cardsfolder/r/rustler_rampage.txt
forge-gui/res/cardsfolder/s/shifting_grift.txt
forge-gui/res/cardsfolder/s/smugglers_surprise.txt
forge-gui/res/cardsfolder/t/three_steps_ahead.txt
forge-gui/res/cardsfolder/t/trash_the_town.txt
forge-gui/res/cardsfolder/u/unfortunate_accident.txt
forge-gui/res/cardsfolder/upcoming/fire_magic.txt

OR should Spree/SpreeCost and Tiered/TieredCost be simplified?
Also should they check for the Keyword instead of Param?

Tiered: first example

---

forge-gui/res/cardsfolder/e/emperor_of_bones.txt
forge-gui/res/cardsfolder/upcoming/a_realm_reborn.txt
forge-gui/res/cardsfolder/upcoming/absolute_virtue.txt
forge-gui/res/cardsfolder/upcoming/adventurers_inn.txt
forge-gui/res/cardsfolder/upcoming/aerith_gainsborough.txt
forge-gui/res/cardsfolder/upcoming/ardyn_the_usurper.txt
forge-gui/res/lists/TypeLists.txt

Not much time today, so I only implemented a few.

5 FIN cards

---

forge-game/src/main/java/forge/game/ability/AbilityKey.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChooseCardEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChooseColorEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChooseGenericEffect.java
forge-game/src/main/java/forge/game/ability/effects/EndTurnEffect.java
forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java
forge-game/src/main/java/forge/game/ability/effects/RollDiceEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/spellability/AbilityManaPart.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityCantAttackBlock.java
forge-game/src/main/java/forge/game/trigger/WrappedAbility.java
forge-gui/res/cardsfolder/a/athreos_god_of_passage.txt
forge-gui/res/cardsfolder/b/bravado.txt
forge-gui/res/cardsfolder/c/conclaves_blessing.txt
forge-gui/res/cardsfolder/d/due_diligence.txt
forge-gui/res/cardsfolder/g/gleam_of_authority.txt
forge-gui/res/cardsfolder/k/kjeldoran_pride.txt
forge-gui/res/cardsfolder/l/lost_legacy.txt
forge-gui/res/cardsfolder/o/one_with_the_kami.txt
forge-gui/res/cardsfolder/r/rumbling_ruin.txt
forge-gui/res/cardsfolder/s/sigil_of_sleep.txt
forge-gui/res/cardsfolder/u/unnatural_hunger.txt
forge-gui/res/cardsfolder/v/veterans_voice.txt
forge-gui/src/main/java/forge/gui/card/CardScriptParser.java

Some support for Desert Cenote

---

forge-ai/src/main/java/forge/ai/simulation/GameCopier.java
forge-core/src/main/java/forge/ImageKeys.java
forge-core/src/main/java/forge/StaticData.java
forge-core/src/main/java/forge/card/CardDb.java
forge-core/src/main/java/forge/card/CardEdition.java
forge-game/src/main/java/forge/game/Game.java
forge-game/src/main/java/forge/game/GameFormat.java
forge-game/src/main/java/forge/game/GameSnapshot.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/AscendEffect.java
forge-game/src/main/java/forge/game/ability/effects/BecomeMonarchEffect.java
forge-game/src/main/java/forge/game/ability/effects/RestartGameEffect.java
forge-game/src/main/java/forge/game/ability/effects/RingTemptsYouEffect.java
forge-game/src/main/java/forge/game/ability/effects/TakeInitiativeEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardView.java
forge-game/src/main/java/forge/game/player/Player.java
forge-gui-mobile/src/forge/adventure/data/RewardData.java
forge-gui-mobile/src/forge/adventure/scene/SpellSmithScene.java
forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java
forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestPlane.java
forge-gui/src/main/java/forge/gamemodes/quest/QuestEventDraft.java
forge-gui/src/main/java/forge/util/ImageFetcher.java

Added Other Collector Number
(need to update the other sets)
so other references to Helper cards (facedown/manifest) and Emblem can be updated to check if they are part of the set

CardEdition: add collector number for other

---

forge-gui/res/cardsfolder/s/serra_avenger.txt
forge-gui/res/cardsfolder/upcoming/terra_magical_adept_esper_terra.txt

Might require some attention to work correctly with Doubling Season and similar things.

Terra, Magical Adept

---

forge-gui/res/cardsfolder/m/motion_sickness.txt
forge-gui/res/cardsfolder/s/storybook_ride.txt

2 attraction fixes

---

forge-gui/res/cardsfolder/a/awestruck_cygnet.txt
forge-gui/res/cardsfolder/e/enduring_friendship.txt
forge-gui/res/cardsfolder/n/naktamun_shines_again.txt
forge-gui/res/cardsfolder/r/ribald_shanty.txt

Source: https://magic.wizards.com/en/news/mtg-arena/announcements-may-12-2025#Alchemy
Alchemy only - no new script needed:

Alchemy Rebalancing for May 13, 2025

---

forge-game/src/main/java/forge/game/card/CardProperty.java
forge-gui/res/cardsfolder/g/gisela_the_broken_blade_brisela_voice_of_nightmares.txt
forge-gui/res/cardsfolder/g/graf_rats_chittering_host.txt
forge-gui/res/cardsfolder/t/titania_voice_of_gaea_titania_gaea_incarnate.txt
forge-gui/res/cardsfolder/upcoming/balthier_and_fran.txt
forge-gui/res/cardsfolder/upcoming/cid_timeless_artificer.txt
forge-gui/res/cardsfolder/upcoming/clive_ifrits_dominant_ifrit_warden_of_inferno.txt
forge-gui/res/cardsfolder/upcoming/fang_fearless_lcie.txt
forge-gui/res/cardsfolder/upcoming/jill_shivas_dominant_shiva_warden_of_ice.txt
forge-gui/res/cardsfolder/upcoming/the_crystals_chosen.txt
forge-gui/res/cardsfolder/upcoming/the_emperor_of_palamecia_the_lord_master_of_hell.txt
forge-gui/res/cardsfolder/upcoming/ultimecia_time_sorceress_ultimecia_omnipotent.txt
forge-gui/res/cardsfolder/upcoming/vanille_cheerful_lcie_ragnarok_divine_deliverance.txt
forge-gui/res/cardsfolder/upcoming/zanarkand_ancient_metropolis_lasting_fayth.txt
forge-gui/res/cardsfolder/w/werewolf_pack_leader.txt

As revealed recently; tested to satisfaction ~~where not noted otherwise~~:
- [Balthier and Fran](https://scryfall.com/card/fin/213/balthier-and-fran) and `CrewedBySourceThisTurn` property
~~=>The triggered ability was tested with `ValidCard$ Vehicle.YouCtrl` and found to work as expected in that context. The actual trigger condition is suggested as `ValidCard$ Vehicle.CrewedBySourceThisTurn` but hasn't been implemented as it's frankly beyond my expertise in Java.~~
- [Cid, Timeless Artificer](https://scryfall.com/card/fin/414/cid-timeless-artificer)
- [Clive, Ifrit's Dominant // Ifrit, Warden of Inferno](https://scryfall.com/card/fin/133/clive-ifrits-dominant-ifrit-warden-of-inferno)
- [Fang, Fearless l'Cie](https://scryfall.com/card/fin/446/fang-fearless-lcie)
- [Jill, Shiva's Dominant …

FIN: 10 more cards

---

forge-game/src/main/java/forge/game/Game.java

Support for Lord Jyscal Guado

---

forge-gui/res/cardsfolder/upcoming/auron_venerated_guardian.txt
forge-gui/res/cardsfolder/upcoming/blitzball_stadium.txt
forge-gui/res/cardsfolder/upcoming/chocobo_knights.txt
forge-gui/res/cardsfolder/upcoming/gatta_and_luzzu.txt
forge-gui/res/cardsfolder/upcoming/kimahri_valiant guardian.txt

- [Auron, Venerated Guardian](https://scryfall.com/card/fic/10/auron-venerated-guardian)
- [Blitzball Stadium](https://scryfall.com/card/fic/34/blitzball-stadium)
- [Chocobo Knights](https://scryfall.com/card/fic/12/chocobo-knights)
- [Gatta and Luzzu](https://scryfall.com/card/fic/19/gatta-and-luzzu)
- [Kimahri, Valiant Guardian](https://scryfall.com/card/fic/85/kimahri-valiant-guardian)

FIC: 5 cards

---

forge-gui/res/cardsfolder/v/value town_take_a_trip_to.txt

Might as well, considering the FIN cycle of adventurer lands. In any case, tested to satisfaction.
- [Value Town // Take a Trip to...](https://scryfall.com/card/mb2/621/value-town-take-a-trip-to)

MB2: Value Town

---

forge-gui/res/cardsfolder/upcoming/summon_knights_of_round.txt
forge-gui/res/cardsfolder/upcoming/summon_primal_garuda.txt

- [Summon: Knights of Round](https://www.reddit.com/r/magicTCG/comments/1ko4n5o/summonknights_of_round_brandon_sanderson/)
- [Summon: Primal Garuda](https://www.reddit.com/r/magicTCG/comments/1ko4uxd/fin_summon_primal_garuda/)

FIN: another 2 cards

---

forge-gui/res/cardsfolder/upcoming/instant_ramen.txt
forge-gui/res/cardsfolder/upcoming/kefka_dancing_mad.txt
forge-gui/res/cardsfolder/upcoming/machinists_arsenal.txt
forge-gui/res/cardsfolder/upcoming/snort.txt

- [Kefka, Dancing Mad](https://scryfall.com/card/fic/84/kefka-dancing-mad)
- [Snort](https://scryfall.com/card/fic/58/snort)
- [Machinist's Arsenal](https://www.reddit.com/r/magicTCG/comments/1ko088z/fin_machinists_arsenal_jackxsaunders_preview/)
- [Instant Ramen](https://www.reddit.com/r/magicTCG/comments/1ko36bz/fin_instant_ramen_card_image_gallery/)

FIC: last 2 cards + FIN: 2 cards

---

forge-gui/res/cardsfolder/upcoming/kefka_dancing_mad.txt
forge-gui/res/cardsfolder/upcoming/nibelheim_aflame.txt
forge-gui/res/cardsfolder/upcoming/reno_and_rude.txt

- [Nibelheim Aflame](https://www.reddit.com/r/magicTCG/comments/1koj27s/fin_nibelheim_aflame_finalfantasycom/)
- [Reno and Rude](https://www.reddit.com/r/magicTCG/comments/1kohkx8/fin_reno_and_rude_loadingreadyrun/)
Incidental fixes:
- Kefka, Dancing Mad: editing lapse.

FIN: 2 more cards

---

forge-gui/res/cardsfolder/s/sanguine_soothsayer.txt

Fix Sanguine Soothsayer

---

forge-gui/res/cardsfolder/upcoming/ice_flan.txt

[As revealed recently](https://scryfall.com/card/fin/55/ice-flan); tested to satisfaction.

FIN: Ice Flan

---

forge-gui/res/cardsfolder/upcoming/adelbert_steiner.txt
forge-gui/res/cardsfolder/upcoming/blitzball_shot.txt
forge-gui/res/cardsfolder/upcoming/dwarven_castle_guard.txt
forge-gui/res/cardsfolder/upcoming/tidus_blitzball_star.txt

- [Adelbert Steiner](https://scryfall.com/card/fin/422/adelbert-steiner)
- [Blitzball Shot](https://scryfall.com/card/fin/176/blitzball-shot)
- [Dwarven Castle Guard](https://scryfall.com/card/fin/18/dwarven-castle-guard)
- [Tidus, Blitzball Star](https://scryfall.com/card/fin/512/tidus-blitzball-star)

FIC: 4 cards

---

forge-gui/res/cardsfolder/upcoming/clash_of_the_eikons.txt

- [Clash of the Eikons](https://www.reddit.com/r/magicTCG/comments/1ks256h/fin_clash_of_the_eikons_tolarian_community_college/)

FIN: Clash of the Eikons

---

forge-game/src/main/java/forge/game/CardTraitBase.java
forge-game/src/main/java/forge/game/spellability/AbilitySub.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-gui/res/cardsfolder/h/henzie_toolbox_torre.txt

@tool4ever can you check if that doesn't break anything else?
otherwise the Henzie Svar rename might be enough for now?

Fix Henzie again with SvarFallback

---

forge-gui/res/cardsfolder/upcoming/black_waltz_no_3.txt

- [Black Waltz No. 3](https://www.reddit.com/r/magicTCG/comments/1ktxyx3/fin_black_waltz_no_3_scrybabies/)

FIN: Black Waltz No. 3

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/DamageEachEffect.java
forge-game/src/main/java/forge/game/ability/effects/FlipCoinEffect.java
forge-game/src/main/java/forge/game/cost/CostFlipCoin.java
forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityFlipCoinMod.java
forge-game/src/main/java/forge/game/staticability/StaticAbilityMode.java
forge-gui/res/cardsfolder/a/amulet_of_quoz.txt
forge-gui/res/cardsfolder/c/crazed_firecat.txt
forge-gui/res/cardsfolder/c/crooked_scales.txt
forge-gui/res/cardsfolder/g/game_of_chaos.txt
forge-gui/res/cardsfolder/g/goblin_assassin.txt
forge-gui/res/cardsfolder/g/goblin_kaboomist.txt
forge-gui/res/cardsfolder/m/mirror_march.txt
forge-gui/res/cardsfolder/m/mirrored_depths.txt
forge-gui/res/cardsfolder/p/planar_chaos.txt
forge-gui/res/cardsfolder/t/tide_of_war.txt
forge-gui/res/cardsfolder/upcoming/edgar_king_of_figaro.txt

 Edgar, King of Figaro and support

---

forge-ai/src/main/java/forge/ai/ComputerUtilCost.java
forge-game/src/main/java/forge/game/cost/Cost.java
forge-game/src/main/java/forge/game/cost/CostPayment.java
forge-game/src/main/java/forge/game/spellability/SpellPermanent.java
forge-gui/res/cardsfolder/upcoming/the_gold_saucer.txt

UnlessCost: fix checking wrong payer

---

forge-game/src/main/java/forge/game/ability/effects/CopySpellAbilityEffect.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java
forge-gui/res/cardsfolder/upcoming/gogo_master_of_mimicry.txt

Gogo, Master of Mimicry (FIN)

---

forge-gui/res/cardsfolder/i/indicate.txt
forge-gui/res/cardsfolder/s/stone_drake.txt

Seemed quick enough to do. Tested to satisfaction:
- [Stone Drake](https://scryfall.com/card/mb2/602/stone-drake)
- [Indicate](https://scryfall.com/card/mb2/501/indicate)

MB2: 2 cards

---

forge-gui/res/cardsfolder/upcoming/elixir.txt
forge-gui/res/cardsfolder/upcoming/judge_magister_gabranth.txt
forge-gui/res/cardsfolder/upcoming/louisoixs_sacrifice.txt
forge-gui/res/cardsfolder/upcoming/magitek_infantry.txt
forge-gui/res/cardsfolder/upcoming/sorceresss_schemes.txt
forge-gui/res/cardsfolder/upcoming/the_final_days.txt
forge-gui/res/tokenscripts/b_2_2_horror.txt

- [Elixir](https://scryfall.com/card/fin/256/elixir)
- [Judge Magister Gabranth](https://scryfall.com/card/fin/495/judge-magister-gabranth)
- [Louisoix's Sacrifice](https://scryfall.com/card/fin/59/louisoixs-sacrifice)
- [Magitek Infantry](https://scryfall.com/card/fin/25/magitek-infantry)
- [Sorceress's Schemes](https://scryfall.com/card/fin/159/sorceresss-schemes)
- [The Final Days](https://scryfall.com/card/fin/101/the-final-days) and token

FIN: 6 cards

---

forge-gui/res/adventure/Amonkhet/world/quests.json
forge-gui/res/adventure/Shandalar/world/quests.json
forge-gui/res/adventure/common/maps/map/aerie/aerie_0.tmx
forge-gui/res/adventure/common/maps/map/demontower/portal_2.tmx
forge-gui/res/adventure/common/maps/map/grove/grove_8_hydra.tmx
forge-gui/res/adventure/common/maps/map/main_story/castles/black_castle.tmx
forge-gui/res/adventure/common/maps/map/main_story/castles/blue_castle.tmx
forge-gui/res/adventure/common/maps/map/main_story/castles/green_castle.tmx
forge-gui/res/adventure/common/maps/map/main_story/castles/red_castle.tmx
forge-gui/res/adventure/common/maps/map/main_story/castles/white_castle.tmx
forge-gui/res/adventure/common/maps/map/main_story/temple_of_gideon/steppe.tmx
forge-gui/res/adventure/common/maps/map/main_story/temple_of_gideon/town.tmx
forge-gui/res/adventure/common/maps/map/main_story/temple_of_liliana/town.tmx
forge-gui/res/adventure/common/maps/map/main_story_explore/library_of_varsil_2.tmx
forge-gui/res/adventure/common/maps/map/skep/skep_outer.tmx
forge-gui/res/adventure/common/maps/map/vampirecastle/vampirecastle_grave_1.tmx
forge-gui/res/adventure/common/maps/map/vampirecastle/vampirecastle_grave_2.tmx
forge-gui/res/adventure/common/maps/map/vampirecastle/vampirecastle_grave_3.tmx

Following up on https://github.com/Card-Forge/forge/pull/7674 again, with additional proofreading.

Adventure cleanup: 2025-05-27

---

forge-gui/res/cardsfolder/upcoming/minwu_white_mage.txt

- [Minwu, White Mage](https://scryfall.com/card/fin/26/minwu-white-mage)

FIN: Minwu

---

forge-gui/res/cardsfolder/a/aether_spike.txt
forge-gui/res/cardsfolder/upcoming/coliseum_behemoth.txt
forge-gui/res/cardsfolder/upcoming/scorpion_sentinel.txt
forge-gui/res/cardsfolder/upcoming/stuck_in_summoners_sanctum.txt
forge-gui/res/cardsfolder/upcoming/swallowed_by_leviathan.txt
forge-gui/res/cardsfolder/upcoming/thiefs_knife.txt
forge-gui/res/cardsfolder/upcoming/thunder_magic.txt
forge-gui/res/cardsfolder/upcoming/unexpected_request.txt

- [Coliseum Behemoth](https://scryfall.com/card/fin/181/coliseum-behemoth)
- [Scorpion Sentinel](https://scryfall.com/card/fin/72/scorpion-sentinel)
- [Stuck in Summoner's Sanctum](https://scryfall.com/card/fin/76/stuck-in-summoners-sanctum)
- [Swallowed by Leviathan](https://scryfall.com/card/fin/79/swallowed-by-leviathan)
- [Thief's Knife](https://scryfall.com/card/fin/81/thiefs-knife)
- [Thunder Magic](https://scryfall.com/card/fin/165/thunder-magic)
- [Unexpected Request](https://scryfall.com/card/fin/167/unexpected-request)
Incidental fixes:
- Aether Spike: Updated to follow Swallowed by Leviathan

FIN: 7 cards

---

forge-gui/res/cardsfolder/upcoming/golbez_crystal_collector.txt

- [Golbez, Crystal Collector](https://scryfall.com/card/fin/225/golbez-crystal-collector)

FIN: Golbez, Crystal Collector

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardState.java
forge-game/src/main/java/forge/game/phase/PhaseHandler.java

Saga: do State-Based and Turn-Based Action only with Chapters

---

forge-gui/res/cardsfolder/c/clackbridge_troll.txt
forge-gui/res/cardsfolder/m/monastery_messenger.txt

Associated with the process for https://github.com/Card-Forge/forge/pull/7798 , changes that eased it along, namely by making scripts more predictable when gleaning card names.

Incidental fixes: 2025-06-05

---

CONTRIBUTING.md

Changes:
* Added missing descriptions to top level modules
* Fixed any typos found
* Consistent use of single space after period

Some small edits to CONTRIBUTING docs

---

forge-gui/res/cardsfolder/s/sundown_pass.txt

Prevents hit in search for cards with `Add {R} or {W}`, c.f. https://discord.com/channels/267367946135928833/1383455315470581852

card: correct sundown pass mana order

---

forge-game/src/main/java/forge/game/cost/CostPayment.java

Fix ConcurrentModificationException (#7865)
I haven't seen 50 tokens with Prossh vs Omnath, Locus of All again yet, but my 20+ test games did not produce an error or get stuck like before.

Fix ConcurrentModificationException (#7865)

---

forge-gui/res/editions/Commander 2021.txt

Fix Triplicate Titans tokens ids

---

forge-core/src/main/java/forge/util/ImageUtil.java

Fix Meld art download (#7858)

---

forge-gui-mobile/src/forge/adventure/stage/Console.java
forge-gui-mobile/src/forge/adventure/stage/GameHUD.java
forge-gui-mobile/src/forge/adventure/util/KeyBinding.java

also add "exit" console command, should be useful for mobile device without physical/soft/hidden back key

Fix Android Keybind for Adventure Mode Console toggle

---

forge-core/src/main/java/forge/card/CardRules.java
forge-core/src/main/java/forge/card/CardType.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-gui/res/cardsfolder/upcoming/the_seriema.txt
forge-gui/res/lists/TypeLists.txt

Adds new Spacecraft Type
Adds Station Keyword (might need AI logic?)
Allows Legendary Vehicle and Spacecraft as Commander

Add Spacecraft

---

forge-game/src/main/java/forge/game/ability/effects/TextBoxExchangeEffect.java
forge-gui-mobile/src/forge/deck/FDeckEditor.java
forge-gui/res/cardsfolder/e/exchange_of_words.txt

An attempt to add duration handling to TextgBoxExchangeEffect (Deadpool's effect) and adding Exchange of Words.
This is my first contribution and there might be some corner cases / better way to handle this, please do feel free to edit or provide feedback in case.
Card script for Exchange of Words made by @tribot_leader on [Discord](https://discord.com/channels/267367946135928833/402524622958100501/1385509180881895527)

Add Duration handling to TextBoxExchangeEffect and added Exchange of Words

---

forge-gui/res/cardsfolder/upcoming/amy_rose.txt
forge-gui/res/cardsfolder/upcoming/dr_eggman.txt
forge-gui/res/cardsfolder/upcoming/knuckles_the_echidna.txt
forge-gui/res/cardsfolder/upcoming/miles_tails_prower.txt
forge-gui/res/cardsfolder/upcoming/shadow_the_hedgehog.txt
forge-gui/res/cardsfolder/upcoming/sonic_the_hedgehog.txt
forge-gui/res/cardsfolder/upcoming/super_state.txt
forge-gui/res/lists/TypeLists.txt

I originally tried direct targeting in Attach ability for Amy, but it had the side effect of attempting to attach ALL targets to her.

Sonic the Hedgehog and the rest of his Secret Lair

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/effects/ChangeTargetsEffect.java
forge-game/src/main/java/forge/game/spellability/SpellAbilityStackInstance.java

 Fix updateTarget 

---

forge-game/src/main/java/forge/game/card/CardFactory.java

Fix #7937: offspring token key malformed

---

forge-gui/res/cardsfolder/e/eat_to_extinction.txt
forge-gui/res/cardsfolder/m/mycosynth_golem.txt
forge-gui/res/cardsfolder/upcoming/chrome_companion.txt
forge-gui/res/cardsfolder/upcoming/emergency_eject.txt
forge-gui/res/cardsfolder/upcoming/emissary_escort.txt
forge-gui/res/cardsfolder/upcoming/famished_worldsire.txt
forge-gui/res/cardsfolder/upcoming/genemorph_imago.txt
forge-gui/res/cardsfolder/upcoming/hearthhull_the_worldseed.txt
forge-gui/res/cardsfolder/upcoming/inspirit_flagship_vessel.txt
forge-gui/res/cardsfolder/upcoming/kav_landseeker.txt
forge-gui/res/cardsfolder/upcoming/ouroboroid.txt
forge-gui/res/cardsfolder/upcoming/ragost_deft_gastronaut.txt
forge-gui/res/cardsfolder/upcoming/sami_wildcat_captain.txt
forge-gui/res/cardsfolder/upcoming/seedship_impact.txt
forge-gui/res/cardsfolder/upcoming/shattered_wings.txt
forge-gui/res/cardsfolder/upcoming/singularity_rupture.txt
forge-gui/res/cardsfolder/upcoming/syr_vondam_the_lucent.txt
forge-gui/res/cardsfolder/upcoming/terminal_velocity.txt
forge-gui/res/cardsfolder/upcoming/the_endstone.txt
forge-gui/res/cardsfolder/upcoming/unravel.txt
forge-gui/res/cardsfolder/upcoming/weapons_manufacturing.txt
forge-gui/res/cardsfolder/upcoming/wurmwall_sweeper.txt
forge-gui/res/tokenscripts/munitions.txt

Everything seems to work except Kav Landseeker delayed trigger, but I need to go to bed.

18 EOE + 2 EOC cards

---

forge-gui/res/cardsfolder/upcoming/mmmenon_the_right_hand.txt
forge-gui/res/cardsfolder/upcoming/reroute_systems.txt
forge-gui/res/cardsfolder/upcoming/sunstar_chaplain.txt

- [Mm'menon, the Right Hand](https://scryfall.com/card/eoe/68/mmmenon-the-right-hand)
- [Reroute Systems](https://scryfall.com/card/eoe/31/reroute-systems)
- [Sunstar Chaplain](https://scryfall.com/card/eoe/40/sunstar-chaplain)

EOE: 3 cards

---

forge-ai/src/main/java/forge/ai/GameState.java

Fix token generation in puzzles

---

forge-core/src/main/java/forge/card/CardDb.java
forge-gui-mobile/src/forge/screens/planarconquest/ConquestPlaneswalkersScreen.java
forge-gui-mobile/src/forge/screens/planarconquest/NewConquestScreen.java
forge-gui/res/conquest/planes/Alara/cards.txt
forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestCommander.java
forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestPlane.java
forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestRegion.java
forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestUtil.java

Should alleviate problems in #8025
* Only add commanders once.
* Fix REPRINT_SET_TYPES check for Planeswalkers.
* Allow `cards.txt` to specify a set.

Planar Conquest fixes

---

forge-gui/res/editions/Jumpstart Historic Horizons.txt

J21 Update

---

forge-game/src/main/java/forge/game/replacement/ReplaceDrawCards.java
forge-gui/res/cardsfolder/upcoming/quantum_riddler.txt

Quantum Riddler (EOE)

---

forge-gui/res/cardsfolder/q/quest_for_the_holy_relic.txt
forge-gui/res/cardsfolder/upcoming/atmospheric_greenhouse.txt
forge-gui/res/cardsfolder/upcoming/cryogen_relic.txt
forge-gui/res/cardsfolder/upcoming/dauntless_scrapbot.txt
forge-gui/res/cardsfolder/upcoming/honored_knight_captain.txt
forge-gui/res/cardsfolder/upcoming/lightless_evangel.txt
forge-gui/res/cardsfolder/upcoming/lumen_class_frigate.txt
forge-gui/res/cardsfolder/upcoming/radiant_strike.txt

- [Honored Knight-Captain](https://scryfall.com/card/eoe/22/honored-knight-captain)
- [Lightless Evangel](https://scryfall.com/card/eoe/109/lightless-evangel)
- [Lumen-Class Frigate](https://scryfall.com/card/eoe/25/lumen-class-frigate)
- [Radiant Strike](https://scryfall.com/card/eoe/29/radiant-strike)
Some incidental cleanup as well. ~~I hope the Dauntless Scrapbot merge conflict is dealt with adequately.~~
Also, @Valensior , I'd be much obliged if you kept tabs on [project page for EOE](https://github.com/orgs/Card-Forge/projects/76/views/1). General rule of thumb is to give people who claim cards two weeks to work on them. I'd think three cards I claimed this Monday would still be in this grace period.

EOE: 4 cards

---

forge-gui-mobile/src/forge/adventure/util/KeyBinding.java
forge-gui/res/adventure/Innistrad/ui/new_game.json
forge-gui/res/adventure/common/ui/new_game.json

update keybinding for NewGameScene

---

forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-game/src/main/java/forge/game/ability/effects/PermanentEffect.java

When copying a spell the token shouldn't magically gain Blitz on ETB.
Since the delayed triggers aren't connected that strongly to their keywords we also need to check there if it really existed.

Henzie day: fix copied spell gaining Blitz

---

forge-core/src/main/java/forge/card/CardDb.java
forge-core/src/main/java/forge/card/CardEdition.java
forge-core/src/main/java/forge/item/PaperCardPredicates.java
forge-gui-mobile/src/forge/adventure/data/RewardData.java

Removal of conjured cards from the reward pool, made more prominent with #8080

Remove conjured cards from rewards

---

forge-gui/res/cardsfolder/upcoming/atomic_microsizer.txt
forge-gui/res/cardsfolder/upcoming/glacier_godmaw.txt

- [Atomic Microsizer](https://scryfall.com/card/eoe/47/atomic-microsizer)
- [Glacier Godmaw](https://scryfall.com/card/eoe/188/glacier-godmaw)
There's an overlap with https://github.com/Card-Forge/forge/pull/8081 . I'll leave it to the maintainers to resolve the conflict as they wish.

EOE: 2 cards

---

forge-gui-mobile/src/forge/adventure/scene/QuestLogScene.java

Back to quest list button fix

---

forge-gui-mobile/src/forge/adventure/stage/ConsoleCommandInterpreter.java

More console commands for easier testing.

More console commands

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Devour.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/keyword/KeywordWithAmountAndType.java
forge-gui/res/cardsfolder/c/caprichrome.txt
forge-gui/res/cardsfolder/f/famished_worldsire.txt
forge-gui/res/cardsfolder/f/feasting_hobbit.txt
forge-gui/res/cardsfolder/t/thromok_the_insatiable.txt

Devour: better keyword

---

forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-gui/res/cardsfolder/d/dragoons_lance.txt
forge-gui/res/cardsfolder/s/summoners_grimoire.txt

Flavor for Equip

---

forge-gui/res/cardsfolder/g/gilder_bairn.txt
forge-gui/res/cardsfolder/h/hateflayer.txt
forge-gui/res/cardsfolder/m/merrow_grimeblotter.txt
forge-gui/res/cardsfolder/m/merrow_wavebreakers.txt
forge-gui/res/cardsfolder/o/order_of_whiteclay.txt
forge-gui/res/cardsfolder/p/pale_wayfarer.txt
forge-gui/res/cardsfolder/p/patrol_signaler.txt
forge-gui/res/cardsfolder/p/primeval_bounty.txt
forge-gui/res/cardsfolder/p/puresight_merrow.txt
forge-gui/res/cardsfolder/r/restless_fortress.txt
forge-gui/res/cardsfolder/r/ryu_world_warrior.txt
forge-gui/res/cardsfolder/s/safehold_sentry.txt
forge-gui/res/cardsfolder/s/short_circuit.txt
forge-gui/res/cardsfolder/s/silkbind_faerie.txt
forge-gui/res/cardsfolder/s/summon_magus_sisters.txt
forge-gui/res/cardsfolder/t/the_aesir_escape_valhalla.txt
forge-gui/res/cardsfolder/t/the_creation_of_avacyn.txt
forge-gui/res/cardsfolder/y/your_plans_mean_nothing.txt
forge-gui/res/cardsfolder/y/yunas_decision.txt

Dealing with editing lapses and standardizing to ease future cleanup passes.

Cleanup: 2025-07-22

---

forge-gui/res/draft/rankings/dft.rnk
forge-gui/res/draft/rankings/fin.rnk
forge-gui/res/draft/rankings/pio.rnk
forge-gui/res/draft/rankings/tdm.rnk

With the EOE draft being implemented, we needed the latest rankings for some recent sets too

Update draft rankings: DFT, FIN, PIO, TDM

---

forge-gui/res/blockdata/blocks.txt
forge-gui/res/draft/rankings/eoe.rnk
forge-gui/res/editions/Edge of Eternities Stellar Sights.txt
forge-gui/res/editions/Edge of Eternities.txt

Draft definitions for EOE guided using scryfall API data and https://mtgscribe.com/2025/07/16/edge-of-eternities-play-booster-fact-sheet/

Draft definitions for EOE

---

forge-game/src/main/java/forge/game/card/CardFactory.java

Can be used for WH40K token
But FalloutToken need a fallback to Copy?

CardFactory: fix Squad TokenNames

---

forge-ai/src/main/java/forge/ai/AiPlayDecision.java
forge-ai/src/main/java/forge/ai/ComputerUtil.java
forge-ai/src/main/java/forge/ai/ability/AnimateAi.java
forge-ai/src/main/java/forge/ai/ability/DestroyAi.java
forge-gui/res/cardsfolder/s/shared_fate.txt

Fix Brave the Wilds

---

forge-gui-desktop/src/main/config/forge.sh

Allow parameters to be passed in to the shell script

Update forge.sh - quick fix

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardProperty.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
forge-gui/res/cardsfolder/upcoming/electros_bolt.txt
forge-gui/res/cardsfolder/upcoming/spider_islanders.txt

Mayhem: add new Cast-from-Graveyard variant

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/spellability/AlternativeCost.java
forge-gui/res/cardsfolder/upcoming/peter_parker_amazing_spider_man.txt
forge-gui/res/cardsfolder/upcoming/spider_man_brooklyn_visionary.txt
forge-gui/res/cardsfolder/upcoming/spider_man_web_slinger.txt

Closes #8186 
(Peter Parker can't transform yet)

Keyword: Web-slinging

---

forge-ai/src/main/java/forge/ai/AiController.java

`Thread.stop()` is somewhat brutal but still safer than having e.g. AI api calling ``checkStaticAbilities()`` after we're already back in engine code 💣

Fix AI timeout still keeping Future in calculation even when infinite loop

---

forge-game/src/main/java/forge/game/ability/SpellAbilityEffect.java

Closes #8311 until @Hanmac truly solves linked abilities

ExiledWith check for keyworded

---

forge-game/src/main/java/forge/game/ability/effects/AnimateEffectBase.java
forge-game/src/main/java/forge/game/ability/effects/PowerExchangeEffect.java
forge-game/src/main/java/forge/game/ability/effects/PumpAllEffect.java
forge-game/src/main/java/forge/game/ability/effects/PumpEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualAbilities.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualColors.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualIncorporate.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualInterface.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualKeywords.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualNewPT.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualPTBoost.java
forge-game/src/main/java/forge/game/card/perpetual/PerpetualTypes.java

This uses Records with applyEffect instead of ambiguous Map

Perpetual: use Record for different types

---

forge-game/src/main/java/forge/game/event/GameEventManaPool.java

GameEventManaPool: Fix NullPointerException

---

forge-gui/src/main/java/forge/gamemodes/match/input/InputAttack.java

Try to attack mustAttackEntities first.

---

forge-core/src/main/java/forge/item/PaperCardPredicates.java
forge-gui/src/main/java/forge/itemmanager/AdvancedSearchParser.java

Add support in search for "is:foil" and "is:nonfoil"

Filter by foil status

---

forge-gui/res/editions/Unfinity.txt

Add "Name Sticker" Goblin to UNF for #8348

Edition updates: UNF

---

forge-game/src/main/java/forge/game/card/CardFactory.java
forge-gui-android/pom.xml

also fix sync for sentry native ndk since this is declared as system scope

fix flip cards redownloading same image with different name

---

forge-game/src/main/java/forge/game/card/CardView.java
forge-gui-mobile/src/forge/adventure/scene/SettingsScene.java
forge-gui-mobile/src/forge/screens/settings/SettingsPage.java

limit hasprintedpt to vehicles and spacecraft to fix modal card renders with non creature backside
- closes #8413

update SettingsScene, Settings page indent

---

forge-game/src/main/java/forge/game/ability/ApiType.java
forge-game/src/main/java/forge/game/ability/effects/AirbendEffect.java
forge-game/src/main/java/forge/game/ability/effects/ChangeZoneEffect.java
forge-gui/res/cardsfolder/upcoming/airbending_lesson.txt

TLA: Airbend

---

forge-game/src/main/java/forge/game/ability/effects/ManaEffect.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/card/CardFactoryUtil.java
forge-game/src/main/java/forge/game/keyword/Firebending.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/keyword/KeywordWithAmount.java
forge-gui/res/cardsfolder/upcoming/loyal_fire_sage.txt
forge-gui/res/cardsfolder/upcoming/zuko_exiled_prince.txt

TLA: Firebending

---

forge-ai/src/main/java/forge/ai/ability/EndureAi.java
forge-gui/res/cardsfolder/k/krumar_initiate.txt
forge-gui/res/lists/planeswalker-achievements.txt

Fixes #8449.
Not sure how to properly limit the upper value for X, this is pretty conservative when it comes to timing and the AI won't go overboard (past the danger limit), but otherwise it'll choose quite freely.

AI logic for Krumar Initiate

---

forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
forge-gui/res/cardsfolder/a/ambrosia_whiteheart.txt
forge-gui/res/cardsfolder/a/aviary_mechanic.txt
forge-gui/res/cardsfolder/r/rescuer_chwinga.txt

Fix missing trigger

---

adventure-editor/src/main/java/forge/adventure/Main.java
forge-gui-android/src/forge/app/Main.java
forge-gui-ios/src/forge/ios/Main.java
forge-gui-mobile-dev/pom.xml
forge-gui-mobile-dev/src/forge/app/GameLauncher.java
forge-gui-mobile/src/forge/Forge.java
forge-gui/src/main/java/forge/gui/GuiBase.java
forge-gui/src/main/java/forge/model/FModel.java
forge-gui/src/main/java/forge/util/HWInfo.java

should fill up sentry basic device and os info for mobile builds

update device info

---

forge-ai/src/main/java/forge/ai/ability/ChangeZoneAi.java
forge-gui/res/cardsfolder/a/ambrosia_whiteheart.txt
forge-gui/res/cardsfolder/a/aviary_mechanic.txt

Revert "Ambrosia Whiteheart AI slight improvement"

---

forge-gui-mobile/src/forge/adventure/data/RewardData.java

Might as well allow custom cards in rewards when user has them.

Allow custom cards as reward

---

forge-game/src/main/java/forge/game/ability/effects/CountersRemoveEffect.java
forge-gui/res/cardsfolder/s/sin_unending_cataclysm.txt
forge-gui/res/cardsfolder/s/suncleanser.txt
forge-gui/res/cardsfolder/t/thief_of_blood.txt

Fix Thief of Blood simultaneous ETB

---

forge-game/src/main/java/forge/game/Game.java

Reversing the Turn Order should have no Effect there if only 2 players

Game: only reverse NonactivePlayers if more than one

---

forge-gui/res/cardsfolder/t/treetop_recluse.txt

Add treetop_recluse.txt

---

forge-core/src/main/java/forge/item/PaperCard.java
forge-gui-mobile/src/forge/adventure/player/AdventurePlayer.java
forge-gui-mobile/src/forge/adventure/scene/AdventureDeckEditor.java
forge-gui-mobile/src/forge/adventure/stage/Console.java
forge-gui-mobile/src/forge/adventure/util/RewardActor.java
forge-gui/res/languages/de-DE.properties
forge-gui/res/languages/en-US.properties
forge-gui/res/languages/es-ES.properties
forge-gui/res/languages/fr-FR.properties
forge-gui/res/languages/it-IT.properties
forge-gui/res/languages/ja-JP.properties
forge-gui/res/languages/pt-BR.properties
forge-gui/res/languages/zh-CN.properties

Remove unsupported cards from AdventurePlayer inventory

---

forge-gui/res/cardsfolder/upcoming/stoic_star_captain.txt
forge-gui/res/cardsfolder/upcoming/thendar_the_overminer.txt
forge-gui/res/cardsfolder/upcoming/val_marooned_surveyor.txt
forge-gui/res/cardsfolder/upcoming/vvviza_orbital_overseer.txt
forge-gui/res/cardsfolder/upcoming/worldweave.txt

- [Stoic Star-Captain](https://scryfall.com/card/yeoe/3/stoic-star-captain)
- [Thendar, the Overminer](https://scryfall.com/card/yeoe/17/thendar-the-overminer)
- [Val, Marooned Surveyor](https://scryfall.com/card/yeoe/26/val-marooned-surveyor)
- [Vv'viza, Orbital Overseer](https://scryfall.com/card/yeoe/28/vvviza-orbital-overseer)
- [Worldweave](https://scryfall.com/card/yeoe/21/worldweave)

YEOE: 5 cards

---

forge-gui-mobile/src/forge/assets/ImageCache.java
forge-gui-mobile/src/forge/itemmanager/views/ImageView.java

prevent NPE, ConcurrentModification on ImageView onRefresh

---

forge-game/src/main/java/forge/game/player/Player.java
forge-game/src/main/java/forge/game/zone/MagicStack.java

this removes one of the last uses of `getNonactivePlayers`

MagicStack: remove getNonactivePlayers for SinceBeg

---

forge-game/src/main/java/forge/game/trigger/TriggerHandler.java

The order of the Trigger will be handled later in MagicStack

TriggerHandler: no need for APNAP

---

forge-game/src/main/java/forge/game/GameActionUtil.java
forge-game/src/main/java/forge/game/ability/effects/PermanentCreatureEffect.java
forge-game/src/main/java/forge/game/card/CardState.java

This should fix the Emerge + Prototype thing
i also did a fix for Prototype Stack Description

GameActionUtil: fix getFirstSpellAbility using castSA

---

forge-game/src/main/java/forge/game/ability/effects/ImmediateTriggerEffect.java
forge-game/src/main/java/forge/game/trigger/TriggerHandler.java
forge-gui/res/cardsfolder/u/urzas_miter.txt

Fix Urza's Miter

---

forge-gui-mobile/src/forge/adventure/scene/DuelScene.java

Should now use the size and quantity limits from the appropriate deck format. Also adds support for maximum deck sizes if we ever have any events that use those.

Fix incorrect conformity in adventure events.

---

forge-ai/src/main/java/forge/ai/PlayerControllerAi.java
forge-core/src/main/java/forge/deck/Deck.java
forge-game/src/main/java/forge/game/GameAction.java
forge-game/src/main/java/forge/game/Match.java
forge-game/src/main/java/forge/game/player/PlayerController.java
forge-gui-desktop/src/test/java/forge/gamesimulationtests/util/PlayerControllerForTests.java
forge-gui/src/main/java/forge/player/PlayerControllerHuman.java

remove unsupported cards on game matches

---

forge-game/src/main/java/forge/game/combat/AttackRequirement.java
forge-game/src/main/java/forge/game/combat/CombatUtil.java
forge-gui/res/cardsfolder/k/kardur_doomscourge.txt

Remove fake KW

---

forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/game/keyword/Keyword.java
forge-game/src/main/java/forge/game/keyword/Mayhem.java

This adds the ReminderText for `Oscorp Industries`

Mayhem: add Reminder for Land with no Cost

---

forge-gui-desktop/src/main/java/forge/screens/home/sanctioned/VSubmenuSealed.java

update VSubmenuSealed panel

---

forge-gui-mobile/src/forge/adventure/util/SaveFileData.java
forge-gui-mobile/src/forge/adventure/world/WorldSave.java

- todo find a better way to inform player with save error

revert save read

---

forge-gui/res/editions/Alchemy Horizons Baldur's Gate.txt
forge-gui/res/editions/Commander Collection Black.txt
forge-gui/res/editions/Friday Night Magic 2012.txt
forge-gui/res/editions/Friday Night Magic 2017.txt
forge-gui/res/editions/Global Series Jiang Yanggu & Mu Yanling.txt
forge-gui/res/editions/Guilds of Ravnica Guild Kit.txt
forge-gui/res/editions/Innistrad Crimson Vow.txt
forge-gui/res/editions/Innistrad Midnight Hunt.txt
forge-gui/res/editions/Innistrad Remastered.txt
forge-gui/res/editions/Open the Helvault.txt

* Double-sided tokens should now be supported.
* Fixed some incorrect IDs.

Fix tokens and some images ID

---

forge-gui/res/cardsfolder/r/recruit_instructor.txt

Update Recruit Instructor

---

forge-core/src/main/java/forge/card/ColorSet.java
forge-core/src/main/java/forge/card/MagicColor.java
forge-core/src/main/java/forge/deck/DeckRecognizer.java
forge-core/src/main/java/forge/item/PaperCard.java
forge-game/src/main/java/forge/game/ForgeScript.java
forge-game/src/main/java/forge/game/card/Card.java
forge-game/src/main/java/forge/trackable/TrackableTypes.java
forge-gui-desktop/src/main/java/forge/itemmanager/views/ColorSetRenderer.java
forge-gui-desktop/src/main/java/forge/toolbox/CardFaceSymbols.java
forge-gui-mobile/src/forge/card/CardFaceSymbols.java
forge-gui-mobile/src/forge/card/ColorSetImage.java
forge-gui-mobile/src/forge/itemmanager/views/ImageView.java
forge-gui/src/main/java/forge/gamemodes/planarconquest/ConquestUtil.java
forge-gui/src/main/java/forge/gui/card/CardDetailUtil.java
forge-gui/src/main/java/forge/itemmanager/ColumnDef.java

part of #8682
ColorSet doesn't need ManaCostShard
the EnumSet and the String representation are created in constructor and marked as final

ColorSet: store EnumSet and toString as Final

---

forge-game/src/main/java/forge/game/ability/effects/SacrificeEffect.java
forge-game/src/main/java/forge/game/spellability/SpellAbility.java

Fix copied SA using old replacingObjects

---

forge-ai/src/main/java/forge/ai/ability/ConniveAi.java
forge-ai/src/main/java/forge/ai/ability/ControlExchangeAi.java
forge-ai/src/main/java/forge/ai/ability/MustBlockAi.java
forge-ai/src/main/java/forge/ai/ability/PhasesAi.java
forge-gui/res/cardsfolder/a/axelrod_gunnarson.txt
forge-gui/res/cardsfolder/b/brudiclad_telchor_engineer.txt
forge-gui/res/cardsfolder/c/caesar_legions_emperor.txt
forge-gui/res/cardsfolder/c/crisis_of_conscience.txt
forge-gui/res/cardsfolder/g/grishnakh_brash_instigator.txt
forge-gui/res/cardsfolder/p/prosperity_tycoon.txt
forge-gui/res/cardsfolder/s/soul_collector.txt

Restore fixes

---

forge-game/src/main/java/forge/game/ability/AbilityUtils.java
forge-gui/res/cardsfolder/c/central_elevator_promising_stairs.txt
forge-gui/res/cardsfolder/r/rampaging_soulrager.txt
forge-gui/res/cardsfolder/s/smoky_lounge_misty_salon.txt

Refactor UnlockedDoors using PlayerProperty

---

forge-ai/src/main/java/forge/ai/ability/CountersMoveAi.java

Fix MoveCounters with beneficial counters
